packages/chat/yarn.lock
packages/chatbot/yarn.lock
packages/core-ethereum/yarn.lock
packages/core/yarn.lock
packages/ethereum/yarn.lock
packages/hoprd/Dockerfile
packages/hoprd/src/admin.ts
packages/hoprd/src/env.ts
packages/hoprd/yarn.lock
packages/server/yarn.lock
packages/testing/yarn.lock

Production build on `hopr-admin` should serve from the `build` and not re-build on demand.

serve production build

---

.github/workflows/deploy.yaml

NB: Ideally we keep `dappnodesdk` to avoid forking to much from the original project if the contributions to the original `sdk` are not too many.

Upgrading to avadosdk

---

packages/avado/docker-compose.yml

Since we [removed](https://github.com/hoprnet/hoprnet/blob/095fdb8e51077b2febcba222d19d21668d43b437/packages/hoprd/docker-entrypoint.sh) the default one now our AVADO users can’t automatically start their nodes.

Reinstated docker-entrypoint values

---

packages/hoprd/.dockerignore
packages/hoprd/Dockerfile
packages/hoprd/src/index.ts

Based on @snyk's [recommendations](https://twitter.com/liran_tal/status/1349352339996631045?s=20), we identified three improvements, one particular to our issue of the process not exiting properly and thus, failing to be picked up by `konlet` to be restarted.
Fixes #977.

Improvements on our docker image

---

packages/avado/Dockerfile

As `localhost` isn't a valid configuration for an AVADO.

Updated AVADO to listen to 0.0.0.0

---

packages/core-ethereum/src/indexer/index.ts

Manually add the block numbers of when the HoprChannel contract was deployed, this is a hotfix to address the recent issue with quering past logs.

fix indexer fromBlock

---

packages/core-ethereum/src/indexer/index.ts

Fixes indexer from skipping blocks when congestion happens, also adds some backoff when pulling past logs

fix indexer

---

packages/core/src/channel-strategy.ts

Before, the promiscuous channel would simply take a random channel, and
evaluate it for quality. If the threshold was above a level it would
auto open.
The problem is, if it hadn't seen the channel before, the quality is not
good enough. Therefore to open a channel, it must be randomly selected
twice. When there are a lot of channels open, this takes a while.
To avoid this, and as a naive solution, appropriate for our promiscuous
strategy, we now auto open to any interesting node at the beginning of
the tick, before also adding new random channels to evaluate.

Make promiscuous strategy open channels to any interesting node.

---

packages/core-ethereum/src/channel/index.ts
packages/core-ethereum/src/indexer/index.ts
packages/core-ethereum/src/types/signedChannel.spec.ts
packages/core-ethereum/src/types/signedChannel.ts

Fixes #572
We patch `SignedChannel` to include counterparty, this way it doesn't require a signature from the counterparty, this is a short-term fix, we will be removing `SignedChannel` in the refactor.
Removing it now will cause lots of breaking changes throughout the codebase.

patch signed channel

---

packages/core-ethereum/src/account.ts
packages/core-ethereum/src/hashedSecret.spec.ts
packages/core-ethereum/src/hashedSecret.ts
packages/core-ethereum/src/index.ts

Fixes #1202
Because hashedSecret wasn't actually an instance, and reloaded values
every time it was `check()`ed, `findPreImage` was called whenever we
initialized, which was incorrectly assumed to be a no-op.
In core we use initialize to try and initialize on each tick, so we
initialize as soon as possible, therefore findPreImage was being called
repeatedly.
Instead of simply hacking this init call, this PR refactors hashedSecret
to actually store information in it's instance.

Reduce hash calls in hashedSecret

---

packages/core-connector-interface/src/types/ticket.d.ts
packages/core-connector-interface/src/utils.d.ts
packages/core-ethereum/src/channel/index.ts
packages/core-ethereum/src/channel/ticket.ts
packages/core-ethereum/src/types/channel/index.ts
packages/core-ethereum/src/types/signedTicket.spec.ts
packages/core-ethereum/src/types/ticket.ts
packages/core-ethereum/src/utils/index.ts
packages/core/src/messages/acknowledgement/index.ts
packages/core/src/messages/packet/challenge.ts
packages/core/src/messages/ticket/index.spec.ts

Part of overall refactoring.
- Remove side effects of signature function
- Make explicit where we are mutating array buffers.

Simplify signing

---

packages/hoprd/src/commands/listOpenChannels.ts

No output at all was produced when there were only unintialized channels.

Fix 'channels' command producing no output

---

.gitpod.dockerfile
.gitpod.yml

Solves https://github.com/hoprnet/hoprnet/issues/1500
- Added the `gitpod.dockerfile` so that we can extend the gitpod workspace image with custom tooling.
- Added `tmux` and `nvim` to the tool chain
- Ran `yarn build` instead of `yarn setup`
Small note regarding the Dockerfile:
I did choose to use the USER switching on the Dockerfile instead of calling "sudo", so that it's more readable and we know exactly which user is executing given commands. This comes with the downside that we're adding more layers to the docker image but this isn't a problem on development images IMO. Gitpod themselves do the same thing on their base images:  https://github.com/gitpod-io/workspace-images/tree/master/base & https://github.com/gitpod-io/workspace-images/tree/master/full

gitpod: add possibility to install additional tools like tmux and vim

---

.snyk
yarn.lock

Whenever there's a security on our dependencies, we can run `snyk protect` as part of our build process to patch vulnerabilities found by Snyk even if the package does not have an upgrade available. More information in their [docs](https://support.snyk.io/hc/en-us/articles/360003812558-Protect-your-code-with-patches).
Fixes #1306

Adding initial report from Snyk

---

packages/ethereum/contracts/HoprForwarder.sol

The `HoprForwarder` contract is placed in front of the multisig that receives the minted HOPR (ERC777) token and immediately forwards to the multisig wallet.

Add HoprForwarder contract

---

packages/hoprd/src/index.ts

* Since Quiknode does not support archive node yet, nodes are useless at this point
* Will be used to showcase the release workflow for documentation purposes

Using xDAI default RPC endpoint

---

.github/workflows/deploy.yaml
scripts/cleanup.sh
scripts/deploy.sh
scripts/dns.sh
scripts/environments.sh
scripts/gcloud.sh
scripts/internal.sh
scripts/nightly.sh
scripts/qa.sh
scripts/testnet.sh
scripts/utils.sh

After my changes to make the shell scripts more strict, the deploy workflow, specifically `deploy.sh` didn't work anymore due to an undefined variable. This PR fixes such occasions by moving the check into the files themselves.

Fix sourcing check of shell scripts

---

.actrc
.github/workflows/deploy.yaml
.github/workflows/docs.yaml
.github/workflows/test.yaml
README.md
packages/hoprd/.gitignore
scripts/get-package-version.sh
scripts/publish-patch-release.sh
scripts/publish-pre-release.sh
shell.nix

This way the workflow can be tested locally via 
```sh
act -j release
```

Remove uses of GITHUB_ENV in Github release workflow

---

.github/workflows/deploy.yaml
.github/workflows/docs.yaml

Using double-quotes in such conditions breaks when there are multiple conditions.

Use single-quotes in Github workflow yaml conditions

---

packages/core/src/index.ts
packages/utils/src/libp2p/index.ts

Fixes:
- repopulates DHT on restart
- various bug fixes in `dial` logic
Also fixes #1356

Fix DHT address population and dial error

---

packages/ethereum/chain/contracts.json
packages/ethereum/tasks/utils/contracts.ts
scripts/run-integration-tests-locally.sh

due to a hardhat + hardhat-deploy quirk we are forced to use the `hardhat` network when we want to run a hardhat node
this update runs the node in hardhat network but pretends to be a localhost network, all other scripts should do `--network localhost`, addressing this issue better in #1676

specify E2E networks

---

packages/core-ethereum/src/ethereum.ts
packages/core-ethereum/src/index.ts
packages/core/src/index.ts
packages/hoprd/src/commands/closeChannel.ts
packages/hoprd/src/commands/commands.spec.ts
packages/hoprd/src/commands/info.ts

- fixes #1770
- return an object with smart contract info from `core-ethereum`

add closure time to info

---

scripts/gcloud.sh
scripts/testnet.sh

These images add up and can fill the available disk space,
making the VM unreachable. Instead we remove old images right away.
If they are used at a later point in time again, they will be fetched
again by Docker.

Remove unused docker images when updating container VM

---

packages/avado/Dockerfile

That path has been set to its default before which would lead to the
identity being wiped if the container was removed. Now that identity is
stored within the database folder on a separate volume.
Fixes #1788

Fix path to identity in Avado Docker container

---

packages/core/package.json
packages/utils/src/libp2p/index.ts
yarn.lock

Fixes:
- stronger typing
- clear timeouts on all control flow paths
- prevent AbortErrors when dialing
Fixes #1829 
Changes:
- bumps hoprConnect to 0.2.27, see https://github.com/hoprnet/hopr-connect/compare/v0.2.26...v0.2.27

clear timeouts when dialing & minor fixes

---

.github/workflows/deploy.yaml
scripts/testnet.sh

Also re-add funding of nodes upon deployment
This process step got lost after deprecating bootstrap nodes. This
change runs the funding check whenever a node is started or updated.
Fixes #1842

Ensure Avado builds are only done on version changes

---

scripts/run-integration-tests-npm.sh
scripts/run-integration-tests-source.sh

This fixes #1838.
In e2d tests there is a 4th node which only executes some commands via `--run` flag and exits. The execution is verified by checking the logs.

test --run command in e2e tests

---

packages/core-ethereum/package.json
packages/core/package.json
packages/ethereum/package.json
packages/hoprd/package.json
packages/utils/package.json
yarn.lock

Inlcuding typedoc to 0.21.0 which was blocking the typescript upgrade so
far.

Upgrade typescript to 4.3.4

---

.github/workflows/deploy.yaml
.github/workflows/docs.yaml
.github/workflows/e2e.yaml
.github/workflows/lint.yaml
.github/workflows/nightly.yaml
.github/workflows/npm-e2e.yaml
.github/workflows/test.yaml
.gitignore
nix/sources.json
packages/avado/dappnode_package.json
packages/avado/releases.json
packages/hoprd/cloudbuild.yaml
scripts/configure-git-info.sh
scripts/publish-patch-release.sh
scripts/publish-pre-release.sh
scripts/run-integration-tests-npm.sh
scripts/run-integration-tests-source.sh
shell.nix

Improve Github deploy workflow so it can be tested locally as well.
Fixes the issue seen on `master`: https://github.com/hoprnet/hoprnet/runs/2848123069
A side-effect is that each built docker image now receives a unique tag first, which is useful in testing, and only within the CI will receive proper version tags.

Fix gcloud cloudbuild execution

---

.github/workflows/deploy.yaml
packages/avado/Dockerfile

This fixes a crash where the entrypoint module could not be found.
Also changed the tag of the docker image so that Avado only uses images
from release branches and not pre-releases.

Fix entrypoint in Avado docker image

---

DISCUSSIONS.md
packages/core-ethereum/src/indexer/index.ts
packages/core/src/interactions/packet/index.spec.ts
packages/ethereum/contracts/HoprChannels.sol
packages/ethereum/test/HoprChannels.spec.ts
packages/utils/src/types/accountEntry.spec.ts
packages/utils/src/types/accountEntry.ts
packages/utils/src/types/response.spec.ts
packages/utils/src/types/response.ts

Fixes #1791 
Changes:
- check that response is within the field. Previously it was possible to use e.g. `1` and `1 + FIELD_ORDER` as a response.
- fail on invalid public keys that are announced on-chain. Make sure that nodes cannot trick other nodes with wrong public keys, see https://github.com/christianlundkvist/blog/blob/master/2020_05_26_secp256k1_twist_attacks/secp256k1_twist_attacks.md
- add test that checks SC for invalid response to challenge

Check that values are on the curve

---

scripts/run-integration-tests-npm.sh
scripts/run-integration-tests-source.sh
scripts/utils.sh
test/integration-test.sh

Previously errors could be overlooked and the script would continue.
Now it checks against an assertion and will terminate if the check
fails.
Refs #1806

make integration tests strict to catch errors

---

test/integration-test.sh

e2e tests were failing on mac, because macOS doesn't support `%N` format string in `date` command. Replaced with node.js version.

replaced date with node js nanoseconds getter

---

.github/workflows/e2e.yaml
.github/workflows/npm-e2e.yaml

Being able to download the full node logs is useful when debugging CI test failures.

Store node logs as CI artifacts after e2e tests

---

.github/workflows/e2e.yaml
.github/workflows/npm-e2e.yaml
.github/workflows/test.yaml

Using macos as a platform for tests in CI ensures that all scripts and tools work on both supported platforms. This addresses issues where PRs introduced incompatible tooling.

Add macos as platform to CI tests

---

packages/hoprd/Dockerfile

The migration isn't working automatically, so we need to stick to the root mode for existing releases.

Restore priviledged mode in Docker image temporarily

---

scripts/environments.sh
scripts/run-integration-tests-npm.sh
scripts/run-integration-tests-source.sh
test/integration-test.sh

This will ensure the gcloud machines are terminated and deleted.
Fixes #2001
Also fixed some e2e test timings which should improve results on macOS CI.

Retire stirling gcloud environment

---

.github/workflows/deploy.yaml
.github/workflows/e2e.yaml
.github/workflows/npm-e2e.yaml
scripts/notify-matrix-github-workflow-failure.sh
scripts/notify-matrix.sh

Fixes #1735 
NOTE: This only enables such notifications for failures on `master` and `release/*` branches and specifically for the `deploy` and `e2e` workflows. We can add more workflows later if needed.

Add notification on CI failures

---

packages/utils/package.json

`bs58` is required by `hopr-utils` in `AccountEntry` but not part of dependencies in package.json

add missing dependency

---

.github/workflows/deploy.yaml
README.md
WORKFLOW.md
docs/hopr-documentation/src/install-hoprd/using-docker.md
packages/avado/Dockerfile
packages/core/package.json
packages/hoprd/Dockerfile
packages/hoprd/cloudbuild.yaml
yarn.lock

This includes some fixes for the CI docker pipeline to properly tag the images.
These changes fix the behavior seen in #2020 and #1995
I've verified this by manually running 2 public relay nodes and one node behind NAT.

Port hopr-connect fixes to release/kiautschou

---

scripts/gcloud.sh
scripts/testnet.sh

New args would only be used when re-creating VMs entirely. This change
adds new args even if the container is only updated.

Add container args to container update call in glcoud

---

packages/hoprd/package.json
packages/hoprd/src/index.ts
scripts/run-integration-tests-npm.sh
scripts/run-integration-tests-source.sh
test/integration-test.sh
test/security-test.sh
yarn.lock

Closes #1984 
Doesn't allow you to start hoprd with missing security. 
How to test:
`hoprd --admin` or `hoprd --rest` should fail.
`hoprd --admin --apiToken <weak_token>` should fail
`hoprd --admin --apiToken <strong_token>` should succeed.
A strong token requires a lowercase letter, an uppercase letter, a number and a special symbol and be at least 8 symbols long.

weak api token not allowed

---

.github/workflows/e2e-gcloud.yaml
.github/workflows/e2e-npm.yaml
scripts/gcloud.sh
scripts/run-integration-tests-gcloud.sh
scripts/run-integration-tests-npm.sh
scripts/run-integration-tests-source.sh
scripts/testnet.sh
scripts/utils.sh
test/integration-test.sh
test/security-test.sh

1. Introducing the basic blocks to start/stop a cluster of hoprd nodes on gcloud which can then be used to run tests against. The nodes can be configured to use a given RPC endpoint.
2. A new e2e script uses that to start a cluster of nodes with the latest Docker image and run the existing end-2-end tests against it. The nodes are configured to use Goerli as the network, and are funded upon startup.
3. The new Github Actions workflow executes that script on pushed to specific branches.
The script itself can also be tested locally (must have a working gcloud account set up though):
```
export FUNDING_PRIV_KEY="<add_value>"
export HOPRD_INFURA_KEY="<add_value>"
./scripts/run-integration-tests-gcloud.sh
```
Alternatively check all options:
```
./scripts/run-integration-tests-gcloud.sh -h
``` …

Enable e2e testing on gcloud networks

---

scripts/run-integration-tests-gcloud.sh
scripts/setup-gcloud-cluster.sh
scripts/topologies/full_interconnected_cluster.sh

This PR adds a script to spin up a cluster of nodes on gcloud against which a setup script can be executed to create channels and send messages. This is useful top create certain channel topologies for further testing.
Check out the help info of the script:
```
./scripts/setup-gcloud-cluster.sh -h
```
Create a cluster and setup channels between all nodes:
```
HOPRD_PERFORM_CLEANUP=false HOPRD_SHOW_PRESTART_INFO=true ./scripts/setup-gcloud-cluster.sh mysupertestcluster gcr.io/hoprassociation/hoprd:latest `pwd`/scripts/topologies/full_interconnected_cluster.sh
```
Once manual testing has finished cleanup the cluster:
```
HOPRD_PERFORM_CLEANUP=true ./scripts/setup-gcloud-cluster.sh mysupertestcluster
```

Add basic topology script

---

packages/core/package.json
packages/core/src/index.ts
packages/ethereum/deployments/default/goerli/HoprChannels.json
packages/ethereum/deployments/default/goerli/HoprToken.json
packages/ethereum/deployments/default/mumbai/HoprChannels.json
packages/ethereum/deployments/default/mumbai/HoprToken.json
packages/ethereum/deployments/default/polygon/HoprChannels.json
packages/ethereum/deployments/default/polygon/HoprDistributor.json
packages/ethereum/deployments/default/polygon/HoprToken.json
packages/ethereum/deployments/default/xdai/HoprChannels.json
packages/ethereum/deployments/default/xdai/HoprDistributor.json
packages/ethereum/deployments/default/xdai/HoprToken.json
packages/ethereum/deployments/default/xdai/HoprWrapper.json
packages/ethereum/tasks/slimDeployments.ts
yarn.lock

Fixes:
- fix type issue on `core/index.ts#getObservedAddrs()`
- fix `missing blockNumber`, see https://github.com/hoprnet/hoprnet/actions/runs/1127815375
- fix deployment slimmer
Changes:
- `hopr-connect@0.2.41`, see [changes](https://github.com/hoprnet/hopr-connect/compare/v0.2.40...v0.2.41)

Bump hopr-connect to 0.2.41 & minor fixes

---

scripts/commit-and-push-all-changes.sh

This PR fixes the (sometimes) failing `git pull --rebase` in the deploy workflow.

fixed git pull in deploy

---

packages/core-ethereum/src/ethereum.ts
packages/ethereum/test/utils.ts

Fixes #2337
In `wildhorn` we have used an [http endpoint](https://github.com/hoprnet/hoprnet/blob/310463dd1489f51cc9c2de13dfd83540a00c2735/packages/hoprd/src/index.ts#L21) for our provider, see https://github.com/ethers-io/ethers.js/issues/901 for why that causes many chain ID calls.
We now use `StaticJsonRpcProvider` which assumes the network wont change, caching chain ID.
At the same time, this is not an issue when a `websocket` provider is used. https://github.com/ethers-io/ethers.js/issues/1054

caching chain ID

---

packages/core/package.json
packages/core/src/index.ts
packages/core/src/test-utils.ts
scripts/get-supported-protocols-from-peer.ts
yarn.lock

Breaking changes:
- make HOPR incompatible to **IPFS nodes**
- make HOPR incompatible to other projects using libp2p
- make HOPR incompatible to **older HOPR nodes** because of different protocol prefix
Changes:
- use `hopr` protocol prefix, closes #2342 
- upgrade from `libp2p-noise` to `@chainsafe/libp2p-noise`
- use typed `libp2p-tcp`, closes #2379 
- update libp2p-kad-dht, closes #2378

libp2p ecosystem upgrades

---

packages/hoprd/package.json
yarn.lock

When building `hoprd`, `hopr-admin` is built using `next-js`'built system which assumes certain files being present in `next-js` installation directory. If built `hopr-admin` is used with a different version of `next-js`, some files might have been renamed, or deleted.
Hardcode version of Next JS to prevent from version updates that change internals

fixed nextjs version

---

packages/core/src/index.ts

Cherry picks DEADR fix from #2387 
Changes:
- feed libp2p instance with previously announced nodes such that libp2p can use them

Add already announced nodes to libp2p

---

packages/core/package.json
yarn.lock

Cherry pick hopr-connect upgrade from #2387 
bump `hopr-connect@0.2.42` , see https://github.com/hoprnet/hopr-connect/compare/v0.2.41...v0.2.42 for code changes and https://github.com/hoprnet/hopr-connect/blob/main/CHANGELOG.md#0242-2021-09-10 for new features

hopr-connect 0.2.42

---

packages/hoprd/src/logs.ts

This is needed for log forwarding from outside of the daemon.

print JSON logs onto single line

---

packages/core-ethereum/src/indexer/index.ts

related to #2359
Catch errors caused by missing `Announcements`, channels in which one of the parties have not announced will not be indexed.
Once they announce they will remain unindexed.
Follow up on https://github.com/hoprnet/hoprnet/pull/2448

catch event processing errors

---

.github/workflows/deploy.yaml
packages/cover-traffic/Dockerfile
packages/cover-traffic/README.md
packages/cover-traffic/cloudbuild.yaml
packages/cover-traffic/package.json
packages/cover-traffic/src/dashboard.ts
packages/cover-traffic/src/index.ts
yarn.lock

Refers to #2004 
This adds a Docker image build which is based on the generated NPM package.
The image is built and published in parallel to the `hoprd` Docker image to not delay the deploy pipeline further.
The `provider` option has been made configurable via the command line as a parameter such that resulting Docker image can be tested against different networks.

Add basic Docker build support to cover traffic daemon

---

packages/core-ethereum/package.json
packages/core/package.json
packages/cover-traffic/package.json
packages/ethereum/package.json
packages/hoprd/package.json
packages/utils/package.json

For some reason the branch, in which this tag was created is gone. I suspect it was on a debug branch.
Thus merging it into master will trigger the generation of the next pre-release which can be published to NPM.

Merge tangling pre-release tag to unblock master

---

scripts/gcloud.sh
scripts/setup-ct-gcloud-cluster.sh

This PR adds a script to setup a cluster of CT nodes similar to how its done for hoprd nodes.
Check the help for instructions on how to use the script.
```
./scripts/setup-ct-gcloud.cluster.sh -h
```
For the Rio testnet one would use the `<docker_image_tag>` as `latest-rio` or a specific version of the image which is configured to run on rio. Also the provider will need to be set to a Matic endpoint.
- should the run command from the hoprd nodes (which start cover traffic) be removed?

Add setup gcloud script variant for CT nodes

---

packages/cover-traffic-daemon/package.json

This fixes CT daemon inability to start due to the resource file not being copied during the build step.

added build:copy step when building ct daemon

---

packages/cover-traffic-daemon/src/index.ts

This PR implements a simple hack to prevent CT daemon from crashing on startup until libp2p is updated.
See: https://github.com/libp2p/js-libp2p/pull/1025

added hack not to crash

---

packages/cover-traffic-daemon/src/index.ts

This PR disables forceful indexer DB recreation on CT daemon startup, speeding up the spinup time.

disabled indexer db recreation

---

packages/core/CHANGELOG.md
packages/utils/src/crypto/randomInteger.spec.ts
packages/utils/src/crypto/randomInteger.ts

Now uses an optimized Lemire's method of generating upper-bounded non-negative random integers.
See https://github.com/apple/swift/pull/39143 for details on this method.
Also had to remove one unit test for `randomInteger` as we cannot force a fixed seed while using a proper CSPRNG.
Resolves #2932

Updated randomInteger function to be cryptographically safe

---

packages/cover-traffic-daemon/package.json
packages/hoprd/package.json
yarn.lock

The PR #2889 introduced using restana, but didn't add it to the
dependencies. Thus, the resulting Docker images cannot start.

Add missing dep restana to cover-traffic-daemon

---

.github/workflows/deploy.yaml
scripts/build-docker.sh

The image names were missing the prefix `hopr-` which resulted in some
other helper scripts not working.

Fix prefix of docker image names for cover traffic daemon

---

packages/cover-traffic-daemon/src/index.spec.ts

Current tests simply set up the strategy w/o letting a single tick to work, but allowing kickstarting the process.
- Fixes #2902

Initial coverage for `cover-traffic`

---

.processes/wallets.md

For simplicity, accounting and accountability, we are showcasing which wallets HOPR Association interacts with. These are meant to,
- showcase that some wallets had been used by employees and ex-employees, and their on-chain transactions do not represent the interest of the association or company
- share that some wallets are used for the purpose and testing and will execute on-chain transactions given the permission of the association (e.g. NFT minting)
- showcase that in case of assets falling or being airdropped to these wallets due to usage of services in the blockchain industry, these are considered assets of the association, and only the association can decide what to do with them
Here's a [good example](https://twitter.com/hoprnet/status/1458084085805498371?s=20 ) of the …

Added `wallets.md` to define policy

---

scripts/fund-address.ts

There was an incorrect type (`HOPR` but should be `NATIVE`) in the funding script.

Fix incorrect coin type on withdraw

---

packages/core/src/index.ts
packages/cover-traffic-daemon/package.json
packages/cover-traffic-daemon/src/healthcheck.ts
packages/cover-traffic-daemon/src/index.ts
packages/hoprd/README.md
packages/hoprd/package.json
packages/hoprd/rest-api-v2-spec.yaml
packages/hoprd/src/api.ts
packages/hoprd/src/api/v1.ts
packages/hoprd/src/api/v2.ts
packages/hoprd/src/api/v2/paths/account/address.ts
packages/hoprd/src/api/v2/paths/node/version.ts
packages/hoprd/src/healthcheck.ts
packages/hoprd/src/index.ts
yarn.lock

As part of this change the Rest API v1 has been migrated from restana
to express, just like the healthcheck APIs from hoprd and
cover-traffic-daemon. This was done for easier integration of Swagger
tools in the future.
The feature set of Rest API v2 is minimal in this change and will be
extended later. Focus is on the tooling and making sure tests keep
working.
Refs https://github.com/hoprnet/myne-chat/issues/10

Add basic Swagger-based Rest API v2

---

packages/connect/package.json
packages/core/package.json
packages/hoprd/package.json
packages/utils/package.json
packages/utils/src/libp2p/dialHelper.spec.ts
patches/libp2p-0.35.0.patch
yarn.lock

Fixes an uncaught promise rejection in libp2p by temporarily replacing libp2p with a fork that contains a fix.
See [libp2p#1044](https://github.com/libp2p/js-libp2p/pull/1044)

Replace libp2p

---

packages/connect/package.json
packages/core/package.json
packages/utils/package.json
yarn.lock

Switch back to upstream libp2p
See [Changelog](https://github.com/libp2p/js-libp2p/blob/master/CHANGELOG.md#0353-2021-12-13) of libp2p

Upgrade libp2p

---

.processes/release.md

During the last release `prague` missing documentation was identified. This PR tries to expand the release steps to make most changes clear. As a next improvement most release steps could be automated, but this is out of scope for this change.

Update required release steps

---

scripts/deploy.sh

The api token was missing when passing the endpoint to the get function.

add api token to address getter in deploy script

---

scripts/setup-gcloud-cluster.sh

This change is needed, to get the helper script working which is used to start a topology cluster.

Add missing api token to gcloud cluster creation script

---

packages/connect/src/base/listener.spec.ts

Port allocation sometimes takes very long within CI unit tests

Slightly increased timeouts for CI

---

packages/cover-traffic-daemon/src/constants.ts
packages/cover-traffic-daemon/src/strategy.ts

1. Fix minimum channel stake. CT node opened channels with too little stake (1e-15), which is clearly too smaller than what messages with 2 intermediate hops would need (0.02). Change the constant so that CT node fund CT channel with tokens for 50 cover traffic.

Fix various issues in CT

---

packages/hoprd/Dockerfile

This is required because some dependencies loaded by Yarn might refer to
Git repositories instead of NPM packages. At that point Yarn tries to
use the Git binary locally.
Fixes #3185

Add git binary to Docker image builder

---

packages/connect/package.json
packages/connect/src/base/listener.spec.ts
packages/connect/src/base/listener.ts
packages/connect/src/base/tcp.ts
packages/connect/src/filter.spec.ts
packages/core/package.json
packages/core/src/constants.ts
packages/core/src/index.ts
packages/core/src/main.ts
packages/utils/package.json
packages/utils/src/libp2p/dialHelper.ts
yarn.lock

Fixes:
- check *all* entry nodes and not the first 7, closes #3180
- allow DHT to dial other peers, i.e. set `autoDial: true`
- fixes an error in libp2p that forwards only one DHT entry, relevant commit https://github.com/hoprnet/js-libp2p/commit/d5c5777df948cb00f016ee3a82830a652cbc246b
- directly feed DHT with bootstrap peers aka *entry nodes*
- fixes #3184 
~~TODO:
adjust unit tests to match changed functionality~~

Fix connectivity

---

packages/core/src/index.ts
packages/utils/src/libp2p/addressSorters.ts

Always sort announced addressed deterministically.
- if preferLocalAddresses is set, addresses are sorted by their class (class A first, class B second,...)
- otherwise only non-local addresses are used and local addresses are discarded

Add deterministic announce address sorting

---

package.json
yarn.lock

Fixes #3249
The faulty dependencies are pinned so Yarn doesn't add them by dependency resolution.

Fix endless startup loop

---

package.json
packages/hoprd/package.json

Refs #3249
This ensures the hints are packages and usable upon package
installation. Previously, the hints were only available in development
setups.

Move yarn resolution hints into hoprd package

---

scripts/vm-nat-testing/Vagrantfile
scripts/vm-nat-testing/setup-vm.sh

This is needed to run the setup scripts on macOS M1 machines.

Add arm64 support to the Vagrant NAT testing setup

---

yarn.lock

Fixes build on master after merging the `futoin-hkdf` package update.

Update yarn.lock with futoin-hkdf

---

packages/hoprd/src/api/v2/paths/message/sign.ts

Sadly API doesn't provide automatic type to requested parameters from schema, so `req.body.message` was passed as `any` and missed the fact we needed to encode it for `core.sign`.
Related to hoprnet/myne-chat#92

Wrong type for `sign`

---

scripts/deploy.sh
scripts/gcloud.sh
scripts/run-integration-tests-gcloud.sh
scripts/setup-ct-gcloud-cluster.sh
scripts/setup-gcloud-cluster.sh
yarn.lock

Previously, NATed cloud were started with the `--announce` flag, such that they try to announce themselves.
This PR changes the default behavior to start without the `--announce` flag.

start NATed nodes without announce flag

---

scripts/setup-local-cluster.sh

The `fund` task might fail if we don't wait, since node `identity` files will not be created until nodes have been properly bootstrapped.

Ensuring await on unfunded nodes

---

scripts/gcloud.sh
scripts/nat/start-nat-node.sh

Fixes `start-nat-node.sh` script: assign a name to the NAT'd container and make sure it is stopped.
Refs #3296

Improve start-nat-node.sh - make sure container is stopped

---

scripts/nat/start-nat-node.sh

Fixes start-nat-node.sh script so `--version` runs as a shortcut.
Refs #3296

Add shortcut for --version, fix NAT node start determinism

---

CHANGELOG.md
packages/connect/src/base/entry.spec.ts
packages/connect/src/base/entry.ts
packages/connect/src/constants.ts
packages/connect/src/types.ts
packages/connect/src/utils/index.spec.ts
packages/connect/src/utils/index.ts
packages/core/src/index.ts
packages/core/src/network/heartbeat.ts
packages/utils/src/libp2p/relayCode.spec.ts
packages/utils/src/process/retimer.spec.ts
packages/utils/src/process/retimer.ts

Fixes #3280 
Additional changes:
- refactor `retimer` to return the right timeout, not the first one
- add some unit tests for `connect` util functions

Automatically renew relay key entries in the DHT

---

packages/core/src/main.ts

Fixes an issue with libp2p's address sorter

Overwrite address sorter

---

scripts/testnet.sh

Typo in the command to retry node funding.

Fix typo in funding script

---

packages/core-ethereum/src/index.ts

This prevents startup stalls when there is a problem in the communication with the provider.
Problem observed in https://github.com/hoprnet/hoprnet/runs/4950701074?check_suite_focus=true
Release: #3220 
PR on `master`: #3327

Hotfix release/athens:  Ensure node crashes when the provider chain object cannot be created

---

packages/core-ethereum/src/index.ts

This prevents startup stalls when there is a problem in the communication with the provider.
Problem observed in https://github.com/hoprnet/hoprnet/runs/4950701074?check_suite_focus=true

Ensure node crashes when the provider chain object cannot be created

---

packages/core/src/constants.ts

The timeout for heartbeat needs to be strictly smaller than the interval of heartbeat attempts.
New values (ms): 
- `HEARTBEAT_TIMEOUT = 4000`
- `HEARTBEAT_INTERVAL = 30000`
Relates to #3334

Release Athens hotfix: Fix the heartbeat timeout and interval values

---

.github/workflows/deploy.yaml
.processes/release.md
scripts/deploy.sh
scripts/gcloud.sh
scripts/setup-gcloud-cluster.sh

Previously every reboot would result in the instance receive a new IP
address. This change reserves the external addresses upon creation so
reboots don't cycle these IP addresses. Before the cluster is deleted
the IP addresses are released.
Fixes:
- #3054
- #3195 
1. Create cluster
```
HOPRD_PERFORM_CLEANUP=false HOPRD_SHOW_PRESTART_INFO=true ./scripts/setup-gcloud-cluster.sh athens "" my-test-cluster-random-NUMBER
```
2. Check reserved IP addresses
```
gcloud compute addresses list
```
3. Delete cluster
```
HOPRD_PERFORM_CLEANUP=true HOPRD_SHOW_PRESTART_INFO=true ./scripts/setup-gcloud-cluster.sh athens "" my-test-cluster-random-NUMBER
```
4. Check reserved IP addresses again, ensure IPs were released
```
gcloud compute addresses list
```

devops: Add use of static IPs to all gcloud cluster instances

---

packages/utils/src/async/abortableTimeout.spec.ts
packages/utils/src/async/abortableTimeout.ts

Changes:
- unassign outer abort listener after timeout / error thrown
- simplify control flow
- cleanup event listener if an error is thrown

Minor fixes on abortableTimeout

---

packages/core/src/index.ts

If the announce transaction fails, then other nodes have no chance to learn about the node
Therefore, terminate the process and let the user know what went wrong.
Closes #3314

add proper message when `announce` fails

---

CHANGELOG.md
packages/connect/src/filter.spec.ts
packages/connect/src/filter.ts
packages/connect/src/index.ts
packages/connect/src/types.ts
packages/core/src/index.ts
packages/core/src/main.ts
packages/hoprd/src/index.ts
scripts/run-integration-tests-npm.sh
scripts/run-integration-tests-source.sh
scripts/setup-local-cluster.sh

Resolves #3336  and might be related to #3362 
Already merged to `master` as #3349

Release Athens hotfix: Add CLI argument to explicitly allow localhost connections

---

packages/connect/src/filter.ts
packages/utils/src/network/addrs.spec.ts
packages/utils/src/network/addrs.ts

The debug logs in GCloud look suspicious and there is probably a bug in the address filter.
Changes:
- log CIDR address strings to see if address filter is working properly
Sample debug log from GCloud nodes

Hotfix/log CIDR addresses

---

scripts/gcloud.sh
scripts/get-gcloud-instances-accounts-info.sh
scripts/setup-gcloud-cluster.sh
scripts/utils.sh

The script can be useful during release deployments to acquire the account of multiple cluster nodes faster.

Add helper script to get account info from gcloud nodes

---

packages/core/src/index.ts
packages/utils/src/types/channelEntry.ts

Before attempt to finalize we now check that the closure time window has
passed. This prevents transactions to fail because of the same check
on-chain.
Fixes #3364

core: Prevent pre-mature channel finalize closure attempts

---

packages/hoprd/src/commands/index.ts

Merge to Athens release, see #3402 and the related issue #3398

Athens hotfix: Add a try-catch block around each admin command call

---

packages/utils/src/types/channelEntry.ts

Refs #3364 
Previously it used milliseconds instead of seconds. See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTime

[Hotfix release/athens] utils: Fix precision of timing check in channel entry

---

package.json
packages/ethereum/package.json
yarn.lock

Due to `hopr-ethereum` using `ethereum-waffle`, we have a trickled down dependency of `eth-sig-util` that goes as low as `1.x`, whereas the current one is `3.x`. This fails during a brand new install when doing `yarn`, figuring it out while testing #3346 in a brand new machine.
Please do not merge until a green build has been created to verify that these changes do not break any of our tests or current functionality.

Forces `eth-sig-util` to a less outdated version

---

.processes/release.md
packages/avado/build/Dockerfile
scripts/build_avado.sh
scripts/get-default-environment.sh
scripts/publish-version.sh

Fixes AVADO build:
- use environment_id as docker Docker database folder
- automatically adjust AVADO Dockerfile according to default environment

add default environment to AVADO build

---

CHANGELOG.md
packages/core-ethereum/src/commitment.spec.ts
packages/core-ethereum/src/commitment.ts
packages/core-ethereum/src/ethereum.ts
packages/core-ethereum/src/index.ts
packages/core/src/channel-strategy.ts
packages/core/src/index.ts
packages/core/src/interactions/packet/acknowledgement.ts
packages/core/src/messages/packet.ts
packages/ethereum/tasks/faucet.ts
packages/utils/src/async/concurrency.spec.ts
packages/utils/src/async/concurrency.ts
packages/utils/src/crypto/por/index.ts
packages/utils/src/db.ts
packages/utils/src/types/acknowledgedTicket.ts
packages/utils/src/types/solidity.ts
packages/utils/src/types/ticket.ts
scripts/run-integration-tests-source.sh
test/integration-test.sh

Fixes #3365 
Fixes #3306
Fixes #3172
Multiple issues impacted the correctness of ticket redemption:
- Ordering of tickets read from the database wasn't guaranteed, therefore we added explicit sorting.
- Tickets read from the database used an incorrect channel filter, which was fixed.
- The `oneAtATime` concurreny queue didn't block when an operation was executed, which was fixed.
- When redeeming tickets, all tickets were read in one chunk from the database and processed. This could lead to early race-conditions when tickets would arrive late to the database. This has been fixed by reading and processing tickets one-by-one.
Moreover, smoke tests were extended to cover ticket rejection and successful ticket redemption.
This PR includes changes from #3318

Fix ticket redemption

---

docs/hopr-documentation/docs/developers/connecting-node.md
docs/hopr-documentation/docs/developers/starting-local-cluster.md
docs/hopr-documentation/docs/developers/tutorial-hello-world.md

- Defaulted to `bash` whenever language does not fit
- Fixes hoprnet/hopr-devrel#186

Added missing syntax highlighting to docs

---

packages/connect/src/base/listener.ts
packages/core-ethereum/src/indexer/index.ts

Fixes #3455 
Fixes two logical errors:
- remove slippage between querying old events and new events
- finish startup of entry node code before starting to query entry nodes

Fix indexer and entry node code

---

scripts/init-gitpod.sh
scripts/setup-local-cluster.sh

When local cluster setup is done, a file specific for this cluster is generated and can be sourced by the developer in their shell to setup useful environment variables:
- `HOPR_NODE_x_ADDR` (HOPR address)
- `HOPR_NODE_x_HTTP_URL` (REST API URL)
- `HOPR_NODE_x_WS_URL` (WebSocket URL)
for all local cluster nodes x = 1,2...5

Generate sourceable file for easier environment setup in setup-local-cluster.sh

---

packages/avado/build/Dockerfile

I accidentally changed it when doing the release.

Hotfix release/lisbon: avado: Revert docker tag to master-goerli

---

docs/hopr-documentation/docs/developers/components/atoms/ClusterHelper.jsx

- For some reason unbeknownst to me `[...Array(5)]` return `undefined` in production, so we used `Array.from({ length: 5 })` instead.
- Fixes #3526

Rendering actual buttons for `<ClusterHelper>`

---

scripts/gcloud.sh
scripts/setup-gcloud-cluster.sh

Replacing leads to new IP assignments, which we don't need. Thus,
instances should only be updated without being replaced. Moreover, this
change ensure we clean up old intstance templates.

ci: Ensure instances are not replaced when updated

---

packages/core-ethereum/src/indexer/index.ts

Fixes the following error:
```
(node:4140541) UnhandledPromiseRejectionWarning
TypeError: Cannot read property 'length' of undefined
at Indexer.onNewEvents (/somewhere/work/hopr/hoprnet/packages/core-ethereum/lib/indexer/index.js:338:20)
at Indexer.onNewBlock (/somewhere/work/hopr/hoprnet/packages/core-ethereum/lib/indexer/index.js:328:18)
at async Indexer.<anonymous> (/somewhere/work/hopr/hoprnet/packages/core-ethereum/lib/indexer/index.js:63:17)
2022-02-17T07:05:26.207Z hoprd { type: 'log', msg: 'Process exiting with signal 1', ts: '2022-02-17T07:05:26.207Z' }
```
Refs #3513

core-ethereum: Fix use of array when undefined

---

packages/core-ethereum/src/index.ts
scripts/run-integration-tests-npm.sh
scripts/run-integration-tests-source.sh

Re #3544 
Changes the e2e test scripts to fail with non-zero exit code if any of the started subprocesses fails with a non-zero exit code.
**This makes the e2e tests way stricter**
- Fix unhandled promise rejection in ticket redemption code

fail on non-zero exit codes

---

packages/connect/src/relay/index.ts

Whenever a node intends to use another node as a relay, it asks that node whether it wants to act as a relay, i.e.
Alice -> Relay:
```
CAN_RELAY?
```
Relay -> Alice:
```
OK
```
_Before_ replying with `OK`, the relay publishes this information to the DHT and await the result of that query. This easily takes > 10 seconds and unnecessarily increases the latency of the query.
When receiving the response, nodes will latencies > the threshold and therefore unnecessarily consider the node offline.
The relay replies with `OK` before awaiting the result of the DHT `provide` query.

do not await dht call

---

.github/workflows/deploy.yaml

The secret must be assigned to the environment, which wasn't the case before.

ci: Add missing api token in env for notification script

---

scripts/gcloud.sh

We don't need 16GB of memory. Thus, the smaller 4GB will provide a useful hard limit and make sure memory leaks don't overrun for too long.

gcloud: use smaller instances with less memory

---

CHANGELOG.md
packages/core/src/index.ts
packages/hoprd/src/api/v2/paths/channels/index.ts
packages/hoprd/src/api/v2/paths/channels/peerid.spec.ts
packages/hoprd/src/api/v2/paths/channels/{peerid}.ts
packages/hoprd/src/api/v2/paths/channels/{peerid}/direction.spec.ts
packages/hoprd/src/api/v2/paths/channels/{peerid}/{direction}.ts
packages/hoprd/src/commands/closeChannel.ts

Fixes https://github.com/hoprnet/hoprnet/issues/3627
- fix `/api/v2/channels/{peerid}` by requiring a `direction` to be specified `/api/v2/channels/{peerid}/{direction}`
- fix functions `getTickets` and `redeemTicketsInChannel` to use the incoming channel of the node and a counterparty, not the outgoing, since tickets can only exist and redeemed in incoming channels
- update `CHANGELOG.md`

improve `/api/v2/channels/{peerid}`

---

package.json
packages/hoprd/package.json
yarn.lock

Sets the resolution for `@ethersproject/providers` to a fork that contains **built** source code to solve a memory leak in `base-provder.ts`.
Source code lives in https://github.com/robertkiel/ethers.js.
Changes are:
- https://github.com/robertkiel/ethers.js/commit/0a05998ec821c44220e33a93a879a0e548edd4ca
- https://github.com/robertkiel/ethers.js/commit/fd356081d4e8aee3897c9aca5efa8d40f0a20922
- https://github.com/robertkiel/ethers.js/commit/d8942467d38816080f0710ebb4990df751a8746b
Fork is at https://github.com/hoprnet/ethers-js-provider
HTTP does not support pushes *from* the server, hence in order to get notified about new blockchain events, such as new blocks, the node needs to *poll*.
Ethers.js uses an optimized way to poll latest on-chain changes to keep the number of provider …

[Hotfix release/athens] Fix ethers.js http provider memory leak

---

scripts/build_lockfiles.sh
scripts/gcloud.sh

- Correctly use bash syntax http://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html#Command-Grouping in `build_lockfiles` script
- Fix GCloud machine region

fix syntax in lockfile script and update regions

---

packages/core/src/main.ts

Disables peerstore persistence due to issues with serialization and deserialization of PeerIds

disable peerstore persistence

---

packages/core-ethereum/src/indexer/index.spec.ts
packages/core-ethereum/src/indexer/index.ts

Fixes release block processing lock and enhances indexer tests that tackle indexer restarts to match all states that might occur during an indexer restart

e2e test fix and unit test fix

---

packages/connect/src/filter.spec.ts
packages/connect/src/filter.ts
packages/connect/src/utils/addrs.ts
packages/connect/src/utils/index.ts

Minor refactoring of the AddressFilter using enums and case distinction rather than plenty of `if` conditions

refactor address filtering

---

packages/core/src/index.ts
packages/core/src/main.ts
scripts/run-integration-tests-npm.sh
scripts/run-integration-tests-source.sh

This PR contains following changes:
- `peerstore` support has been added back
- peers removed from the `peerstore` via `NetworkPeers`
- small code tweaks
Refs #3692

Add back peerstore functionality

---

README.md
docs/hopr-documentation/docs/node/using-docker.md
packages/avado/build/Dockerfile
packages/avado/dappnode_package.json
packages/avado/docker-compose.yml
packages/cover-traffic-daemon/Dockerfile
packages/hoprd/Dockerfile
scripts/gcloud.sh
scripts/nat/start-nat-node.sh
scripts/testnet.sh

Fixes #3733 
The default path was changed as part of introducing the on-disk peer-store. Therefore, all uses of the path must be adapted as well.

Update db path used in Docker images to new default path prefix.

---

packages/connect/src/base/tcp.ts
packages/connect/src/index.ts
packages/connect/src/relay/index.ts

Some checks for `signal.aborted` are completely unnecessary and can cause issue with timeouts.

Remove unnecessary abort signal checks

---

package.json
yarn.lock

Fixes an error in libp2p which causes its `Dialer` to abort unrelated connection attempts
Relevant commit:
https://github.com/hoprnet/js-libp2p/commit/7d1badcb3d001629523b4ab39ce3f3e4adfa4639

fix unintended aborts

---

packages/connect/src/relay/index.ts

Remove unnecessary `AbortController` that guards the relay connection timeout. 
This is already handled upstream by libp2p.

Remove unnecessary abort

---

packages/utils/src/libp2p/dialHelper.ts

The connection attempt comprises of 3 stages:
- direct connection attempt
- DHT query for circuit addresses
- connection attempt via circuit addresses
All three of them were using the same `AbortController` which when failed in any stage due to timeout, prevented the further ones from ever happening. 
This PR removes the same `AbortController` so all of these stages can actually take place if needed.
This improves NAT-to-NAT functionality drastically.

Remove abort controller from circuit connection attempt

---

packages/core/src/index.ts
packages/core/src/network/heartbeat.ts

Adds a utility function that closes all (existing) open connections to a peer *and* catches errors that might occur when closing the connection(s).

utility function to close connections

---

packages/hoprd/src/index.ts

see https://github.com/hoprnet/hoprnet/issues/3755 for the implementation plan
Silences promise rejections caused by the following packages:
- `stream-to-it`: convert Node.js streams into AsyncIterable
- `abortable-iterator`: add an AbortController to an AsyncIterable

silence specific promise rejections

---

packages/connect/src/base/entry.ts
packages/connect/src/index.ts
packages/core/src/network/network-peers.ts
packages/hoprd/src/index.ts
packages/utils/src/libp2p/dialHelper.ts

This PR improves connection persistence:
- set system keep-alive flag for all direct TCP connections
- better handling of socket events and errors
- do not remove entry nodes on the list for the time being
- fixed heartbeat message values in the period log printout
Fixes #3770

Connection persistence improvements

---

CHANGELOG.md
packages/hoprd/src/index.ts
packages/utils/src/libp2p/dialHelper.ts

This PR fixes the event listener leak and increases maximum number of listeners to 20.
Fixes #3065 and should improve OOM situations like one described in #3502

Fix event listener leak on failed connection 

---

packages/core-ethereum/src/indexer/fixtures.ts
packages/core-ethereum/src/indexer/index.ts
packages/ethereum/contracts/HoprNetworkRegistry.sol
packages/ethereum/hardhat.config.ts
packages/ethereum/tasks/register.ts
packages/utils/src/db/db.spec.ts
packages/utils/src/db/db.ts
test/integration-test.sh

- use compressed representation as keys for storing network registry entries, see below why
- add a mapping from eligible Ethereum accounts to public key (hopr address)
- Finish migration from allowing multiaddrs to PeerIds, as started by #3783
The Network Registry is used as follows:
Check if incoming connection identified by the `PeerId` of the counterparty is allowed to connect
Input; PeerId (from TLS-like library) -> compressed public key representation
Once there is a new node that became eligible to connect, add it to the database
Input: PeerId (hopr address) from Multiaddr + Ethereum account -> compressed public key representation
Get the Ethereum account that fulfills the requirements to be allowed to establish a connection.
Input: PeerId (hopr address) from Multiaddr -> …

Whitelist efficiency enhancements + bugfix

---

CHANGELOG.md
packages/core/src/index.ts
packages/core/src/network/heartbeat.spec.ts
packages/core/src/network/heartbeat.ts
packages/core/src/network/network-peers.ts
packages/hoprd/src/index.ts

This PR creates necessary backend changes to implement Network Connectivity Indicator ("Semaphore") as described in #3758. This is the first step improve the user's understanding of when their node has a good connection to the rest of the P2P network.
The Semaphore currently supports 5 possible states (semaphore values):
- ❔  `Unknown`: initial value when the node is started. Means the connectivity could not be assessed.
- 🔴  `Red`: No connection to any nodes at all.
- 🟠  `Orange`: Low-quality (<= 0.5) connection to at least 1 public node.
- 🟡  `Yellow`: High-quality connection to at least 1 public node.
- 🟢  `Green`: High-quality connection to at least 1 public node and at least 1 non-public node.
The "connection" in this case means the ability to do ping/pong with a node, no matter …

Network Connectivity Indicator

---

CHANGELOG.md
packages/core-ethereum/src/ethereum.mock.ts
packages/core-ethereum/src/ethereum.ts
packages/core-ethereum/src/index.ts
packages/core-ethereum/src/indexer/index.mock.ts
packages/core-ethereum/src/indexer/index.ts
packages/core-ethereum/src/nonce-tracker.spec.ts
packages/core-ethereum/src/transaction-manager.spec.ts
packages/core-ethereum/src/transaction-manager.ts
packages/core/protocol-config-schema.json
packages/core/protocol-config.json
packages/core/src/environment.ts
packages/core/src/main.ts
packages/ethereum/hardhat.config.ts
scripts/fund-address.ts

A preliminary solution for https://github.com/hoprnet/hoprnet/issues/3745 and https://github.com/hoprnet/hoprnet/issues/3799.
In both tickets, provider starts to return `503` and `524` status code (where both relate to server overload) in response to `eth_getBlockByNumber` method. This method, as mentioned [in the comment](https://github.com/hoprnet/hoprnet/issues/3745#issuecomment-1127733733), are used by multiple functions in `ethers.js`. In our codebase, there are two places where `eth_getBlockByNumber` are primarily used:
1. `fetchNativeTxs` (that removes the transaction listener when the indexer process it as confirmed)
2. `feeData()` in `sendTransaction` (to get `maxFeePerGas` and `maxPriorityFeePerGas` according to EIP1559)
Changes in this PR includes:
1. Add condition in …

Reduce eth_getBlockByNumber calls 

---

packages/hoprd/crates/Makefile
packages/hoprd/crates/hoprd-misc/src/lib.rs
packages/hoprd/src/index.ts
packages/real/crates/real-base/src/real.rs
packages/real/src/io.spec.ts
packages/real/src/io.ts

This PR implements small refactoring of the Rust code, mainly:
- removal of `DataOrError` due to corrected `#[wasm_bindgen]` application
- unified JS code generation during build (usage of `nodejs` target instead of `bundler` in hoprd package)
This mostly simplifies code.

Smaller refactoring within Rust code

---

packages/hoprd/crates/Makefile
packages/hoprd/crates/hoprd-misc/src/lib.rs
packages/hoprd/src/index.ts

Fix `hoprd` not starting due to missing CJS extension on WASM module.

Fix use of CJS for WASM in hoprd

---

packages/ethereum/src/index.ts

Related to https://github.com/hoprnet/hoprnet/issues/3687
While we have moved `hopr-stake` smart contract to the monorepo, `devrel/stake` still uses `hopr-stake` repository.
The website depends on some types which the monorepo doesn't export.

export all contract types

---

packages/ethereum/src/index.ts

Related to https://github.com/hoprnet/hoprnet/issues/3687
While we have moved hopr-stake smart contract to the monorepo, devrel/stake still uses hopr-stake repository.
The website depends on some types which the monorepo doesn't export.

export xHoprToken type

---

packages/core/src/channel-strategy.ts
packages/core/src/index.ts
packages/core/src/network/access-control.ts
packages/core/src/network/network-peers.ts
packages/core/src/path/index.ts
packages/cover-traffic-daemon/src/index.ts
packages/cover-traffic-daemon/src/state.ts
packages/cover-traffic-daemon/src/strategy.ts
packages/cover-traffic-daemon/src/utils.ts
scripts/run-integration-tests-source.sh

Cherry-pick from #3836
- refactor channel topology StrategyTick API to use stronger typing
- reimplement ctd util function with enhanced complexity and stronger typing
- network peers: reimplement `getAll` + `getAllDenied` to use (synchronous) iterators instead of cloning arrays
- pass Heartbeat environment flags to `ctd` (as already done for `core`)
- use cryptographically sound entropy functions within `core` and `ctd`
- reimplement `ctd` state serialization and deserialization to use *no EC SQRT* operations
- fix e2e tests, see #3836 
- fix Rust crate test build issue

core + ctd refactoring & efficiency enhancements

---

packages/core/src/main.ts

Cherry-pick from #3836 
- use libp2p's connection gater API instead of overriding internal methods
See https://github.com/libp2p/js-libp2p/blob/13d95b413cc85092752a6dd3dbe998c6f935e2e6/src/libp2p.ts#L84-L95
- fix e2e tests, see #3836

use libp2p connection gater API

---

.github/workflows/deploy.yaml
.github/workflows/docs.yaml
.github/workflows/lint.yaml
Makefile
package.json
packages/connect/package.json
packages/core-ethereum/package.json
packages/core/package.json
packages/core/protocol-config.json
packages/cover-traffic-daemon/package.json
packages/ethereum/deploy/01_ERC1820Registry.ts
packages/ethereum/deploy/02_HoprToken.ts
packages/ethereum/deploy/03_HoprDistributor.ts
packages/ethereum/deploy/04_HoprWrapper.ts
packages/ethereum/deploy/05_HoprChannels.ts
packages/ethereum/deploy/06_xHoprMock.ts
packages/ethereum/deploy/07_HoprBoost.ts
packages/ethereum/deploy/08_HoprStake.ts
packages/ethereum/deploy/16_HoprNetworkRegistryProxy.ts
packages/ethereum/deploy/17_HoprNetworkRegistry.ts
packages/ethereum/deploy/20_mintDevNftTransferOwnership.ts
packages/ethereum/package.json
packages/hoprd/package.json
packages/real/package.json
packages/utils/package.json
scripts/build_lockfiles.sh
scripts/publish-version.sh

Replaced use of `npm version` with directly using the underlying `semver` tool, which reduces reliance on `npm`.
Also improved waiting for transactions during hardhat deploy.
Refs #3833 
- lockfile generation fails in CI

Fix NPM package versioning

---

.processes/tokens.md
package.json
packages/avado/releases.json
packages/connect/package.json
packages/core-ethereum/package.json
packages/core/package.json
packages/cover-traffic-daemon/Dockerfile
packages/cover-traffic-daemon/package.json
packages/ethereum/package.json
packages/hoprd/Dockerfile
packages/hoprd/package.json
packages/real/package.json
packages/utils/package.json
scripts/build-lockfiles.sh
scripts/publish-version.sh
yarn.lock

This unblocks the npm package publishing process. The problem was caused
by using a resolution to override a direct dependency.
Refs #3833

Fix npm lockfile generation

---

packages/core-ethereum/package.json
packages/core/package.json
packages/cover-traffic-daemon/package.json
packages/ethereum/package.hardhat.json
packages/hoprd/package.json
packages/real/package.json
packages/utils/package.json
packages/utils/src/index.ts
packages/utils/tsconfig.json
yarn.lock

Make packages self-containing, i.e. `npx tsc` will build all relevant Typescript files of a package

fix build issues

---

package.json
yarn.lock

This wrapper exposes the library as a JS executable. However,
installation is broken on some platforms. Thus, since we don't use it
yet, its better to remove it and later use native installation
mthods instead of yarn/npm.

Remove wasm-opt JS wrapper

---

packages/ethereum/tasks/register.ts
packages/ethereum/tasks/selfRegister.ts
packages/ethereum/tasks/stake.ts
packages/ethereum/test/HoprNetworkRegistry.test.ts

Refs #3899
`ethers.provider` cannot access hardhat-instance. Therefore, all the deployed contracts are not available.

Selected provider based on environment

---

Makefile

According to the default installation docs from `yarn`, it should be installed using `corepack`

Install yarn using Node.js corepack

---

packages/connect/src/base/entry.spec.ts
packages/connect/src/base/entry.ts
packages/connect/src/base/tcp.spec.ts
packages/connect/src/index.ts
packages/connect/src/relay/connection.ts
packages/connect/src/relay/index.ts

Fixes
```
hopr-connect:entry:error error while contacting entry node 16Uiu2HAmKfEux3LUxxKHf6gTebTDSEaTZvaSVZk3aTUKjgqA9usk. Cannot read properties of undefined (reading 'upgradeOutbound') +1ms
```

`connect` bugfix

---

CHANGELOG.md
packages/core/src/index.ts
packages/core/src/network/network-peers.ts
packages/hoprd/src/api/v2/paths/node/info.integration.spec.ts
packages/hoprd/src/api/v2/paths/node/info.ts

This PR modifies the `info` command and adds the following information there:
- `isEligible` - indicates if the staking account associated with the current node is eligible for network access
- `connectivityStatus` - either `RED`, `ORANGE`, `YELLOW ` or `GREEN` indicates the connectivity health (see #3758)
Also fixes too much logging verbosity when a peer is denied access.
Fixes #3915

Improvements to NR information visibility

---

packages/core/src/index.ts
packages/hoprd/src/api/v2/paths/node/info.integration.spec.ts
packages/hoprd/src/api/v2/paths/node/info.ts
packages/hoprd/src/index.ts

Fixes `/info` REST method that got broken with #3921 
Silence `read ECONNRESET` errors coming from `stream-to-it` library

fix broken info call

---

packages/hoprd/src/commands/commands.spec.ts
packages/hoprd/src/commands/info.ts

Changes introduced in #3921 added also to the `info` command for WebSocket interface.

Add NR and connectivity information to `info` WS command as well

---

packages/connect/src/base/listener.ts
packages/connect/src/base/stun.ts
packages/connect/src/relay/handshake.spec.ts
packages/connect/src/relay/handshake.ts
packages/connect/src/relay/index.ts

- Correctly pass libp2p upgrader instance when extending a connection to a relayed connection
- do not await timeouts when closing node process

Fix error in module injection & unregister timeouts

---

Makefile
scripts/setup-gcloud-cluster.sh

In the `Makefile` - use only `PRIVATE_KEY` environment variable to pass the private key to the NR related targets.

Pass the private key rather as an env variable

---

packages/hoprd/package.json

`hopr` uses the builtin JSON-loader based on ECMAScript modules to load JSON files, which is the new de-facto standard to import JSON files.
Loaded JSON files using `import` statements has been added to Node.js 16.15, hence `hoprd` requires Node.js 16.15 +

pin node.js version to 16.15

---

CHANGELOG.md
packages/avado/releases.json
packages/hoprd/src/commands/utils/message.spec.ts
packages/hoprd/src/commands/utils/message.ts
packages/hoprd/src/index.ts

This PR:
- adds proper unit test for `encodeMessage` and `decodeMessage` in HOPRd
- unifies code in HOPRd to use these functions
- fixes decoding
Closes #3935

Fix & unify message encoding and decoding

---

Makefile
NETWORK_REGISTRY.md

Some improvements to the NR docs and Makefile
- add `deregister-nodes` target to Makefile
- add missing `privkey` argument to `self-deregister` task call
- improved & unified docs
- removed `privkey` CLI args and use `PRIVATE_KEY` env variable instead

Improvements to the docs and the Makefile

---

.github/workflows/deploy.yaml

Makes sure GH Actions deploy nodes to GCP in-order (public first, then NAT nodes).

Deploy NAT nodes after Public nodes have been deployed

---

packages/ethereum/test/utils/constants.ts

eth.link has been "discontinued", see https://twitter.com/luigyGT/status/1554092735229034496

use eth.limo instead of eth.link

---

Makefile

Currently the `clean` and `reset` scripts in `package.json` can do the cleanup job well, so extended them as `Makefile` targets as well.
Some additional cleanup may be added.

Add Makefile targets for `clean` and `reset`

---

Makefile
NETWORK_REGISTRY.md
packages/ethereum/hardhat.config.ts
packages/ethereum/tasks/requestTestTokens.ts
scripts/get-hopr-address.sh
scripts/register-node.sh

When deployment multiple txHOPR contracts on the network, it is confusing to distinguish which contract is currently in use, especially when NR is introduced and txHOPR tokens can be used for staking and making accounts eligible.
Add `register-node-with-stake` make target to streamline the process of
- requesting txHOPR
- stake txHOPR
- register node to NR

Script for request txhopr

---

scripts/pluto/Dockerfile
scripts/setup-local-cluster.sh

This is required for external services to be able to access the hoprd
interfaces. Otherwise, the interfaces are only accessible from within
the container.
Ref https://github.com/hoprnet/playground/issues/1

Make hoprd nodes listen on external IP in pluto container

---

.github/workflows/e2e.yaml
Cargo.lock
Cargo.toml
Makefile
README.md
SETUP_LOCAL_CLUSTER.md
docs/hopr-documentation/docs/developers/starting-local-cluster.md
packages/hoprd/crates/hoprd-misc/Cargo.toml
packages/real/crates/real-base/Cargo.toml
packages/utils/crates/utils-misc/Cargo.toml
scripts/publish-version.sh
scripts/vm-nat-testing/README.md

- use `make` to build WASM boilerplate code
- remove `utils` dependency from Makefile from Typechain generation because `ethereum/hardhat` package no longer requires built utils
- move Rust `release.profile` to top-level `cargo.toml` as it is ignored otherwise - according to cargo

use make to initiate build of WASM packages

---

packages/hoprd/hopr-admin/src/state/useWS.ts

This bug made the HOPR admin not load if an endpoint behind `https` is used.

hopr-admin: Fix conversion of https to wss protocol string

---

packages/core/src/index.ts
packages/ethereum/contracts/HoprNetworkRegistry.sol
packages/hoprd/hopr-admin/src/commands/sendMessage.ts
packages/hoprd/hopr-admin/src/commands/withdraw.ts
packages/hoprd/hopr-admin/src/utils/command.spec.ts
packages/hoprd/hopr-admin/src/utils/command.ts
packages/hoprd/src/admin.ts
packages/hoprd/src/api/v2/paths/messages/sign.ts

- Fixes command sign message to create proper signature
- Fixes command withdraw to use currency spelling required by APIv2
- Fixes command send for multi-hop manual path usage
Fixes #3967

hopr-admin: Fix regression in commands in v2

---

scripts/testnet.sh

If funding wallet info cannot be retrieved, the deployment should fail and not silently continue.
Refs #3984

Check output of `funding_wallet_info` during deployment

---

packages/core/src/index.ts
packages/hoprd/hopr-admin/src/commands/channels.ts
packages/hoprd/hopr-admin/src/commands/openChannel.ts
packages/hoprd/src/index.ts

This PR addresses following issues:
- `Successfully opened channel "[object Promise]" to node "qBh8y".` (missing `await` on channel ID retrieval)
- Prevent opening channel to self (fixes #3994)
- The `channels` command prints `Outgoing channels` text for channels that are incoming
- Unhandled rejection handler in `hoprd` checks if `reason` is not `undefined` before printing `reason.message` (refs #3995 
Refs #3803

Various minor fixes to issues found during Paleochora release tests

---

CHANGELOG.md
packages/core/src/index.ts
packages/core/src/messages/packet.ts

Warn when duplicate peer id entries in the manual path selection
Closes #4006

Prevent duplicate peer ids in the manual path

---

packages/hoprd/src/index.ts

Silences ETIMEDOUT socket errors that lead to unhandled promise rejections.
The error is handled by `connect` code (see debug log) but for some reason it gets treated as an unhandled promise rejection
```
hopr-connect:error SOCKET ERROR on connection to /ip4/34.91.92.221/tcp/9091/p2p/16Uiu2HAm64wMg8mVM93qTRB71455R7EmS3yrWW78Q2ihYwqorz6C: ' {"errno":-110,"code":"ETIMEDOUT","syscall":"read"} +2ms
hopr-connect:tcp:error unexpected error in TCP sink function Error: read ETIMEDOUT
at TCP.onStreamRead (node:internal/stream_base_commons:217:20) {
errno: -110,
code: 'ETIMEDOUT',
syscall: 'read'
} +1ms
(node:433555) UnhandledPromiseRejectionWarning
Error: read ETIMEDOUT
at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
UnhandledPromiseRejectionWarning
Error: read ETIMEDOUT
at …
```

Silence ETIMEDOUT socket errors

---

packages/connect/src/base/entry.ts
packages/core-ethereum/src/indexer/index.ts
packages/core/src/index.ts
packages/utils/src/async/backoff.spec.ts
packages/utils/src/async/backoff.ts

- rename `retryWithBackoff` to `retryWithBackoffThenThrow` to highlight *that* it will throw if none of the retries were successful
- add convenience functions to precompute *when* and after *how many* retries the function *will eventually* throw.
- simplify unit tests
- add try / catch block to indexer restart functionality

Enhance backoff and waitForFunds functionality 

---

packages/connect/src/base/entry.ts
packages/connect/src/index.ts

Establishing a connection to a node goes through two main steps
- finding a way to send raw packets to that node
- negotiating with the node which protocol and which version to use
Due to unclear network conditions, both of the steps need to deal with unexpected behavior, such as nodes suddenly stopping the communication or bugs that prevent correct execution.
Add a timeout to the protocol upgrade, which is libp2p's name for protocol negotiation.
The issue is properly fixed by changing code within `js-libp2p` or `libp2p-noise` (the TLS-like module)

Timeout connection upgrade

---

packages/avado/dappnode_package.json
scripts/build_avado.sh

This PR fixes the following:
- API endpoint and token are statically embedded into the URL that appears in the Avado UI for HOPR. This is a temp fix, because if the user decides to change the token, the token in the URL won't change and they'll have to enter it manually in the UI.
- Backport a fix from `master` (see #4014 ): environment ID and provider env variables were incorrectly populated in the CI build

Add API endpoint & token to Avado URL, backport environment ID fix

---

packages/core/src/index.ts

Fixes regression introduced by fixing #4015.
In general, we should re-factor the code so that state diagram of lifecycle of our classes is closed and consistent.

Allow calling `Hopr.stop()` called without `Hopr.start()` being called first

---

Makefile
NETWORK_REGISTRY.md
scripts/get-hopr-address.sh

- When registering node to NR, it must pass an additional field `api_token` in the make target when registering a node in order to retrieve peerId automatically
- update readme
Fixes #3993

must accept api token when registering

---

CHANGELOG.md
packages/core/src/index.ts
packages/hoprd/hopr-admin/src/commands/entryNodes.ts
packages/hoprd/hopr-admin/src/commands/help.ts
packages/hoprd/hopr-admin/src/commands/index.ts
packages/hoprd/hopr-admin/src/utils/api.ts
packages/hoprd/src/api/v2/paths/node/entryNodes.integration.spec.ts
packages/hoprd/src/api/v2/paths/node/entryNodes.ts
packages/hoprd/src/api/v2/paths/node/peers.integration.spec.ts
packages/hoprd/src/api/v2/paths/peerInfo/{peerid}.spec.ts

- adds `entryNodes` API to `hoprd` to show known entry nodes
- adds `entryNodes` command to `hopr-admin`
- sort commands on help page alphabetically
- stronger typing
- some typos

add entryNodes command

---

packages/core/src/index.ts
packages/hoprd/hopr-admin/src/commands/sendMessage.spec.ts
packages/hoprd/hopr-admin/src/commands/sendMessage.ts
packages/hoprd/hopr-admin/src/utils/api.ts
packages/hoprd/src/api/v2.ts
packages/hoprd/src/api/v2/paths/messages/index.ts
packages/hoprd/src/index.ts

This PR changes the following:
- removes waiting by the API for message acknowledgment after sending
- adds global event handler for message acknowledgments
- sends per-message acknowledgments via WS: `ack:'aabbccddeeff...'`
- refactoring in `sendMessage`
Closes #3599

Do not await message acknowledgements in the API, code refactoring

---

docs/hopr-documentation/docs/developers/starting-local-cluster.md
packages/hoprd/hopr-admin/pages/index.tsx
packages/hoprd/hopr-admin/src/commands/help.ts
packages/hoprd/hopr-admin/src/commands/sendMessage.ts
packages/hoprd/hopr-admin/src/state/index.ts
packages/hoprd/hopr-admin/src/utils/command.ts
packages/hoprd/hopr-admin/src/utils/stream.ts
packages/hoprd/src/api/v2.ts
packages/hoprd/src/api/v2/paths/node/stream/websocket.ts
packages/hoprd/src/logs.ts
scripts/setup-local-cluster.sh

- Fixes https://github.com/hoprnet/hoprnet/issues/4001 (manual path issue)
- Improves `constant` command type
- Removes unused `/messages` code in `hopr-admin`
we will keep using `/legacy` stream since it gives you back the history of the logs upon connection, we don't have an API v2 alternative
- Fixes legacy stream bug
1. it should behave like legacy, filtering out messages was a mistake
2. unsubscribe socket when connection is closed
3. remove unused code
- Fix cluster script and update documentation

hopr-admin bugs fixes vol 2

---

packages/hoprd/package.json
yarn.lock

Forces `hoprd` to use `@multiformats/multiaddr` at `10.3.3`

Fix multiaddr to 10.3.3 in hoprd

---

packages/hoprd/Dockerfile

Removes unnecessary stuff from the Docker container
- don't install `devDependencies`
- remove all unused packages, such as `avado` and `cover-traffic-daemon`
- remove lots of unused files
- cleans yarn cache

shrink Docker container

---

Makefile
NETWORK_REGISTRY.md
docs/hopr-documentation/docs/developers/network-registry.md
packages/ethereum/contracts/proxy/HoprStakingProxyForNetworkRegistry.sol
packages/ethereum/deploy/16_HoprNetworkRegistryProxy.ts
packages/ethereum/deploy/20_mintNetworkRegistryNfts.ts
packages/ethereum/hardhat.config.ts
packages/ethereum/tasks/register.ts
packages/ethereum/tasks/requestTestTokens.ts
packages/ethereum/tasks/stake.ts
packages/ethereum/test/HoprNetworkRegistry.test.ts
packages/ethereum/test/proxy/HoprStakingProxyForNetworkRegistry.test.ts
packages/ethereum/utils/constants.ts
scripts/register-node.sh
scripts/setup-gcloud-cluster.sh

- Closes https://github.com/hoprnet/hoprnet/issues/4065 (except for contract deployment)
- Fix "remove" in `packages/ethereum/tasks/register.ts`. It should call `ownerDeregister(peerIds)` despite proxy being in usage and only force checking `addresses` when dummy proxy is used, because an additional call of `ownerBatchRemoveAccounts(addresses)` must be done on the proxy contract.

Replace Dummy Proxy with StakingProxy

---

NETWORK_REGISTRY.md
packages/ethereum/contracts/proxy/HoprStakingProxyForNetworkRegistry.sol
packages/ethereum/deploy/02_HoprToken.ts
packages/ethereum/deploy/16_HoprNetworkRegistryProxy.ts
packages/ethereum/deploy/17_HoprNetworkRegistry.ts
packages/ethereum/deploy/20_mintNetworkRegistryNfts.ts

Fix https://github.com/hoprnet/hoprnet/issues/4109
- Fix bug in SC that does not update `maxRegistrationsPerSpecialNft` when adding a special NFT
- Fix script that skip adding special NFTs in production environment
- Skip HoprToken deployment in staging and prod. 
- Allow proxy to be updated when a NR contract is in place. (Note: This will always update the proxy implementation in the last NetworkRegistry contract, even when a new NR contract will be deployed.)

Deploy script registers nodes to NR

---

scripts/get-default-environment.sh

Script should output the actual environment_id from releases.json

Fix the `get-default-environment` script

---

packages/hoprd/Dockerfile
packages/hoprd/src/index.ts
scripts/run-integration-tests-source.sh

Some bugfixes to enhance usability
- set default `data` directory to user-mountable directory
-  make `--testNoAuthentication` conflict with `--apiToken`
- hide some debugging CLI arguments
- fail on unknown arguments, this *explicitly* includes typos such as `--testNoAuthenticatio`
- allow user to see hidden CLI arguments through `--show-hidden`

Enhance option parsing

---

packages/core/src/index.ts

Fix unhandled promise rejection when node is left unfunded for some time.
Refs #4015

Fix unhandled promise rejection when not funded

---

scripts/nat/start-nat-node.sh

Environment variables that are prefixed by `HOPRD_` are treated as CLI arguments, hence copying an entire environment should unset all `HOPRD_` prefixed variables that are not meant to be passed to the `hoprd` process.
- when building `hoprd-behind-nat` image, unset all irrelevant `HOPRD_` prefixed environment variables before passing them into the internal `hoprd` image.

unset HOPRD_ environment variables

---

packages/hoprd/src/index.ts

`trace-unhandled` is used to decorate unhandled promise rejection in order to enhance debugging. This requires encapsulating each promise by a `TraceablePromise` which requires a lot of CPU time. 
- do not load *or* register `trace-unhandled` if `NODE_ENV == production`

Silence trace unhandled

---

packages/hoprd/Dockerfile

`node-webrtc` supports two builds - a Release build and a Debug build, including debug symbols
- when installing node packages within production `hoprd` Docker image, use Release build instead of Debug build, see https://github.com/node-webrtc/node-webrtc/blob/685aa433623b9bf98e8c7c0124e7864e01b883e6/scripts/download-prebuilt.js#L11

Use webrtc release build

---

Makefile

Fix missing `s` when calling `self-register-node`

fix type in self-register-node

---

packages/core/src/index.ts
packages/core/src/main.ts

Libp2p's DHT implementation provides its own availability measurement functionality. By default, `libp2p` runs two DHTs, one for WAN and one for LAN. This distinction is beneficial since routing works differently in a local network than in a global public network. In its current version, it seems that some ping attempts issued *by the DHT* never get done, so these queues grow without bounds and thus causes the process to consume way more memory than necessary.
See https://github.com/libp2p/js-libp2p-kad-dht/blob/a6129f39732f78217fe8cd6410c76b6332613353/src/routing-table/index.ts#L93
- manually wipes both LAN and WAN ping queues every minute
- reduces the *DHT* ping timeout from 10s to 2s

free memory from DHT ping queues

---

packages/connect/src/relay/handshake.ts

Attempt to fix unhandled promise rejections on Relay nodes, like:
````
2022-09-17T21:54:08.649Z hopr-connect:relay:handshake counterparty identified as 16Uiu2HAkw6Kv7prypc7mt1VkxeRYUHEBMaA6ndNxPBCSitxU7G5n
2022-09-17T21:54:08.651Z hopr-connect:relay:handshake:error Failed to create circuit from 16Uiu2HAm3h1kuHHmgmpt4yktaZKAmxNsjg6wVw7hbFF245pKPyCw to 16Uiu2HAkw6Kv7prypc7mt1VkxeRYUHEBMaA6ndNxPBCSitxU7G5n because destination is not reachable
UnhandledPromiseRejectionWarning
Error: aborted
at connResetException (node:internal/errors:692:14)
at abortIncoming (node:_http_server:602:17)
at socketOnClose (node:_http_server:596:3)
at Socket.emit (node:events:539:35)
at TCP.<anonymous> (node:net:709:12) {
code: 'ECONNRESET'
}
````

Add try/catch to shaker.write uses

---

packages/hoprd/hopr-admin/pages/index.tsx

Period update of aliases in HOPR Admin UI can cause unhandled promise rejection.
Plus some minor readability refactoring
Possibly fixes #4046

Fix potential unhandled promise rejection

---

.processes/wallets.md
DAPPNODE_PUBLISH.md

- updates `wallets.md` with the Dappnode HOPR Repo Owner wallet
- adds `DAPPNODE_PUBLISH.md` with a guide on how to publish a version to Dappnode Public repo.

Update wallets.md & add Dappnode Public repo release guide

---

packages/connect/src/relay/connection.spec.ts
packages/connect/src/relay/connection.ts
packages/connect/src/relay/index.ts
packages/connect/src/utils/index.ts
packages/connect/src/webrtc/connection.spec.ts
packages/connect/src/webrtc/connection.ts

Refs https://github.com/hoprnet/hoprnet/issues/4042
Streams in `connect` are implemented using AsyncIterables, hence consuming a stream is done by
```ts
for await (const chunk of stream) {
console.log(`stream msg`, msg)
}
```
whereas `stream` gets constructed by implementing the `[Symbol.asyncIterator]()` property of a class, or - as done in `connect` - using Generators, meaning
```ts
const stream = (async function * () {
yield stringToU8a(`0xdeadbeef`)
})()
```
Note that the Generator is functionable *once* it has been called. In contrast to "normal" functions, Generator *always* run in *their own* scope, so if the body needs to access properties such as `this`, it needs to be explicitly passed to the object, meaning.
```ts
const stream = async function * () {
this.doSthFancy()
yield …
```

explicit extent

---

CHANGELOG.md
scripts/pluto/Dockerfile

Replace `yarn` with `npx` in `pluto` Docker image to run `hoprd` to fix binary discoverability issue

pluto: Use npx instead of yarn to start hoprd

---

CHANGELOG.md
Makefile
packages/connect/src/base/entry.ts
packages/connect/src/constants.ts
packages/connect/src/relay/handshake.ts
packages/connect/src/relay/index.ts
packages/connect/src/types.ts
packages/core/src/index.ts
packages/core/src/main.ts
packages/core/src/network/heartbeat.spec.ts
packages/utils/src/libp2p/dialHelper.spec.ts
packages/utils/src/libp2p/dialHelper.ts
packages/utils/src/libp2p/index.spec.ts
packages/utils/src/libp2p/index.ts

Refs #4037 
Must be back-ported to #3803 in order to make https://github.com/hoprnet/hoprnet/pull/4167 work.
---
We previously called all libp2p connection handlers with a single
specified and supported protocol-prefix which was tied to the version
the node is running. This prevented nodes with different versions
communicating within the same environment even though they might be
supporting that as per the protocol config.
This change adds support for providing multiple supported protocols to
libp2p, which will handle the negotiation and pick the right protocol.
The supported protocols are determined based on the environments from the
protocol config.

connect: Add support for handling multiple protocols

---

CHANGELOG.md
packages/avado/docker-compose.yml

The companion change for dappnode is https://github.com/hoprnet/DAppNodePackage-Hopr/pull/3

Avado: limit Docker container memory to maximum 1GB

---

.github/workflows/e2e-npm.yaml
.github/workflows/e2e.yaml

Bumps `upload-artifacts` in GH actions to latest version to reduce errors such as https://github.com/hoprnet/hoprnet/actions/runs/3150122687/jobs/5122544786
See https://github.com/actions/upload-artifact/releases for changes

bump upload artifacts

---

packages/connect/src/index.ts
packages/connect/src/relay/connection.ts
packages/connect/src/types.ts
packages/connect/src/webrtc/connection.ts
packages/core/src/index.ts

Adds better distinction between multiple types of relayed connection, including
- `WEBRTC_DIRECT` -> WebRTC was successful, now using a direct connection
- `WEBRTC_RELAYED` -> initial state and fallback if WebRTC upgrade failed, i.e. due to bidirectional NAT
- `RELAYED` - configuration permits WebRTC upgrades, used for testing

More indicators

---

packages/cover-traffic-daemon/src/index.ts
packages/hoprd/src/index.ts
packages/utils/src/process/index.ts
packages/utils/src/process/promiseRejectionFilter.ts

Streamlines the promise rejection filter to be usable in both leaf packages, `ctd` and `hoprd`.
Promises originating from socket errors that cannot be caught for some reason are now silenced for all packages that import that function.

streamline promise rejection filter

---

packages/ethereum/deploy/postDeploy.ts

Related to failure in [GitHub Actions](https://github.com/hoprnet/hoprnet/actions/runs/3200007234)
- Simply skip post-deployment contract source code verification when reaching API limit.
- Fix a typo

skip contract verification if verification status is unclear

---

packages/core/src/index.ts
packages/core/src/interactions/packet/acknowledgement.ts
packages/core/src/interactions/packet/forward.ts
packages/core/src/network/heartbeat.spec.ts
packages/core/src/network/heartbeat.ts

Recently, `hopr` switched from protocol identifiers, such as
```
/hopr/<ENVIRONMENT>/ack
```
to 
```
/hopr/<ENVIRONMENT>/ack/<VERSION>
```
Inbound connections with *old* protocol identifiers work on *new* nodes. Whereas outbound connection don't work.
This PR allows node to interact with *new* and *old* identifiers.

fix protocol identifiers

---

packages/hoprd/src/api/v2.ts

A followup PR after #4210 
Fixes #4217 
Refs #4181

Properly use `encodeURIComponent` instead of `encodeURI`

---

packages/core-ethereum/src/indexer/index.ts

Handle some additional code path that can throw an exception:
````
hopr-core-ethereum:indexer channel-updated for hash 0x365d48786495f92d5f001f6d386dd5fbd8d5f9c2e6c7e0a7c36e580a5fdaf528 +0ms
(node:196996) UnhandledPromiseRejectionWarning
Error: Could not find public key for address - have they announced? -0xea021b6A4b2AdD6C04a5174913D63873aEc0dA0D
at Indexer.getPublicKeyOf (file:///home/luc/repos/hopr/hoprnet/packages/core-ethereum/lib/indexer/index.js:720:15)
at async Function.fromSCEvent (file:///home/luc/repos/hopr/hoprnet/packages/utils/lib/types/channelEntry.js:90:33)
at async Indexer.onChannelUpdated (file:///home/luc/repos/hopr/hoprnet/packages/core-ethereum/lib/indexer/index.js:595:25)
at async Indexer.processUnconfirmedEvents …
```

Handle exceptions thrown within Indexer

---

packages/hoprd/src/api/v2.ts

The `:` character was not encoded using `encodeURI`, but since we switched to `encodeURIComponet`, a fix is needed to make `Authorization` header parsing work again.

Split auth token then encode

---

packages/connect/src/base/entry.spec.ts
packages/connect/src/base/entry.ts
packages/connect/src/base/listener.ts
packages/connect/src/base/tcp.spec.ts
packages/connect/src/base/tcp.ts
packages/connect/src/index.ts
packages/connect/src/relay/index.ts
packages/connect/src/webrtc/connection.ts
packages/utils/src/process/promiseRejectionFilter.ts

Second cherry-pick from #4171 
After opening and writing to a socket, user-space code in the Node.js process needs to explicitly call `socket.end()` and afterwards `socket.destroy()`. Whereas, `socket.end()` makes the socket send a FIN packet to the other party and thus creates a *half-open* connection, `socket.destroy()` effectively closes the socket, no matter whether one of the parties has sent a FIN packet.
Thus, the *send* workflow is changed as follows from:
```ts
for await (const chunk of toSend) {
socket.send(chunk)
}
```
to
```ts
for await (const chunk of toSend) {
socket.send(chunk)
}
// added by the PR
socket.end()
```
Once a NATed node connects to a public relay, this connection might eventually become one of the only connection through which other nodes can reach this node - …

enhance tcp socket teardowns

---

packages/core/src/index.ts

A typo caused that PeerIds of public nodes were not added properly to the cache.

Fix typo in the public node cache

---

CHANGELOG.md
packages/connect/package.json
packages/connect/src/base/entry.ts
packages/connect/src/base/listener.ts
packages/connect/src/base/stun.ts
packages/connect/src/base/tcp.spec.ts
packages/connect/src/base/tcp.ts
packages/connect/src/relay/context.ts
packages/connect/src/relay/state.ts
packages/connect/src/webrtc/connection.spec.ts
packages/connect/src/webrtc/connection.ts
packages/core/package.json
packages/core/src/constants.ts
packages/core/src/index.ts
packages/core/src/network/heartbeat.spec.ts
packages/core/src/network/heartbeat.ts
packages/hoprd/package.json
packages/hoprd/src/admin.ts
packages/hoprd/src/api/v2/paths/node/peers.ts
packages/hoprd/src/logs.ts
packages/utils/package.json
packages/utils/src/async/parallel.ts
packages/utils/src/async/timeout.spec.ts
packages/utils/src/async/timeout.ts
packages/utils/src/libp2p/dialHelper.spec.ts
packages/utils/src/libp2p/dialHelper.ts
packages/utils/src/libp2p/index.ts
yarn.lock

In general, timeouts Javascript are used as:
```ts
const timeout = setTimeout(() => console.log('never shown'), 500)
// do stuff
clearTimeout(timeout)
```
This works as long as there are a only a few timeout, but soon `clearTimeout` becomes an expensive operation.
`retimer` and `timeout-abort-controller` "reuse" timeouts to prevent the usage of `clearTimeout` to free timeouts.
This PR replaces several critical occurences by `retimer` / `timeout-abort-controller` to save memory and CPU time.
Previously: many protocols set their own dial timeout, leading to undeterministic behavior when connecting to other nodes, plus created lots of listeners to AbortControllers.
New behavior: Dial attempts are split into two stages: 
- establishing a message stream and
- handling the specified protocol …

timeout refactor & more iterables

---

CHANGELOG.md
packages/core/package.json
packages/core/src/index.ts
packages/core/src/interactions/packet/acknowledgement.ts
packages/core/src/interactions/packet/forward.ts
packages/core/src/interactions/packet/index.spec.ts
packages/core/src/mixer.spec.ts
packages/core/src/mixer.ts
yarn.lock

This PR improves scheduling and reduces locking
Reimplement mixer as async interable, which
- allows removal of `await setImmediate()` in `ForwardInteraction`
- limits backpressure for relaying mixnet packets
Reimplement acknowledgement workflow to:
- have a queue for `outgoing` acknowledgements (send queue)
- have a queue for `incoming` acknowledgements (receive queue)
- allow removal of `await setImmediate()`
Individual packet send queues for individual recipients

non-blocking mixer & proper acknowledgement queueing

---

CHANGELOG.md
packages/connect/src/index.ts
packages/connect/src/relay/connection.ts
packages/connect/src/relay/handshake.spec.ts
packages/connect/src/relay/handshake.ts
packages/connect/src/relay/index.spec.ts
packages/connect/src/relay/index.ts
packages/connect/src/utils/libp2p.mock.spec.ts

Cherry-pick from #4171 
Current bevavior: `connect` ignores any existing connect when initiating a relayed connection over a public relay.
New behavior: Reuse existing connections by using same connection method as other sub-protocols
Implements a minimal version of libp2p for testing that does not require any real sockets.

mitigate duplicate relay connections

---

CHANGELOG.md
packages/connect/src/base/entry.spec.ts
packages/connect/src/base/entry.ts
packages/connect/src/base/listener.ts
packages/connect/src/index.ts

cherry-pick from #4171 
**Current behavior**: Whenever `connect` connects to an entry node, e.g. to reserve a relay slot, it creates a new connection to the entry nodes, no matter whether there was already a connection.
**New behavior**: Reuse existing connections and use same dial method as rest of the code.

mitigate duplicate entry connections

---

CHANGELOG.md
packages/core/src/index.ts
packages/core/src/main.ts
packages/utils/src/network/addrs.spec.ts
packages/utils/src/network/addrs.ts

Filter multiaddrs that are stored in libp2p's peer-store.
Current behavior: addresses appear twice, namely
```
/ip4/1.2.3.4/tcp/23/p2p/16Uiu2HAmQBZA4TzjKjU5fpCSprGuM2y8mpepNwMS6ZKFATiKg68h
/ip4/1.2.3.4/tcp/23
/p2p/16Uiu2HAkzEnkW3xGJbvpXSXmvVR177LcR4Sw7z5S1ijuBcnbVFsV/p2p-circuit
/p2p/16Uiu2HAkzEnkW3xGJbvpXSXmvVR177LcR4Sw7z5S1ijuBcnbVFsV/p2p-circuit/p2p/16Uiu2HAmQBZA4TzjKjU5fpCSprGuM2y8mpepNwMS6ZKFATiKg68h
```
... which causes libp2p to interpret them as multiple addresses for the same peer, and thus try to dial the same address more than once
New behavior: addresses get filtered before they are added to the peer-store, leading to
```
/ip4/1.2.3.4/tcp/23
/p2p/16Uiu2HAkzEnkW3xGJbvpXSXmvVR177LcR4Sw7z5S1ijuBcnbVFsV/p2p-circuit
```

filter multiaddrs

---

packages/core/protocol-config.json

Version 1.91 will be supported in `monte_rosa` environment.

Add 1.91 version range as supported in `monte_rosa` environment

---

CHANGELOG.md
packages/core/src/index.ts

Users can use the `info` command to get meaningful information before the node has finished startup

Allow `info` command before node has finished startup

---

packages/utils/src/process/promiseRejectionFilter.ts

Closes #4057
The error is silenced because it can be safely ignored.

silence promise rejection

---

package.json
yarn.lock

Fixes an issue in `it-length-prefixed` which caused the process to randomly allocate 10 KB memory.
Relevant commit https://github.com/hoprnet/it-length-prefixed/commit/458eae4d1e832c6f7434e60f82ba29d84023b6c7
Solved with libp2p 0.38+

Fix `it-length-prefixed` to allocate less memory

---

packages/ethereum/src/index.ts

Blocks deployment of staking website.

ethereum: add missing export of HoprStakeSeason5

---

packages/cover-traffic-daemon/package.json
packages/hoprd/package.json

Fixes build issues in Docker, see https://github.com/hoprnet/hoprnet/actions/runs/3297241630/jobs/5437981744

Fix hoprd/ctd engine spec to allow more recent NodeJS versions

---

packages/core/protocol-config.json

Gas prices are up to 40 now. This change unblocks `master` deployment workflows.
See https://explorer.bitquery.io/goerli/gas?from=2022-10-01&till=2022-10-24

ci: Raise gas price for Goerli to 50gwei

---

packages/core/protocol-config.json

We only perform very few operations, so let's raise the limit further temporary.

ci: Raise gas price for Goerli to 200gwei

---

packages/connect/crates/Makefile
packages/core-ethereum/crates/Makefile
packages/core/crates/Makefile
packages/core/src/network/heartbeat.ts
packages/cover-traffic-daemon/crates/Makefile
packages/ethereum/crates/Makefile
packages/hoprd/crates/Makefile
packages/real/crates/Makefile
packages/utils/crates/Makefile

A leftover bug introduced during the Rust improvements PR - only WASM tests were running. After this fix `cargo test` and `npx wasm-pack test` should run both.
Bonus fix: proper heartbeat time measurement

Make all tests run during Rust crates testing + minor metric fix

---

CHANGELOG.md
package.json
packages/core/src/main.ts
packages/utils/src/libp2p/dialHelper.spec.ts
packages/utils/src/libp2p/relayCode.spec.ts
yarn.lock

TLDR; replaces DHT package by a fork to disable `lan` DHT in order to use less memory
Libp2p uses a DHT that consists of a DHT meant for nodes living in different subnets and those who live in the same subnet. The former one is known as `wan` DHT and the latter as `lan` DHT.
Entries in the DHT are organized within `kBuckets`. Once an entry reaches its full capacity, it need to get split into smaller buckets - which is done by those nodes who run the DHT in *server*-mode.
If a node detects that a bucket need to get split, it starts to *find* another node which runs the DHT in *server*-mode.
By default, both DHTs, `lan` and `wan` are running in *client*-mode, which means they depend on others to split the DHT buckets. For `wan` DHT, the value can be configured, i.e. all `hoprd` entry nodes …

mono dht, disable dual dht

---

README.md

We agreed to change the memory limit of the running Docker container to 2GB.
This PR reflects that change in the docs.
Closes #4271

Change Docker memory limit to 2GB in docs

---

.github/workflows/deploy.yaml
.github/workflows/lint.yaml
.github/workflows/pr_checks.yaml
CHANGELOG.md
scripts/deployment-gater.sh
scripts/deployment-status.sh
scripts/gcloud.sh

This PR adds Failure Flags into project-wide GCP metadata.
- Failure Flags are specific per branch that is supposed to have an active GCP deployment (e.g. `master`, `release/**`, `debug-deploy/**`).
- the Failure Flag is set before a deployment to GCP is triggered via GH Action on  branch
- as soon as the GCP deployment via GH Action has *successfully* finished (public nodes up, NAT nodes up and Avado build succeded), the Failure Flag for that deployment is unset.
- when a commit is made to a PR with a target to a branch that is supposed to have an active deployment, a pre-merge check is made to find out if there's a Failure Flag set (a set flag indicates last deployment via GH action did not succeed or hasn't finished yet)
- PR pre-merge check will also fail when deployment on the target …

Indicator of a broken deployment in pre-merge check

---

packages/connect/src/base/entry.ts
packages/core/src/main.ts
packages/utils/src/libp2p/dialHelper.ts

Fixes a bug where non-entry nodes, i.e. NATed nodes cannot connect to any relay node
This was caused by the address filter which takes care that addresses are not added twice (and thus dialed twice).

enhance debug log of dialHelper

---

cloudbuild.yaml

Increases timeouts in `cloudbuild.yaml` to 20 minutes to make sure the build does not fail with errors like:
````
Finished Step #3 - "buildHardhat"
ERROR
ERROR: build step 3 "gcr.io/kaniko-project/executor:latest" failed: context deadline exceeded
````

Increase GCloud build timeouts

---

Makefile
package.json
packages/connect/crates/Makefile
packages/core-ethereum/crates/Makefile
packages/core/crates/Makefile
packages/cover-traffic-daemon/crates/Makefile
packages/ethereum/crates/Makefile
packages/hoprd/crates/Makefile
packages/real/crates/Makefile
packages/utils/crates/Makefile
yarn.lock

Install `wasm-pack` using `cargo` to make sure the correct version is used according to the platform.
Closes #4317

Use `cargo` to install `wasm-pack`

---

scripts/setup-local-cluster.sh

Fixes what gets printed out by the `setup-local-cluster` scripts, so users use the correct WebSocket URL.

Fix `setup-local-cluster` script to use correct WS URL

---

Dockerfile.hardhat
docs/hopr-documentation/docs/node/hoprd-commands.md
packages/ethereum/package.hardhat.json
packages/ethereum/package.json
yarn.lock

The build was broken due to more recent `solc` requiring libc compat files in Alpine and Hardhat ignoring errors from the execution of `solc`. This led to deadlocked compilation attempts.
Hardhat fix: https://github.com/NomicFoundation/hardhat/pull/3284
This changes adds the required compat files in our Alpine image as well.

Fix compilation of smart contracts in Docker containers

---

scripts/pluto/Dockerfile

The recent improvement now trigger a simple link error. This PR removes the obsolete commands.
See https://github.com/hoprnet/hoprnet/actions/runs/3376397699/jobs/5604376199

pluto: Remove now obsolete link in Docker file

---

packages/cover-traffic-daemon/Dockerfile

The `--experimental-wasm-modules` flag was missing in the Cover Traffic Daemon.

Add missing flag in the CTD

---

packages/avado/docker-compose.yml
scripts/build_avado.sh

The `0.100.0` Docker tag is not published for Avado to grab.

Use proper upstream version tag for Avado on `master`

---

.github/workflows/deploy.yaml
Dockerfile.hardhat
cloudbuild.yaml
packages/avado/docker-compose.yml
packages/cover-traffic-daemon/Dockerfile
packages/ethereum/package.hardhat.json
packages/ethereum/package.json
scripts/build_avado.sh
scripts/deployment-gater.sh
scripts/pluto/Dockerfile
yarn.lock

Backports of the following PRs to `release/bogota`. 
- #4331 
- #4330 
- #4329 
- #4327
- #4326 
This should unblock the Docker image build for Bogota.

Backported hotfixes to unblock CI Docker & Avado builds

---

packages/hoprd/Dockerfile
packages/hoprd/src/main.cts

- Changes the shebang to forward specific environment variables, namely `NODE_OPTIONS` and `DEBUG`
- Directly use `node` process to start `horpd` client. This is possible because we're not using *pnp* and / or *zero-installs*
This is a temporary fix! Forwarding additional environment variablesor fixing that properly is out of scope, will be fixed by https://github.com/hoprnet/hoprnet/pull/4320

fix shebang

---

Makefile
NETWORK_REGISTRY.md
packages/ethereum/deploy/20_mintNetworkRegistryNfts.ts
packages/ethereum/tasks/selfRegister.ts
packages/ethereum/utils/constants.ts
scripts/setup-gcloud-cluster.sh

Close #4101 
CI used to use `ownerRegister` and register VM instances under 4 staking wallets (`CLUSTER_NETWORK_REGISTERY_LINKED_ADDRESSES`). Each staking wallet has to have one NR NFT staked in the ongoing staking season. This approach become obsolete as the NetworkRegistry allows staking account with "Network_registry/developer" to register multiple peers. 
This PR
- Removes `CLUSTER_NETWORK_REGISTERY_LINKED_ADDRESSES` in hardhat tasks as well as `STAKING_ACCOUNT_BA28`, `STAKING_ACCOUNT_F84B`, `STAKING_ACCOUNT_0FD4`, `STAKING_ACCOUNT_6C15` from `setup-gcloud-cluster.sh`.
- Makes the CI wallet the default associated staking account for all VM instances in the deployed cluster.
- Replaces "HOPRD_STAKING_ADDR" with "HOPRD_STAKING_STATUS" in `instance_metadata`.
Some on-chain actions have …

CI register VM instances with `selfRegister`

---

CHANGELOG.md
packages/core/src/index.ts
packages/core/src/network/heartbeat.spec.ts
packages/core/src/network/heartbeat.ts

This PR modifies the criteria for the GREEN state of the Connectivity Indicator, refs #3758
Connectivity indicator is GREEN if:
at least 1 HQ connection to a public node AND
at least 1 HQ connection to a NAT-node OR being a public relay (= used the --announce CLI flag)
Closes #4313

Allow connectivity indicator to be GREEN on public nodes too

---

scripts/setup-local-cluster.sh

Fixes what gets printed out by the setup-local-cluster scripts, so users use the correct WebSocket URL.
Cherry picked from commit 9b1602c19b249fc6e7ac24e4e6f699e8e1a1906a as hotfix for release Bogota 
See #4321

Fix `setup-local-cluster` script to use correct WS URL (backport #4321)

---

CHANGELOG.md
packages/connect/package.json
packages/connect/src/base/listener.ts
packages/connect/src/base/stun.spec.ts
packages/connect/src/base/stun.ts
packages/connect/src/base/utils.spec.ts
packages/connect/src/relay/handshake.spec.ts
yarn.lock

By default, *each* hopr node acts as a STUN server.
Due to updates to the ecosystem, the functionality got broken. This PR reenables the functionality by using new modules.
*Changes in detail*:
- Use `udp6` socket instead of `udp4` -> fixes general listening issue. IPv4 traffic using IPv4 addresses prefixed by `::ffff:`
- Replaces the *hacky* `webrtc-stun` library by `stun`, so `console.log` overwrites become obsolete
- Simplify STUN logic
Fixes https://github.com/hoprnet/hoprnet/issues/4303

Restore STUN functionality

---

.prettierignore

Extend prettier-ignore to ignore:
- WASM files
- cached Rust artifacts

Adapt prettier to Rust

---

.github/workflows/pr_checks.yaml

Deployment flag pre-merge check was not triggered when no commits were pushed to the PR.

Prevent bypassing pre-merge checks by not pushing commits to the PR

---

.github/workflows/deploy.yaml
.github/workflows/e2e-gcloud.yaml
.github/workflows/e2e-npm.yaml
.github/workflows/e2e.yaml
.github/workflows/test.yaml
rust-toolchain.toml

Changes Rust setup to be more explicit.
- within workflows: bind cache to explicit Rust toolchain
- within toolchain file: use explicit version of Rust and install only required packages
Whenever Rust version changes, `cargo` needs to recompile all packages using the new version - which makes caching built Rust artifacts obsolete.
Specifying an explicit version of Rust and its toolchain utilities makes builds more deterministic since they *always* use the same version - unless there is a manual version bump.

bind to specific Rust version

---

CHANGELOG.md
packages/hoprd/src/api/v2/paths/channels/index.ts

Print proper source/destination in the `channels` Admin UI command.
Closes #4364

Fix source/destination print out for channels

---

packages/connect/src/base/stun.ts

- Distinguishes RFC 3489 compliant STUN requests from RFC 5780 compliant STUN requests and reply accordingly
RFC 3489 compliance:
On *nix system:
`stun <IP address>:<Port>`
RFC 5780 compliance:
Using WebRTC:
https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/
and add `stun:<IP address>:<Port>`, then click `Gather candidates`

Fix STUN requests

---

.github/workflows/deploy.yaml
scripts/build-docker.sh
scripts/build_avado.sh
scripts/deploy.sh

The `staging` build was building incorrectly tagged images.
Images built in the Staging pipeline will be tagged with the `staging-` prefix, e.g.:
`gcr.io/hoprassociation/hoprd:staging-bogota` for release Bogota.

Use correct image tags for staging images

---

Makefile

Compiling Rust code is pretty slow, hence it is advisable to compile it not more than once.
Currently, when building `hoprnet` monorepo, packages with Rust crates are compiled individually and do not use caching done by `cargo`.
This PR changes the build process such that `wasm-pack` builds are initiated from top-level, so `cargo` can make use of its cache.
To keep compilation of individual crates convenient, this PR does not remove `make` target of individual crates.

wasm-pack workspaces

---

CHANGELOG.md
packages/core-ethereum/src/constants.ts
packages/core-ethereum/src/ethereum.ts

Refs #4422 
This fixes the un-subscription which would previously fail due to the listener parameter being undefined. Moreover, the timeout for waiting for a tx to appear on-chain is increased to 60seconds to make room for delays.
Also if confirmations is 0 we log some information and keep the listener alive.

core-ethereum: Fix bug in on-chain tx listener

---

CHANGELOG.md
packages/utils/src/db/db.ts

A copy-paste error introduced a bug which caused acknowledged tickets not to get properly erased from the DB after redeeming.
Fixes https://github.com/hoprnet/hoprnet/issues/4421
Fixes https://github.com/hoprnet/hoprnet/issues/4421
Fixes https://github.com/hoprnet/hoprnet/issues/4398

Fixed incorrect handling of acknowledged tickets by the DB

---

CHANGELOG.md
packages/connect/src/base/addrs.ts
packages/connect/src/base/stun/udp/client.ts
packages/connect/src/filter.ts
packages/core/src/index.ts
packages/utils/src/network/addrs.ts

Fixes an issue with private addresses considered public when running on DAppnode / AVADO machines.
**Current situation**
`connect` detects that it is running on a DAppnode machine and therefore considers the address private - and publishes it as their private address. To make sure that nodes in the same network can connect to each other.
Whereas other nodes - which are not running on a DAppnode / AVADO - consider this address public and thus try to connect to it.
**New behavior**
`connect` detects that it is running on a DAppnode / AVADO machine and ignores that internal container address. As it is not expected to have multiple nodes running on the same DAppnode / AVADO machine, clients running on DAppnode / AVADO machines don't try to dial internal container addresses.

Fix internal container addresses on AVADO / Dappnode

---

packages/hoprd/src/api/v2.ts
packages/hoprd/src/index.ts

Allow `--disableApiAuthentication` and `--apiToken` CLI arguments to be specified at the same time.
However, the usage of `--disableApiAuthentication` will reset whatever is set by `--apiToken` (as expected).
This behaviour is required by e.g. Avado, which will always pass both arguments, no matter their values.

Allow `disableApiAuthentication` and `apiToken` CLI args together

---

packages/core/src/network/heartbeat.ts

Fixes an incorrect if-clause that could lead to errors if `sendMessage` returns an empty response, which is unexpected in this case.

fix empty ping response

---

packages/core/crates/core-misc/Cargo.toml
packages/core/crates/core-misc/src/environment.rs
packages/core/crates/core-misc/src/lib.rs
packages/hoprd/crates/hoprd-misc/Cargo.toml
packages/hoprd/crates/hoprd-misc/src/lib.rs
packages/utils/crates/utils-metrics/Cargo.toml
packages/utils/crates/utils-metrics/src/lib.rs
packages/utils/crates/utils-metrics/src/metrics.rs
packages/utils/crates/utils-misc/Cargo.toml
packages/utils/crates/utils-misc/src/lib.rs
packages/utils/crates/utils-misc/src/utils.rs

This adds a `wasm` feature (enabled by default) to all crates, so that the WASM modules within our crates are built only if this feature is turned on.

Add wasm feature to all crates

---

.github/workflows/e2e.yaml
scripts/api.sh

From the bash manual:
Each arg is an arithmetic expression to be evaluated (see ARITHMETIC EVALUATION). If the last arg evaluates to 0, let returns 1; 0 is returned otherwise.
Fixes #4481

Use pre-increment addition to prevent wrong exit code

---

scripts/get-npm-package-info.sh

Fixes issue seen in
https://github.com/hoprnet/hoprnet/actions/runs/3890447740/jobs/6639578776#step:12:2337

ci: Handle npm execution error gracefully when publishing packages

---

packages/connect/src/base/entry.ts
packages/utils/src/process/retimer.spec.ts
packages/utils/src/process/retimer.ts

Closes #4489 
Fixes a regression that prevented heartbeat rounds from running through.
```ts
await heartbeatRound() // 99% complete, waiting forever for 1%
```
```ts
heartbeatRound()
await setTimeout(1234)
heartbeatRound()
```

Fix regression that led to flat ping rate

---

.github/workflows/deploy.yaml
CHANGELOG.md
Makefile
packages/core/src/messages/packet.ts
packages/core/src/messages/validations.spec.ts
scripts/api.sh

Refs #4505 
This PR changes the ticket validation to be order-independent. The order is still being enforced at the ticket redemption stage. This unlocks the smoke tests which are green again.
Moreover, some minor build issues were fixed.

Fix validation of out-of-order tickets

---

.github/workflows/docs.yaml
README.md
packages/hoprd/README.md
packages/hoprd/crates/hoprd-misc/src/cli.rs
scripts/build-rest-api-spec.sh
scripts/publish-version.sh

Fixes the issue seen during publishing: https://github.com/hoprnet/hoprnet/actions/runs/3984409154/jobs/6830591979
Also fixes issue generating the API spec due to a typo in the CLI environment variables handler

publish-version: Fix incorrect use of old ethereum package

---

packages/ethereum/foundry-tool/src/key_pair.rs
packages/ethereum/foundry-tool/src/main.rs

Removes unused imports from `foundry-tool` to keep the compiler quiet :)
````
warning: unused import: `ethers::core::rand::thread_rng`
--> packages/ethereum/foundry-tool/src/key_pair.rs:2:5
|
2 | use ethers::core::rand::thread_rng;
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: `#[warn(unused_imports)]` on by default
warning: `foundry-tool` (lib) generated 1 warning
warning: unused import: `std::path::Path`
--> packages/ethereum/foundry-tool/src/main.rs:3:5
|
3 | use std::path::Path;
|     ^^^^^^^^^^^^^^^
|
= note: `#[warn(unused_imports)]` on by default
warning: unused import: `std::process::Command`
--> packages/ethereum/foundry-tool/src/main.rs:4:5
|
4 | use std::process::Command;
|     ^^^^^^^^^^^^^^^^^^^^^
warning: unused import: `ethers::core::rand::thread_rng`
--> …
```

Remove unused imports

---

.gitattributes

Remove `vendor` directory from language counting in GitHub.
see https://docs.github.com/en/repositories/working-with-files/managing-files/customizing-how-changed-files-appear-on-github

ignore vendor files

---

scripts/build-docker.sh
scripts/nat/Dockerfile

Fixes issue in CI: https://github.com/hoprnet/hoprnet/actions/runs/4068108689/jobs/7006537132
This was a regression introduced in the SC PR recently. The `docker` binary was missing in the plain alpine image.

docker: Fix hoprd-nat build to use docker-based image

---

Makefile

This prevents issue from using Foundry nightly to carry over into our CI. The bindings can still be compiled manually. Once we actually use them we have to figure out a way to pin Foundry versions.
Fixes issue seen in CI: https://github.com/hoprnet/hoprnet/actions/runs/4096580671/jobs/7064345676

Disable automatic compilation of Rust SC bindings

---

.github/workflows/deploy.yaml
scripts/setup-gcloud-cluster.sh

Toolchain uses `DEPLOYER_PRIVATE_KEY` to send out txs to staging environment. Align its naming.

Change env name from DEPLOYER_WALLET_PRIVATE_KEY to DEPLOYER_PRIVATE_KEY

---

README.md
packages/ethereum/contracts/Makefile
scripts/setup-gcloud-cluster.sh

- Wrap peersId in brackets to convert into string[]
- Update parameter `network` to `environment_type`
It has been tested locally

Fix riga deployment scripts

---

packages/hoprd/src/index.ts

wasm-bindgen seems to properly export Uint8Array but does not call the constructor
test with:
```
yarn run:hoprd --environment monte_rosa --private_key <some privkey>
```

fix: call uint8array constructor

---

packages/avado/build/Dockerfile

There has been a typo in the Dockerbuild of Avado

Fix a typo in Avado Dockerfile

---

packages/hoprd/crates/hoprd-misc/src/cli.rs

Default value must be set to `false`
closes #4595 
closes #4577

fix wrong default value

---

packages/hoprd/src/index.ts

Adds missing logic that forwards CLI settings to API settings

forward CLI arguments to settings cache

---

packages/core/src/index.ts

Add a try-catch to `strategyOpenChannel` and `strategyCloseChannel` functions, allowing the upper level loop to continue when individual attempts to open/close fail.

Allow individual channel closure to pass on fail

---

packages/ethereum/contracts/Makefile
packages/ethereum/contracts/script/SingleAction.s.sol

Allow `faucet` target to specify hopr token amount and native token amount. This facilitates the funding process. 
Test with local anvil instance:
```
make run-anvil
```
```
export NODE_WALLET=<your_node_ethereum_wallet>
export PRIVATE_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
```
Fund 30 HOPR token and 50 native token
```
make -C packages/ethereum/contracts \
faucet environment-name=anvil_localhost environment-type=development \
recipient=$NODE_WALLET hopramount=30 nativeamount=50
```
Fund 20000 HOPR token and 10 native token
```
make -C packages/ethereum/contracts \
faucet environment-name=anvil_localhost environment-type=development \
recipient=$NODE_WALLET
```

Optimize funding script

---

README.md
packages/avado/releases.json
packages/core/src/index.ts
packages/core/src/interactions/packet/forward.ts
packages/core/src/interactions/packet/index.spec.ts
packages/core/src/messages/packet.ts
packages/core/src/messages/validations.spec.ts
packages/hoprd/crates/hoprd-misc/src/cli.rs
packages/hoprd/src/index.ts

Check for unrealized balance should be optional per default as requested by RPCh.
It also creates adds a new CLI argument: `--checkUnrealizedBalance` to explicitly enable the check for unrealized balances.
Other minor fixes:
- fix some long parameter names
- fix printing out of an error stack trace when the strategy cannot open a channel
Refs #4535, closes #4609

Make check of unrealized balance optional

---

packages/core/src/network/heartbeat.spec.ts
packages/core/src/network/heartbeat.ts

- Add `HEART_BEAT_ROUND_TIMEOUT` which is 1 min
- If pinging node takes more than `HEART_BEAT_ROUND_TIMEOUT`, abort the `pingNode` action
Closes #4600

Early abort heartbeat when timeout

---

README.md
packages/avado/docker-compose.yml
packages/hoprd/crates/hoprd-misc/src/cli.rs

Adds back missing environment variable to make `supervisord` happy.
Also corrects an invalid name of an environment variable.

Fix Avado startup in Riga

---

CHANGELOG.md
packages/hoprd/package.json
packages/hoprd/src/api/token.spec.ts
packages/hoprd/src/api/token.ts
packages/hoprd/src/api/v2/paths/token.integration.spec.ts
packages/hoprd/src/api/v2/paths/tokens/index.ts
packages/hoprd/src/api/v2/paths/tokens/{id}.integration.spec.ts
yarn.lock

Fixes #4571 
A new validation step has been added to the token creation routine, which ensures that lifetime and capabilities of the new token are a subset of the token used to perform the operation. That way no new capabilities can be generated, and the lifetime is capped at the scope's lifetime.

[hotfix riga] Prevent API privilege escalation

---

packages/core/src/index.ts
packages/core/src/interactions/packet/acknowledgement.ts
packages/core/src/interactions/packet/forward.ts
packages/core/src/interactions/packet/index.spec.ts
packages/core/src/messages/acknowledgement.ts
packages/core/src/messages/acknowledgementChallenge.ts
packages/core/src/messages/packet.ts

Removes an abstraction that fetches only the very first chunk of a stream, meaning
```
chunk_0
chunk_1
...
```
Current situation:
```
chunk_0
// all other messages are dropped
```
New behavior, applies to packet forwarding (consuming mixer output) and acknowledgement processing:
```
chunk_0
chunk_1
...
(until stream finishes)
```

fetch all stream chunks

---

packages/core-ethereum/package.json
packages/core/package.json
packages/hoprd/package.json
packages/real/package.json
packages/utils/package.json
yarn.lock

Fix failing deploy pipeline due to incompatible typedoc version, see https://github.com/hoprnet/hoprnet/actions/runs/4192779967

bump typedoc version

---

.processes/release.md
packages/avado/releases.json
packages/connect/package.json
packages/core-ethereum/package.json
packages/core/docs/classes/default.md
packages/core/docs/enums/NetworkHealthIndicator.md
packages/core/docs/modules.md
packages/core/package.json
packages/ethereum/contracts/contracts-addresses.json
packages/hoprd/docs/modules.md
packages/hoprd/package.json
packages/real/package.json
packages/utils/package.json

Merge-back from `release/riga` to `staging/riga`. This is required such that the prerelease version is automatically bumped before we can update `release/riga` again.

Staging update riga/mergeback release

---

CHANGELOG.md
packages/core-ethereum/src/index.ts
packages/core/src/channel-strategy.ts
packages/core/src/index.ts
packages/core/src/interactions/packet/acknowledgement.ts
packages/core/src/interactions/packet/index.spec.ts
packages/cover-traffic-daemon/src/strategy.ts
packages/utils/src/db/db.ts
packages/utils/src/types/acknowledgedTicket.ts

Fixes #4623, #4617 and #4549
- Remove the assignment of preImage from ticket acknowledgment to ticket redemption.
- Save all the tickets, regardless if it's a winning ticket
- Allow to remove an acked ticket right before doing redemption on-chain, when 
- the ticket will be a loss
- node is out of commits
- ticket preimage is empty
- remove `markLosing` method in database and add `markLosingAckedTicket`
- `onWinningTicket` hook for strategies is replaced with `onAckedTicket`

Allow to redeem tickets with a gap in ticket index

---

scripts/toolchain/Dockerfile

While registering the node in the Network registry, I'm using the docker image Toolchain, and the command time is not included but used in command `make self-register-node peer_ids="${HOPRD_PEER_ID}" environment="${HOPRD_ENVIRONMENT}" environment_type=${ENVIRONMENT_TYPE}`

Adding time command needed for register nodes

---

CHANGELOG.md
packages/core/crates/core-misc/src/constants.rs
packages/core/src/index.ts
packages/core/src/main.ts
packages/hoprd/crates/hoprd-misc/src/cli.rs
packages/hoprd/src/index.ts

`js-libp2p` allows to configure a maximum number of parallel connections. This is useful to limit the number of connections of NATed nodes since some routers appear to have issues with too many connections.
In case the limit is reached, `js-libp2p` fails with stack traces such as
```
Feb 28 11:07:47 files bash[2865580]: 2023-02-28T10:07:47.881Z hopr-core:libp2p:error Dial error: Error: No dial tokens available
Feb 28 11:07:47 files bash[2865580]:     at DialRequest.run (file:///home/hopr/hoprnet/node_modules/libp2p/dist/src/connection-manager/dialer/dial-request.js:26:27)
Feb 28 11:07:47 files bash[2865580]:     at Dialer._createPendingDial (file:///home/hopr/hoprnet/node_modules/libp2p/dist/src/connection-manager/dialer/index.js:205:34)
Feb 28 11:07:47 files bash[2865580]:     at …
```

add max parallel connections command

---

CHANGELOG.md
packages/core/src/main.ts

This PR reduces the overall timeout that establishing a connection is allowed to take.
The node waits 10s to establish a TCP connection *before* it tries the next address, which appears to be too long.
Connection attempts get canceled after 3s

adjust timeout

---

packages/core/src/main.ts

Enhances libp2p's address sorting 
When dialing peers, `core` / `libp2p` use naive address sorting which just places public IP addresses first, e.g.
```
avado_public (172.33.0.0/16)
public
relayed
localhost
relayed
```
Use class-based address sorting from `connect`
```
public
...
public
relayed
...
relayed
private
...
private
localhost
```
see https://github.com/hoprnet/hoprnet/blob/76fa88940a19bf63803f5cf264b473173536b64d/packages/connect/src/utils/addressSorters.ts#L30-L53

enhance address sorting

---

packages/hoprd/Dockerfile

In the command line of hopli it requires access to the contracts folder

Do not remove contracts from image as they are needed by hopli

---

README.md
docs/hopr-documentation/docs/node/using-hopr-admin.md
docs/hopr-documentation/versioned_docs/version-v1.85/node/using-docker.md
docs/hopr-documentation/versioned_docs/version-v1.86/node/using-docker.md
docs/hopr-documentation/versioned_docs/version-v1.87/node/using-docker.md
docs/hopr-documentation/versioned_docs/version-v1.90/node/using-docker.md
docs/hopr-documentation/versioned_docs/version-v1.90/node/using-hopr-admin.md
docs/hopr-documentation/versioned_docs/version-v1.91/node/using-docker.md
docs/hopr-documentation/versioned_docs/version-v1.91/node/using-hopr-admin.md
packages/cover-traffic-daemon/Dockerfile
packages/hoprd/Dockerfile

Hopr uses UDP traffic to determine its external IP address and detect if the process is running on an exposed host.
Neither the Dockerfile nor the `docker run` suggestions include the UDP port, hence nodes running in Docker always assume that they are running behind a restrictive NAT
All Dockerfile + all `docker run` instruction include port forwarding for UDP traffic.

Docker: expose udp ports

---

CHANGELOG.md
packages/connect/src/index.ts
packages/connect/src/utils/addressSorters.ts
packages/core/src/index.ts
packages/core/src/main.ts

Once node detects that it is running on an exposed host, switch to DHT `server`-mode. ~Also corrects some typos in libp2p protocol prefixes that led to issues.~ postponed for `monte_rosa_2.0`
If started with `--announce` flag, answer to DHT requests, otherwise don't (DHT `client`-mode).
If node announces publicly routable addresses *to the DHT*, switch DHT to `server`-mode.

enhance dht and libp2p config

---

packages/connect/src/base/listener.ts
packages/connect/src/base/stun/index.ts

Re #4679
Removes a temporary workaround that prevented `hopr`-clients from using own STUN servers
In order to bootstrap the network, hopr clients are configured to use public external STUN servers as a fallback since not all `hopr` nodes are running the latest version and / or have exposed to UDP socket, e.g. due to bad Docker command see #4686
`hopr` nodes use by default other `hopr` nodes to perform STUN requests. External STUN servers are still used as a fallback.
some refactoring to enhance code maintainability

Use native hopr stun servers

---

packages/utils/crates/utils-log/README.md

`utils-log` package was missing a clear documentation on how to use the package. This PR adds that documentation with a simple example.

Add log documentation

---

packages/core/crates/core-network/src/network.rs
packages/core/crates/core-network/src/ping.rs

The original implementation relied on API objects to behave correctly (e.g. PeerIds being always parsable...) by utilizing an `unwrap` operation on the `Option` instances. Since the APIs can be passed any type of data from the JavaScript realm, it is safer to implement boundary checks with appropriate handling that will not trigger panics and ensure the node functionality in cases of recoverable situations.

Update network objects to account for possibly failing inputs

---

Makefile
scripts/build-docker.sh
scripts/compose/docker-compose.local-dev.yml
scripts/compose/prometheus/prometheus.local-dev.yml

The new make target will start local Anvil and Hoprd instances and Grafana/Prometheus via  our Docker compose configuration. That way one can more easily develop in Hoprd while seeing metrics.

compose: Add local dev setup

---

packages/ethereum/Dockerfile.anvil
scripts/pluto/Dockerfile

The docker images failed to build, this PR fixes those issues:

Fix docker builds to allow local testing

---

.gitignore
Makefile

The vendor directory contains dependencies which also might have a build
directory in place. Previously, this line would have filtered those out
when trying to build Docker images via gcloud.

git: Remove ignore line which prevented gcloud docker builds to succeed

---

packages/utils/src/libp2p/dialHelper.ts

Optimizes connection setup to query for relays in advance while attempting to establish relayed connections
```
while (!successful) {
await fetchPotentialRelay
await tryConnection
}
```
The dialing code eagerly fetches new potential relays from the DHT while trying to establish relayed connections
```
await fetchFirstRelay
while (!successful) {
if pendingRequest {
await pendingDHTRequest
}
fetchAnotherRelay
await tryConnection
}

eagerly issue dht requests

---

packages/connect/crates/connect-relay/src/server.rs
packages/connect/crates/connect-relay/src/streaming_iterable.rs

removes now obsolete extensive debug logs from `connect-relay` crate

reduce relay logging

---

packages/core/crates/core-network/src/network.rs
packages/core/src/index.ts
packages/hoprd/src/api/v2/paths/node/info.integration.spec.ts
packages/hoprd/src/api/v2/paths/node/info.ts
packages/hoprd/src/index.ts
yarn.lock

The enum for network health indicator failed to properly display in the Admin UI and logs.
Fixes #4822 
This implementation is backwards compatible, i.e. does not force the HOPR Admin UI change:

Network health indicator shown as number

---

packages/connect/crates/connect-relay/src/server.rs

The docs were missing `use` clauses causing the docs to fail tests.

Fix failing relay docs tests

---

DAPPNODE_PUBLISH.md

Updated steps for publishing a Dappnode release for clarity.

Updated Dappnode publish guide

---

CHANGELOG.md
Cargo.lock
packages/core/crates/core-network/Cargo.toml
packages/core/crates/core-network/src/ping.rs

The scopeguard caused the counters to be moved, thereby always leaving an empty default 0 counter behind it.
Fixed to make sure the timer always gets updated inside a correct object.
Refs #4600

[HOTFIX] Ping metrics not being propagated correctly

---

packages/connect/package.json
packages/connect/src/webrtc/upgrader.ts
packages/core/src/channel-strategy.ts
yarn.lock

Returns the wrtc version used in the release Riga, drops support for Apple Sillicon.
Necessary due to an increased amount of failed connections causing restarts.
Likely will fix #4881 to Riga behavior.

Return the Riga version of webRTC

---

CHANGELOG.md
packages/connect/src/relay/handshake.spec.ts
packages/connect/src/relay/handshake.ts
packages/connect/src/relay/index.ts
packages/connect/src/relay/state.ts
packages/core/src/main.ts

Fixes the bug of ever-growing number of relayed connections on a relay node.
Fixes https://github.com/hoprnet/hoprnet/issues/4507

Add RelayState cleanup and set a limit of maximum relayed connections to 2000

---

packages/core/crates/core-network/src/ping.rs

The histogram metrics for heartbeat were cancelled instead of recorded.

Fix heartbeat metrics

---

packages/avado/build/Dockerfile
packages/avado/build/supervisord.conf
scripts/build-avado.sh

This PR fixes the `memmon` introduced in #4898 . 
The reason for `memmon` failing to monitor was missing `ps` command in the HOPRd Avado docker image.
It also introduces the `DRY_RUN` flag that can be used with `build-avado.sh` script to only generate the `docker-compose.yml` file without building the actual Avado image. This is useful for testing.
The order of `upstream_version` and `api_token` in the `build-avado.sh` script was also swapped for convenience.
Refs #4854

Fix `memmon` to properly monitor memory usage of HOPRd on Avado

---

CHANGELOG.md
packages/connect/src/relay/handshake.ts
packages/connect/src/relay/index.ts
packages/core/src/index.ts
packages/utils/src/libp2p/connection.ts
packages/utils/src/libp2p/dialHelper.ts
packages/utils/src/libp2p/index.ts

Dead connections are not properly cleaned from the libp2p connection managers internal data. This PR tries to ensure that this happens, such that these entries are properly freed.
```
2023-04-22T21:34:59.585Z hopr-core:libp2p dead connections to 16Uiu2HAmQ3CgoDqZE4eub44nZ7RUnNTqd1eTsk1vZxUhA5uaa97i [ 'abgzy41682198229621', '58xi1c1682198490514', '9rm2d01682198736128' ]
```

Enforce closing and clean-up of libp2p2 connections

---

CHANGELOG.md
packages/utils/src/libp2p/dialHelper.ts

Enhancements to the dialing logic to make its debugging easier
- when outputting known addresses, sort them in the order in which they are dialed
- add connection identifiers whenever possible to debug logs
- when establishing a connection, add the utilized Multiaddr to the debug logs

enhance dialing logs

---

CHANGELOG.md
METRICS.md
packages/core/src/index.ts
packages/hoprd/src/api/v2.ts
packages/hoprd/src/api/v2/paths/messages/index.ts
packages/hoprd/src/index.ts

This PR add some metrics relevant to RPCh failed request debugging.
It also adds a regex distinguisher of raw RPCh messages in order to log them in hoprd logs for further processing.

Add metrics & logs relevant for RPCh debugging

---

packages/connect/src/utils/libp2p.mock.spec.ts
packages/utils/src/libp2p/index.spec.ts

Adds mock for a missing method that made the unit test break after #5004 
re https://github.com/hoprnet/hoprnet/actions/runs/4820700047/jobs/8585558510?pr=5006

fix unit test suite

---

.yarn/patches/libp2p-npm-0.37.3-ae5be411f2.patch
CHANGELOG.md
package.json
yarn.lock

`hopr` uses libp2p for peer-to-peer communication. libp2p uses multiformats/Multiaddr to address nodes. Multiaddrs *can* include the PeerId of the destination, e.g.
```
/p2p/16Uiu2HAkwecC3n6BG3odw4WC3PjEPv36HyHsHE4dxGotXWgXynrh/p2p-circuit/p2p/16Uiu2HAmEcAW62hrT2Rd19SFLJvx7ZxvtuDFFf8pbUwMRZx4xyfv
```
but they don't need to since the destination peerId is already known when dialing a peer. this is why they are stored and transferred as:
```
/p2p/16Uiu2HAkwecC3n6BG3odw4WC3PjEPv36HyHsHE4dxGotXWgXynrh/p2p-circuit
``` 
unfortunately, there is no *coercing* method foreseen to automatically convert *long* addresses into *short* addresses.
This PR adds a `yarn patch` to add the missing coercion from *long* addresses to *short* address when pushing address information to other peers.

coerce libp2p addrs

---

.yarn/patches/@libp2p-peer-store-npm-1.0.17-714b0c0ec5.patch
package.json
yarn.lock

Adds a patch to a libp2p library used for managing known addresses
*Before* adding new addresses to the PeerStore (== the list of known addresses), there is a check whether the size of the addresses is the same.
If an address in the list *changes*, the *size* stays the same and thus the entire request is ignored.
Remove this check and rather do some additional db queries

fix libp2p address store

---

Cargo.lock
packages/core/crates/core-db/src/db.rs
packages/core/crates/core-db/src/traits.rs
packages/core/crates/core-types/Cargo.toml
packages/core/crates/core-types/src/account.rs
packages/core/crates/core-types/src/acknowledgement.rs
packages/core/crates/core-types/src/lib.rs

Added `AccountEntry` type to `core-types` crate, because it was missing.
Prerequisite for DB migration to Rust #4543 
Also fixes a typo in `acknowledgement` module name in `core-types`

Add missing AccountEntry type for use in the DB

---

packages/core/crates/core-crypto/src/iterated_hash.rs
packages/core/crates/core-crypto/src/shared_keys.rs
packages/core/crates/core-crypto/src/types.rs
packages/core/crates/core-network/src/heartbeat.rs
packages/core/crates/core-network/src/messaging.rs
packages/core/crates/core-network/src/ping.rs
packages/core/crates/core-types/src/account.rs
packages/core/crates/core-types/src/acknowledgement.rs
packages/core/crates/core-types/src/channels.rs
packages/hopli/src/key_pair.rs
packages/utils/crates/utils-types/src/primitives.rs
packages/utils/crates/utils-types/src/traits.rs

Simple renaming of methods of the `BinarySerializable` trait to make it compatible with `serde`

Rename `serialize`/`deserialize` to `to_bytes`/`from_bytes` in the `BinarySerializable` trait

---

packages/core/crates/core-crypto/src/types.rs
packages/utils/crates/utils-types/src/primitives.rs

This PR improves the following:
- better error handling when parsing Balance
- PublicKey type now supports also non-prefixed deserialized forms (64 bytes)
- adds missing `serialize` TS binding for the PublicKey type 
- add unit tests for `Address` type
- add convenience `hash` method to `Hash` type in Rust
Prerequisite for https://github.com/hoprnet/hoprnet/pull/5039

Add missing TS binding and small Rust types fixes

---

cloudbuild.yaml
packages/hopli/Dockerfile
scripts/build-docker.sh
scripts/pluto/Dockerfile

RE https://github.com/hoprnet/hoprnet/issues/4848, hopli artifact was not import to pluto. 
The idea is to fix the docker build so that Pluto can invoke hopli when funding nodes with 
```
make -C "${mydir}/../" fund-local-all \
id_dir="${tmp_dir}"` 
```

Attempt to import hopli to pluto

---

Makefile
shell.nix

The pinned version lives in our fork:
https://github.com/hoprnet/foundry/tree/hopr-release
The build we are currently using:
https://github.com/hoprnet/foundry/actions/runs/5021989638
An upgrade of foundry requires us to add the commits to the `hopr-release` branch on our fork and push a new tag. Then the CI will build the binaries for that tag and we may start using it in our `Makefile`.

Pin foundry

---

.github/workflows/e2e.yaml
.prettierignore
Makefile
scripts/api.sh
tests/integration-test.sh
tests/test_integration.py

This reduces the time the tests wait for ticket redemption in order to ensure that not all tickets are redeemed at once and we can verify progress.

tests: Fix smoke test runs

---

Cargo.lock
packages/core/crates/core-mixer/Cargo.toml
packages/core/crates/core-mixer/src/mixer.rs

This PR makes `core-mixer::Mixer` a generic class which could accept any type for mixing.
It also adds default implementation of configuration, making the entire `Mixer` type default-able.
Metrics creation for mixer is not per-instance, but rather using `lazy_static` which registers it per-crate. This follows the recommended approach here: https://docs.rs/prometheus/latest/prometheus/#static-metrics
For future development, non-default configurable instance should be created.
This change is needed as a prerequisite for #5074

Make Mixer more generic

---

.github/workflows/docs.yaml
.github/workflows/test.yaml

Switch some tasks back to the default runner to make sure the larger runner is not depleted fast.

ci: Switch back to default runners

---

packages/core/protocol-config.json

Add a temporary Network Rotsee to enable Faucet API to be able to fund it because it needs to download it
https://github.com/hoprnet/api/blob/main/api/package.json#L6

Adding temporary Rotsee

---

packages/ethereum/contracts/src/Announcements.sol
packages/ethereum/contracts/test/Announcements.t.sol

Removes announcement of secp256k1 public keys because they are no longer needed in `hoprd`.

remove secp256k1 public key announcement

---

Cargo.lock
Cargo.toml
packages/core-ethereum/crates/core-ethereum-misc/Cargo.toml
packages/core-ethereum/crates/core-ethereum-misc/src/commitment.rs
packages/core-ethereum/src/db.ts
packages/core-ethereum/src/index.ts
packages/core/crates/Makefile
packages/core/crates/core-crypto/Cargo.toml
packages/core/crates/core-crypto/src/iterated_hash.rs
packages/core/crates/core-hopr/.gitignore
packages/core/crates/core-hopr/Cargo.toml
packages/core/crates/core-hopr/README.md
packages/core/crates/core-hopr/src/lib.rs
packages/core/crates/core-packet/src/interaction.rs
packages/core/crates/core-packet/src/lib.rs
packages/core/crates/core-packet/src/path.rs
packages/core/src/index.spec.ts
packages/core/src/index.ts
packages/core/src/main.ts
packages/hoprd/src/api/token.spec.ts
packages/hoprd/src/api/token.ts
packages/hoprd/src/api/v2.ts
packages/hoprd/src/api/v2/paths/channels/{peerid}/{direction}/index.ts
packages/hoprd/src/api/v2/paths/token.integration.spec.ts
packages/hoprd/src/api/v2/paths/tokens/index.integration.spec.ts
packages/hoprd/src/api/v2/paths/tokens/{id}.integration.spec.ts
packages/utils/crates/utils-db/src/db.rs
packages/utils/crates/utils-types/src/primitives.rs

This PR adds the following changes to the DB related code:
This lock is not necessary, because database is always accessed through the business logic objects.
This was made possible by introducing the `core-hopr` crate, which unified the types from `core-packet`, `core-ethereum-db` and `core-ethereum-db-misc` for the TS code
The `initialize_commitment` function was taking the `set_commitment` and `get_commitment` closures. The `initialize_commitment` function acquires a write lock to the DB, and the calling the `get_commitment` closure. The `get_commitment` JS closure attempted a read in the DB (from the JS context), which caused a deadlock due to already acquired lock previously.
**Resolution**: The `get_commitment` closure has been removed, because it is never needed by the TS code for …

Deadlock database fixes and improvements

---

.vscode/settings.json

Extend the VSCode configuration to automatically latch on executables from inside the nix development environment

Add VSCode integration with the nix environment

---

rest-api-v3-full-spec.yaml

This is the updated spec for the next API v3 which is meant to be part of Providence.
I had to create a full spec file because our actual spec is auto-generated at runtime by our code. Thus, until the full spec is implemented I would keep this file in the repository as a reference.
Included documentation might not be fully updated, I focused on the functions and parameters.
Fixes #5115
For easy review you may load this file into https://editor.swagger.io/ which will generate the Swagger UI ad-hoc.

api: Add target spec for v3

---

packages/hoprd/crates/hoprd-misc/src/cli.rs
packages/hoprd/crates/hoprd-misc/src/config.rs
packages/hoprd/src/index.ts

The cli command args were not passed in properly and the default were overridden with incorrect values, this PR fixes that.
Output of `make run-local`:
```sh
Node configuration: {"host":{"ip":"0.0.0.0","port":9091},"identity":{"file":"/Users/teebor/dev/hopr/hoprnet/.identity-local.id","password":"<REDACTED>","private_key":null},"db":{"data":"/Users/teebor/dev/hopr/hoprnet/packages/hoprd/hoprd-db","initialize":true,"force_initialize":false},"api":{"enable":true,"auth":"None","host":{"ip":"127.0.0.1","port":3001}},"strategy":{"name":"passive","max_auto_channels":null,"auto_redeem_tickets":true},"heartbeat":{"interval":60000,"threshold":60000,"variance":2000},"network_options":{"announce":true,"allow_local_node_connections":false,"allow_private_node_connections":false,"max_parallel_connection …
```

Fix cli command line args parsing

---

CHANGELOG.md
README.md
packages/hoprd/crates/hoprd-misc/src/cli.rs
scripts/check-pr.sh

Some boolean command line arguments have a default true value, the clap parsing logic was adjusted and the naming change to reflect the flag's true actions:
- ticket auto redeem
- unrealized balance check
```shell
➜   make run-local 
env NODE_OPTIONS="--experimental-wasm-modules" NODE_ENV=development DEBUG="hopr*" node \
packages/hoprd/lib/main.cjs --init --api \
--password="local" --identity=`pwd`/.identity-local.id \
--network anvil-localhost --announce \
--testUseWeakCrypto --testAnnounceLocalAddresses \
--testPreferLocalAddresses --disableApiAuthentication
```
generates config:
```
"auto_redeem_tickets":true
```
when a flag is added: `        --disableTicketAutoRedeem \`, it generates:
```
"auto_redeem_tickets":false
```

Fix ticket auto-redeem and check unrealized balance cli arg logic

---

.github/workflows/build.yaml
Makefile
packages/ethereum/contracts/Makefile
scripts/run-local-anvil.sh

In MacOS systems the makefile target `ensure-environment-and-network-are-set` is not working if specified the `environment-type` within the same target.
This PR fixes this compatibility problem and also an issue invoking anvil localhost.

Fixing makefile compatibility

---

.github/workflows/build.yaml
Makefile
packages/ethereum/contracts/Makefile
scripts/fixture_local_test_setup.sh
scripts/run-local-anvil.sh

This PR fixes:
- A makefile typo in the variable `environment_type` 
- Running E2E tests without setting the environment variable `ETHERSCAN_API_KEY`
- Automatic shellcheck errors
- Also start building docker images when the PR changes to `Ready for review`

Fix makefile typo

---

.github/workflows/lint.yaml
.github/workflows/merge.yml
.github/workflows/tests.yaml
.vscode/launch.json

- Fixes the merge pipeline by building hoprd and hopli when toolchain is modified
- Creates a VsCode launch to run tests using VsCode
- Triggers Lint and tests on the event of `Ready for review`
- Fixes running [E2E tests in pipeline](https://github.com/hoprnet/hoprnet/actions/runs/5691428536)

Fixing E2E tests in CI Pipeline

---

Cargo.lock
Cargo.toml
packages/core/crates/core-hopr/Cargo.toml
packages/core/crates/core-hopr/src/adaptors/heartbeat.rs
packages/core/crates/core-hopr/src/adaptors/mod.rs
packages/core/crates/core-hopr/src/adaptors/network.rs
packages/core/crates/core-hopr/src/adaptors/ping.rs
packages/core/crates/core-hopr/src/lib.rs
packages/core/crates/core-hopr/src/p2p.rs
packages/core/crates/core-network/src/heartbeat.rs
packages/core/crates/core-network/src/network.rs
packages/core/crates/core-network/src/ping.rs
packages/utils/crates/utils-metrics/src/metrics.rs

The peer discovery mechanism is missing and will have to be created from scratch using the libp2p loop and chain loading behavior. Also, the `core-network::network::Network` object and it's functionality needs to be synchronized with this feature, as well, as modified to simplify `core-hopr` object construction.

Create the peer discovery network behavior

---

packages/ethereum/contracts/test/node-stake/permissioned-modules/NodeManagementModule.t.sol

Close https://github.com/hoprnet/hoprnet/issues/5263
Address zero was part of the fuzz generated array of addresses, which is supposed to be reverted with error `AddressIsZero`

exclude address zero in testFuzz_ScopeTargetSendFromModule

---

packages/core-ethereum/crates/core-ethereum-db/src/db.rs
packages/core-ethereum/crates/core-ethereum-misc/src/network_registry.rs
packages/core/crates/core-packet/src/validation.rs
packages/core/crates/core-types/src/channels.rs

Fixes a bunch of failing Rust unit tests after the recent merges.
- incorrect `ChannelEntry` serialization size
- removed unit test that is not valid anymore (since `ticket_epoch` field has been removed from the `Ticket`)
- fixed network registry unit test
- fixed build of the unit test (missing mock implementations)

Fix Rust unit tests

---

packages/hopli/src/identity.rs
packages/hopli/src/key_pair.rs
packages/hopli/src/utils.rs

Replace UNIX timestamp from identity file name and use a counter (staring from 0) as suffix.
Throw and error when a file with the same name exisits.

Adjust naming scheme of identity files created by hopli

---

packages/core-ethereum/src/ethereum.ts
packages/core/src/main.ts

Fixes:
- preformats Ed25519 public key in protobuf encoding so it can be consumed by js-peerid
- fixes missing essential TX payload value for Announcement
- proper Address and OffchainKeypair usage

Fix formatting of Ed25519 public key & other fixes

---

packages/ethereum/contracts/Makefile
packages/ethereum/contracts/script/SingleAction.s.sol
packages/ethereum/contracts/src/node-stake/permissioned-module/CapabilityPermissions.sol
packages/ethereum/contracts/src/node-stake/permissioned-module/NodeManagementModule.sol

- Add action to include an "ALL_ALLOWED" target to a module from its Safe
- Add a make target for it `add-all-allowed-target`. E.g. When adding "Announcements" contract to the module, place the announcement contract address as `target_address`
- Cherry-picked necessary changes to smart contracts, ref https://github.com/hoprnet/hoprnet/pull/5364/files

Scope announcement target by default

---

scripts/setup-hoprd-nodes.sh

The `hoprd` node must have `HOPRD_HOST` set to the public IP which other peers may use to connect to it. This PR adapts the GCP setup script to have that entry in the `.env` file.

scripts: Set host IP for GCP nodes

---

Cargo.toml

`core-p2p` was missing as a workspace package.

Fix missing workspace member core-p2p

---

packages/core/crates/core-hopr/src/adaptors/network.rs
packages/core/crates/core-hopr/src/adaptors/ping.rs
packages/core/crates/core-hopr/src/constants.rs
packages/core/crates/core-hopr/src/lib.rs
packages/core/crates/core-hopr/src/p2p.rs
packages/core/crates/core-network/src/network.rs
packages/core/crates/core-network/src/ping.rs
packages/core/crates/core-p2p/src/api.rs
packages/core/crates/core-p2p/src/lib.rs
packages/core/protocol-config.json
packages/core/src/index.ts
packages/ethereum/contracts/contracts-addresses.json
packages/utils/src/index.ts
scripts/setup-local-cluster.sh

Metadata was skipped during the rust-libp2p migration and never made its way back into the register operation. This PR fixes that and removes some obsolete comments as well.
Fixes #5395

Add back metadata storage on register to Network object

---

packages/ethereum/contracts/script/SingleAction.s.sol
packages/hopli/README.md
packages/hopli/src/main.rs
packages/hopli/src/process.rs
packages/hopli/src/sync_network_registry.rs
packages/hopli/src/utils.rs

- Create foundry script to "force sync eligibility" of safes
- Add "force sync eligibility" step in "express setup safe and module" as well as "migrate safe module"
- Create hopli command to force sync eligibility
To update eligibility for Rotsee and Dufour nodes, run
```
PRIVATE_KEY=<deployer_key> DEPLOYER_PRIVATE_KEY=<network_registry_manager_key> \
hopli sync-network-registry --network <rotsee_or_dufour> \
--contracts-root "../ethereum/contracts" \
--safe-addresses <address_of_all_registgered_safe> \
--sync-type forced-sync \
--eligibility true
```
where `<address_of_all_registgered_safe>` is a comma separated value, e.g. for "dufour" `0x4dcd3aa8655f766c69a0c30124b56a91b97da946,0x679bc9610e4c68ee8dc3e5c5046d599ad0e72f27,0x22be10812cd4ffbaa9a075ea8256359b436885a6,0xdd362a8da84aa03f1d6053 …

Hotfix Add force sync task

---

packages/ethereum/contracts/test/node-stake/NodeSafeRegistry.t.sol

fixes a smart-contract unit test where fuzzy-tested private key could belong to a deployed smart contract

ensure that private key does not belong to a contract

---

packages/core/crates/core-mixer/src/future_extensions.rs

Enhances `then_concurrent` to prevent infinite loops and add extensive unit tests

Fix then_concurrent to avoid possible cx abuse

---

packages/core/crates/core-network/src/heartbeat.rs

Minor fix, only the lower range is interesting for the test, should fix the test build failures in the CI.

Fix called times counter to allow for the lower minimum value in heartbeat tests

---

tests/integration-test.sh

Enable ticket redemption in E2E tests.
This does not include redeeming in specific channel yet.

Enable non-specific ticket redemption in E2E tests

---

scripts/setup-local-cluster.sh

Fixes the `setup-local-cluster` script when used with `-l` to specify a listen address.

Use `listen_host` to contact local cluster nodes

---

packages/core-ethereum/crates/core-ethereum-indexer/src/errors.rs
packages/core-ethereum/crates/core-ethereum-indexer/src/handlers.rs
packages/core/src/constants.ts
packages/core/src/index.ts

This PR adds safeguards to the announcement flow and indexer to ensure no empty multiaddresses are pushed or end up in the database.
The following error has been see on Dufour nodes:
```
2023-09-09T14:49:13.692Z [DEBUG] core_ethereum_indexer::handlers on_announcement_event - multiaddr: "" - node: "0x1446…c55a"
2023-09-09T14:49:13.692Z hopr-core-ethereum:indexer indexer on_event callback for transaction hash:  0x4ec206e7cce7f40d82f6c316da43b8634fa79a7be105b19b992e7e7e2048ed6a
2023-09-09T14:49:13.695Z hopr-core Processing multiaddresses for peer 12D3KooWSn6RJDpTqaseMpaycVNyYKbxDRsS1HQQpcUwyz26jCxh: /
UnhandledPromiseRejectionWarning
TypeError: Cannot read properties of undefined (reading '0')
at Hopr.onPeerAnnouncement (file:///app/hoprnet/packages/core/lib/index.js:316:48)
at Indexer.emit …
```

core: Handle empty multiaddr in announcement

---

packages/core-ethereum/crates/core-ethereum-indexer/src/handlers.rs

Following the bug fixed in https://github.com/hoprnet/hoprnet/pull/5470, issue https://github.com/hoprnet/hoprnet/issues/5468 actually reveals another bug in the indexer, as described [here](https://github.com/hoprnet/hoprnet/issues/5468#issuecomment-1713136451), which manifests when `ChannelBalance{Increased,Decreased}` events get emitted. 
Balance of a channel should be "set" instead of "updated" when relevant events are emitted.

Update channel balances in indexer

---

tests/integration-test.sh

The #5477 fixing #5405 introduced an incorrect test for self-pinging in the integration test suite. This PR fixes that.

Fix incorrect integration test for self-pinging

---

Cargo.lock
docs/changelog/changelog-2.0.0-rc.4.md
packages/core/crates/core-types/Cargo.toml
packages/core/crates/core-types/src/acknowledgement.rs
packages/core/crates/core-types/src/channels.rs
yarn.lock

`serde` normal encoding -> local usage, e.g. DB storage
`BinarySerializable` ->over-the-wire`, non-local usage
custom `serde` serializer / deserializer -> often used structs, e.g. tickets
- Adds an additional field to `AcknowledgedTicket` showing whether that ticket is part of an ongoing aggregation or being redeemed on-chain
- change Ticket `serde` serialization / deserialization to position encoding

Add status to acknowledged tickets

---

Cargo.lock
packages/core/src/index.ts
packages/hoprd/crates/hoprd-keypair/src/key_pair.rs
packages/real/crates/real-base/Cargo.toml
packages/real/crates/real-base/src/file.rs
scripts/fixture_local_test_setup.sh

The access check was incorrectly expecting a number return value when `undefined` was returned. This led to identity files being overwritten.

core: Fix reading of existing identities files

---

flake.lock
rust-toolchain.toml

The `aarch64` environment contained a bugged version of bash. While doing the flake update, Rust was bumped to 1.72 stable as well.

Update the development environment and tools

---

packages/core/crates/core-packet/src/interaction.rs
packages/core/crates/core-packet/src/packet.rs
packages/core/crates/core-types/src/channels.rs
packages/core/src/path/index.ts
packages/hoprd/src/api/v3/paths/channels/{channelid}/index.ts
scripts/api.sh
tests/integration-test.sh

Fixes #5526 
The path finding algorithm was choosing paths where the last hop could involve the final destination as source. This isn't possible, therefore has been fixed.

core: Don't use destination in path finding

---

.envrc
Makefile

The hoprd-python-sdk failed to generate due to minor issues fixed in this PR.

Fix generation procedure for hoprd-python-sdk

---

flake.lock
flake.nix
shell.nix

The unstable packages are no longer necessary, as wasm-opt and wasm-pack are in high version in the stable channels. This removes the issues with bash on Darwin derived environments, where smoke-tests could not be run properly.

nix: Remove unstable packages with unstable bugs

---

Makefile

Replacing the official swagger-codegen-cli enables deployment from the arm64 machines.

Replace official swagger-codegen-cli with a multi-platform one

---

Cargo.lock
packages/core-ethereum/crates/core-ethereum-actions/Cargo.toml
packages/core-ethereum/crates/core-ethereum-actions/src/channels.rs
packages/core-ethereum/crates/core-ethereum-actions/src/transaction_queue.rs
packages/core/crates/core-strategy/src/aggregating.rs
packages/core/crates/core-strategy/src/auto_funding.rs
packages/core/crates/core-strategy/src/auto_redeeming.rs
packages/core/crates/core-strategy/src/promiscuous.rs
packages/utils/crates/utils-types/src/primitives.rs
tests/conftest.py
tests/hopr.py
tests/test_integration.py

Fixes the funding TX function call to properly pass the `Address` of the destination instead of the channel ID.
Fixes #5555

Fix channel funding TX

---

packages/core-ethereum/crates/core-ethereum-misc/src/constants.rs
packages/core-ethereum/src/ethereum.mock.ts
packages/core-ethereum/src/index.ts
packages/core-ethereum/src/indexer/index.ts
packages/core-ethereum/src/indexer/utils.ts
packages/core/crates/core-hopr/src/p2p.rs
packages/core/crates/core-misc/src/environment.rs
packages/core/crates/core-types/src/channels.rs
packages/core/protocol-config.json
packages/core/src/main.ts
packages/hoprd/crates/hoprd-hoprd/src/cli.rs
packages/hoprd/crates/hoprd-hoprd/src/config.rs
scripts/fixture_local_test_setup.sh
tests/test_integration.py

Also only use 2 blocks as confirmations in local and testing environments, instead of 8.

core: Fix channel closure

---

packages/hoprd/src/api/v3.ts
tests/requirements.txt

The handling of `500` errors would use the wrong status field which led to another crash and no response sent back.

api: Fix handling of uncaught errors

---

.github/workflows/build-docs.yaml
packages/core/crates/core-crypto/src/derivation.rs
packages/core/crates/core-crypto/src/types.rs
packages/core/crates/core-protocol/src/msg/chain.rs
packages/core/crates/core-types/src/announcement.rs
packages/hoprd/crates/hoprd-hoprd/src/config.rs
packages/hoprd/crates/hoprd-keypair/src/key_pair.rs
packages/utils/crates/utils-misc/src/lib.rs

Add support for generating the docs:

Generate docs on push to master

---

packages/core-ethereum/crates/core-ethereum-db/src/db.rs

This PR temporarily removes batching of `mark_redeemed` DB operations in order to better discover potential bug of invalid acknowledged ticket DB key computation.

Unbatch mark_redeemed method for debugging

---

README.md
packages/hoprd/crates/hoprd-hoprd/src/config.rs

The error was unreadable, so it needed to be passed properly, this will fix the error output to be readable.
The failed parsing is now properly displayed as:
```shell
➜   NODE_ENV=production NODE_OPTIONS="--experimental-wasm-modules" node packages/hoprd/lib/main.cjs --network anvil-localhost --configurationFilePath ~/hoprd.yaml
(node:31339) ExperimentalWarning: Import assertions are not a stable feature of the JavaScript language. Avoid relying on their current behavior and syntax as those might change in a future version of Node.js.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:31339) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(node:31339) ExperimentalWarning: Importing WebAssembly modules is an …
```

Show reasonable error on failure to load config

---

Cargo.lock
packages/core-ethereum/crates/core-ethereum-db/src/db.rs
packages/core/crates/core-hopr/src/lib.rs
packages/core/crates/core-protocol/Cargo.toml
packages/core/crates/core-protocol/src/ticket_aggregation/processor.rs
packages/core/crates/core-strategy/Cargo.toml
packages/core/crates/core-strategy/src/aggregating.rs
packages/core/crates/core-types/src/acknowledgement.rs

This PR splits ticket aggregation API interface into 3 different possible calls:
- aggregate all tickets in the given channel (this was the existing functionality)
- aggregate the given range of tickets in the given channel (new)
- aggregate the give list of acknowledged tickets (new)
This separation is important for the aggregation strategy, which must manually first gather the aggregatable tickets in a channel (and mark them as being aggregated) and only then proceed with the aggregation. 
Without this separation, it was possible that the aggregation requests from the strategy could interleave, resulting in doubling the aggregation request.
Fixes #5638

Improve ticket aggregation interface

---

Cargo.lock
packages/core/crates/core-strategy/Cargo.toml
packages/core/crates/core-strategy/README.md
packages/core/crates/core-strategy/src/aggregating.rs
packages/core/crates/core-strategy/src/auto_funding.rs
packages/core/crates/core-strategy/src/auto_redeeming.rs
packages/core/crates/core-strategy/src/promiscuous.rs

Smaller strategies improvements:
- increase SMA windows size in promiscuous mode to 10 (= the strategy starts to act not earlier than after 10 minutes since Node startup)
- cleaned up logging in strategies

Optimizations to strategies

---

Makefile

The `make clean` command removed the contents of the `bindings` directory, but not the directory structure itself. When followed by the `make build` command, it was not possible to build the project, because the existing empty directory structure forced skipping of the bindings generation.

Fix issue with non-deleting binding repo

---

packages/core/crates/core-crypto/Cargo.toml
packages/core/crates/core-crypto/src/keypairs.rs
packages/core/crates/core-strategy/src/strategy.rs
packages/hoprd/src/index.ts

Also issues a warning to the logs if such key is already in-use.
This is a temporary solution, until a backwards compatible fix is merged in #5665
Closes #5666
Closes #5667

Prevent packet keys with `0xff` prefix to be generated

---

packages/core-ethereum/crates/core-ethereum-actions/src/channels.rs
packages/core-ethereum/crates/core-ethereum-actions/src/errors.rs
packages/core-ethereum/crates/core-ethereum-actions/src/node.rs
packages/core/crates/core-strategy/src/auto_funding.rs

The prior check for token balance before opening or funding channel was missing, which led to redundant TX which will clearly fail on-chain.

Add token balance checks to open/fund channels

---

Cargo.lock
packages/core/crates/core-strategy/Cargo.toml
packages/core/crates/core-strategy/README.md
packages/core/crates/core-strategy/src/aggregating.rs
packages/core/crates/core-strategy/src/auto_funding.rs
packages/core/crates/core-strategy/src/auto_redeeming.rs
packages/core/crates/core-strategy/src/errors.rs
packages/core/crates/core-strategy/src/promiscuous.rs
packages/core/crates/core-strategy/src/strategy.rs

The unrealized balance percentage threshold in the Aggregating strategy must not take unredeemed aggregated tickets into the account, as this could cause recursive aggregation.
Successive aggregations that have the same starting tickets, result in creation of aggregated tickets with the same index (but different offset) and subsequent redemption fails if the first aggregated one has been already redeemed in the meantime.
Closes #5673

Skip aggregated tickets in unrealized balance criteria

---

packages/core/crates/core-protocol/src/msg/processor.rs
packages/core/crates/core-protocol/src/ticket_aggregation/processor.rs
packages/core/crates/core-strategy/src/auto_redeeming.rs
packages/core/crates/core-types/src/channels.rs

- the index on the aggregated ticket was off-by-one - refs #5673
- when ticket validation at the relayer found the ticket invalid, the read lock was still held and deadlocked the database when the ticket was subsequently tried to be marked as rejected.

Fix aggregated ticket index and deadlock on ticket rejection

---

flake.lock

Basic `nix flake update` for 2.1.0 branch.
```shell
• Updated input 'flake-parts':
'github:hercules-ci/flake-parts/7f53fdb7bdc5bb237da7fefef12d099e4fd611ca' (2023-09-01)
→ 'github:hercules-ci/flake-parts/8c9fa2545007b49a5db5f650ae91f227672c3877' (2023-11-01)
• Updated input 'flake-parts/nixpkgs-lib':
'github:NixOS/nixpkgs/3e52e76b70d5508f3cec70b882a29199f4d1ee85?dir=lib' (2023-08-31)
→ 'github:NixOS/nixpkgs/0cbe9f69c234a7700596e943bfae7ef27a31b735?dir=lib' (2023-10-29)
• Updated input 'nixpkgs':
'github:NixOS/nixpkgs/0dd560f0abbe9e0b09bd1626ab44f05c80a68b26' (2023-09-25)
→ 'github:NixOS/nixpkgs/923abd6420e9eb12caaafc701f98d4ad4a6aecc9' (2023-11-08)
• Updated input 'rust-overlay':
'github:oxalica/rust-overlay/014e0035c262e5506f904829e6b925ee3cfdb55e' (2023-09-25)
→ …
```

Update the development environment

---

.github/workflows/build-anvil.yaml
.github/workflows/build-dappnode.yaml
.github/workflows/build-hopli.yaml
.github/workflows/build-hoprd.yaml
.github/workflows/build-pluto.yaml
.github/workflows/build-toolchain.yaml
.github/workflows/close-release.yaml
.github/workflows/merge.yaml
scripts/bump-version.sh
scripts/get-current-version.sh

When a PR is merged against branch `release/providence` the docker tag `providence` is updated independently if it's part of a release or a simple PR.
This PR provides these new tags:
- `saint-louis-latest`: This tag will contain the same value than `latest` while `saint-louis` is being developed in `master` branch.
- `providence-latest`: This tag will contain the latest change applied in branch `release/providence`

Fix docker labeling on merge

---

Cargo.lock
packages/core-ethereum/crates/core-ethereum-db/Cargo.toml
packages/core-ethereum/crates/core-ethereum-db/src/db.rs
packages/core-ethereum/crates/core-ethereum-db/src/traits.rs
packages/core/crates/core-crypto/src/types.rs
packages/core/crates/core-packet/src/validation.rs
packages/core/src/main.ts
packages/utils/crates/utils-db/src/constants.rs

The critical path inside packet processing relied on an expensive DB call that would collect all Acknowledged and Pending tickets. In case of a large ticket collection this operation over the DB would take extremely long and block the critical path.
The unrealized balance value is now calculated internally in the DB on relevant DB operations and not on demand over the entire collection of tickets. This reduces the time to fetch the value, but complicates the logic of ticket handling by introducing the concept of channel life-time deeper into ticket handling. Ideally, these would be separated.
Fixes #5720

Fix iterator based operations in the critical path

---

packages/core-ethereum/crates/core-ethereum-db/src/db.rs
packages/core-ethereum/crates/core-ethereum-db/src/traits.rs
packages/core-ethereum/crates/core-ethereum-indexer/src/handlers.rs
packages/core/crates/core-packet/src/validation.rs
packages/core/crates/core-protocol/src/ticket_aggregation/processor.rs
tests/test_integration.py

Nodes keep "current_ticket_index" in the DB for all the incoming and outgoing channels. This value can be greater or equal to its on-chain counterpart (channel_entry.ticket_index). The offchain record increases by 1 for each issuance of ticket and gets reset to zero when the channel is closed and re-opened. When the this value gets reset incorrectly, e.g. in an event of DB removal, indexer should be able to bring it back to the on-chain state. 
- Add db operation 
- `ensure_current_ticket_index_gte` to set the "current ticket index" to a larger value
-  `increase_current_ticket_index` to increase the "current ticket index" by 1 (unused)
- Indexer update the "current ticket index" in ChannelOpened, ChannelClosed and TicketRedeemed
- During ticket aggregation, add checks on the "current …

Fix offchain ticket_index record out of sync

---

packages/core-ethereum/crates/core-ethereum-db/src/db.rs

On DB start, the cached unrealized balance was computed over all the tickets. Tickets from previous epoch or of the current epoch and with smaller index are not redeemable, and thus should be excluded. Tickets from the next epoch (when db is out of sync) should also not be taken into account. Only tickets from the current epoch and with index not smaller than the channel_index should be computed. 
Fixes https://github.com/hoprnet/hoprnet/issues/5737

Calculate unrealized balance for valid redeemable tickets in init_cache

---

Cargo.lock
packages/core/crates/core-crypto/Cargo.toml
packages/core/crates/core-crypto/src/keypairs.rs
packages/core/crates/core-crypto/src/types.rs
packages/core/crates/core-network/src/network.rs
packages/core/crates/core-strategy/src/promiscuous.rs
packages/utils/crates/utils-types/Cargo.toml
packages/utils/crates/utils-types/src/primitives.rs
packages/utils/crates/utils-types/src/sma.rs

This PR introduces new Simple Moving Average implementation (SingleSumSMA), which accumulates floating point error, but has O(1) for sample insertion and average calculation.
This SMA implementation is then used in Promiscuous strategy and in `PeerStatus`. The original NoSumSMA implementation is kept back, if the accumulating floating point error shows to be problematic.
Several minor improvements were added into `utils-types` crates.
Also some minor improvements of ergonomy of certain `core-crypto` types.

SMA improvements

---

packages/utils/crates/utils-types/src/primitives.rs

HOPR balance conversion is off by 1 digit. E.g. HOPR balance of "1230000000000000000" should be converted to "1.23 HOPR" by `to_formatted_string`, as in `1230000000000000000/1e18 = 1.23`

Fix string formatting in Balance type

---

Cargo.lock
packages/core/crates/core-network/src/network.rs
packages/core/crates/core-strategy/src/promiscuous.rs
packages/utils/crates/utils-types/Cargo.toml
packages/utils/crates/utils-types/src/errors.rs
packages/utils/crates/utils-types/src/sma.rs

This optimizes the retrieval of average value from SMA to be O(1) at the cost of accumulating floating point error, which should be less prominent when using `f64` to represent qualities.
This is a back-port from `master` branch, where this fix has been already applied.
Fixes #5752

Use SingleSumSMA in `PeerStatus`

---

Cargo.lock
packages/hoprd/src/api/v3/paths/account/balances.integration.spec.ts
packages/hoprd/src/api/v3/paths/account/balances.ts
packages/utils/crates/utils-types/Cargo.toml
packages/utils/crates/utils-types/src/primitives.rs

This fixes a regression within the API which would brake the SDKs for 2.1.x
Fixes #5732

api: Balances are shown as base values without unit

---

packages/hopli/README.md
packages/hopli/src/faucet.rs
packages/hopli/src/network_registry.rs

`hopli faucet` accepts comma-separated addresses in `--address` so nodes can be funded by supplying a list of addresses.
Closes https://github.com/hoprnet/hoprnet/issues/5750

Allow hopli faucet to accept multiple addresses

---

packages/core/crates/core-p2p/src/lib.rs

Refs #5769 
The values were adjusted to allow use of more buffer memory which should incur less scheduler overhead, which is our most scarce resource at the moment. This can/should be re-adjusted later again based on proper benchmarks when the system is Rust-native.

libp2p: Adjust mplex configuration to allow more sub-streams

---

flake.lock
rust-toolchain.toml

Bump the rust toolchain to Rust v1.74.1 in anticipation of full migration.
```shell
➜   rustc --version 
rustc 1.74.1 (a28077b28 2023-12-04)
➜   cargo --version 
cargo 1.74.1 (ecb9851af 2023-10-18)
```

Update rust toolchain to 1.74.1

---

Cargo.lock
packages/ethereum/crates/bindings/Cargo.toml

This reverts commit 28d7fcf75bcf3c226ab7c597b612868288fed088.
I have no idea how this got in. Maybe an issue with the vendor update workflow.

WTF of the day: Revert "chore(cargo): updated vendored dependencies"

---

packages/core/crates/core-p2p/src/lib.rs

Reduce impact of latest changes in finding current increased latency issues.

libp2p-mplex: Use defaults for buffer size and send size

---

packages/core-ethereum/crates/core-ethereum-db/src/db.rs
packages/utils/crates/utils-db/src/rusty.rs

Refs #5829 
The observation was that during write-heavy operations, namely the initial indexing phase, the database gets into an inconsistent states. It seems no writes get through and the node crashes multiple times, eventually all data is lost (possibly the db is corrupted and re-created) and the nodes starts synching from scratch until possible completion. Another side-effect is that data is only synched to disk in irregular intervals, sometimes 10 seconds. 
Ensuring data is synched to disk after every write improves consistency guarantees. While it does present an overhead, its currently more essential to have a consistent database. We can improve performance later as we go forward.
This changes was tested on bare metal servers and dappnodes. The aforementioned sync problems did not …

db: Fsync on every write

---

packages/hoprd/Dockerfile

Before the limit was set to 4GB while Docker's limit was set to 2GB. This meant Node.js would run very little GC and rather try to get more memory allocated since it was far away from reaching 4GB. However, then Docker would kill the container. This could occur during initial indexing where lots of objects are allocated in short periods of time.
This change lowers the limit for Node.js 1.5GB which is well below the Docker limit and should be enough for the current `hoprd`.

docker: Reduce max memory limit for Node.js to 1.5GB

---

packages/hoprd/Dockerfile

Operations using `fs` and crypto primitives are usually synchronous and handled through that thread pool.

docker: Increase libuv thread pool size from 4 to 16

---

tests/requirements.txt

the 2.1 hoprd-sdk-python will be breaking, this change needs to get into the `master` as well as `release/providence` to not follow the tip of the `hoprd-sdk-python` repository, but a specific tag.

Pin the hoprd-sdk-python to a specific version

---

packages/core-ethereum/crates/core-ethereum-rpc/src/rpc.rs

Sets RPC page size when fetching logs to 2500 log entries.
Fixes #5818

Increase RPC page size

---

scripts/commit-and-push-all-changes.sh

This script is missing for some non-standard CI runs (e.g. renove run).

Add missing commit and push script

---

.github/workflows/tests.yaml
ethereum/bindings/Cargo.toml
flake.lock
rust-toolchain.toml
scripts/toolchain/install-toolchain.sh

Updates:
- nix environment update
- Rust 1.74.0 -> Rust 1.75
Fixes:
- `test` workflow naming update

Update toolchain to Rust 1.75.0 and fix test workflow naming

---

hoprd/hoprd/src/bin/hoprd-cfg.rs

Add the utility to generate a default hoprd configuration YAML file and validate any passed in configuration files.

hoprd-cfg: Add the configuration management utility

---

Cargo.lock
chain/indexer/src/block.rs
chain/rpc/Cargo.toml
chain/rpc/src/client.rs
chain/rpc/src/rpc.rs
hopr/hopr-lib/Cargo.toml

The `surf` middleware logger is not useful as we have more superior RPC logging in-place already.

Remove `surf` client middleware logger

---

tests/conftest.py
tests/test_integration.py
tests/test_stress.py
tests/test_websocket_api.py

The stress tests are run locally at the maximum inbox size of 500 messages.

Fix stress tests to run with the refactored hoprd-api and fixtures

---

.vscode/settings.json

VSCode now autoformats the Rust part of the project.

Add automatic formatting for Rust

---

Cargo.lock
chain/actions/src/action_queue.rs
chain/types/src/lib.rs
logic/strategy/Cargo.toml
logic/strategy/src/promiscuous.rs
logic/strategy/src/strategy.rs
misc/utils-db/src/sqlite.rs
transport/network/src/network.rs
transport/protocol/src/msg/processor.rs

This PR introduces check on the minimal node version in order for the promiscuous strategy to start opening channels with it.
The newly introduced `minimum_peer_version` configuration option in `PromiscuousStrategyConfig` is currently set to `>=2.0.0`. The field fully supports Semver version requirement syntax.
Closes #5929

Peer version check to Promiscuous strategy

---

Makefile
hopli/src/key_pair.rs
hoprd/hoprd/src/cli.rs
hoprd/hoprd/src/config.rs
hoprd/hoprd/src/main.rs
hoprd/keypair/src/key_pair.rs
scripts/setup-local-cluster.sh
scripts/vm-nat-testing/docker-compose-nat.yaml
scripts/vm-nat-testing/docker-compose-pub.yaml
tests/conftest.py
tests/node_5.cfg.yaml

The release build will not have the possibility to use weak-crypto in order to safe-guard possible futures issues associated with such a setup.

Limit the weak crypto option to test and debug builds

---

.github/workflows/build-docs.yaml
README.md
flake.nix

Inplace the README.md to the top-level index file in the Rust generated documentation to keep the code in sync.
Closes https://github.com/hoprnet/hoprnet/issues/5915

Inlay the README.md into the Rust documentation

---

hopr/hopr-lib/src/config.rs
hopr/hopr-lib/src/lib.rs
hoprd/hoprd/src/config.rs
hoprd/hoprd/src/main.rs
hoprd/inbox/src/config.rs
hoprd/rest-api/src/config.rs
transport/api/src/adaptors/network.rs
transport/api/src/config.rs
transport/network/src/heartbeat.rs
transport/protocol/src/config.rs

The PR fixes smaller configuration issues and increases the ergonomics of config file usage:
Fixes #5928

Update config to fix issues and allow mergability of configuration files

---

Cargo.lock
chain/actions/src/action_queue.rs
chain/actions/src/errors.rs
chain/actions/src/payload.rs
chain/actions/src/redeem.rs
chain/api/src/executors.rs
chain/db/src/db.rs
chain/types/src/actions.rs
chain/types/src/lib.rs
common/internal-types/src/acknowledgement.rs
common/internal-types/src/channels.rs
crypto/sphinx/src/derivation.rs
crypto/types/Cargo.toml
crypto/types/src/types.rs
crypto/types/src/vrf.rs
transport/packet/src/validation.rs
transport/protocol/src/ticket_aggregation/processor.rs

This PR add some important size optimizations of object sizes when serialized, namely:
- various Ticket-related objects (`AcknowledgedTicket`, `UnacknowledgedTicket`)
- caching some of the members which are heavy on computation
As for other optimizations:
- postpone cryptographic operations once they are really necessary
- remove unnecessary cryptographic values
- simplify the `AcknowledgedTicketStatus` enum (remove values that are not needed)

Improve Ticket related structures

---

chain/rpc/src/client.rs
chain/rpc/src/errors.rs
chain/rpc/src/rpc.rs
hopr/hopr-lib/src/chain.rs

This PR addresses the following issues:
- fix the retry queue counter in `JsonRpcProviderClient`
- add logs to contract errors
- allow HTTP client for JSON-RPC to follow redirects, defaults to 3
- consolidate chain config structs in hopr-lib
Fixes #5940

Fix retry queue counters and make contract call error logs more specific

---

tests/test_integration.py
tests/test_stress.py

This PR should temporarily resolve the issue the CI encounters with a smoke-test on timestamp. 
When a message has a timestamp equal to the query timestamp in `peek-all`, often (not always) the message is not returned by the API. 
Conditions when filtering are all good, also inspected the content of the inbox when calling `peek-all`, and nothing points to those messages not being returned. However it happens.
The PR "fixes" it by going 1ms in the past when doing the query to `peek-all`. In this case, the chances that a message have exactly this timestamp is super small. Not inexistant.

Tweaking tests for timestamp

---

chain/rpc/src/indexer.rs
chain/rpc/src/rpc.rs
chain/types/src/chain_events.rs
hopr/hopr-lib/src/chain.rs
hopr/hopr-lib/tests/chain_integration_tests.rs

The raw `eth_getLogs` is now used for small block ranges (0-2), for wider block ranges (>= 3,practically only during sync) the paginated getLogs query is used.
Previously, the pagination was used already from ranges of size >= 2

Optimized getLogs queries

---

.github/workflows/clean-pr.yaml
.github/workflows/cleanup.yaml
.github/workflows/merge.yaml
.github/workflows/publish-release.yaml

As in title, removes the `hopr-toolchain`, `hopr-anvil` and `hopr-pluto` images from the GH workflows, as these images no longer exist.

Remove deprecated docker images from workflows

---

chain/actions/src/errors.rs
chain/actions/src/node.rs
common/internal-types/src/account.rs
hopr/hopr-lib/src/lib.rs

Added check that looks up the current node's account entry in the DB to check if the node has announced or not.
Fixes #5976

Do not re-announce on-chain if node has previously announced

---

transport/api/src/p2p.rs
transport/p2p/src/lib.rs
transport/protocol/src/constants.rs

Introduce new libp2p configuration to allow significantly more concurrently dialed outbound connections.
Allows setting the values with secret env overridable values:
- `HOPR_INTERNAL_LIBP2P_MAX_CONCURRENTLY_DIALED_PEER_COUNT`
- `HOPR_INTERNAL_LIBP2P_MAX_NEGOTIATING_INBOUND_STREAM_COUNT`
Fix the listen_on issue for external interfaces not propagated into NATted machines (e.g. by port-forwarding, docker...)

libp2p: Extend the new configuration to allow higher outbound connections counts

---

hopr/hopr-lib/src/lib.rs

The metrics version had a minor parsing issue.

Version string fix for 2.1 metrics

---

transport/network/src/ping.rs

Basic sanity value should be produced... to not have to mentally subtract the values.

Divide the RTT time by 2 to get a single direction value

---

hoprd/rest-api/src/lib.rs
transport/network/src/network.rs

Improve the API to be usable with the hopr-sdk in JS

---

hoprd/hoprd/src/config.rs

This PR fixes incorrectly doubled AutoRedeeming strategy configuration when the `auto_redeem_tickets` CLI argument was specified. This fixes the doubled on-chain transaction seen when the strategy was triggered.
Also when `default_strategy` is given on the CLI argument, it will be the only one used, clearing all the defaults.
Fixes #6015

Fix duplicate redeem strategy configuration from the CLI

---

METRICS.md
hopr/hopr-lib/src/config.rs
hopr/hopr-lib/src/lib.rs
hoprd/hoprd/example_cfg.yaml
hoprd/hoprd/src/config.rs
hoprd/hoprd/src/example_cfg.yaml
logic/strategy/src/aggregating.rs
logic/strategy/src/auto_funding.rs
logic/strategy/src/auto_redeeming.rs
logic/strategy/src/promiscuous.rs
logic/strategy/src/strategy.rs
transport/api/src/config.rs
transport/network/src/network.rs

Adds default `example_cfg.yaml` with documentation.
Closes #6005

Add example_cfg.yaml with documentation

---

hoprd/hoprd/src/main.rs
hoprd/keypair/src/key_pair.rs

Minor fix to not overwrite an existing file
Fixes https://github.com/hoprnet/hoprnet/issues/6010

Do not initialize the identity, if it is passed by the config

---

hoprd/rest-api/src/lib.rs
tests/test_websocket_api.py

- adds missing Bearer token authorization annotation for in Swagger
- adds missing e2e tests for Bearer token authorization

Annotate Bearer token auth in Swagger

---

hopr/hopr-lib/src/lib.rs
hoprd/rest-api/src/lib.rs
transport/api/src/lib.rs
transport/network/src/ping.rs

Minor usability fixes for the API:
Fixes #6008
Fixes #6034 
Fixes #6036

Fixes for issues found in the hopr-sdk testing

---

Cargo.lock
chain/rpc/Cargo.toml
chain/rpc/src/client.rs
chain/rpc/src/errors.rs
chain/rpc/src/helper.rs
chain/rpc/src/indexer.rs
chain/rpc/src/lib.rs
chain/rpc/src/rpc.rs
hopr/hopr-lib/data/protocol-config.json
hoprd/hoprd/src/cli.rs
hoprd/hoprd/src/config.rs

This PR exposes the `max_block_range` parameter on the CLI and ENV variables.
The default value of `max_block_range` is decreased from 2000 to 1000.
Also, as a follow-up to #6057, the logic in RPC log fetching loop (used by the Indexer) is improved, so it does not always panic on fatal errors.
This PR supersedes #6052
Refs #6039

Soft-restart indexer loop on error, expose `max_block_range` on the CLI

---

Makefile

Build and run was replaced by run in place and build if necessary.

Fix the hoprd-api-schema generation by directly executing the binary

---

Cargo.lock
chain/rpc/src/client.rs
chain/rpc/src/indexer.rs
chain/rpc/src/rpc.rs

The log pagination algorithm in `ethers` might request blocks outside the fixed block range, which is handled differently by different RPC providers.
This PR handles the missing block error (-32001) so it is not considered fatal and further blocks are not requested.
Also the minimum block limit to use pagination has been increased to 100, and the maximum block range was as well increased to 2000.

Better handling of missing block errors

---

logic/strategy/src/promiscuous.rs

Separating this expression ensures any interlocking cannot happen in this area, at the cost of slightly worse performance.

Separate `get_peer_with_quality` expression

---

chain/rpc/src/client.rs

Adds more logs.
Refs https://github.com/hoprnet/hoprnet/issues/6072

Add more logs to debug double transaction transmission in mempool

---

flake.lock
flake.nix

Using an adapted solc overlay which chooses the correct source for the `solc` binary to support macos-aarch.
Uses changes from https://github.com/hellwolf/solc.nix/pull/2

nix: Use native solc for macos-aarch

---

transport/api/src/lib.rs

Do not downgrade the privacy against the original call.
Refs #6077

Use exactly the amount of hops specified by the caller

---

.github/workflows/build.yaml
.github/workflows/clean-pr.yaml
.github/workflows/merge.yaml
scripts/get-next-version.sh

The docker tags are based on PR commit hash which disappears when the branch is gone. It needs to be based on commit hash.

Fix commit hash labeling docker images

---

ethereum/contracts/foundry.toml
hopli/README.md
hopli/src/identity_update.rs
hopli/src/key_pair.rs
hopli/src/main.rs
hopli/src/password.rs
hopli/src/utils.rs

Added a hopli command to update and identity password.
Accepts the same kind of arguments as the `identity` command, except that two passwords needs to be provided, either via two files containing the passwords, or two environment variables. See usage:
```
Usage: hopli update-identity-password [OPTIONS]
Options:
--old-password-path <OLD_PASSWORD>
The path to read the old password. If not specified, the IDENTITY_PASSWORD environment variable.
--new-password-path <NEW_PASSWORD>
The path to read the new password. If not specified, the NEW_IDENTITY_PASSWORD environment variable.
-d, --identity-directory <IDENTITY_DIRECTORY>
Path to the directory that stores identity files
-x, --identity-prefix <IDENTITY_PREFIX>
Only use identity files with prefix
--identity-from-path <identity_from_path>
The …
```

Update identity password from CLI

---

logic/strategy/src/channel_finalizer.rs

Fixes missing `serde_as` flag on the `ClosureFinalizerStrategyConfig`

fix: missing serialization info in `ClosureFinalizerStrategyConfig`

---

hoprd/rest-api/src/lib.rs

Fix API /tickets descriptions:
1. `"{BASE_PATH}/tickets"`: STATUS 200: "Fetched all tickets in all the channels"
2. `"{BASE_PATH}/channels/{{channelId}}/tickets"`: STATUS 200: "Fetched all tickets for the given channel ID"

Fix API /tickets descriptions

---

.github/workflows/label.yaml
.github/workflows/lint.yaml
chain/rpc/src/indexer.rs
db/api/src/tickets.rs
hoprd/rest-api/src/lib.rs
tests/requirements.txt
transport/api/src/lib.rs
transport/protocol/src/msg/mixer.rs

Fix minor bugs in the 2.1 implementation before the release.

Saint Louis fixes from practical testing session

---

hoprd/hoprd/src/main.rs
hoprd/rest-api/src/lib.rs

Add the `node/configuration` endpoint that dumps a json format of redacted node configuration.
Closes #6128

Add node configuration endpoint

---

chain/rpc/src/client.rs

As in title.
This will result in less hard failures on 504.

Act softer on HTTP 504 (Gateway timeout) thrown by the RPC provider

---

Cargo.lock
db/api/Cargo.toml
db/api/src/protocol.rs
db/api/src/tickets.rs
db/migration/src/lib.rs
db/migration/src/m20240326_000015_recreate_ticket_stats.rs
hopr/hopr-lib/Cargo.toml
hoprd/rest-api/src/lib.rs
tests/requirements.txt
tests/test_integration.py
transport/api/src/lib.rs
transport/protocol/src/ticket_aggregation/processor.rs

Deprecate the no longer necessary API functionality in the form of ticket displaying through the API endpoints and replace it with a useful implementation of metric export.
Closes #6127

Improvements to ticket metrics and deprecation of ticket displaying API endpoints

---

chain/rpc/src/client.rs
hopr/hopr-lib/src/chain.rs

As in title, this PR adds two things:
- make HTTP error code 503 retried per default
- add minimum number of retries regardless the error code, and set HOPRd default to 2.
Refs #6137

Add 503 as retryable HTTP code per-default, add global min retries

---

db/api/src/tickets.rs
db/entity/src/conversions/tickets.rs
logic/strategy/src/aggregating.rs
transport/api/src/lib.rs
transport/protocol/src/ticket_aggregation/processor.rs

There were multiple bugs discovered in matching the criteria before requesting a ticket aggregation:
- ticket aggregation triggered too often for all channels and draining the connection pool (https://github.com/hoprnet/hoprnet/issues/6138)
- off by one issue when aggregating
This PR should fix them.

Fix ticket aggregation criteria

---

db/api/src/tickets.rs
logic/strategy/src/aggregating.rs

The ticket aggregation criteria in the Aggregating strategy were wrong for the `on_own_channel_closed` event, so this has been fixed.
Also some logging was made less verbose.

Fix on channel close aggregation criteria

---

Cargo.lock
db/api/Cargo.toml
db/api/src/db.rs
db/api/src/peers.rs
db/api/src/ticket_manager.rs
db/api/src/tickets.rs
hoprd/rest-api/src/lib.rs
transport/api/src/lib.rs
transport/network/src/network.rs

Minor fixes identified by running the 2.1.0 candidate:

Move the peers database purge immediately into the DB creation

---

db/api/src/ticket_manager.rs
hopr/hopr-lib/src/lib.rs
logic/strategy/src/aggregating.rs
transport/api/src/p2p.rs
transport/protocol/src/ticket_aggregation/processor.rs

This fixes the issue of partially initialized objects and allows running the strategies only when all other components are operational.

Reorder multistrategy to first start to happen only once the node is fully running

---

Cargo.lock
common/internal-types/Cargo.toml
common/internal-types/src/legacy.rs
common/internal-types/src/lib.rs
hopr/hopr-lib/tests/chain_integration_tests.rs
logic/strategy/src/aggregating.rs
transport/api/src/lib.rs
transport/api/src/p2p.rs
transport/p2p/src/lib.rs
transport/protocol/src/ticket_aggregation/processor.rs

Introduces dummy layer which serializes to the same `cbor4ii` format as in the 2.0.8 version.
A unit test has been added ensuring that the binary representation matches the 2.0.8 format.
This should be removed in 3.0, as that release will be backwards incompatible and should be replaced with proper Ticket Aggregation protocol binary format, see https://github.com/hoprnet/hoprnet/issues/6159.
Closes #6155

Make aggregation protocol backwards compatible with 2.0.8

---

flake.nix
hopli/src/environment_config.rs

This means the user does not have to set the contracts root when using the docker image.

hopli: Configure contracts root in docker image by default

---

Cargo.lock
logic/strategy/Cargo.toml
logic/strategy/src/promiscuous.rs

Due to https://github.com/dtolnay/semver/issues/315, the partial versions in the Promiscuous strategy were not matched correctly.
This PR implements a workaround which only takes the Major, Minor and Patch components into account when checking for minimum version match in Promiscuous strategy.

Workaround version matching issue in Promiscuous strategy

---

crypto/types/src/types.rs
hopli/src/identity.rs
hopli/src/key_pair.rs
hopli/src/utils.rs

Add a hopli command that allows converting between PeerID in Base58 and hex representation of offchain public key.
- `hopli id convert-peer --peer-or-key 12D3KooWBoumtsUgQfbzuMafgQN2a8q1RKGMKDMRVKdZAGyH3JFR`
- `hopli id convert-peer --peer-or-key 0x1d9987b58e08f7982ffb575c3d2655c57537a6963178106d801a1f621c5acf38`

Add PeerID <-> Public key converter to hopli

---

Cargo.lock
hoprd/rest-api/Cargo.toml
hoprd/rest-api/src/lib.rs

URLs are now decoded on parameter parsing fixing issue where escaped symbols were not recognized.

Fix issues with alias urldecoding

---

chain/indexer/src/block.rs

On a restart, where no block was produced on chain, there would be an invalid value in the metrics.
Fixes #6186

Fix the display of sync metric

---

METRICS.md
chain/indexer/src/handlers.rs

Adds a multicounter that counts logs of different HOPR contracts seen by the Indexer.

Add metrics for logs processed by the Indexer

---

chain/actions/src/channels.rs
chain/api/src/lib.rs
chain/indexer/src/handlers.rs
db/api/src/info.rs
hopr/hopr-lib/src/lib.rs
logic/strategy/src/promiscuous.rs

Node Safe's HOPR balance was incorrectly compared with Safe's Native balance.

Fix comparison of invalid balance types

---

.github/workflows/build.yaml

This step would lead to incorrect docker image tags when run outside of a PR.

gha: tag docker image as pr only in prs

---

tests/test_integration.py

Randomization in the alias e2e test sometimes picked the current node for set_alias, which clashed with the "me" alias already existing on that node. This has been fixed.

Make set_alias e2e test stable again

---

chain/indexer/src/block.rs
chain/indexer/src/constants.rs
chain/indexer/src/handlers.rs
chain/indexer/src/traits.rs
db/api/src/info.rs

Previously the logs filter would include addresses which had an empty set of topics. Thus, the log filter behaviour becomes unclear. This is now strict such that the address itself is only used if at least one topic is set.

chain: do not fetch logs if no topics are set

---

chain/indexer/src/constants.rs

The topics for HOPR Token contract were by error used from the HOPR Boost contract.

chain: replace hopr_boost topics with hopr_token topics

---

chain/indexer/src/block.rs

Not failing hard in this step let's the node to think that it reached the tip of the chain and declares the indexing finished, instead of failing and restarting, until the RPC provider can be polled for the block information.

Fail hard on failure to load the block number from RPC provider

---

hoprd/hoprd/src/main.rs
hoprd/inbox/src/inbox.rs

The entire codebase should at this point be using a `saturating_sub` instead of the `-` operation on `Duration` objects, where applicable.

Fix subtraction operations on Durations to be saturating

---

chain/indexer/src/block.rs

The block id value was printed incorrectly in the checksum printout.

Update checksum printout

---

db/api/src/peers.rs
hopr/hopr-lib/src/lib.rs
logic/path/src/selectors/legacy.rs
logic/strategy/src/promiscuous.rs
transport/api/src/lib.rs
transport/api/src/processes/indexer.rs
transport/network/src/network.rs

Previously, the assumption was that a new node (or a node that we don't have quality info about) is automatically considered reliable. This is not correct.
This PR considers all nodes (node, or missing) without a "quality" information to be automatically unreliable and thus not considered for automatic path finding.
The `PeerStatus` type has also been refactored to carry `OffchainPublicKey` and `PeerId` as conversions between those 2 were done quite often.
The peer qualities are also synced to the ChannelGraph (if there are any). This change currently has no effect, as the peers DB is cleaned-up on each run.

Path finding should only consider nodes that proven to be reliable

---

db/api/src/db.rs

The size of the Peers database connection pool has been increased from 30 to 300.
Refs #6212

Increase the connection pool size of Peers DB

---

db/api/src/accounts.rs
db/api/src/peers.rs
hopr/hopr-lib/src/lib.rs
hoprd/rest-api/src/lib.rs
transport/api/src/lib.rs

The trailing `,` in the `multi_address` column in the peers table caused empty multiaddress being returned.
Also the aforementioned endpoint should returned the announced addresses from the chain, not the ones being observed (those are in the `observed` field).

The `/node/peers` API endpoint sometimes returned empty multiaddreses as `announced`

---

transport/p2p/Cargo.toml
transport/p2p/src/lib.rs

Changes not directly affecting the usability of 2.1.x, but necessary for evolution into 2.2.x line:

Update transports and their configurations

---

.github/workflows/build-docs.yaml

The buffer size was too small for the generated documentation failing to update the docs branch.

ci: Extend the buffer size for git on docs generation

---

hoprd/rest-api/src/lib.rs

As in title.
The error when input does not validate cannot be distinguished on the level od invalid address/invalid amount.
Closes #6274

Return `INVALID_INPUT` if channel open arguments are wrong

---

hoprd/hoprd/example_cfg.yaml
logic/strategy/src/lib.rs

- remove AutoFunding strategy from default config
- set `on_close_redeem_single_tickets_value_min` in AutoRedeeming strategy to `90000000000000000 HOPR`

Update default strategy config: remove AutoFunding, lower single ticket AutoRedeem threshold

---

tests/test_integration.py
transport/api/src/lib.rs

The missing check causes `panic!`, but should be present for 2.1.0.
Fixes #6286

Missing length check for send message packet

---

tests/conftest.py
tests/test_stress.py
tests/test_websocket_api.py

The test now uses websockets to allow multiple stressors to focus message sending towards a single relay.
The pytest can be run as:
```
.venv/bin/python3 -m pytest tests/test_stress.py --stress-sources='[{"url": "localhost:19091", "token": "e2e-API-token^^"}]' --stress-target='{"url": "localhost:19093", "token": "e2e-API-token^^"}'
```
Where the sources and target must be already running APIs with valid tokens.

Cleanup the stress test and rework it over the websocket

---

scripts/check_peer_tcp_connectivity.py

A script to efficiently test peer connectivity from the `node/peers` API output for the `announced` key.

scripts: Add peer connectivity check for TCP

---

Cargo.lock
hopr/hopr-lib/Cargo.toml
scripts/get-next-version.sh

This PR provides a fix for the close release pipeline failing due to a variable `pre_release` not set and checked in an if clause.

Remove checking if variable is set

---

.github/workflows/promote-release.yaml

The latest closure of release failed because the generation of the hoprd-sdk-python was expecting the `release/saint-louis` to exist. We should create that branch when the main hoprd version is promoted.

Include hoprd-sdk-python repository in the promotion of releases

---

transport/network/src/config.rs

The upper range value could never be validated successfully, as the `=` condition was missing.

Fix validation checks on network objects

---

Cargo.lock
hoprd/hoprd/example_cfg.yaml
logic/strategy/Cargo.toml
logic/strategy/src/auto_redeeming.rs
logic/strategy/src/lib.rs

The AutoRedeemingStrategyConfig object now includes a new minimum_redeem_ticket_value setting. This determines if the strategy will redeem an acknowledged winning ticket based on its HOPR value. Checks and tests have been added to verify this functionality. The package version has been updated to reflect this new feature addition.
The default value for this setting is 0 HOPR, which means no threshold applies. This is also set a default in the config file.

Add minimum ticket redeeming value configuration

---

Cargo.lock
chain/indexer/src/handlers.rs
hopr/hopr-lib/src/lib.rs

The safety check on HOPR Safe Balance API endpoint is not necessary as the related incorrect smart contract address has been fixed in https://github.com/hoprnet/hoprnet/pull/6229
This safety check could result in database interlocking during Indexer sync phase when the UI was opened at the same time. This could result in skipping chain event logs and incorrect node synchronization.
Closes #6359

Remove unnecessary safety check for HOPR Safe Balance

---

Cargo.toml
common/async-runtime/Cargo.toml
common/network-types/src/session/state.rs

- Modified network-types' session state for calculations of timeout and frame expiration age. 
- Updated the 'async-std' dependency in 'async-runtime/Cargo.toml' to include the 'unstable' feature. 
- Changes to tests also include a consistent seed for the RNG to improve reproducibility.

Improve state management timing in the Session protocol

---

METRICS.md
chain/indexer/src/block.rs
hopr/hopr-lib/src/lib.rs
hoprd/rest-api/src/lib.rs

- Adds indexer checksum and indexer current block into the `node/info` API endpoint.
- Removes the problematic `hopr_indexer_checksum` metric
Closes #6375

Add indexer state to NodeInfoResponse

---

db/api/src/db.rs

The 'optimize_on_close' option in the SQLite configuration has been commented out. This change has been made because the option was causing optimization on each connection, due to the min_connections value being set to 0. This adjustment should help improve the overall performance, connection times and possible deadlocks.
Refs #6359

Disable optimize_on_close in SQLite configuration

---

hoprd/rest-api/src/account.rs
hoprd/rest-api/src/lib.rs
nix/shell.nix
tests/hopr.py
tests/test_integration.py

- Change the definition of the endpoint from `get` to `post` in the routes list
- Fix the conversion in the API, from string to `Balance`

Fix API withdraw endpoint

---

Makefile
README.md
tests/test_stress.py

This allows anyone to launch quick local stress tests. Combined with the changes from #6391 the startup of these local tests  will be fast.

make: Add target to run local stress test

---

chain/api/src/lib.rs
chain/rpc/src/lib.rs
chain/rpc/src/rpc.rs
hopr/hopr-lib/src/lib.rs
hoprd/rest-api/src/checks.rs
hoprd/rest-api/src/lib.rs

PR adds an API endpoint `eligiblez` which requires no authentications to check if the node is allowed in the network, through a direct RPC call.

API: add "/eligiblez" endpoint to get node eligibility via a direct RPC call

---

deploy/compose/.env.example
deploy/compose/docker-compose.yml
hoprd/hoprd/Cargo.toml
hoprd/hoprd/src/lib.rs
hoprd/hoprd/src/main.rs
scripts/setup-local-cluster.sh
tests/node.py

`hoprd` is now able to stream opentelemetry using `tonic` and the default docker-compose setup was extended to allow running a `jaeger` instance.
Fixes #6362 
As seen in: https://broch.tech/posts/rust-tracing-opentelemetry/

Add support for opentelemetry into hoprd

---

Cargo.lock
chain/actions/src/redeem.rs
db/api/src/ticket_manager.rs
db/api/src/tickets.rs

In certain situations, the database can contain an aggregated ticket and also a ticket that is inside this aggregation ticket.
E.g. the DB contains a ticket with Index 1 and Offset 4, but also a ticket with Index 3, Offset 1.
This can happen when packets are arriving out of order, and only e.g. a single ticket is needed to trigger an aggregation.
Example:
- aggregation threshold is set to 3
- there are 2 unredeemed tickets (index 0, offset 1, index 1 offset 1)
- ticket with index 4, offset 1 arrives, completing the batch and the aggregation is triggered
- ticket with index 2 offset 1 and index 3 offset 1 arrive
- aggregated ticket with index 0 offset 5 arrives from the aggregator
This results in tickets: (2,1), (3,1) and (0,5) being in the DB, which have overlapping index intervals. This …

Remove tickets that are within an aggregated ticket prior to sending aggregation request

---

transport/network/src/network.rs

Do not use ascending sort on last seen datetime, but use a descending, favoring more recently seen peers and pushing the later seen peers to the latter stage.
Fixes #6360

Do not sort the heartbeat peers ascending by last seen date

---

logic/strategy/src/auto_redeeming.rs
tests/hopr-smoke-test-node_default.cfg.yaml

Updated the default value of `minimum_redeem_ticket_value` to 30 HOPR from zero in the auto redeeming strategy. This ensures consistency with expected configurations and improves the initialization process.
Closes #6422

Change default minimum ticket value to 30 HOPR in auto redeeming

---

METRICS.md
db/api/src/ticket_manager.rs
db/api/src/tickets.rs
hopr/hopr-lib/src/lib.rs

Improved Prometheus metrics to track neglected, redeemed, and rejected ticket statistics per channel. Also ensured metrics are initialized when the database loads ticket statistics. Improved documentation and fixed typos for better clarity.
Closes #6434
Closes #6424

Properly initialize Prometheus metrics for ticket statistics

---

Makefile
nix/shell.nix
tests/requirements.txt

Before, when modifying HOPRd's API, one should
- create a temp branch in the `hoprd-python-sdk` repo
- generate the new SDK from the monorepo
- push the modification to the temp branch
-  modify the `requirement.txt` file to point to the temp `hoprd-python-sdk` branch 
This manual dance between the two repo is bothering.
This PR generates the Python SDK right before running the smoke tests with the `make` command, and install the locally generated HOPRd library using `pip`.

Generate and use Python SDK within DevShell

---

chain/indexer/src/handlers.rs
db/api/src/errors.rs
db/api/src/tickets.rs
logic/strategy/src/aggregating.rs
transport/protocol/src/ticket_aggregation/processor.rs

This PR fixes the following issues discovered during testing:
1. after a ticket is redeemed in a channel, all tickets with lower ticket indices in that channel are marked as neglected. This makes sure any out-of-order tickets will not be attempted to get redeemed or aggregated at a later point.
2. there was a bug when preparing the aggregation process: the aggregation should not be considered for the tickets that have an index lower than the current ticket index at the channel entry. This makes sure aggregation will not be requested on ticket indices that were already redeemed or neglected. Such left-over tickets will be eventually neglected via 1.
These changes required some modifications in the `TicketSelector` type.
Refs #6421

Neglect tickets with lower index after redeeming & skip aggregating tickets with lower index than on channel

---

db/sql/src/tickets.rs

Fix the metrics update which could sometimes take too long to update in the absence of incoming tickets to be immediate on redeem/neglect operation.
Fixes #6450

Fix neglecting and redeeming metrics updates

---

Cargo.lock
logic/strategy/Cargo.toml
logic/strategy/src/strategy.rs

Introduced a helper function to set the default execution interval to 60 with the `serde(default)` attribute, ensuring a minimum value validation of 5.
Closes #6472

Update default strategy execution interval handling

---

chain/rpc/src/indexer.rs
logic/strategy/src/auto_redeeming.rs

Use `spawn` for log retrieval and directly handle channel funding. This refactor moves the log retrieval logic into a spawned task and ensures channel funding completes before proceeding. Additionally, `on_acknowledged_winning_ticket` now expects errors for non-aggregated tickets, improving error management.

Fix failing unit tests

---

tests/requirements.txt
tests/test_session.py

Added tests for session communication with HTTPS servers, including self-signed certificate generation and retrieval of random text files. Updated test requirements to include the `cryptography` library, and improved existing tests by filtering out empty messages.

Add HTTPS server communication tests

---

hoprd/rest-api/src/lib.rs
tests/hopr.py
tests/requirements.txt
tests/test_integration.py

Fixes the withdraw endpoint in the API. The issue was that the amount withdrawn wasn't internally converted into a `Balance` instance.

Fix withdraw endpoint

---

db/api/src/tickets.rs

Slightly modifies two logs to be able to see for which channel aggregation fails

Log the `channel_id` when aggregation fails

---

hopr/hopr-lib/Cargo.toml
hoprd/hoprd/Cargo.toml
transport/api/Cargo.toml
transport/api/src/config.rs

Allow building of binaries, where the announced address is quic-v1.

Add feature to support building hoprd node with quic-v1 

---

db/api/src/peers.rs
transport/api/src/lib.rs
transport/api/src/p2p.rs
transport/network/src/config.rs

Close #6535 and #6340 
- Handle f64::NAN after reading backoff from the DB
- Insert multiaddress for incoming connection
- Improve returned result handling in `Network`

Fix nulls in peer endpoint

---

db/api/src/tickets.rs

Update the unredeemed value correctly when a ticket is redeemed or neglected.
Closes #6464

Fix updating of unredeemed value metric

---

hoprd/rest-api/src/lib.rs

The string will now be parsed using the new and legacy approach as well.
Fixes #6568

Fix backwards compatibility of the withdraw endpoint in currency

---

README.md

Update the 2.2.x documentation in terms of extra configurable environment options.
Fixes #6544

Add README section for the additional optional environment var based configuration

---

README.md
hoprd/hoprd/example_cfg.yaml
hoprd/rest-api/src/node.rs
tests/barebone-lower-win-prob.cfg.yaml
tests/barebone.cfg.yaml
tests/default.cfg.yaml
tests/node.py
transport/api/src/lib.rs
transport/network/src/config.rs
transport/network/src/network.rs

Fix network behavior inconsistency related to improper ignoring of network peers and closing peer connections for offline peers.
Fixes #6529

Fix the network heartbeat behavior to be more robust and work with /node/peers

---

hoprd/db/api/src/aliases.rs
hoprd/db/api/src/errors.rs
hoprd/rest-api/src/alias.rs
hoprd/rest-api/src/lib.rs
tests/test_integration.py

Reintroduce backwards compatible and POST compliant behavior on alias entry:
1. if an alias exists -> fail with 409
2. if the peer id is already assigned to an alias -> fail with 409
3. otherwise introduce the alias
Refixes #6206

Alias to an existing peer_id or an existing alias should fail

---

tests/test_integration.py

Fix the test leaving a trail of leftover aliases spoiling consequent runs.

tests: Cleanup the forgotten alias after test runs randomly breaking consequent alias tests

---

.github/renovate.json

This removes the unnecessary issue that gets regenerated and reopened in our backlog #2469. Individual update recommendations will be evaluated independently.

Update renovate.json to remove the Dependency Dashboard issue

---

hoprd/hoprd/Cargo.toml

Use the QUIC transport on the libp2p layer by default:
1. announce a quic-v1 multiaddress
2. be reachable by TCP and have TCP transport for backwards compatibility

Use the quic-v1 multiaddress as a default for announcement

---

common/network-types/src/session/frame.rs
common/network-types/src/session/protocol.rs
transport/api/src/config.rs

Introduced `MAX_MESSAGE_SIZE` constant in session protocol and added validation for message length. The upper six bits of length are reserved for future use.
Also, replaced magic numbers with constants for timeout and retries in transport configuration.

Add constants for session protocol and transport config

---

hoprd/rest-api/src/checks.rs

Close #6560 
The root cause it that self-registration on the network registry is not enabled. The "div 0" error is expected.
The error can be better handled on the smart contract level, which will be tackled in https://github.com/hoprnet/hoprnet/issues/5501

Handle restricted self registration

---

Cargo.lock
chain/indexer/src/handlers.rs
db/api/Cargo.toml
db/api/src/tickets.rs
db/sql/Cargo.toml
db/sql/src/tickets.rs
logic/strategy/Cargo.toml
logic/strategy/src/auto_redeeming.rs
logic/strategy/src/lib.rs

- Remove `on_close_redeem_single_tickets_value_min` config option in the AutoRedeem strategy. The only limiting factor for ticket redemptions is `minimum_redeem_ticket_value`.
- Refactored ticket selector methods to use range bounds instead of strict comparisons. Modified selector criteria for indices, winning probability, and amounts.

Remove single ticket redeem bound in AutoRedeem strategy

---

Cargo.lock
crypto/packet/Cargo.toml
crypto/packet/benches/packet_crypto.rs

Add benchmarks for packet creation, forwarding and receiving. Excluding potential cache operations done to retrieve channel information.
These benchmarks represent the upper bound on potential packet throughput.
- `packet_sending_bench`: benchmarks the creation process  `n`-hop packets (for `n` = 0,1,2,3)
- `packet_forwarding_bench`: benchmarks the packet operation done by the relayer (regardless of the number of hops)
- `packet_receiving_bench`: benchmarks the packet operation done by the packet recipient to recover the actual packet payload (regardless of the number of hops)
To run: `cargo bench -p hopr-crypto-packet`

Add criterion benchmarks for crypto-packet crate

---

common/internal-types/src/protocol.rs
common/internal-types/src/tickets.rs
common/primitive-types/src/errors.rs
common/primitive-types/src/lib.rs
common/primitive-types/src/primitives.rs
common/primitive-types/src/traits.rs
crypto/packet/benches/packet_crypto.rs
crypto/packet/src/chain.rs
crypto/packet/src/packet.rs
crypto/packet/src/por.rs
crypto/types/src/types.rs
crypto/types/src/vrf.rs
hoprd/rest-api/src/types.rs
transport/network/src/messaging.rs

Ticket received on the last hop has no value and therefore does not need to be validated. This was causing a backwards compatibility bug, when a 2.1.x version sent an invalid Index Offset on the last ticket anyway.
This fixes backwards compatibility of 2.2 with 2.1.x
Also adds better ParseError traceability.

Remove ticket validation from the last hop

---

Cargo.lock
common/internal-types/Cargo.toml
common/internal-types/benches/bloom_filter.rs
common/internal-types/src/protocol.rs

The `Bloom` filter no longer behaves as a ring buffer after the update to 2.0
This fact has been addressed in the `TagBloomFilter` wrapper, which makes sure that the count of the entries in the filter is correctly tracked.
Also, the false-positive rate decreased to 0.001%
and the capacity is kept at 10M replay tags.
Unit tests have been added to correctly test the new required behavior.
Benchmark was added for Bloom filter performance measurements

Fix TagBloomFilter behavior after updating the crate to 2.0

---

common/network-types/src/session/state.rs
common/network-types/src/session/utils.rs
common/network-types/src/utils.rs
hoprd/rest-api/src/session.rs

The `ReaderStream` has slightly different semantics of buffering data, and that led to data being incorrectly chunked into WS messages.
This has been replaced with `AsyncReadStreamer` which is a fairly simple converter from `AsyncRead` instance into the `Stream` of chunks - by always reading most up to the given number of bytes or waiting if there's nothing to read yet.
This has already been previously used inside the Session and is tested.
Small refactorings have been also made in this PR.

Replace `ReaderStream` with `AsyncStreamReader` in WS Session handler

---

Cargo.lock
common/network-types/Cargo.toml
common/network-types/src/udp.rs
hoprd/rest-api/Cargo.toml
hoprd/rest-api/src/session.rs
transport/session/Cargo.toml
transport/session/src/manager.rs

When UDP-based Session goes idle or is closed by the other side, it should be correctly removed from the Session list.
Also added some cosmetic code improvements.

Properly remove Session from the list when it terminates spontaneously

---

Cargo.lock
chain/indexer/Cargo.toml
chain/indexer/src/block.rs
chain/indexer/src/handlers.rs
chain/indexer/src/lib.rs
db/sql/Cargo.toml
db/sql/src/info.rs

This PR fixes multiple bugs found in the Indexing code so far:
1. The error handling in `collect_block_events` method was causing an early termination of log processing within the block if an error was encountered. This resulted in the remaining logs in the given block to be unprocessed. This also currently affects all 2.1.x versions and is **`the most likely cause of diverging Indexer checksums and rejected tickets`**.
2. invalid querying of the block number stream in Fast-Sync (https://github.com/hoprnet/hoprnet/blob/bf696e4ad2e537d1e084d6f0360e0992b1eef50d/chain/indexer/src/block.rs#L161) results in an infinite loop. It didn't cause an infinite loop before due to side-effects of the bug 1)
3. when Fast-Sync determines if the Indexer DB is empty, it incorrectly accounted node's own …

Fix bugs in log processing and fast-sync

---

SETUP_LOCAL_CLUSTER.md
hoprd/rest-api/src/preconditions.rs
scripts/setup-local-cluster.sh

- websocket authentication needed to decode the URI string to compare against a valid token
- allow local cluster with api authentication as documented in [SETUP_LOCAL_CLUSTER.md](https://github.com/hoprnet/hoprnet/compare/este/clusterAuth?expand=1#diff-7bc89c354a4ac2167f5c0942d569c5383711a4c492d4fecb9be030c848bcf299)

Fix websocket authentication

---

Cargo.lock
chain/indexer/Cargo.toml
chain/indexer/src/block.rs
chain/indexer/src/config.rs
hoprd/hoprd/src/cli.rs
hoprd/hoprd/src/config.rs

This PR fixes the following two issues:
1. When `hopr_logs.db` is present, the Index DB is empty, but Fast-Sync is disabled, the node should sync fully from the RPC. However, it was mistakenly using the last processed block from the `hopr_logs.db`
2. The CLI parameters where incorrectly parsed: the `--noXYY` or `--disableXYZ` CLI args are count-based, and therefore the corresponding config feature should be enabled when these CLI args are equal to 0.

Fix Fast-Sync CLI parameters and behavior when full re-sync is required

---

hoprd/hoprd/src/main.rs

Sets `ME_AS_ALIAS` as an alias to the node only if it is not in the DB already.

Set own alias at startup only if absent

---

hoprd/hoprd/example_cfg.yaml
transport/network/Cargo.toml
transport/network/src/config.rs
transport/p2p/Cargo.toml
transport/p2p/src/swarm.rs

The configuration created a behavior different from 2.1.x which unnecessarily complicated the node interactions. The configuration will be revisited in 3.0 to set proper new values.
@ausias-armesto FYI.

Return backwards compatible configuration with 2.1.x versions

---

.github/workflows/build-binaries.yaml
.github/workflows/build.yaml
flake.nix
hoprd/hoprd/build.rs
nix/rust-package.nix

This ensures users who build cross-platform binaries don't have to perform the `patchelf` step separately. Also the Github actions are simplified that way.

nix: Add patchelf step to cross-builds

---

Cargo.lock
transport/protocol/Cargo.toml
transport/protocol/src/lib.rs

Since all metrics are `lazy_static!`, it means they are not primed (set to 0) immediately, but at a point they are first accessed.
This means, that they do not appear in the `node/metrics` endpoint until they were accessed for the first time.
This PR forcibly initializes the lazy static metrics everywhere, where they might not be used early.

Early initialize lazy static metrics to prime them

---

Cargo.lock
hoprd/hoprd/example_cfg.yaml
hoprd/hoprd/src/cli.rs
hoprd/hoprd/src/config.rs
hoprd/hoprd/src/exit.rs
hoprd/hoprd/src/main.rs
hoprd/rest-api/Cargo.toml
hoprd/rest-api/src/lib.rs
hoprd/rest-api/src/messages.rs
hoprd/rest-api/src/session.rs
transport/api/src/config.rs

This PR makes it possible to specify the default IP listening host (`ip:port`) for Session sockets (for IP forwarding) in the `session_ip_forwarding` section (via `default_entry_listen_host`)
The `listen_host` argument for the `POST session/udp and tcp` REST API now allows partial specification of the listening host. All the following values for `listen_host` are valid:
1) `0.0.0.0:0`
2) `1.2.3.4:1234`
3) `:0`
4) `0.0.0.0`
5) `1.2.3.4`
6) `:1234`
In cases 3-4 the corresponding missing part is replaced by the value from `default_entry_listen_host` (when specified).
The default value for `default_entry_listen_host` if unspecified is `127.0.0.1:0`.
The configuration code was refactored for clarity.

Add default session listen host option

---

Cargo.lock
hoprd/hoprd/example_cfg.yaml
transport/api/Cargo.toml
transport/api/src/lib.rs
transport/network/Cargo.toml
transport/network/src/config.rs
transport/network/src/constants.rs
transport/network/src/heartbeat.rs

Improvements to the heartbeat logic:
Refs #6662

Heartbeat improvements and configurability

---

Cargo.lock
README.md
db/sql/Cargo.toml
db/sql/src/db.rs

Previously the peers were all purged on DB start. This PR adds a new functionality, whereby the most recent records (last record update within the <5mins window) will be kept in the database, to allow orchestrated nodes (K8s, docker...) to retain parts of recent network knowledge after restart.
The most significant changes include the addition of a new configuration option for peer database persistence, updates to the database schema, and new tests to verify the correct behavior of peer cleanup on restarts.
* Added `HOPR_INTERNAL_DB_PEERS_PERSISTENCE_AFTER_RESTART_IN_SECONDS` configuration option to specify the cutoff duration for retaining peers in the database after a restart.
* Defined a default value for `HOPR_INTERNAL_DB_PEERS_PERSISTENCE_AFTER_RESTART_IN_SECONDS` in …

Do not purge peers with records fresher than 5 mins from the DB on restart

---

Cargo.lock
db/sql/src/db.rs
hoprd/rest-api/Cargo.toml
hoprd/rest-api/src/messages.rs
hoprd/rest-api/src/session.rs
scripts/local-cluster-hoprd.cfg.yaml
tests/test_websocket_api.py

Fixes to the REST API behavior:
* [`db/sql/src/db.rs`](diffhunk://#diff-8486b4d107ff48d05d4b876721cafc2d92649ae60b14ee2e16f3d8f3bd506899L163-R163): Updated the debug log statement to use structured logging for the number of rows affected.
* [`hoprd/rest-api/src/messages.rs`](diffhunk://#diff-3d882919c608469f3817110ac12c79adbf27b25de00d91b55c6c5ceeb6cdfbf7L538-R539): Changed the request parameter type from `Query` to `Json` body for the `pop`, `pop_all`, and `peek` functions to handle JSON payloads. [[1]](diffhunk://#diff-3d882919c608469f3817110ac12c79adbf27b25de00d91b55c6c5ceeb6cdfbf7L538-R539) [[2]](diffhunk://#diff-3d882919c608469f3817110ac12c79adbf27b25de00d91b55c6c5ceeb6cdfbf7L589-R590) [[3]](diffhunk://#diff-3d882919c608469f3817110ac12c79adbf27b25de00d91b55c6c5ceeb6cdfbf7L641-R642)
* …

Fix message API request bodies and session target acceptance

---

chain/rpc/src/indexer.rs
hoprd/hoprd/src/main.rs

By pinning the main loop onto the heap the internally generated futures and respective scaffolding would live on the heap as well instead of blowing up the stack.
Fixes #6656 
Some references:
https://users.rust-lang.org/t/tools-for-inspecting-stack-usage/115132
https://rust-lang.github.io/wg-async/vision/submitted_stories/status_quo/alan_runs_into_stack_trouble.html
https://deislabs.io/posts/a-heaping-helping-of-stacks/

tokio: Pin main loop on heap

---

transport/p2p/src/swarm.rs

The error on dialing for offline peers was expected in the heartbeat protocol and should not be a reason for error log.
This should clean the logs up significantly.

Update the logging to remove the offline peer error on heartbeat

---

Cargo.lock
README.md
chain/indexer/Cargo.toml
chain/indexer/src/block.rs
chain/rpc/Cargo.toml
chain/rpc/src/client.rs
chain/rpc/src/indexer.rs
db/api/Cargo.toml
db/api/src/logs.rs
db/sql/Cargo.toml
db/sql/src/logs.rs
hoprd/hoprd/src/main.rs

The indexer hot-path crashed during the processing of logs. The hot-path has been improved to do fewer db operations and be more performant.
Moreover, fast-sync resume has been added. Previously, if the node crashed during fast-sync, it would end up with an incomplete index and never complete it.
Lastly, the http client has been configured to accept brotli and zstd content encoding, drastically reducing the transmitted data, and keep TCP connections open for 30 seconds.
Fixes #6665
Fixes #6664

Fix tokio stack overflow crash during indexing

---

flake.nix
nix/docker-builder.nix

This pull request introduces a new Docker entrypoint script which sets the environment variable `HOPRD_DEFAULT_SESSION_LISTEN_HOST` to the docker container's IP, unless it was configured by the user beforehand.
This allows session users to only specify the listen port when opening a session, e.g. `:50001`, and the hoprd node will use the default internal docker ip automatically.
Moreover, other hopr binaries can now be run using the docker image by specifying them as commands. E.g.
```
docker run -ti --rm hoprd:latest hoprd-api-schema
```

docker: Preset session listen host

---

flake.nix
nix/rust-builder.nix
nix/rust-package.nix

The problem was the cross build identification when the build platform was the same as the target platform. This has been made explicit in the configuration of the builder now.
Fixes #6689

nix: Fix cross-build on same platform

---

.gitignore
Cargo.lock
hopr/hopr-lib/src/lib.rs
hoprd/rest-api/Cargo.toml
hoprd/rest-api/src/lib.rs
hoprd/rest-api/src/node.rs
logic/path/Cargo.toml
logic/path/src/channel_graph.rs
logic/path/src/selectors/legacy.rs
nix/shell.nix

This PR add a new REST API endpoint `/node/graph` that outputs the channel/transport graph as DOT-formatted file. This format can be visualized using tools such as `graphviz`.

Add endpoint for exporting Channel Graph in DOT format

---

.github/workflows/build-docker.yaml
.github/workflows/build.yaml

By default PRs build docker images which include a hoprd debug build. This is done to have faster build times in the CI. This PR adds the option to build production images by adding the Github label `docker-production-build` to a PR and rebuilding the image.

gha: Enable docker production build in PR

---

Cargo.lock
chain/actions/Cargo.toml
chain/actions/src/action_queue.rs
chain/actions/src/errors.rs
chain/actions/src/redeem.rs
chain/types/src/chain_events.rs
common/internal-types/src/announcement.rs
db/sql/Cargo.toml
db/sql/src/db.rs
db/sql/src/ticket_manager.rs
db/sql/src/tickets.rs
deploy/compose/prometheus/metricspusher.sh
hopr/hopr-lib/src/lib.rs
logic/path/src/selectors/legacy.rs
logic/strategy/src/aggregating.rs
logic/strategy/src/auto_redeeming.rs
transport/api/src/helpers.rs
transport/api/src/lib.rs
transport/p2p/src/swarm.rs
transport/protocol/src/lib.rs
transport/protocol/src/ticket_aggregation/processor.rs
transport/protocol/tests/msg_ack_workflows.rs

- update ticket redemption code to not try to redeem tickets with index lower than on the channel entry
- add unit tests for such scenarios
- do not hold ticket redeem DB stream opened for too long
- reorder processing of the acknowledged ticket notification: now the notification is done by the TicketManager *after* the ticket has been persisted into the DB.
- ticket replacement after aggregation has been moved into the TicketManager

Improve ticket redemption handling

---

Cargo.lock
hopr/hopr-lib/src/lib.rs
hoprd/hoprd/src/exit.rs
hoprd/rest-api/Cargo.toml
hoprd/rest-api/src/session.rs
tests/hopr.py
tests/test_session.py
transport/api/Cargo.toml
transport/api/src/lib.rs
transport/session/Cargo.toml
transport/session/src/lib.rs
transport/session/src/manager.rs
transport/session/src/types.rs

The PR introduces a special target, which makes the Exit node to perform loopback of data received on a session back to it.
This is especially useful for the CT, so that no special echo service needs to be set up and the CT operation can be done from a single socket per each node.
This loopback service has ID 0, thus for `target`, the user specifies `"target": {"Service": 0}` in the REST API endpoint (instead of usual `"Plain": ...`)

Add Loopback service to simplify usage for the CT

---

hoprd/hoprd/example_cfg.yaml

Remove no longer existing configuration options from the example config:

cfg: Cleanup the example configuration

---

hoprd/rest-api/Cargo.toml
hoprd/rest-api/src/messages.rs

Fix the missing challenge in the send message response for backwards compatibility.
Fixes #6674

Add back challenge into the send_message endpoint

---

Cargo.lock
chain/indexer/Cargo.toml
chain/indexer/src/block.rs
db/sql/Cargo.toml
db/sql/src/info.rs
hopr/hopr-lib/src/lib.rs
hoprd/rest-api/Cargo.toml
hoprd/rest-api/src/node.rs

Sunsets existing indexer checksum info in the API's node info endpoint and adds additional values which reflect the new log implementation.
Fixes #6659

api: Add additional indexer info

---

Cargo.lock
db/sql/Cargo.toml
db/sql/src/ticket_manager.rs

Adjusted the ticket deletion logic in `ticket_manager.rs` to ensure the deleted ticket count is validated correctly, preventing logical errors.
Bumped the crate version to 0.11.1 in `Cargo.toml` and `Cargo.lock` to reflect changes.
Closes #6761

Fix ticket deletion check

---

Cargo.lock
hoprd/rest-api/Cargo.toml
hoprd/rest-api/src/node.rs

- Updated the `NodeVersionResponse` struct to include a new `apiVersion` field and adjusted the `version` endpoint to return this additional information. Added `serde` attribute for consistent JSON formatting.
- Bumped the package version in Cargo files to 3.10.0.
Closes #6697

Include `apiVersion` into `node/version` endpoint

---

Cargo.lock
hoprd/rest-api/Cargo.toml
hoprd/rest-api/src/alias.rs
hoprd/rest-api/src/lib.rs
sdk/python/api/hopr.py
sdk/python/api/response_objects.py
tests/test_integration.py

The API endpoints `GET aliases` and `GET aliases/:alias` have been doubled in this PR, as  `GET aliases_addresses` and `GET aliases_addresses/:alias` to be able to get peer ETH address from those endpoints.

Extension alias endpoints to return ETH addresses in addition to PeerIds

---

crypto/sphinx/src/routing.rs
crypto/types/src/keypairs.rs

The protocol design was relying on the first byte of public key to never be equal to `0xff`. This was true for secp256k1 keys.
However, it is not the case for Ed25519 public keys as the top-most bit is set depending on the point sign.
This PR fixes this problem by re-organizing the header format, so that the path position is the first byte (possible values: `0x00`, `0x01`, `0x02`) and the `0xff` is set for the last hop.
This ensures it is prefix free.
Supersedes: #5665

Fix public key prefix bug

---

transport/p2p/src/lib.rs

Increase the number of concurrent streams allowed by the msg and ack protocols.

Allow high traffic throughput communication for VPN like traffic

---

chain/api/src/lib.rs
chain/rpc/src/lib.rs
chain/rpc/src/rpc.rs
crypto/packet/src/validation.rs
db/api/src/protocol.rs
db/sql/src/protocol.rs
hopr/hopr-lib/src/lib.rs
transport/api/src/lib.rs
transport/protocol/src/config.rs
transport/protocol/src/msg/processor.rs
transport/protocol/tests/msg_ack_workflows.rs

This change allows to configure manually the ticket price (using `protocol.outgoing_ticket_price` option) to override the value from the oracle with the higher possible price.
Prices lower than the network value are not possible and validated on the node start.
Also a bug has been fixed in the ticket validation, where the expected minimum ticket value should not be the value from the oracle, but it should be multiplied by the path position.

Allow manual configuration of the ticket price

---

transport/api/src/lib.rs
transport/network/src/config.rs

This PR adds the `network.quality_auto_path_threshold` (defaults to 0.95) to allow the auto-path finding algorithm to ignore nodes, which have lower quality than this threshold.

Make auto-path finding quality threshold configurable

---

hoprd/hoprd/Cargo.toml

Use QUIC as a default transport announcement 

---

.github/workflows/tests.yaml
Cargo.lock
hoprd/hoprd/Cargo.toml
transport/identity/src/lib.rs
transport/network/src/ping.rs
transport/p2p/Cargo.toml
transport/p2p/src/swarm.rs
transport/p2p/tests/p2p_transport_test.rs

Add QUIC support as the default implementation:
On a decently fast machine the result of a raw QUIC based request-response communication was ~2MB/s.
```
2025-01-30T01:17:40.584711Z  INFO p2p_transport_test: The measured speed for data transfer is ~1.9284369114877589MB/s
```

Update the default hoprd announce to QUIC and add basic p2p transport integration test for QUIC

---

Cargo.lock
db/sql/Cargo.toml
db/sql/src/tickets.rs
transport/network/Cargo.toml
transport/network/src/ping.rs
transport/p2p/Cargo.toml
transport/p2p/src/swarm.rs
transport/protocol/Cargo.toml
transport/protocol/src/ticket_aggregation/processor.rs

A cap of 10k tickets per aggregation batch was added. The maximum number of tickets in the aggregation request will not go over this limit.
This PR also fixes the notifier problem, that may occur when `Arc<oneshot::Sender>` was cloned by the cache. That resulted in the notification about ping/aggregation not being called and therefore, stalling tickets in the `BeingAggregated` state.
Closes #6813

Cap on aggregation batch size and fix swarm notifiers

---

db/sql/src/tickets.rs

Some printouts in the debug logs were printing large arrays of tickets, which quickly filled the debug logs. This has been fixed.

Remove excessive arrays from debug logs

---

Cargo.lock
common/internal-types/src/tickets.rs
db/sql/Cargo.toml
db/sql/src/tickets.rs

Floats representing winning probability were compared in the Sqlite3 DB using their binary representations, which was incorrect, as they should be compared as floats.

Fix winning probability comparison when preparing ticket aggregation

---

db/sql/src/tickets.rs

This is to workaround a CBOR codec limitation for now.

Change the ticket aggregation batch size to 500

---

chain/indexer/src/block.rs

Chain head was incorrectly queried from the RPC on each fast-synced block, leading to slow fast-sync times.

Remove chain head query from fast-sync

---

README.md
chain/rpc/src/rpc.rs
transport/protocol/src/lib.rs
transport/protocol/src/msg/mixer.rs
transport/protocol/src/msg/processor.rs
transport/protocol/tests/msg_ack_workflows.rs

This PR changes the maximum mixer delay to 50 milliseconds and makes it configurable via new environment variable: `HOPR_INTERNAL_MIXER_PACKET_MAX_DELAY_MILLIS`

Adjust default  maximum mixer delay

---

deploy/compose/hoprd_data/hoprd.cfg.yaml
hoprd/hoprd/example_cfg.yaml
hoprd/hoprd/src/config.rs
hoprd/hoprd/src/exit.rs
hoprd/hoprd/src/main.rs
logic/strategy/src/channel_finalizer.rs
sdk/barebone-lower-win-prob.cfg.yaml
sdk/barebone.cfg.yaml
sdk/default.cfg.yaml

Per default, nodes should not be acting as Exit nodes (receive Sessions), unless some list of allowed targets is specified. This has been reflected in all default configs.
Note that this change does not affect Service-type Sessions, such as the ones used by the CT. These will always be allowed to be opened.
Also corrected other defaults in the config.

Make the allowlist of Session targets empty in default configs

---

.github/workflows/merge.yaml

Before even a closed PR would have been tagged as the latest docker image.

gha: Fix merge workflow to not run on closed

---

hoprd/hoprd/example_cfg.yaml
logic/strategy/src/aggregating.rs

Align the default value for ticket aggregation in the middle of the possible range.
The current aggregation value means, that e.g. for CT with p=1.0 and ticket price = 0.0015, given the maximum non-sloped off stake at 75k, the CT node will generate 1msg/5s.
1 aggregation request period = 250[msg] / 1/5[msg/s] = 1250s

Set the aggregation ticket threshold to the middle of configuration range

---

Cargo.lock
transport/p2p/Cargo.toml
transport/p2p/src/behavior/discovery.rs
transport/p2p/src/lib.rs
transport/p2p/src/swarm.rs

As identified by @tolbrino the swarm voids the cache for the peer id that failed to dial, causing the multiaddress to be further unknown for redials, causing an incremental decline in peer connectability.
To solve this, the node now holds the entire announced peer list and on failed dials reinserts the multiaddress for a peer that failed to be dialed.
Closes #6869

Fix the cache cleaning of multiaddresses on peer dial

---

flake.nix

The shell test would succeed for directories too, which is incorrect.

docker: Fix entrypoint script

---

Cargo.lock
chain/indexer/Cargo.toml
chain/indexer/src/handlers.rs
common/internal-types/src/channels.rs
db/sql/Cargo.toml
db/sql/src/channels.rs

Foreign channels (the ones where the running node is not source nor destination) do not need to be kept in the database once they are closed.
To be merged after: #6739 
Fixes #6880

Delete closed foreign channels from the database

---

Cargo.lock
hoprd/hoprd/example_cfg.yaml
logic/strategy/Cargo.toml
logic/strategy/src/auto_funding.rs
logic/strategy/src/promiscuous.rs

- several default values were tweaked and renamed.
- fixed a bug of incorrectly filtered out offline peers.

Fix incorrectly filtered out offline peers and other tweaks in Promiscuous strategy defaults

---

Cargo.lock
logic/strategy/Cargo.toml
logic/strategy/src/promiscuous.rs

Introduced an `initial_delay` configuration to defer strategy actions after startup. Enhanced peer handling logic to incorporate heartbeat pings, ensuring decisions are based on peers with sufficient activity. These changes improve channel management reliability and configurability.
Refs #6879

Add initial delay and improve peer pings handling in strategy

---

sdk/python/localcluster/constants.py
tests/conftest.py
tests/pytest.ini
tests/test_hopli.py
tests/test_integration.py
tests/test_redeeming.py
tests/test_rest_api.py
tests/test_session.py
tests/test_websocket_api.py
tests/test_win_prob.py

This change is needed to add alternative swarm7 fixture implementations. 
- The original swarm7 is executed per test session instead of per module, reducing test runtime when executing multiple test modules.
- The teardown fixture is  used selectively on test classes which are explicitly using swarm7. This allows test suites which use alternative swarm7 implementations to not use that teardown fixture.
Refs #6908

tests: Fix per-test teardown

---

.github/workflows/build-binaries.yaml
.github/workflows/build-dappnode.yaml
.github/workflows/build-docker.yaml
.github/workflows/build-docs.yaml
.github/workflows/build.yaml
.github/workflows/clean-pr.yaml
.github/workflows/cleanup.yaml
.github/workflows/close-release.yaml
.github/workflows/deploy-nodes.yaml
.github/workflows/generate-dappnode-pr.yaml
.github/workflows/k8s.yaml
.github/workflows/latexcompile.yaml
.github/workflows/lint.yaml
.github/workflows/load-tests.yaml
.github/workflows/merge.yaml
.github/workflows/open-release.yaml
.github/workflows/promote-release.yaml
.github/workflows/publish-release.yaml
.github/workflows/renovate-cargo-update.yaml
.github/workflows/tests.yaml
.github/workflows/update-flake-lock.yaml
.github/workflows/zizmor.yaml
nix/shell.nix

Inspired by https://www.stepsecurity.io/blog/harden-runner-detection-tj-actions-changed-files-action-is-compromised
Security dashboard: https://app.stepsecurity.io/github/hoprnet/actions/dashboard
Also add new GHA workflow `zizmor` which runs a static analysis on all Github workflows and reports them to GHA as code security issues.
Example: https://github.com/hoprnet/hoprnet/security/code-scanning?query=pr%3A6934+

ci: Add harden-runner to all workflows

---

Cargo.lock
db/sql/Cargo.toml
db/sql/src/tickets.rs

During the aggregation check values of previously aggregated tickets are now also taken into account. This is fine since there is a safe-guard which ensures that the number of aggregated tickets must be more than 1.
Refs #6926

db: Fix ticket aggregation balance threshold

---

.github/workflows/build-dappnode.yaml

The previous approach would also match `2.2.3-commit` which is not expected.

ci: Fix prefix match in dappnode action

---

METRICS.md
chain/indexer/src/handlers.rs
logic/strategy/src/promiscuous.rs
transport/session/src/manager.rs

To follow Prometheus metrics naming conventions, each counter should end in `_total`, `_sum`, `_bucket` or `_count`.
The following metrics have been renamed:
- ~`hopr_strategy_promiscuous_max_auto_channels` -> `hopr_strategy_promiscuous_max_auto_channels_count`~
- ~`hopr_session_num_active_sessions` -> `hopr_session_active_sessions_count`~
- `hopr_session_established_sessions` -> `hopr_session_established_sessions_count`
- `hopr_session_initiated_sessions` -> `hopr_session_initiated_sessions_count`
- `hopr_session_received_error_counts` -> `hopr_session_received_error_count`
- `hopr_session_sent_error_counts` -> `hopr_session_sent_error_count`
- `hopr_indexer_contract_log_counters` -> `hopr_indexer_contract_log_count`
There's an open PR https://github.com/hoprnet/gitops/pull/263 to update …

Follow Prometheus metrics naming convention

---

nix/mkShell.nix

The linker was missing in the shell when needed on Darwin.

nix: Add missing lld to shell

---

Cargo.lock
Cargo.toml
crypto/types/Cargo.toml

Update dependencies:
This pull request updates several dependencies across the project to their latest versions. These updates primarily focus on maintaining compatibility, improving security, and benefiting from upstream bug fixes.
* Updated the `axum` dependency from `0.8.3` to `0.8.4`, which includes improvements and bug fixes for web framework features like WebSocket and HTTP/2.
* Upgraded the `chrono` dependency from `0.4.40` to `0.4.41`, likely addressing minor bug fixes or improvements in the date and time library.
* Updated `libp2p-identity` from `0.2.10` to `0.2.11`, ensuring compatibility and enhancements in peer identity handling.
* Bumped `tokio-util` from `0.7.14` to `0.7.15`, improving utility features for the Tokio async runtime.
* Updated `blake3` from `1.8.0` to `1.8.2`, …

deps: Update cargo dependencies

---

common/network-types/Cargo.toml
common/network-types/benches/session.rs
common/network-types/src/session/mod.rs

This pull request refactors the handling of the `FaultyNetwork` and `FaultyNetworkConfig` utilities by consolidating their usage and removing conditional compilation for the `testing` feature. The changes streamline the codebase and improve maintainability.
* [`common/network-types/benches/session.rs`](diffhunk://#diff-b0c2fda04b5b34fbd454b1d7ac033ee816c410c842ce05d2240ce7df49a0cbb0R1-R12): Introduced a new `mod utils` declaration with an explicit path to `utils.rs`, allowing the `FaultyNetwork` and `FaultyNetworkConfig` utilities to be used without conditional compilation. Removed the `compile_error!` macro that enforced the presence of the `testing` feature.
* [`common/network-types/src/session/mod.rs`](diffhunk://#diff-ce43aec550149c6fe980dbc6205afb04e8228b355863a135a22459b840b5647dL27- …

Use bench without the testing feature

---

Cargo.lock
Cargo.toml
common/network-types/Cargo.toml
db/api/Cargo.toml
hoprd/rest-api/Cargo.toml
transport/network/Cargo.toml
transport/protocol/Cargo.toml
transport/protocol/benches/protocol_throughput_emulated.rs

This pull request includes updates to dependencies and some minor code changes. The most notable updates involve upgrading various dependency versions and removing unused dependencies across multiple `Cargo.toml` files. Additionally, there is a minor change in a benchmarking file to improve code clarity.
* Updated the versions of several dependencies in `Cargo.toml`, including `clap` (4.5.38), `sea-orm` (1.1.11), `sea-query` (0.32.5), `signal-hook` (0.3.18), and `tempfile` (3.20.0). [[1]](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L74-R74) [[2]](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L143-R153) [[3]](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L163-R168) …

deps: Update and clean

---

Cargo.lock

1 dependency was incorrectly updated in #7131 . This PR fixes it.

deps: Fix inconsistent Cargo.lock

---

Cargo.lock
transport/p2p/Cargo.toml
transport/p2p/src/constants.rs
transport/p2p/src/lib.rs
transport/p2p/src/swarm.rs

If the heartbeat protocol remained unchanged, a v2 release would collide with the current implementation on the `msg/ack` protocol level within the same network.
Heartbeat maps the current network to usable peers. If v2 peers (`singapore`) can't connect to the latest release due to protocol version changes, they discard v3 peers from the usability mapping. Conversely, the latest nodes attempt to probe v2 nodes but fail to register them for message sending due to protocol differences.

protocol: Bump heartbeat protocol version to disallow connections to previous versions

---

Cargo.toml
flake.lock
logic/path/src/channel_graph.rs
rust-toolchain.toml

This pull request includes two minor updates to the Rust project configuration files. The changes involve formatting improvements and updating the Rust toolchain version.
Configuration updates:
* [`Cargo.toml`](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L78-R78): Reformatted the `criterion` dependency to place all features on a single line for consistency.
* [`rust-toolchain.toml`](diffhunk://#diff-2b1bde2cf3a858b7bf7424cb8bcbf01f35b94dc80b925d9432cbab3319ca9b4eL2-R2): Updated the Rust toolchain version from `1.86` to `1.87`.
Fix linting and formatting issues in `master`.

toolchain: Update Rust to 1.87

---

Cargo.toml
hoprd/hoprd/src/main.rs

This pull request removes references to the `surf` library and its related components from the project. The changes involve cleaning up dependencies and adjusting logging configurations accordingly.
* [`Cargo.toml`](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L179-L180): Removed the `surf` and `surf-governor` dependencies from the project. These libraries are no longer used.
* [`hoprd/hoprd/src/main.rs`](diffhunk://#diff-b4d76d2ca8cb825810502c755c62f98c6e9e784a5197c0d4fe93d9171be7914bL41): Removed the logging directive for `surf::middleware::logger::native` in the `init_logger` function, as the `surf` library has been removed.

deps: Remove surf and surf-governor

---

Cargo.toml
nix/docker-builder.nix

This pull request refactors the `nix/docker-builder.nix` file to improve readability and functionality by reorganizing code and adding a new library path. The most important changes include consolidating the parameter declaration, adding a library path for OpenSSL, and simplifying the `contents` array formatting.
* Consolidated the parameter declaration into a single line for improved readability.
* Added a new `libPath` variable to include the OpenSSL library path, and updated the `Env` array to set the `LD_LIBRARY_PATH` environment variable. This ensures that the necessary libraries are available at runtime.
* Simplified the formatting of the `contents` array by combining elements into a single line, making the code more concise.

docker: Fix missing SSL library in the image 

---

.github/workflows/cleanup.yaml
.github/workflows/tests.yaml
.github/workflows/update-flake-lock.yaml
hopr/hopr-lib/data/protocol-config.json

- Fixed upload of log files to GCP for every smoke test suite
- Fixed permission problem in flake update GHA workflow
- Fixed missing Git checkout in cleanup GHA workflow
- Fixed protocol config to allow 3.x nodes in Rotsee and Dufour networks, also removed obsolete Monte Rosa network

ci: Fix log upload

---

flake.nix
nix/cargo-bench.nix
nix/ciShell.nix
nix/ciTestShell.nix
nix/devShell.nix
nix/docker-builder.nix
nix/mkShell.nix
nix/rust-builder.nix
nix/rust-package.nix
nix/testShell.nix

This pull request refactors multiple Nix files to improve code readability and maintainability by adopting a consistent formatting style. The changes primarily involve restructuring function arguments, reformatting lists, and improving indentation. Additionally, some minor logic adjustments and cleanups were made to streamline the code.
* Updated function argument definitions across all modified files to use a consistent inline object format instead of a mix of destructured and inline styles. This change improves readability and aligns with common Nix conventions. (`nix/cargo-bench.nix` - [[1]](diffhunk://#diff-2e576ca04cdc311f97e3619ce90c45ec70e7d53e6170c41045697223c62cf889L1-R25) `nix/ciShell.nix` - [[2]](diffhunk://#diff-e2b1cc06fb4e986ed68bd96ae1ad461d8cba80219bae109c09cbfbed51696e93L1 …

nix: Full reformat according to RFC 166

---

Cargo.lock
Cargo.toml
hoprd/rest-api/Cargo.toml

This pull request updates several dependencies in the `Cargo.toml` files across the project to ensure compatibility with newer versions and maintain library security and stability. The changes include version bumps for dependencies in the root `Cargo.toml` as well as the `hoprd/rest-api/Cargo.toml`.
* Updated `async-signal` from `0.2.10` to `0.2.11` for minor improvements or bug fixes.
* Updated `socket2` from `0.5.9` to `0.5.10` and `sqlx` from `0.8.5` to `0.8.6` for better performance and stability.
* Updated `tokio` from `1.45.0` to `1.45.1` to include the latest features and fixes.
* Updated `uuid` from `1.16.0` to `1.17.0` to maintain compatibility with other dependencies.
* Changed `tower` to use the workspace version for consistency across the project.
* Updated `utoipa-swagger-ui` …

deps: Update older dependencies

---

Cargo.lock
hopr/hopr-lib/src/lib.rs
hopr/hopr-lib/tests/session_integration_tests.rs
hoprd/rest-api/src/prometheus.rs
hoprd/rest-api/src/session.rs
transport/api/src/lib.rs
transport/packet/Cargo.toml
transport/packet/src/errors.rs
transport/packet/src/lib.rs
transport/packet/src/v1.rs
transport/probe/src/probe.rs
transport/session/Cargo.toml
transport/session/src/errors.rs
transport/session/src/initiation.rs
transport/session/src/lib.rs
transport/session/src/manager.rs
transport/session/src/types.rs

Changes to the packet structure in the tag section and reserved tag allocation:

Improve the tag organization for v3 packet payload format

---

Cargo.lock
chain/api/Cargo.toml
chain/api/src/lib.rs
chain/indexer/src/block.rs
common/async-runtime/Cargo.toml
common/async-runtime/src/lib.rs
hopr/hopr-lib/src/lib.rs
hopr/hopr-lib/tests/chain_integration_tests.rs
hoprd/hoprd/src/main.rs
hoprd/rest-api/src/session.rs
transport/api/Cargo.toml
transport/api/src/lib.rs
transport/probe/Cargo.toml
transport/probe/src/probe.rs
transport/protocol/Cargo.toml
transport/protocol/src/lib.rs
transport/session/Cargo.toml
transport/session/src/manager.rs

This pull request introduces a significant refactor across multiple modules to replace the use of `JoinHandle` with `AbortHandle` for managing asynchronous tasks. This change improves task cancellation capabilities and aligns the codebase with modern async patterns. The changes span several files and include updates to function signatures, imports, and task spawning logic.
* Replaced `JoinHandle` with `AbortHandle` in task management across multiple modules, including `chain/api`, `chain/indexer`, `hopr-lib`, `hoprd`, and `hoprd/rest-api`. This required updating function signatures, return types, and task storage structures. [[1]](diffhunk://#diff-1190b47adce276227437e510df3d3250d35e7857a9f26189ed07cd59291ae13dL244-R250) [[2]](diffhunk://#diff-062748e5c084f2b0e350d07a9361f260daf0176c7dfc98 …

feat(runtime): make spawned tasks abortable through futures mechanism

---

chain/indexer/src/handlers.rs
db/sql/src/accounts.rs
db/sql/src/cache.rs

Fixes errors like `logical error: inconsistent key-id binding`, caused by re-announcements.
Now the key-id binding is inserted only when the announcement is made for the first time, as subsequent updates of key-binding are not necessary.

fix(indexer): key-binding errors

---

.github/workflows/checks-pre-commit.yaml
.github/workflows/checks.yaml

This pull request introduces a new pre-commit workflow to streamline checks before merging and integrates it into the existing `checks.yaml` workflow. The changes focus on defining the pre-commit workflow and ensuring it is properly linked and configured.
* [`.github/workflows/checks-pre-commit.yaml`](diffhunk://#diff-af487f6988a751c9f8f1a422777e3e09ded55b4d843883102510947b0afc9a1fR1-R50): Added a new pre-commit workflow that runs on `merge_group` events and uses self-hosted runners. It includes steps for hardening the runner, checking out the repository, installing Nix, setting up Cachix, and running pre-commit checks.
* [`.github/workflows/checks.yaml`](diffhunk://#diff-4af11422a4987e947e5a47adead7a30d32cdb2db82e2d3fe36f8e6cbe84d5ac5R27-R34): Integrated the pre-commit workflow into the …

feat(ci): add pre-commit checks

---

.github/workflows/build-docker.yaml
Cargo.lock
README.md
db/api/src/protocol.rs
flake.nix
hopr/hopr-lib/Cargo.toml
hoprd/hoprd/Cargo.toml
transport/api/Cargo.toml
transport/mixer/src/channel.rs
transport/probe/Cargo.toml
transport/probe/src/content.rs
transport/probe/src/probe.rs
transport/protocol/Cargo.toml
transport/protocol/hopr.lua
transport/protocol/src/capture.rs
transport/protocol/src/lib.rs
transport/protocol/src/processor.rs

Allows capturing HOPR packets in custom format, which can be dissected via Wireshark.
1. build `hoprd` with the `capture` feature (`cargo b --features capture`)
2. run `hoprd` with `HOPR_CAPTURE_PACKETS=capture-file.pcap`
3. install dissector from `transport/protocol/hopr.lua` into `$HOME/.local/lib/wireshark/plugins/`
4. once `hoprd` terminates, open `capture-file.pcap` in Wireshark
Alternatively, `HOPR_CAPTURE_PACKETS` can specify a UDP socket for `udpdump` (also supported by Wireshark), e.g.: `HOPR_CAPTURE_PACKETS=127.0.0.1:5555`

feat: add Wireshark dissector and custom capture format

---

Cargo.lock
README.md
docs/changelog/changelog-3.0.0-rc.1.md
transport/protocol/Cargo.toml
transport/protocol/src/stream.rs

Adds `HOPR_TRANSPORT_MAX_CONCURRENT_PACKETS` and `HOPR_TRANSPORT_STREAM_OPEN_TIMEOUT_MS` environment variables.
Closes #7304

feat: add configurable limits for transport packet handling and stream open timeout

---

.github/workflows/create-release.yaml
.github/workflows/generate-dappnode-pr.yaml
.github/workflows/merge.yaml
.github/workflows/open-release.yaml
docs/changelog/changelog-3.0.0-rc.1.md

Fixes the following:
- Changes the github token used for tagging because when using pull_request_target it requires write permissions
- Adds manual execution to create-release and generate-dappnode-pr pipelines so they can be launched manually in case of failure.
- Add more robustness to git tag step

fix: Fixing different bugs on create release

---

.envrc
Cargo.lock
db/sql/Cargo.toml
db/sql/src/cache.rs
nix/mkShell.nix
transport/api/src/lib.rs
transport/session/Cargo.toml
transport/session/src/errors.rs
transport/session/src/manager.rs

- Increases the reply opener cache expiration to 1 hour.
- Adds the maximum session limit in the Session manager (for both incoming and outgoing). The default is 16.
- Cherry-pick 4bc56dd

fix: increase reply opener cache timeout and enforce the maximum session limit

---

Cargo.lock
transport/protocol/Cargo.toml
transport/protocol/src/lib.rs

Fixes the missing `forwarded` and `received` types of the packet_count metric. Also fixes the labels for another metric.

fix: improve messages metrics

---

db/sql/Cargo.toml
db/sql/src/db.rs

This pull request modifies database connection settings in the `HoprDb` implementation to address potential database lock issues and optimize connection management. The key changes involve adjusting the `max_connections` parameter for the indexer and peers databases.
* [`db/sql/src/db.rs`](diffhunk://#diff-8486b4d107ff48d05d4b876721cafc2d92649ae60b14ee2e16f3d8f3bd506899L85-L96): Reduced `max_connections` for the indexer database from 30 to 1 to avoid database lock issues by serializing all operations.
* [`db/sql/src/db.rs`](diffhunk://#diff-8486b4d107ff48d05d4b876721cafc2d92649ae60b14ee2e16f3d8f3bd506899L85-L96): Adjusted the `max_connections` for the peers database to ensure it is explicitly set to 300, maintaining the previous behavior but clarifying the configuration.

fix(hopr-lib): decrease the amount of connections to 1 on the index db

---

Cargo.lock
common/internal-types/src/tickets.rs
crypto/packet/src/por.rs
crypto/packet/src/validation.rs
db/sql/Cargo.toml
db/sql/src/accounts.rs
db/sql/src/channels.rs
db/sql/src/info.rs
db/sql/src/protocol.rs
db/sql/src/ticket_manager.rs
transport/protocol/src/lib.rs

The `TicketManager::unrealized_value()` method create a connection even on a cache-hit. This caused connections to be created per-packet, as this method is called in the hot-path.
This bug was present also on 2.x versions, possibly causing the Sessions to get stalled on higher throughputs.

fix: remove ticket manager db connection per-packet

---

Cargo.lock
chain/api/Cargo.toml
chain/api/src/executors.rs
chain/rpc/Cargo.toml
chain/rpc/src/errors.rs
chain/rpc/src/lib.rs
chain/rpc/src/rpc.rs
hopr/hopr-lib/src/lib.rs

Fixes #7342 
The previous approach would wait for on-chain confirmations, but not check the status of the transaction. This has been changed such that if the status if failed, an explicit error is raised.

fix(chain): Raise error on reverted transactions

---

sdk/python/localcluster.test.params.yml
tests/conftest.py
uv.lock

This PR splits the behavior of the localcluster into two modes, wether it's being used as a standalone module, or within the smoketests:
- standalone mode: all node have the same config
- smoketests: the nodes uses the custom configs with different probabilities and strategies

fix(tests): update localcluster parameters and adjust test configuration

---

Cargo.lock
common/network-types/Cargo.toml
common/network-types/src/udp.rs
transport/session/src/manager.rs

As in title.
When `ConnectedUdpStream` was not closed properly via `shutdown` it would leak the UDP socket and not terminate the running processes, effectively causing the process to run OOM when many Sessions were used over time. 
Closes #7450
Refs #7449

fix: end correctly the socket and processes once the entire UDP connection is dropped

---

Cargo.lock
db/migration/Cargo.toml
db/migration/src/lib.rs
db/migration/src/m20250909_000031_peer_store_add_indices.rs
db/sql/src/peers.rs
transport/api/Cargo.toml
transport/api/src/network_notifier.rs
transport/network/Cargo.toml
transport/network/src/network.rs

Indices were missing on columns that are used often in WHERE clauses to query the `NetworkPeer` table.
The PR optimizes the code path of `find_peers_to_ping` which is called very often by the new probing mechanism.
Closes #7442

fix: add missing columns to the NetworkPeer table

---

hoprd/rest-api/Cargo.toml
hoprd/rest-api/src/session.rs

fix(api): update schema value types for max_surb_upstream and response buffer

---

Cargo.lock
db/sql/Cargo.toml
db/sql/src/tickets.rs
tests/test_win_prob.py

The rejected metric was considering each rejected ticket as a possibly winning ticket. This made the metric grow to a massive number now that the ticket value is 10wxHOPR.
This PR account each rejected ticket as a ticket worth the ticket price, not value.
This should be further improved in 4.0 with https://github.com/hoprnet/hoprnet/issues/7520

fix: rejected ticket metric

---

Cargo.lock
hopr/chain-config/Cargo.toml
hopr/chain-config/src/lib.rs

This is needed for `blokli` since it follows a new version base.

feat(chain-config): Add non-version-checked constructor

---

Cargo.lock
Cargo.toml
chain/indexer/Cargo.toml
chain/indexer/src/snapshot/download.rs
common/primitive-types/Cargo.toml
common/primitive-types/src/traits.rs
flake.lock
rust-toolchain.toml

This pull request updates several dependencies and refines code for improved clarity and maintainability across the project. The main changes include bumping versions for Rust toolchain and multiple libraries, as well as replacing manual modulus checks with the more idiomatic `.is_multiple_of()` method for better readability.
**Dependency version upgrades:**
* Updated the Rust toolchain channel from `1.89` to `1.90` in `rust-toolchain.toml` to use the latest stable compiler features.
* Bumped versions for several dependencies in `Cargo.toml`, including `alloy` (`1.0.32` → `1.0.35`), `anyhow` (`1.0.99` → `1.0.100`), `clap` (`4.5.47` → `4.5.48`), `primitive-types` (`0.13.1` → `0.14.0`), `serde_bytes` (`0.11.18` → `0.11.19`), and `serde_with` (`3.14.0` → `3.14.1`). …

chore(deps): update Rust, crate dependencies and the flake.lock

---

Cargo.lock
chain/indexer/src/handlers.rs
db/sql/Cargo.toml
db/sql/src/registry.rs

This pull request updates the logic for checking network registry entries by adding a feature flag based on the `chain_info` table. Now, registry checks are only enforced if the registry is enabled in the database.
**Feature flag for registry checks:**
* Added a check for `network_registry_enabled` in the `chain_info` table using the `SINGULAR_TABLE_FIXED_ID` constant to determine if registry checks should be performed (`db/sql/src/registry.rs`). [[1]](diffhunk://#diff-307b47d05b1001c0e493e30b6552516316d42a9db14fde34a9dcd3308b5a30b7L2-R8) [[2]](diffhunk://#diff-307b47d05b1001c0e493e30b6552516316d42a9db14fde34a9dcd3308b5a30b7R86-R102)
* If the registry is not enabled, the check always returns `true`, effectively bypassing the network registry validation (`db/sql/src/registry.rs`).
Fixes …

fix(hopr-lib): consider network registry enabled state

---

Cargo.lock
Cargo.toml
chain/api/Cargo.toml
chain/api/build.rs
chain/api/src/config.rs
chain/api/src/lib.rs
db/entity/build.rs
db/entity/src/codegen/mod.rs
hopr/hopr-lib/Cargo.toml
hopr/hopr-lib/src/lib.rs
hoprd/hoprd/Cargo.toml
hoprd/hoprd/src/main.rs
transport/api/Cargo.toml
transport/api/src/lib.rs
transport/api/src/socket.rs

This pull request introduces several dependency updates and a significant refactor of the HOPR socket interface to improve modularity and flexibility in the transport layer. The main focus is on decoupling the socket implementation from the core library and moving it into the transport layer, making it more generic and adaptable for different use cases.
**Key changes:**
* Moved the `HoprSocket` struct from `hopr-lib` to a new module `transport/api/src/socket.rs`, and refactored it to be generic over any `Stream` and `Sink` types for improved flexibility.
* Bumped the version of `hopr-transport` to `0.14.0` and downgraded `hopr-lib` to version `3.1.0`.

chore(hopr-lib): adapt interfaces for more ergonomy in edgli and external usage

---

Cargo.lock
chain/indexer/src/handlers.rs
db/sql/Cargo.toml
db/sql/src/registry.rs

This pull request consists of dependency updates, metrics schema changes, and improvements to registry logic and UDP metrics handling. The most significant changes include updating multiple Rust dependencies, refactoring UDP packet length metrics to simplify their structure, and enhancing the database registry logic to respect a global enable/disable flag. Additionally, several metrics definitions were clarified or renamed for better consistency, and minor improvements were made to progress reporting and hex parsing.
**Dependency Updates:**
* Updated several Rust dependencies in `Cargo.toml` files across the workspace, including `alloy`, `anyhow`, `async-compression`, `clap`, `moka`, `primitive-types`, `regex`, `serde`, `serde_bytes`, `serde_with`, and `tempfile`, to their latest patch …

fix(hopr-lib): backport network registry changes
