.github/ISSUE_TEMPLATE/feature-request.md

Add feature request template 

---

packages/hoprd/README.md
packages/hoprd/src/index.ts

allow: `yarn run:hoprd -- --run="myAddress"` for example

Hoprd single command

---

packages/chat/commands/abstractCommand.ts
packages/chat/commands/sendMessage.ts
packages/chat/commands/settings/routing.ts
packages/chat/commands/tickets.ts
packages/core/src/index.ts

Fixes #249 , fixes #224 , fixes #235 , fixes #251

🐛 various bugfixes

---

packages/chat/commands/abstractCommand.ts
packages/chat/commands/index.ts
packages/chat/commands/sendMessage.ts
packages/chat/commands/settings/routing.ts
packages/chat/yarn.lock
packages/chatbot/yarn.lock
packages/core-ethereum/yarn.lock
packages/core/yarn.lock
packages/ethereum/yarn.lock
packages/hoprd/yarn.lock
packages/server/yarn.lock
packages/testing/yarn.lock

Fixes #372, fixes #340, fixes #253

various fixes and improvements to chat

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/custom-template.md
.github/ISSUE_TEMPLATE/feature-request.md
ISSUES.md

introduce 'needs review' label

---

.github/workflows/deploy.yaml
.github/workflows/lint.yaml
lerna.json
packages/core/src/network/crawler.spec.ts
packages/hoprd/Dockerfile

Github Actions

---

packages/hoprd/package.json

make hopr-admin part of the distribution

---

README.md

Pointing users where our docker images live

---

packages/core/src/constants.ts
packages/core/src/index.ts
packages/hoprd/src/admin.ts

Crawl periodically in core

---

packages/core-ethereum/src/channel/index.ts

comment out counterparty funding

---

.github/workflows/smoke.yaml
packages/hoprd/src/admin.ts
packages/hoprd/src/index.ts
packages/hoprd/tsconfig.json
packages/utils/src/bootstrap.ts
test/build/ubuntu-20.04/Dockerfile
test/smoke.sh

- Add alias for bootstrap, fixes #598 
- Clearer hoprd options
- Merge back from release/zurich
- Fix docker build

Various changes / fixes

---

packages/chat/commands/sendMessage.ts
packages/chat/commands/settings/routing.ts
packages/core/src/index.ts

stop mutating intermediate path

---

README.md
packages/ethereum/.env.example
packages/ethereum/README.md
packages/ethereum/chain/addresses.json

migrate smart contracts for release/Zug

---

packages/core-ethereum/src/channel/index.ts

do not fund the channel twice

---

packages/core/src/channel-strategy.ts
packages/core/src/path/index.ts

Use BN weights

---

packages/chat/commands/closeChannel.ts
packages/chat/commands/listOpenChannels.ts
packages/chat/commands/openChannel.ts
packages/chat/commands/sendMessage.ts

Fixes #398, fixes #723, fixes #728

various chat fixes

---

packages/core/src/index.ts

fix database path

---

packages/avado/dappnode_package.json

remove geth from avado re #658

---

packages/core-ethereum/src/hashedSecret.spec.ts
packages/core-ethereum/src/index.ts
packages/core-ethereum/src/utils/index.ts
packages/ethereum/chain/addresses.json
packages/ethereum/hardhat.config.ts
packages/ethereum/tasks/migrate.ts
packages/ethereum/utils/networks.ts

add binance support & addresses

---

packages/chat/commands/printBalance.ts
packages/core-connector-interface/src/index.d.ts
packages/core-connector-interface/src/types/balance.d.ts
packages/core-connector-interface/src/types/nativeBalance.d.ts
packages/core-ethereum/src/account.ts
packages/core-ethereum/src/channel/index.spec.ts
packages/core-ethereum/src/channel/index.ts
packages/core-ethereum/src/channel/ticket.ts
packages/core-ethereum/src/hashedSecret.spec.ts
packages/core-ethereum/src/hashedSecret.ts
packages/core-ethereum/src/index.ts
packages/core-ethereum/src/indexer/index.spec.ts
packages/core-ethereum/src/types/balance.ts
packages/core-ethereum/src/types/nativeBalance.ts
packages/core/src/constants.ts
packages/core/src/index.ts
packages/core/src/messages/packet/index.spec.ts
packages/hoprd/src/admin.ts

Fixes #645 
Fixes #591 
Fixes #205

Run without funds

---

packages/chat/commands/commands.spec.ts
packages/chat/commands/listConnected.ts
packages/chat/commands/sendMessage.ts
packages/chat/commands/version.ts
packages/core/src/constants.ts
packages/core/src/index.ts
packages/core/src/network/heartbeat.spec.ts
packages/core/src/network/heartbeat.ts
packages/core/src/network/network-peers.ts
packages/core/src/path/index.spec.ts
packages/core/src/path/index.ts
packages/hoprd/src/admin.ts
packages/hoprd/src/index.ts

Fixes #798 
Fixes #790 
Fixes #791
Fixes #770
Fixes #425

Various fixes.

---

WORKFLOW.md

Update WORKFLOW.md to be more descriptive 

---

WORKFLOW.md

Adding PRs update instruction for changelog

---

packages/hoprd/src/index.ts

Cherry pick API changes from #835

---

packages/core-ethereum/src/utils/index.ts

log send transactions

---

packages/core-ethereum/src/indexer/index.ts
packages/core/src/channel-strategy.ts
packages/core/src/index.ts
yarn.lock

Fix Auto-open issue

---

packages/ethereum/contracts/ERC777/ERC777Snapshot.sol

minize changes from the original ERC20Snapshot

---

packages/ethereum/test/openzeppelin-contracts/ERC777/ERC777Snapshot.test.js

test send method

---

.yarnclean
packages/ethereum/.solcover.js
packages/ethereum/AUDIT.md
packages/ethereum/contracts/HoprDistributor.sol
packages/ethereum/hardhat.config.ts
packages/ethereum/package.json
packages/ethereum/test/HoprDistributor.test.ts
tsconfig.json
yarn.lock

Add HoprDistributor

---

.github/workflows/deploy.yaml

Re-pull to get latest version

---

packages/core-ethereum/.gitignore
packages/core-ethereum/src/account.ts
packages/core-ethereum/src/hashedSecret.ts
packages/core/src/index.ts
packages/core/src/interactions/packet/acknowledgement.ts
packages/core/src/messages/packet/index.spec.ts
packages/core/src/messages/packet/index.ts
packages/core/src/messages/ticket/index.spec.ts

fix ticket unredeemable & better debug info

---

packages/core-ethereum/src/indexer/index.ts
scripts/deploy.sh

Increasing testnet size for NYC

---

packages/core-ethereum/src/account.ts
packages/core-ethereum/src/constants.ts
packages/core-ethereum/src/nonce-tracker.spec.ts
packages/core-ethereum/src/nonce-tracker.ts
packages/core-ethereum/src/transaction-manager.spec.ts
packages/core-ethereum/src/transaction-manager.ts
packages/core-ethereum/src/utils/index.ts

replace long-time pending transactions

---

packages/hoprd/Dockerfile
packages/hoprd/package.json

Already solved in #1019, but included @lirantal comments.
Closes #977

docs: Fixes #977, updates information about docker image

---

docs/hopr-documentation-sphinx/core-concepts/bootstrap-nodes.md
docs/hopr-documentation-sphinx/core-concepts/commands.md
docs/hopr-documentation-sphinx/core-concepts/cover-traffic.md
docs/hopr-documentation-sphinx/core-concepts/overview.md
docs/hopr-documentation-sphinx/core-concepts/payment-channels.md
docs/hopr-documentation-sphinx/core-concepts/proof-of-relay.md
docs/hopr-documentation-sphinx/core-concepts/protocol-network-token.md
docs/hopr-documentation-sphinx/core-concepts/tickets.md
docs/hopr-documentation-sphinx/core-concepts/tokens/README.md
docs/hopr-documentation-sphinx/core-concepts/tokens/hopr-tokens.md
docs/hopr-documentation-sphinx/core-concepts/tokens/native-tokens.md
docs/hopr-documentation-sphinx/index.md
docs/hopr-documentation-sphinx/src/install-hoprd/start-here.md
docs/hopr-documentation-sphinx/src/install-hoprd/using-avado.md
docs/hopr-documentation-sphinx/src/install-hoprd/using-script.md

Titlis documentation

---

packages/core-ethereum/src/account.ts
packages/core-ethereum/src/nonce-tracker.ts

add more debug logs

---

packages/hoprd/hoprd-default.sh
packages/hoprd/package.json

Default hoprd sh

---

packages/core/package.json
yarn.lock

Upgrade transport

---

packages/core-ethereum/src/types/signedTicket.spec.ts
packages/core-ethereum/src/utils/index.spec.ts
packages/core/src/messages/acknowledgement/index.spec.ts
packages/core/src/messages/packet/challenge.spec.ts
packages/utils/src/randomInteger.ts
yarn.lock

fixes the description of randomInteger in utils

fix randomInteger description

---

packages/core/package.json
packages/core/src/index.ts
yarn.lock

Contains latest enhancements that we learned from Emmenbrücke

Hopr connect 0.2.10

---

packages/core/src/index.ts
packages/core/src/interactions/network/heartbeat.spec.ts
packages/core/src/interactions/network/heartbeat.ts
packages/core/src/network/heartbeat.spec.ts
packages/core/src/network/heartbeat.ts
packages/hoprd/src/commands/ping.ts

Heartbeat returns number >= 0 if ping was successful. And -1 otherwise.

heartbeat returns number

---

packages/ethereum/contracts/ERC777/ERC777Snapshot.sol

audit report 2

---

docs/hopr-documentation/old_docs/community/saentis-testnet/funding-your-node.md
docs/hopr-documentation/old_docs/core-concepts/tokens/README.md
docs/hopr-documentation/old_docs/core-concepts/tokens/native-tokens.md
docs/hopr-documentation/old_docs/getting-started/funding-your-node.md
docs/hopr-documentation/old_docs/getting-started/hoprd/funding-account.md
docs/hopr-documentation/old_docs/getting-started/quickstart/windows-quickstart.md
docs/hopr-documentation/old_docs/getting-started/saentis-testnet/funding-your-node.md
docs/hopr-documentation/old_docs/hopr-avado-node-tutorial/withdrawing-funds.md
docs/hopr-documentation/src/running-hoprd/funding/hopr-tokens.md
docs/hopr-documentation/src/running-hoprd/funding/native-tokens.md
docs/hopr-documentation/src/running-hoprd/index.md
packages/core-ethereum/src/account.ts
packages/core-ethereum/src/indexer/index.ts
packages/core-ethereum/src/types/nativeBalance.ts
packages/core-ethereum/src/utils/index.ts
packages/ethereum/chain/addresses.json
packages/ethereum/utils/networks.ts
packages/hoprd/hopr-admin/connection.js
packages/hoprd/src/admin.ts
packages/hoprd/src/index.ts

deploy and use goerli testnet

---

packages/ethereum/contracts/HoprDistributor.sol
packages/ethereum/test/HoprDistributor.test.ts

Small check to ensure we don't screw up with `totalToBeMinted`

disallow double revoke

---

packages/utils/package.json
packages/utils/src/bootstrap.ts
scripts/environments.sh
scripts/testnet.sh
scripts/utils.sh

To avoid missing testing versions on master. Closes #1238

Using only x.y.z for DNS

---

packages/ethereum/package.json
yarn.lock

HoprToken flattened https://gist.github.com/nionis/dbb629b966b69c091f059444031afd98

fix OZ to 3.0.1

---

.github/workflows/smoke.yaml

Using it as a secret from now on

Replacing ropsten wss provider

---

packages/ethereum/contracts/HoprWrapper.sol
packages/ethereum/contracts/testing/PermittableToken.sol
packages/ethereum/hardhat.config.ts
packages/ethereum/test/HoprWrapper.test.ts

HoprWrapper

---

docs/hopr-documentation/src/install-hoprd/using-script.md

Revert "Update using-script.md"

---

packages/core/src/messages/packet/header/createHeader.ts
packages/core/src/messages/packet/header/index.spec.ts
packages/core/src/messages/packet/header/index.ts
packages/core/src/messages/packet/index.ts

- Remove generic types from header, instead only provide hash function

Header Refactor.

---

packages/core-connector-interface/src/types/index.d.ts
packages/core-ethereum/src/channel/index.ts
packages/core-ethereum/src/indexer/index.spec.ts
packages/core-ethereum/src/indexer/index.ts
packages/core-ethereum/src/indexer/reducers.fixtures.spec.ts
packages/core-ethereum/src/indexer/reducers.ts
packages/core-ethereum/src/types/channelEntry.spec.ts
packages/core-ethereum/src/types/channelEntry.ts
packages/hoprd/src/commands/listOpenChannels.ts

- store `partyA` and `partyB` instread of `parties`
- add `getChannelId`

flatten channelEntry

---

packages/ethereum/package.json
packages/ethereum/tasks/faucet.ts
packages/ethereum/tasks/utils/contracts.ts
yarn.lock

removes duplicated code

---

packages/core-ethereum/src/indexer/index.ts

Fixed by https://github.com/ethers-io/ethers.js/issues/1458#issuecomment-822120573

remove hack

---

docs/hopr-documentation/README.md
docs/hopr-documentation/index.md
docs/hopr-documentation/src/install-hoprd/index.md
docs/hopr-documentation/src/install-hoprd/using-script.md
docs/hopr-documentation/src/quickstart/index.md

Improvements on documentation

---

packages/core/src/index.ts
packages/core/src/interactions/packet/forward.ts

Make libp2p private

---

DISCUSSIONS.md

Removing discussion tickets

---

DISCUSSIONS.md

Further discussions

---

DISCUSSIONS.md

Deprioritized EIP-712 by moving to our DISCUSSIONS.md

---

packages/hoprd/src/admin.ts

Adding testing instructions w/o removing disclaimer

---

packages/hoprd/hopr-admin/connection.js

Fixes #1558. Apparently, my initial hack (see 90f0886) only works for localhost, but not for actual invalid SSL certs.

Solves AVADO SSL error

---

WORKFLOW.md

- Diagrams to show the direction of merges
- Diagrams to show the bumping of `package.json`
- Simplification of content in general
- Removing outdated info about BS + DNS
- Clarified and enhanced principles and rules
- Enhance explanation about workflow in general

Clarified our development workflow

---

README.md

…t not be supported by a team member in the future

Disclaimer about specific tech

---

.github/workflows/deploy.yaml
scripts/deploy.sh
scripts/dns.sh
scripts/environments.sh
scripts/gcloud.sh
scripts/internal.sh
scripts/nightly.sh
scripts/qa.sh
scripts/testnet.sh
scripts/utils.sh

I had to revert some more changes in the shell scripts which were preventing proper sourcing. I also added the ability to debug the deployment by using the branch prefix `debug-deploy/` which makes working on such an issue easier.

Fix Github workflow action: deployment 

---

DISCUSSIONS.md

Move 'future' tickets to discussions.md

---

.github/workflows/deploy.yaml

Fixes the build issue as can be seen at https://github.com/hoprnet/hoprnet/runs/2566393933?check_suite_focus=true
Refs #1637

Fix invocation of release build in Github workflow

---

scripts/gcloud.sh

Also make image familty sticky to cos-stable

Enable monitoring for GCP compute instances

---

packages/core/src/index.ts
packages/core/src/interactions/packet/forward.ts
packages/utils/src/libp2p/index.ts

Fix bug in utils that prevented HOPR from sending messages

Fix sendMessage

---

packages/core/src/index.ts
packages/core/src/interactions/packet/acknowledgement.ts
packages/core/src/interactions/packet/forward.ts
packages/core/src/messages/packet.ts
packages/utils/package.json
packages/utils/src/libp2p/index.spec.ts
packages/utils/src/libp2p/index.ts

Fixes multiple errors that prevented 0-hop messages from being properly acknowledged
Adds a proper unit test for libp2p helper functions that simulates stream behavior in libp2p

Fix 0-hop acknowledgement & improve testing

---

packages/core/src/index.ts
packages/hoprd/src/commands/abstractCommand.ts
packages/hoprd/src/commands/alias.ts
packages/hoprd/src/commands/commands.spec.ts
packages/hoprd/src/commands/index.ts
packages/hoprd/src/commands/ping.ts
packages/hoprd/src/commands/sendMessage.ts
packages/hoprd/src/commands/withdraw.ts

remove outdated autocomplete code

---

packages/hoprd/src/commands/withdraw.ts

withdraw command does not recognise currency (native / HOPR) no matter what

fix withdraw command

---

.github/workflows/deploy.yaml
.github/workflows/docs.yaml
.github/workflows/e2e.yaml
.gitignore
README.md
scripts/configure-git-info.sh
scripts/gcloud.sh
scripts/publish-patch-release.sh
scripts/publish-pre-release.sh
scripts/run-integration-tests-locally.sh
scripts/run-integration-tests.sh
scripts/testnet.sh
test/integration-test.sh

Made scripts usable on systems without `/bin/bash`.

Improved variable handling and logging

---

packages/ethereum/contracts/HoprChannels.sol
packages/ethereum/test/HoprChannels.spec.ts

Fixes a a typo in bumpChannel and update tests to test for correct behavior

fix bumpChannel

---

scripts/cleanup.sh
scripts/deploy.sh
scripts/testnet.sh

Fixes an issue seen on `master`:
https://github.com/hoprnet/hoprnet/runs/2662486686?check_suite_focus=true

Add missing variable defaults in scripts

---

packages/ethereum/package.json
scripts/cleanup.sh

Fix CI errors while generating docs and cleaning gcloud resources

---

.github/workflows/deploy.yaml
package.json
scripts/dependencies.sh
scripts/deploy.sh
scripts/environments.sh
scripts/internal.sh
scripts/nightly.sh
scripts/testnet.sh
yarn.lock

Fixes the issue on `master`: https://github.com/hoprnet/hoprnet/runs/2682548186?check_suite_focus=true
Also removed the `bash -x` uses as previously agreed and `git pull` which is a side-effect when run in a Github Action workflow which should not be used.

Fix testnet deployment in Github Actions workflow

---

packages/ethereum/tsconfig.json

typedoc exclude declaration files

---

MIGRATION.md

Upgrade docs

---

packages/hoprd/package.json
packages/utils/package.json
yarn.lock

downgrade strip-ansi

---

MIGRATION.md
lerna.json
packages/core-ethereum/package.json
packages/core-ethereum/src/ethereum.ts
packages/core/package.json
packages/core/tsconfig.json
packages/ethereum/contracts/HoprChannels.sol
packages/ethereum/contracts/mocks/ChannelsMock.sol
packages/ethereum/deployments/goerli/HoprChannels.json
packages/ethereum/deployments/xdai/HoprChannels.json
packages/ethereum/index.ts
packages/ethereum/package.json
packages/ethereum/test/HoprChannels.spec.ts
packages/ethereum/tsconfig.json
packages/hoprd/package.json
packages/utils/package.json
packages/utils/src/types/challenge.ts
packages/utils/src/types/primitives.spec.ts
packages/utils/src/types/primitives.ts
packages/utils/src/types/solidity.ts
packages/utils/src/types/ticket.spec.ts
packages/utils/src/types/ticket.ts
yarn.lock

Patches https://github.com/hoprnet/hoprnet/pull/1721

turn off noImplicitAny

---

packages/ethereum/contracts/HoprChannels.sol
packages/ethereum/test/HoprChannels.spec.ts

remove ticketEpoch bump from redeemTicket()

do not bump ticket epoch on ticket redemption

---

packages/core-ethereum/src/channel.ts
packages/core/src/interactions/packet/acknowledgement.ts

limit concurrency in Channel.acknowledge()

---

packages/hoprd/src/commands/listOpenChannels.ts
packages/hoprd/src/commands/openChannel.ts

UI changes

---

packages/core/src/messages/acknowledgement.ts
packages/core/src/messages/acknowledgementChallenge.ts
packages/core/src/messages/packet.ts
packages/hoprd/src/commands/sendMessage.ts
packages/utils/src/types/halfKeyChallenge.ts

fix challenge signature & UI fix for sendMessage

---

.github/workflows/deploy.yaml
packages/ethereum/deployments/localhost/HoprChannels.json
packages/ethereum/package.json
scripts/deploy-smart-contracts.sh

This is required after the changes to HoprChannels in
dcd06a32959fd15652c6f6f131ad31bba43a467b

Re-generate contract address for localhost hardhat network

---

packages/core-ethereum/src/index.ts
packages/core-ethereum/src/indexer/index.ts
packages/core/src/index.ts
packages/core/src/path/index.spec.ts
packages/core/src/path/index.ts

get only open routing channels

---

packages/core-ethereum/src/indexer/fixtures.ts
packages/core-ethereum/src/indexer/index.spec.ts
packages/core-ethereum/src/indexer/index.ts

fix and improve indexer tests

---

packages/utils/src/types/channelEntry.spec.ts
packages/utils/src/types/channelEntry.ts

Fix indexer swapping state

---

packages/core-ethereum/src/channel.spec.ts

add challenge tests

---

scripts/deploy-smart-contracts.sh
scripts/publish-pre-release.sh
scripts/regenerate-typedocs.sh
scripts/run-integration-tests-npm.sh
scripts/run-integration-tests-source.sh
scripts/wait-for-npm-package.sh

readlink works differently on Linux and macOS

Replace use of readlink for portability

---

packages/core-ethereum/src/channel.ts
packages/core/src/channel-strategy.ts
packages/core/src/index.ts

Only for non-passive strategies.
Fixes #1013

Auto redeem tickets on channel closure

---

.gitpod.dockerfile

Fixes #1832 as per recommended in the latest [Gcloud SDK install instructions](https://cloud.google.com/sdk/docs/install)

Added gcloud to our Gitpod container for internal testing our infra

---

lerna.json
package.json
packages/avado/dappnode_package.json
packages/avado/releases.json
packages/core-ethereum/docs/classes/channel.md
packages/core-ethereum/package.json
packages/core-ethereum/src/channel.ts
packages/core/docs/classes/default.md
packages/core/package.json
packages/core/src/channel-strategy.ts
packages/core/src/index.ts
packages/ethereum/package.json
packages/hoprd/package.json
packages/hoprd/src/index.ts
packages/utils/package.json
scripts/deploy-smart-contracts.sh
scripts/publish-pre-release.sh
scripts/regenerate-typedocs.sh
scripts/run-integration-tests-npm.sh
scripts/run-integration-tests-source.sh
scripts/wait-for-npm-package.sh

fixed Commands#execute call 

---

.github/workflows/npm-e2e.yaml
lerna.json
packages/core-ethereum/package.json
packages/core/package.json
packages/ethereum/package.json
packages/hoprd/package.json
packages/utils/docs/modules.md
packages/utils/package.json
packages/utils/src/libp2p/index.ts
scripts/environments.sh
yarn.lock

Define release kiautschou as v1.72.0 in environments

---

packages/core/src/index.ts
packages/hoprd/src/commands/redeemTickets.ts

Correctly show redeemed HOPR tokens

---

.github/workflows/deploy.yaml
packages/avado/dappnode_package.json
packages/avado/releases.json
packages/core/src/index.ts
packages/hoprd/src/commands/redeemTickets.ts
packages/hoprd/src/index.ts
scripts/testnet.sh

Also include recent fixes from master branch.

Fix auto-funding and node identity retainment

---

scripts/internal.sh

by adding a simple patch to an internal script.

Retriggering build

---

packages/hoprd/src/index.ts

quickfixed --run logging error

---

README.md
scripts/gcloud.sh
scripts/internal.sh
scripts/testnet.sh

- Adding sample Docker running commands

Ensure we can redeploy via internal.sh to pick un bugs our e2e are not picking up

---

packages/core/src/index.ts

Fixes #1817 
Changes:
- store peerId in libp2p KeyBook
- store multiaddrs if they are dialable in AddressBook
Rationale:
Libp2p uses an internal addressBook which is a registry of known addresses. These addresses are used to dial other peers once it is requested by the API.
The dialable addresses are specified by the utilized transport modules, in our case HoprConnect. The worklfow is like this:
- libp2p.dial(peerId)
- check internal addressBook, if not empty
- run TransportModules.filter to get all dialable address, if empty throw Error, otherwise
- dial address
The problem when using addresses such as `/p2p/<HoprId>` is that we cannot dial these addresses because they do not contain any necessary information, hence the AddressBook will contain lots of unusable addresses such that libp2p …

do not store p2p address in addressBook

---

packages/core/src/index.ts

Changes:
- enable libp2p's autoDial functionality
- overwrite libp2p's addressSorter

Improve connectivity

---

packages/hoprd/hopr-admin/connection.js
packages/hoprd/hopr-admin/pages/index.js
packages/hoprd/package.json
packages/hoprd/src/commands/closeChannel.ts
packages/hoprd/src/commands/fundChannel.ts
packages/hoprd/src/commands/openChannel.ts
packages/hoprd/src/commands/redeemTickets.ts
packages/hoprd/src/index.ts
packages/hoprd/src/logs.ts

improve user experience
- log more things into admin panel
- disable command input until node is ready

more verbose panel

---

DISCUSSIONS.md
packages/ethereum/contracts/HoprChannels.sol
packages/ethereum/test/HoprChannels.spec.ts

SC changes

---

.gitignore
scripts/install-websocat.sh
scripts/run-integration-tests-npm.sh
scripts/run-integration-tests-source.sh
test/security-test.sh

This unblocks the execution of e2e tests in the CI.

Enable websocat installation on macOS as well

---

README.md

Update docker commands in README

---

README.md
docs/hopr-documentation/index.md
docs/hopr-documentation/src/install-hoprd/using-docker.md
docs/hopr-documentation/src/install-hoprd/using-npm.md
docs/hopr-documentation/src/install-hoprd/using-script.md
docs/hopr-documentation/src/running-hoprd/commands.md
docs/hopr-documentation/src/running-hoprd/flags.md
docs/hopr-documentation/src/running-hoprd/index.md

update docs for Paphos

---

README.md

Provides context about our unit tests in our README

---

README.md
package.json

Further docs on testing for particular packages

---

.github/workflows/deploy.yaml
scripts/deploy.sh

Ensure release branches use xdai when deploying nodes

---

.vscode/launch.json
.vscode/settings.json
README.md
package.json
packages/hoprd/src/identity.spec.ts
packages/hoprd/src/identity.ts
packages/hoprd/src/index.ts

Allowing the option of passing private key

---

packages/hoprd/Dockerfile
packages/hoprd/cloudbuild.yaml

Use build arg instead of env var for hoprd version in Docker image build

---

.github/workflows/deploy.yaml
README.md
docs/hopr-documentation/src/install-hoprd/using-docker.md
packages/avado/Dockerfile
scripts/run-integration-tests-npm.sh
scripts/run-integration-tests-source.sh
test/integration-test.sh

Fixes #2023 
Also add check for inclusion of the correct npm package version in the Docker image being built.

Change Docker tag latest-release to latest-SOMERELEASENAME

---

packages/ethereum/contracts/HoprChannels.sol

In preparation for https://github.com/hoprnet/hoprnet/issues/2007

various HoprChannels cleanup 1

---

packages/core/package.json
yarn.lock

Update hopr-connect to v0.2.30

---

README.md
packages/hoprd/src/identity.spec.ts
packages/hoprd/src/identity.ts

Added instruction on workflow for testing

---

.github/workflows/deploy.yaml
.github/workflows/e2e.yaml
.github/workflows/nightly.yaml
.github/workflows/npm-e2e.yaml
packages/avado/dappnode_package.json
packages/avado/releases.json
scripts/deploy.sh
scripts/gcloud.sh
scripts/internal.sh
scripts/nightly.sh
scripts/run-integration-tests-npm.sh
scripts/run-integration-tests-source.sh
scripts/testnet.sh

Replace pokt with infura

---

.vscode/launch.json
README.md
package.json
packages/ethereum/test/HoprChannels.spec.ts

Added mocking channel functions for proper event emitting testing

---

packages/ethereum/contracts/HoprChannels.sol

re #2007
- Fixes #2079
- Fixes #2029
- Fixes #2034
----
Blocked by topology testing

various improvements

---

packages/hoprd/src/admin.ts
scripts/run-integration-tests-npm.sh
scripts/run-integration-tests-source.sh
test/security-test.sh

To test add `--admin --testNoAuthentication` to command line and try to open admin panel. There should be no auth request.

fixed testNoAuthentication in admin panel

---

packages/ethereum/deployments/localhost/HoprChannels.json
packages/hoprd/hopr-admin/connection.js
packages/hoprd/hopr-admin/pages/index.js
packages/hoprd/src/admin.ts
packages/hoprd/src/commands/listOpenChannels.ts
packages/hoprd/src/index.ts
packages/hoprd/src/logs.ts

various ux improvements

---

packages/core/src/index.ts

Exclude self from interesting nodes

---

packages/core-ethereum/package.json
packages/core/package.json
packages/ethereum/package.json
packages/utils/package.json

support v14 and v16

---

packages/core-ethereum/src/channel.ts
packages/core-ethereum/src/index.ts
packages/core-ethereum/src/indexer/index.spec.ts
packages/core-ethereum/src/indexer/index.ts
packages/core/src/channel-strategy.ts
packages/core/src/index.ts
packages/core/src/path/index.spec.ts
packages/core/src/path/index.ts
packages/hoprd/src/commands/commands.spec.ts
packages/hoprd/src/commands/settings.ts
packages/hoprd/src/index.ts
packages/utils/src/db.ts
packages/utils/src/types/primitives.ts

We won't merge cover traffic for a while, but let's get some of the core changes into master to mimimise the diff, and future conflicts.

Cherry pick core changes from Cover traffic

---

DISCUSSIONS.md

Add relay incentives to discussion

---

test/integration-test.sh

restore path finding E2E test

---

packages/ethereum/contracts/HoprChannels.sol

add Multicall to HoprChannels

---

packages/ethereum/contracts/HoprChannels.sol

remove SafeMath from HoprChannels

---

packages/avado/Dockerfile
yarn.lock

Fix:
- use wrong release in Docker file

Fix release

---

WORKFLOW.md

Update release workflow to change dockerfile

---

package.json

Add Göerli scripts

---

package.json
packages/utils/src/libp2p/index.ts
packages/utils/src/libp2p/verifySignatureFromPeerId.spec.ts
packages/utils/src/libp2p/verifySignatureFromPeerId.ts

Adding verification method for signatures

---

README.md
WORKFLOW.md
docs/hopr-documentation/src/install-hoprd/using-docker.md

The additional documentation also covers starting clusters on GCP.
Relates to #1865 and #1960

Improve documentation on testing

---

.envrc
.github/workflows/latexcompile.yml
docs/yellowpaper/sections/05-HOPR-incentivization-mechanism/01-probabilistic-payments.tex
docs/yellowpaper/sections/05-HOPR-incentivization-mechanism/02-on-chain-commitment.tex
docs/yellowpaper/sections/05-HOPR-incentivization-mechanism/03-proof-of-relay.tex
docs/yellowpaper/sections/05-HOPR-incentivization-mechanism/index.tex
docs/yellowpaper/sections/06-tickets/index.tex
shell.nix

Also add some minor tool- chain improvements.

Improving section on incentives in the yellowpaper

---

packages/hoprd/hopr-admin/pages/index.js

This PR tries to fix the problem when a funded and started node didn't present the command input field in the HOPR Admin interface.

removed disabled property on input

---

.github/workflows/deploy.yaml

This PR fixed a problem: deploy workflow was not always deploying the latest code version.

added git pull before deploy script

---

packages/utils/package.json

Tests are broken, follow-up on #2275

Restoring support for node v14 on utils

---

packages/utils/src/u8a/equals.ts

Removed operator only available on v16

---

packages/avado/Dockerfile
packages/avado/dappnode_package.json
packages/hoprd/src/index.ts
packages/utils/src/types/primitives.ts

Updating provider and symbol

---

packages/hoprd/src/index.ts
scripts/environments.sh

Includes node address in startup

---

.github/workflows/deploy.yaml
packages/ethereum/hardhat.config.ts

This is as hot as a hotfix can be described, so here's a small post-mortem on the reasoning on this since this will trigger a bunch of things.
24th August 2021 17:40 CEST - @jjperezaguinaga mentioned an issue in our internal #tech channel.
24th August 2021 17:42 CEST - @SCBuergel replied to the issue in said #tech channel
24th August 2021 17:46 CEST - @SCBuergel identifies the smart contract isn't verified
24th August 2021 18:25 CEST - @SCBuergel follows-up about the contract being verified
24th August 2021 19:00~20:00 CEST - @jjperezaguinaga proceeds to try and verify the contract, while working in other topics. Last communication from @jjperezaguinaga is around 20:01 CEST, regarding the Dashboard for testnet. @jjperezaguinaga continues to verify the contract w/o success, proceeds to …

Redeployment of smart contract for MATIC testnet

---

packages/core-ethereum/src/ethereum.ts

Fixes https://github.com/hoprnet/hoprnet/issues/2337

pass chain id to send tx

---

.github/workflows/deploy.yaml
.yarnrc.yml
packages/avado/dappnode_package.json
packages/avado/releases.json
packages/core-ethereum/package.json
packages/core/package.json
packages/cover-traffic/package.json
packages/ethereum/deployments/default/goerli/HoprChannels.json
packages/ethereum/deployments/default/xdai/HoprChannels.json
packages/ethereum/package.json
packages/hoprd/package.json
packages/utils/package.json
scripts/get-npm-package-info.sh
scripts/get-package-version.sh
scripts/publish-version.sh
scripts/wait-for-npm-package.sh

Previously the scripts would be error-prone due to their implicit use of environment variables.

Fix package helper scripts to be more stable

---

packages/core-ethereum/src/indexer/fixtures.ts
packages/core-ethereum/src/indexer/index.spec.ts
packages/core-ethereum/src/indexer/index.ts
packages/ethereum/contracts/HoprChannels.sol
packages/ethereum/test/HoprChannels.spec.ts

Fixes #2397 
- remove `TokensReceived` event
- add `ChannelFunded` event
- rename `ChannelUpdate` event to `ChannelUpdated`
- add `ChannelOpened` event

improve HoprChannels events

---

docs/yellowpaper/sections/02-path-selection/index.tex
docs/yellowpaper/sections/09-cover-traffic/index.tex
packages/core/src/network/network-peers.spec.ts
packages/core/src/network/network-peers.ts
packages/core/src/test-utils.ts

- correct implementation on path selection
- correct importance of stake.
- Move "no-circle check" to default path selection
- Add explanation of "backoff time" 
- Modify criteria of node quality checks (with test cases)

Yp path selection ct

---

packages/cover-traffic/src/constants.ts
packages/cover-traffic/src/state.ts
packages/cover-traffic/src/strategy.ts
packages/cover-traffic/src/utils.ts

Add code comments to cover traffic nodes
Close #2404

Cover traffic code comments

---

packages/cover-traffic/src/constants.ts
packages/cover-traffic/src/index.ts
packages/cover-traffic/src/state.ts
packages/cover-traffic/src/strategy.ts
packages/cover-traffic/src/utils.ts

Handle WAIT_FOR_COMMITMENT stalls in cover traffic

---

packages/core-ethereum/src/channel.ts
packages/core-ethereum/src/ethereum.ts
packages/core-ethereum/src/indexer/index.ts

Commitment fails crash should be non fatal.

---

packages/core-ethereum/src/indexer/index.spec.ts
packages/core-ethereum/src/indexer/index.ts
packages/core/src/interactions/packet/forward.ts
packages/utils/src/db.ts

Fix Ticket Epoch crash

---

packages/ethereum/contracts/HoprWrapperProxy.sol

add HoprWrapperProxy contract for xDAI MS

---

packages/core/src/index.ts

Handle some RPC failures

---

packages/core-ethereum/src/ethereum.ts
packages/core-ethereum/src/transaction-manager.ts

return obj with has when duplicated items are found

---

docs/hopr-documentation/src/running-hoprd/commands.md
packages/cover-traffic-daemon/src/utils.ts
packages/hoprd/src/commands/openChannel.ts

- Fixes `TypeError: Cannot read property 'openFrom' of undefined`

fix undefined openFrom

---

DEVELOPMENT_PROCESSES.md

how to suggest changes in our development processes

add section on how to suggest changes

---

scripts/publish-version.sh

CD versioning

---

packages/core-ethereum/src/channel.ts
packages/core/src/index.ts
packages/hoprd/src/commands/sendMessage.ts

properly handle error when a channel is missing

---

packages/core-ethereum/src/ethereum.ts
packages/core-ethereum/src/indexer/fixtures.ts
packages/core-ethereum/src/indexer/index.spec.ts
packages/core-ethereum/src/indexer/index.ts
packages/core-ethereum/src/indexer/utils.ts
packages/ethereum/deployments/default/localhost/HoprChannels.json
packages/ethereum/deployments/default/localhost/HoprDistributor.json
packages/ethereum/deployments/default/localhost/HoprToken.json

Fixes #2542
Fixes #2550
- increase `gasLimit` to `400e3`
- remove secondary event sorting

various indexer bug fixes & improvements

---

DEPLOYMENT_CHECKLIST.md

Instead of manually tracking deployment tasks (e.g. https://github.com/hoprnet/hopr-devops/issues/35, https://github.com/hoprnet/hoprnet/issues/2526, https://github.com/hoprnet/hopr-devrel/issues/51, https://github.com/hoprnet/hopr-devrel/issues/52, we should have a single entry deployment checklist and ensure the release has someone confirming it has gone through it.
This PR introduces that checklist, which we can use for https://github.com/hoprnet/hopr-devrel/issues/12.

Deployment checklist

---

docs/yellowpaper/references.bib

Fix references

---

packages/hoprd/package.json

Forcing support only on `v16`

---

packages/ethereum/contracts/HoprToken.sol
packages/ethereum/deploy/02_HoprToken.ts
packages/ethereum/hardhat.config.ts
packages/ethereum/test/HoprToken.test.ts
packages/utils/src/types/primitives.spec.ts
packages/utils/src/types/primitives.ts
scripts/run-integration-tests-source.sh
scripts/topologies/full_interconnected_cluster.sh
test/integration-test.sh

use txHOPR

---

packages/ethereum/deploy/02_HoprToken.ts

increase gasLimit on mint

---

packages/core-ethereum/src/constants.ts
packages/core-ethereum/src/indexer/constants.ts
packages/core-ethereum/src/indexer/index.ts

Promises never gets rejected. Maybe related to memory leak?

Add promise rejection

---

.github/workflows/deploy.yaml
.github/workflows/docs.yaml
.github/workflows/e2e-gcloud.yaml
.github/workflows/e2e-npm.yaml
.github/workflows/e2e.yaml
.github/workflows/latexcompile.yml
.github/workflows/test.yaml
.processes/index.md

Do not run test suite (e2e, test, api docs) on .process changes

Improve CI

---

.processes/development.md

When this is merged, the old projects will be archived.
Please vote.

Update processes to use new project boards

---

.processes/development.md

This is a proposal, vote with 👍👎 or 👀 if u are not voting.
Add the ability to re-elect representatives.

Add the ability to re-elect representatives

---

.processes/development.md

- update representatives expiry
- fix type: re-election cycle

Representatives update

---

README.md
package.json
test/security-test.sh

- updated README.md
- added a workaround for issue with hardhat-localhost deployment files (cf. https://github.com/hoprnet/hoprnet/issues/2907)
- fixed labels in security-tests

Update README.md and package.json to reflect latest changes

---

.processes/community.md
.processes/development.md
.processes/index.md

re https://github.com/hoprnet/hoprnet/issues/2632
- Fixes https://github.com/hoprnet/hoprnet/issues/2891

add community process

---

packages/avado/dappnode_package.json
packages/avado/releases.json
packages/core-ethereum/package.json
packages/core/package.json
packages/core/protocol-config-schema.json
packages/core/protocol-config.json
packages/cover-traffic-daemon/package.json
packages/ethereum/deploy/02_HoprToken.ts
packages/ethereum/package.json
packages/hoprd/package.json
packages/utils/package.json

fix receiver account for minted tokens in CI/CD

---

packages/cover-traffic-daemon/README.md
packages/cover-traffic-daemon/metrics.md
packages/cover-traffic-daemon/package.json
yarn.lock

Closes #2854 and #2743 
Also closes https://github.com/hoprnet/hoprnet/pull/2881 PR

migrate changes on metrics and readme md

---

.processes/development.md

Adding a staggered period schedule

Update reprensentative election

---

packages/utils/src/process/resourceLogger.ts

The units were slightly off, making the reporting confusing.

Improve reporting of memory usage information

---

packages/cover-traffic-daemon/src/index.ts
scripts/run-integration-tests-source.sh

This is based on previous change by @jjperezaguinaga 
It ran into the issue of address resolution, see: https://github.com/hoprnet/hoprnet/runs/4310214182?check_suite_focus=true

Improve ct logging

---

packages/connect/package.json
yarn.lock

downgrade libp2p-interfaces to version 1.1.0

Rollback libp2p-interfaces

---

README.md

Fixes https://github.com/hoprnet/hoprnet/issues/3003

Update README.md update instructions

---

packages/core/src/libp2p.mock.ts

See https://github.com/hoprnet/hoprnet/runs/4361755683?check_suite_focus=true

Missing type definition breaks build

---

.github/workflows/connect-integration-testing.yaml
.github/workflows/e2e-npm.yaml
.github/workflows/e2e.yaml
scripts/run-integration-tests-npm.sh

Changes:
- use different filenames for macOS and Linux for uploaded logs after running e2e tests
- include hardhat log to npm e2e debug log upload

Improved logs

---

.processes/development.md

This PR adds a proposal to somehow more organized Retros generating more trackable action items.

Retro followups

---

packages/core/src/index.mock.ts
packages/core/src/index.ts
packages/core/src/libp2p.mock.ts
packages/core/tsconfig.json

Fix two uncaught promise rejections

Fix uncaught promise rejections

---

README.md

Fix that makes the workaround step actually work :)

Tiny fix in README.md dev network steps

---

packages/core/protocol-config.json
packages/hoprd/releases.json

Preparation for the next Internal release

Update environment for the Prague internal release

---

package.json
tsconfig.scripts.json

Add necessary dependencies when type-checking scripts folder

Add dependencies

---

CHANGELOG.md
packages/core/src/network/heartbeat.spec.ts
packages/core/src/network/heartbeat.ts

Unification of hash functions we use - Blake2s instead of SHA256
Resolves #3038

Change ping to use Blake2s-256 instead of SHA256 for response calculation

---

packages/connect/package.json
packages/core/package.json
packages/utils/package.json
yarn.lock

Fixes #3079 
Commit that does the magic:
https://github.com/hoprnet/js-libp2p/commit/04fe17f05191cc68c9d24ed57e1f09526542a296

Use properly fixed libp2p

---

scripts/testnet.sh

Increase XDAI amount to 0.1 for testnets
Closes #3061

Updated minimum funding NATIVE amount for testnets

---

.processes/index.md

Link wallets.md to main processes page

---

README.md
packages/cover-traffic-daemon/src/index.ts
packages/hoprd/package.json
packages/hoprd/rest-api-v2-spec.yaml
packages/hoprd/src/admin.ts
packages/hoprd/src/api/v2.ts
packages/hoprd/src/api/v2/paths/messages.ts
packages/hoprd/src/index.ts
packages/hoprd/src/logs.ts
scripts/deploy.sh
scripts/run-integration-tests-gcloud.sh
scripts/run-integration-tests-npm.sh
scripts/run-integration-tests-source.sh
scripts/setup-gcloud-cluster.sh
scripts/setup-local-cluster.sh
scripts/testnet.sh
scripts/topologies/full_interconnected_cluster.sh
scripts/utils.sh
test/integration-test.sh
test/security-test.sh
yarn.lock

This PR enables the use of the API for Myne Chat v0.1.
Depends on https://github.com/hoprnet/myne-chat/pull/35 to be merged first, so the changes are available under `https://int-dev-app.myne.chat`.
Refs https://github.com/hoprnet/myne-chat/issues/1
Fixes https://github.com/hoprnet/myne-chat/issues/10
- added helper script to launch a local cluster of nodes which can also be initialized using a helper script
- added security checks to Rest API v2
- added ability to send messages through Rest API v2
- added CORS handling to Rest API v2
- various improvements to helper scripts 
You can run a local cluster of nodes:
```
yarn build && ./scripts/setup-local-cluster.sh -m "https://int-dev-app.myne.chat" -i scripts/topologies/full_interconnected_cluster.sh
```
Then you will get the following …

Add message sending to Rest API v2

---

scripts/run-integration-tests-npm.sh

Fixes https://github.com/hoprnet/hoprnet/issues/3114

fix npm e2e tests

---

packages/connect/src/base/listener.spec.ts
packages/connect/src/base/listener.ts
packages/connect/src/base/tcp.spec.ts
packages/connect/src/base/utils.spec.ts

Fix flaky `hopr-connect` tests resulting from hanging open sockets

Fix hanging tests

---

packages/core-ethereum/src/indexer/fixtures.ts
packages/core-ethereum/src/indexer/index.mock.ts
packages/core-ethereum/src/indexer/index.spec.ts
packages/core-ethereum/src/indexer/index.ts
packages/core/src/messages/packet.ts
packages/utils/src/db.ts

handle TicketRedeemed

---

packages/core-ethereum/src/indexer/index.ts

fix read-after-write error in indexer.

Fix read-after-write error

---

packages/core-ethereum/src/constants.ts
packages/core-ethereum/src/ethereum.ts
packages/core-ethereum/src/transaction-manager.ts

Fixes #3096 
TODO:
1. ensure there is no race condition between the time it's mined and the receipt is asked
2. somehow write tests for it

throw error on tx reverts

---

packages/core-ethereum/src/ethereum.ts

Try block can fail before deferrer is initialized

fix missing deferrer listener

---

scripts/testnet.sh

Opened issue https://github.com/hoprnet/hoprnet/issues/3161
This is a quick fix

avoid nonce reuse when funding

---

scripts/testnet.sh

- increase fund script's min funds

various hotfixes

---

packages/cover-traffic-daemon/metrics.md
packages/cover-traffic-daemon/src/index.ts

Let CT node to log something when receiving messages

add listener of receiving message

---

packages/hoprd/src/admin.ts
packages/hoprd/src/api/v2.ts
packages/hoprd/src/api/v2/paths/messages.ts
scripts/setup-local-cluster.sh

The `/messages` endpoint now uses automatic path finding as the default. This is also used by Myne Chat as a result.

Use automatic path finding in Rest API v2

---

packages/cover-traffic-daemon/Dockerfile

Fix docker build of CT daemon, which was lacking git binary as well

---

packages/core-ethereum/src/index.ts
packages/core-ethereum/src/indexer/fixtures.ts
packages/core-ethereum/src/indexer/index.mock.ts
packages/core-ethereum/src/indexer/index.spec.ts
packages/core-ethereum/src/indexer/index.ts
packages/utils/src/db.spec.ts
packages/utils/src/db.ts

Fixes https://github.com/hoprnet/hoprnet/issues/3196

store hopr balance

---

packages/core/src/index.ts
packages/core/src/messages/packet.ts
packages/cover-traffic-daemon/package.json
packages/cover-traffic-daemon/src/index.ts
packages/cover-traffic-daemon/src/state.mock.ts
packages/cover-traffic-daemon/src/state.spec.ts
packages/cover-traffic-daemon/src/state.ts
packages/cover-traffic-daemon/src/strategy.spec.ts
packages/cover-traffic-daemon/src/strategy.ts
packages/cover-traffic-daemon/src/utils.ts
yarn.lock

Fix #3197 
Fix #3204 
Add unit tests for `state` and `strategy` (starting point)

Fix missing implementations in CT and add unit tests

---

packages/core-ethereum/src/indexer/index.ts

fix unhandled promise 3202

---

packages/hoprd/src/identity.spec.ts
packages/hoprd/src/identity.ts

Minor fixes on the identity creation code
Intends to fix https://github.com/hoprnet/hoprnet/issues/3174

Fix identity creation

---

packages/connect/src/base/listener.spec.ts
packages/connect/src/base/listener.ts

Fixes #3214 
slightly improve testing

Improve connectivity #3

---

CHANGELOG.md
packages/core-ethereum/src/index.ts
packages/hoprd/src/index.ts
packages/utils/src/crypto/keyPair.ts

Fix unhandled rejection with no network, change invalid password message

---

scripts/publish-version.sh

ci: exclude hopr-docs from package publishing routine

---

packages/hoprd/src/api/v2/paths/message/sign.ts

During working with hoprnet/myne-chat#89 this was found.

Wrong request body, updated to reflect actual param

---

docs/hopr-documentation/docusaurus.config.js

I configured the data as repository secrets already.
Ref #1960

docs: grab algolia configuration secrets from env

---

.gitignore
packages/avado/.gitignore
packages/connect/.gitignore
packages/core-ethereum/.gitignore
packages/core/.gitignore
packages/cover-traffic-daemon/.gitignore
packages/ethereum/.gitignore
packages/hoprd/.gitignore
packages/utils/.gitignore
scripts/vm-nat-testing/.gitignore

be more specific what to ignore.
A trailing `/` ignores the immediate subdirectory which is what is expected

git ignore improvements

---

packages/core-ethereum/src/ethereum.ts
scripts/deploy.sh
scripts/fund-address.ts
scripts/gcloud.sh

Fixes:
- fail if not successful
- use gasPrice from `protocolConfig.json`
- make confirmation timeout adjustable
- log hopr-connect debug log on ct node
How to test:
Get CI/CD from password manager ...
PRIVATE_KEY="FIND ME IN PW MANAGER" DEBUG=hopr* ./scripts/fund-address.ts --environment=master-goerli --address 0x78F569559659b561b7b9Cd15EFc1A657fe38F342 --target 0.10 --erc20

various fixes on fund script

---

packages/core/src/index.ts
packages/utils/src/libp2p/dialHelper.ts

Fixes:
Add debug logs for:
```
hopr-core:libp2p:error Dial error: no protocol with name: "'p2p'". Must have a valid family name: "{ip4, ip6, dns4, dns6}". "
```

Improve debugging and repair addresses command

---

.github/workflows/deploy.yaml
scripts/testnet.sh

Changes:
- don't run `yarn install / yarn build` twice
- fix environments in fund script
Test with:
create an executable script `tryout.sh` and add
```
source "./scripts/testnet.sh"
FUNDING_PRIV_KEY=FIND_ME_IN_PW_MANAGER fund_if_empty 0x80Aaa2453CCf2f301cee2ce7F4be842db4c945dC master-goerli
```
then `DEBUG=hopr* ./tryout.sh`

ci improvements

---

.github/workflows/deploy.yaml
scripts/testnet.sh

Ports:
- #3320 
Release: 
- #3220

Hotfix release/athens: ci improvements (#3320)

---

README.md

Hotfix release/athens: fix home dir reference in readme

---

CHANGELOG.md
packages/connect/src/filter.spec.ts
packages/connect/src/filter.ts

Resolves #3311 
Release: 
- #3220

Release athens hotfix: check localhost port before dialing

---

CHANGELOG.md
packages/connect/src/filter.spec.ts
packages/connect/src/filter.ts

Check localhost dial port

---

.github/workflows/deploy.yaml

changes:
- also wait for connect package in CI pipeline

wait for connect package in CI pipeline

---

.github/workflows/deploy.yaml
.processes/release.md
scripts/deploy.sh
scripts/gcloud.sh
scripts/setup-gcloud-cluster.sh

devops: Add use of static IPs to all gcloud cluster instances
See original PR:
- #3343

Hotfix release/athens: Merge pull request #3343 from hoprnet/tb/add-gcloud-static-ips

---

scripts/deploy.sh
scripts/setup-gcloud-cluster.sh

scripts: Fix missing parameter when calling gcloud setup script

---

scripts/deploy.sh
scripts/setup-gcloud-cluster.sh

PR for `master`: #3369 
Refs #3368

Hotfix release/athens: scripts: Fix missing parameter when calling gcloud setup script

---

scripts/deploy.sh

scripts: fix missing line break continuation

---

docs/hopr-documentation/docusaurus.config.js

docs: correct index name for algolia doc search

---

.vscode/launch.json
packages/core/src/environment.ts
packages/core/src/index.ts
packages/hoprd/package.json
packages/hoprd/src/index.ts
packages/hoprd/src/main.ts
yarn.lock

- See https://github.com/hoprnet/hoprnet/pull/3103#discussion_r796629199
- Reverts hoprnet/hoprnet#3103

Revert "Setup for runnable `hoprd` as a package"

---

.github/ISSUE_TEMPLATE/release.md
VERIFICATION_GUIDE.md

This is to ensure the step isn't missed.

processes: Add contract verification check to release issue template

---

.github/ISSUE_TEMPLATE/bounty.md
.processes/bounty.md
.processes/development.md
.processes/index.md

Bounty processes

---

packages/hoprd/src/commands/index.ts

Add a try-catch block around each admin command call

---

docs/hopr-documentation/src/css/custom.css
docs/hopr-documentation/versioned_docs/version-v1.86/node/guide-using-a-hoprd-node.md
docs/hopr-documentation/versioned_docs/version-v1.86/node/using-docker.md
docs/hopr-documentation/versioned_docs/version-v1.86/node/using-npm.md

- By given feedback from COM team I updated content for NPM, Docker 
- In general added css margin bottom inside admonition for `p` element.

Content update for versioning 1.86 + css correction for general

---

docs/hopr-documentation/src/css/custom.css
docs/hopr-documentation/versioned_docs/version-v1.86/node/using-docker.md
docs/hopr-documentation/versioned_docs/version-v1.86/node/using-npm.md

- Added new NPM version, removed whitespaces for command on NPM and Docker
- Added word wrap for the code blocks

Versioned docs 1.86 update

---

docs/hopr-documentation/docs/developers/connecting-node.md
docs/hopr-documentation/docs/developers/intro.md
docs/hopr-documentation/docs/developers/starting-local-cluster.md
docs/hopr-documentation/docs/developers/tutorial-hello-world.md
docs/hopr-documentation/sidebars.js
docs/hopr-documentation/src/components/HOPRfrontPage.js

- Linked everything and brought up latest comments and feedback from past rounds
- Fixes hoprnet/hopr-devrel#170

Completed all documentation

---

CHANGELOG.md
packages/core-ethereum/src/commitment.spec.ts
packages/core-ethereum/src/commitment.ts
packages/core-ethereum/src/ethereum.ts
packages/core-ethereum/src/index.ts
packages/core/src/channel-strategy.ts
packages/core/src/index.ts
packages/core/src/interactions/packet/acknowledgement.ts
packages/core/src/messages/packet.ts
packages/ethereum/tasks/faucet.ts
packages/utils/src/async/concurrency.spec.ts
packages/utils/src/async/concurrency.ts
packages/utils/src/crypto/por/index.ts
packages/utils/src/db.ts
packages/utils/src/types/acknowledgedTicket.ts
packages/utils/src/types/solidity.ts
packages/utils/src/types/ticket.ts
scripts/run-integration-tests-source.sh
test/integration-test.sh

See original PR for details: https://github.com/hoprnet/hoprnet/pull/3395

Hotfix release/athens: Port of ticket redemption fixes

---

packages/avado/README.md

Removes obsolete AVADO documentation

update AVADO documentation

---

packages/avado/dappnode_package.json
packages/avado/docker-compose.yml
scripts/build_avado.sh

Removes obsolete `avado`  and `docker` config.
Use well-known link `OnboardingWizard` to automatically redirect users to Hopr Admin interface
Updates AVADOSDK version

Update avado docker config

---

CHANGELOG.md
packages/connect/src/constants.ts

Normalize protocol version before checking relay usability

---

.processes/bounty.md

document how to make contributing PRs when bounty

---

.github/ISSUE_TEMPLATE/bounty.md
docs/hopr-documentation/docs/developers/connecting-node.md

Fixes #3446 
Point developers to our docs

Improve bounty template

---

packages/hoprd/src/admin.ts
packages/hoprd/src/api/index.ts
packages/hoprd/src/api/utils.spec.ts
packages/hoprd/src/api/utils.ts
packages/hoprd/src/api/v1.ts
packages/hoprd/src/api/v2.ts
packages/hoprd/src/api/v2/paths/messages/index.ts
packages/hoprd/src/api/v2/paths/messages/websocket.ts
test/security-test.sh

Related #3425 
- improve WS endpoint and tests
- various documentation improvements

API v2 improvements

---

scripts/run-integration-tests-npm.sh

fix e2e npm test

---

docs/hopr-documentation/src/components/HOPRfrontPage.js
docs/hopr-documentation/versioned_docs/version-v1.86/node/start-here.md
docs/hopr-documentation/versioned_sidebars/version-v1.86-sidebars.json

- added 1.86 links on the frontpage
- Removed other install methods from content and sidebar

Updating frontpage

---

docs/hopr-documentation/docusaurus.config.js
docs/hopr-documentation/versioned_docs/version-v1.86/node/guide-using-a-hoprd-node.md
docs/hopr-documentation/versioned_docs/version-v1.86/node/using-avado.md
docs/hopr-documentation/versioned_docs/version-v1.86/node/using-docker.md

- These changes will need to be bridged back to `master`
- Fixes hoprnet/hopr-devrel#189

`release/athens` specific documentation

---

docs/hopr-documentation/docusaurus.config.js
docs/hopr-documentation/versioned_docs/version-v1.86/node/guide-using-a-hoprd-node.md
packages/core/protocol-config.json
packages/hoprd/releases.json

Add new environment and release: lisbon

---

docs/hopr-documentation/src/css/custom.css
docs/hopr-documentation/versioned_docs/version-v1.86/node/using-avado.md

- Hide docs version warning with css
- Update avado with security token and follow the user guide.

Some minor fixes

---

docs/hopr-documentation/docs/developers/components/BoomerangChat.jsx
docs/hopr-documentation/docs/developers/components/IframeLoader.jsx
docs/hopr-documentation/docs/developers/components/RPSGame.jsx
docs/hopr-documentation/docs/developers/components/WebSocketHandler.jsx
docs/hopr-documentation/docs/developers/components/atoms/ClusterHelper.jsx
docs/hopr-documentation/docs/developers/components/atoms/Connector.jsx
docs/hopr-documentation/docs/developers/components/utils.js
docs/hopr-documentation/docs/developers/containers/connector.mdx
docs/hopr-documentation/docs/developers/demo-rps-game.mdx
docs/hopr-documentation/docs/developers/rest-api.mdx
docs/hopr-documentation/sidebars.js

- Fixes hoprnet/hopr-devrel#174

Rock, paper & scissors demo game

---

docs/hopr-documentation/docs/developers/starting-local-cluster.md

Added new Gitpod setup instructions w/cluster

---

packages/connect/package.json
packages/core-ethereum/package.json
packages/core/package.json
packages/cover-traffic-daemon/package.json
packages/ethereum/package.json
packages/hoprd/package.json
packages/utils/package.json

Due to a bug this wasn't triggered automatically. Will be further investigated.

Update version to next minor version

---

.gitpod.Dockerfile
.gitpod.yml
scripts/setup-local-cluster.sh

Add GitPod setup also to the Athens release branch.
See #3416

Add GitPod setup for Hello World also to Athens

---

CHANGELOG.md
packages/connect/src/base/listener.spec.ts
packages/connect/src/base/listener.ts
packages/connect/src/index.ts
packages/core/src/index.mock.ts
packages/core/src/index.spec.ts
packages/core/src/main.ts
packages/cover-traffic-daemon/src/index.spec.ts

Fixes https://github.com/hoprnet/hoprnet/issues/3404
Other changes:
- reduce dial timeout from 30s to 10s
- minor changes to mocks to work with updated filter

fix address filter / listener issue

---

scripts/gcloud.sh

devops(gcloud): Use different european region/zone for VMs

---

docs/hopr-documentation/README.md

Readme file for Docs page

---

docs/hopr-documentation/docs/developers/starting-local-cluster.md

- As agreed with @tolbrino 
- Fixes hoprnet/hopr-devrel#167

Set up `lisbon` as latest stable release

---

scripts/testnet.sh

Especially on Goerli this should prevent race conditions.

ci: Add wait time between funding attempts

---

.github/workflows/deploy.yaml
.github/workflows/e2e-gcloud.yaml
scripts/gcloud.sh

This requires the beta components of gcloud to be installed too.

ci: Fix deletion of instance template when updating group

---

scripts/run-integration-tests-npm.sh
scripts/run-integration-tests-source.sh

This was broken after https://github.com/hoprnet/hoprnet/pull/3511 was
merged.

ci: Fix balance checks in smoke tests

---

.gitpod.yml

rebuild gitpod less often

---

docs/hopr-documentation/docs/developers/snippets.mdx
docs/hopr-documentation/docs/developers/snippets/WebSocketHandler.md
docs/hopr-documentation/docs/developers/snippets/getHeaders.md
docs/hopr-documentation/docs/developers/snippets/useWebSocket.md
docs/hopr-documentation/sidebars.js

- Included the connection ones for the time being
- Fixes #3530

Added code snippets to documentation

---

docs/hopr-documentation/docs/developers/starting-local-cluster.md

Add link to Vimeo with Hopr Hello World demo in GitPod video

Add video link to Docs page

---

.gitpod.yml
scripts/init-gitpod.sh
scripts/setup-local-cluster.sh

Earlier merge-back some GitPod changes from release/lisbon to master

---

docs/hopr-documentation/docs/developers/connecting-node.md
docs/hopr-documentation/docs/developers/demo-boomerang-chat.mdx
docs/hopr-documentation/docs/developers/demo-rps-game.mdx
docs/hopr-documentation/docs/developers/intro.md
docs/hopr-documentation/docs/developers/starting-local-cluster.md
docs/hopr-documentation/docs/developers/tutorial-hello-world.md

Language edits to developer docs, up to RPS demo

Edits to Developer Docs

---

docs/hopr-documentation/README.md
docs/hopr-documentation/docs/about-hopr.md
docs/hopr-documentation/docs/developers/starting-local-cluster.md
docs/hopr-documentation/src/css/custom.css

- Replaced YT video with Vimeo
- Fixed embed videos full width issue.

Embed videos full width fix

---

.gitpod.yml
packages/hoprd/src/healthcheck.ts
scripts/setup-local-cluster.sh

exposed healthcheck ports

---

scripts/testnet.sh
scripts/utils.sh

- Our API endpoint (see [latest](https://github.com/hoprnet/api/pull/7) PR) handles now all issues with the nonce tracker and what not.
- Fixes #3351

Restored API-based funding script for CI

---

scripts/setup-local-cluster.sh

Print more information about the local cluster setup into the console.

Hotfix: Print more information for local cluster setup

---

docs/hopr-documentation/docs/developers/starting-local-cluster.md
docs/hopr-documentation/sidebars.js
docs/hopr-documentation/versioned_docs/version-v1.87/developers/starting-local-cluster.md
docs/hopr-documentation/versioned_sidebars/version-v1.85-sidebars.json
docs/hopr-documentation/versioned_sidebars/version-v1.86-sidebars.json
docs/hopr-documentation/versioned_sidebars/version-v1.87-sidebars.json

There's a duplicate entry for incentives

Removed duplicate sidebar entry in documentation

---

.processes/development.md

Update process to reflect representative changes

---

.processes/bounty.md
.processes/development.md
.processes/devrel.md
.processes/index.md
.processes/release.md
.processes/wallets.md

- Fixes #3639 
- Fixes #3638 
- various cosmetic changes
- renamed `community.md` process to `devrel.md` process

various processes changes

---

packages/connect/src/relay/context.ts

An interesting typo in the relay code...

A typo in relay context.ts might result in a restart

---

scripts/publish-version.sh

Use correct path for `wait-for-npm-package` script

fix typo in publish script

---

packages/core/protocol-config.json
packages/hoprd/releases.json

Should unblock deployment pipeline of new release

Add Ouagadougou release info to master

---

scripts/build_lockfiles.sh
scripts/gcloud.sh

Re: https://github.com/hoprnet/hoprnet/pull/3665 for `master`

fix lockfile script and regions

---

scripts/testnet.sh

hotfix funding issue

---

scripts/notify-matrix-cluster-info.sh

Fix unbound variable and refactored script.

Fixed unbound variable and other improvements in `notify-matrix-cluster-info.sh`

---

packages/connect/package.json
packages/core/package.json
packages/utils/package.json
yarn.lock

Bump libp2p-noise to include this bugfix https://github.com/ChainSafe/js-libp2p-noise/pull/130

bump libp2p-noise

---

packages/core-ethereum/src/ethereum.ts
packages/core-ethereum/src/index.ts
packages/core-ethereum/src/indexer/fixtures.ts
packages/core-ethereum/src/indexer/index.mock.ts
packages/core-ethereum/src/indexer/index.spec.ts
packages/core-ethereum/src/indexer/index.ts
packages/core/src/index.ts
packages/ethereum/deploy/06_HoprNetworkRegistry.ts
packages/ethereum/test/proxy/HoprStakingProxyForNetworkRegistry.test.ts
packages/utils/src/db/db.spec.ts
packages/utils/src/db/db.ts

Related to #3182 
Fixes https://github.com/hoprnet/hoprnet/issues/3679

add isWhitelisted

---

.gitignore
docs/hopr-documentation/docusaurus.config.js
docs/hopr-documentation/package.json
package.json
scripts/run-integration-tests-npm.sh
scripts/run-integration-tests-source.sh
yarn.lock

Fixes Vercel builds and e2e tests

Hotfix/fix Vercel build and e2e tests

---

.github/workflows/lint.yaml
scripts/utils.sh
shell.nix

This change ensure various endpoint url combinations are handled and escaping is done properly during command retry.

Improve shell utils to get address information from node

---

packages/ethereum/deploy/02_HoprToken.ts
packages/ethereum/deploy/03_HoprDistributor.ts
packages/ethereum/deploy/04_HoprWrapper.ts

Reduces hardhat waiting time and some type enhancements

reduce hardhat waiting time in e2e tests

---

packages/ethereum/contracts/HoprNetworkRegistry.sol
packages/ethereum/contracts/proxy/HoprDummyProxyForNetworkRegistry.sol
packages/ethereum/deploy/06_HoprNetworkRegistryProxy.ts
packages/ethereum/deploy/07_HoprNetworkRegistry.ts
packages/ethereum/test/HoprNetworkRegistry.test.ts
packages/ethereum/test/proxy/HoprDummyProxyForNetworkRegistry.test.ts

`NetworkRegistry` SC
- Add global toggle and functions for owner to switch it.
- Add modifier for all the function to be called only when the registry is on.
----
- do we need a killswitch?

Whitelist add toogle dummy proxy

---

scripts/get-gcloud-instances-accounts-info.sh
scripts/utils.sh

The result is a working cluster info notification CI step.

Fix error handling in url helper

---

CHANGELOG.md
README.md
packages/core-ethereum/src/ethereum.ts
packages/core/src/environment.spec.ts
packages/core/src/environment.ts
packages/core/src/main.ts
packages/cover-traffic-daemon/README.md
packages/cover-traffic-daemon/src/index.ts
packages/ethereum/src/index.ts
packages/hoprd/README.md
packages/hoprd/src/index.ts

- Create implementation and tests for issue #3371
- Allow `--provider` flag in `hoprd` and `cover-traffic` packages

Custom provider endpoint 3371

---

packages/core-ethereum/src/index.spec.ts
packages/core-ethereum/src/index.ts
packages/core-ethereum/src/indexer/fixtures.ts
packages/core-ethereum/src/indexer/index.spec.ts
packages/core-ethereum/src/indexer/index.ts
packages/core/src/index.ts
packages/core/src/main.ts
packages/ethereum/contracts/proxy/HoprStakingProxyForNetworkRegistry.sol
packages/ethereum/deploy/06_HoprNetworkRegistryProxy.ts
packages/ethereum/deploy/07_HoprNetworkRegistry.ts
packages/ethereum/hardhat.config.ts
packages/ethereum/tasks/register.ts
packages/ethereum/test/proxy/HoprStakingProxyForNetworkRegistry.test.ts
packages/utils/src/db/db.spec.ts
packages/utils/src/db/db.ts
scripts/run-integration-tests-npm.sh
scripts/run-integration-tests-source.sh
test/ct-test.sh
test/integration-test.sh

remove mentions of whitelist

---

packages/core-ethereum/src/index.ts
packages/core-ethereum/src/indexer/index.ts
packages/core/src/index.ts
packages/core/src/main.ts
packages/core/src/network/access-control.ts
packages/core/src/network/heartbeat.spec.ts
packages/core/src/network/heartbeat.ts
packages/core/src/network/network-peers.ts
packages/cover-traffic-daemon/src/index.ts
packages/hoprd/src/index.ts
packages/utils/src/db/db.spec.ts
packages/utils/src/db/db.ts
scripts/run-integration-tests-source.sh

reconnect peers once they are eligible

---

CHANGELOG.md
packages/connect/src/relay/handshake.ts
packages/connect/src/relay/index.ts

Missing `await` and `try/catch`. Fixes #3563

Added missing await in onRelay event handler

---

.github/workflows/latexcompile.yaml
docs/hopr-documentation/docs/dapps/myne-chat.md
docs/hopr-documentation/sidebars.js
docs/hopr-documentation/src/components/HOPRfrontPage.js
docs/hopr-documentation/versioned_docs/version-v1.86/dapps/myne-chat.md
docs/hopr-documentation/versioned_docs/version-v1.87/dapps/myne-chat.md

Fix commit message in GA workflow for yellowpaper

---

.envrc
docs/hopr-documentation/docs/dapps/myne-chat.md
docs/hopr-documentation/sidebars.js
docs/hopr-documentation/src/components/HOPRfrontPage.js
docs/hopr-documentation/versioned_docs/version-v1.86/dapps/myne-chat.md
docs/hopr-documentation/versioned_docs/version-v1.87/dapps/myne-chat.md

Minor improvement to the local set up for developer using `nix`.

Update nix configuration

---

packages/core-ethereum/src/index.spec.ts
packages/core-ethereum/src/index.ts
packages/core-ethereum/src/indexer/index.spec.ts
packages/core-ethereum/src/indexer/index.ts
packages/core/src/index.ts
packages/core/src/network/access-control.ts
packages/utils/src/db/db.spec.ts
packages/utils/src/db/db.ts

- more consistent naming
- catch errors in reviewConnection

various whitelist fixes

---

packages/hoprd/src/index.ts

This is in addition to already handling the write version in a similar
way.
Fixes #3699

Silence unhandled rejection: read ECONNRESET

---

docs/hopr-documentation/docusaurus.config.js
scripts/utils.sh

Related #3182 
- add back docesaurus file
- remove unused code

addressing whitelist feedback

---

.github/workflows/e2e-npm.yaml
.github/workflows/e2e.yaml
packages/ethereum/deploy/07_HoprNetworkRegistry.ts
packages/ethereum/tasks/register.ts
test/integration-test.sh

Related to https://github.com/hoprnet/hoprnet/issues/3687
Only enable NR in production.
The environment / network code will be greatly improved in https://github.com/hoprnet/hoprnet/issues/3687

disable NR in development networks

---

.github/workflows/deploy.yaml
.github/workflows/e2e-gcloud.yaml
.github/workflows/e2e-npm.yaml
.github/workflows/e2e.yaml
.github/workflows/test.yaml
test/integration-test.sh

Hacky workaround to fix build process by running `yarn build` twice

hotfix WASM build issue

---

.github/workflows/docs.yaml
Makefile
package.json
packages/cover-traffic-daemon/package.json
packages/hoprd/package.json
yarn.lock

This adds three targets for all relevant docs generation tasks.

Add make targets for docs generation

---

packages/connect/package.json
packages/core-ethereum/package.json
packages/core/package.json
packages/cover-traffic-daemon/package.json
packages/ethereum/package.json
packages/hoprd/package.json
packages/real/package.json
packages/utils/package.json

These versions got our of sync during some PR merge races.
Refs #3833

Fix incorrect package versions

---

packages/core-ethereum/package.json
packages/core/package.json
packages/cover-traffic-daemon/package.json
packages/ethereum/package.json
packages/hoprd/package.json
packages/real/package.json
packages/utils/package.json
yarn.lock

Bump typedoc to support Typescript 4.7+

fix typedoc issue

---

.github/workflows/deploy.yaml
scripts/setup-gcloud-cluster.sh

This is needed when using dashes in keys.

Fix jq string quoting

---

docs/hopr-documentation/docs/ecosystem/gnosis-hopr-tokens.md
docs/hopr-documentation/docs/ecosystem/hopr-token.md
docs/hopr-documentation/docs/ecosystem/hoprd.md
docs/hopr-documentation/docs/ecosystem/intro.md
docs/hopr-documentation/docs/ecosystem/staking.md
docs/hopr-documentation/sidebars.js
docs/hopr-documentation/src/components/HOPRfrontPage.js

fix ecosystem section

---

Makefile
scripts/gcloud.sh
scripts/testnet.sh
scripts/utils.sh

Fix further CI funding issues in scripts

---

scripts/testnet.sh

Remove debug info

---

.github/workflows/deploy.yaml

Add missing deployer key as env var in CI

---

README.md

Rust toolchain requirement & instructions added to README.md

Add missing Rust requirement to README

---

Makefile
NETWORK_REGISTRY.md
packages/ethereum/deploy/20_mintDevNftTransferOwnership.ts
packages/ethereum/hardhat.config.ts
packages/ethereum/tasks/requestDevNft.ts
packages/ethereum/tasks/stake.ts

- Address partially #3916. Reduce actions to be done for NR and replace manual interaction with UI with make targets.
- Found a bug in `stake.ts` where a dead loop may occur.

Add a task to request dev nft and fix loop bug

---

packages/connect/src/base/listener.ts
packages/connect/src/base/stun.ts
packages/connect/src/relay/handshake.spec.ts
packages/connect/src/relay/handshake.ts
packages/connect/src/relay/index.ts
packages/hoprd/src/api/v2/paths/node/info.integration.spec.ts
packages/hoprd/src/index.ts
packages/utils/src/db/db.ts

- `hoprd` use correct lexical scope when passing function handles
- `db`  on `init()`, either force-create db or check if it is there

minor startup fixes

---

Makefile
scripts/setup-gcloud-cluster.sh

Enhances the makefile to check and pass private key

pass and check private key for self-register action

---

scripts/run-integration-tests-npm.sh
scripts/testnet.sh

Fixes problem seen in https://github.com/hoprnet/hoprnet/runs/7577497617?check_suite_focus=true#step:8:2193

Make last parameter optional in helper script for funding nodes

---

Makefile
NETWORK_REGISTRY.md

Fix bug in Makefile and add missing `export`s to the docs

More smaller improvements to NR registration

---

docs/hopr-documentation/package.json
packages/connect/package.json
packages/core-ethereum/package.json
packages/core/package.json
packages/cover-traffic-daemon/package.json
packages/ethereum/package.json
packages/utils/package.json
packages/utils/src/libp2p/dialHelper.spec.ts
yarn.lock

`multiaddr` version needs to be updated to fix libp2p issue during build.

Update @multiformats/multiaddr to 10.3.3 to satisfy version bump on libp2p

---

.processes/development.md
.processes/release.md

Updating processes according to our discussions during tech deep dive.

Various process updates

---

packages/ethereum/tasks/register.ts

- extend evrionment where register accounts to dummy-proxy is done.

extend environment to add accounts onto proxy

---

packages/connect/package.json
packages/core-ethereum/package.json
packages/core/package.json
packages/cover-traffic-daemon/package.json
packages/ethereum/package.json
packages/hoprd/package.json
packages/real/package.json
packages/utils/package.json

Reverts versions of the packages on `master` to the state prior to the 2nd merge back of the Paleochora release branch.

Partial revert of the merge-back: properly update versions

---

packages/connect/package.json
packages/core-ethereum/package.json
packages/core/package.json
packages/cover-traffic-daemon/package.json
packages/ethereum/package.json
packages/hoprd/package.json
packages/real/package.json
packages/utils/package.json

Revert package.json version prior to the merge-back num. 2.

Revert package version pre-merge-back

---

packages/connect/src/base/entry.spec.ts
packages/connect/src/base/entry.ts

Enhance logging of entry node code

enhance logging

---

scripts/api.sh
scripts/setup-gcloud-cluster.sh
scripts/topologies/full_interconnected_cluster.sh

Ensure it works with the recent network registry addition.

Fix topology cluster deployment

---

.processes/release.md

Update to the release process spotted during Paleochora release.
Refs #3984

Update to the release process to reflect api.hoprnet.org redeploy

---

scripts/build_avado.sh

Fix Avado script environment id replacement

---

packages/ethereum/package.json
packages/ethereum/test/HoprChannels.spec.ts
packages/hoprd/src/identity.ts
packages/utils/package.json
packages/utils/src/crypto/keyPair.ts
yarn.lock

Fix wallet creation:
- add missing `@ethersproject/wallet` dependency to `utils` package.json
- remove hack that replaces `crypto` by `Crypto`
- globally bumps `@ethersproject/wallet` to latest version 5.7.0

fix wallet creation

---

packages/ethereum/package.json
packages/ethereum/test/HoprChannels.spec.ts
packages/hoprd/src/identity.ts
packages/utils/package.json
packages/utils/src/crypto/keyPair.ts
yarn.lock

Cherry-pick #4017 to `master` to unblock testing on Goerli.

Cherry-pick wallet creation fix to master

---

scripts/testnet.sh

Refs https://github.com/hoprnet/hoprnet/issues/4012
Required because of the changes in https://github.com/hoprnet/api/pull/15

[Hotfix paleochora] Faucet Helper api key fix

---

scripts/testnet.sh

[Hotfix Paleochora] scripts: fix incorrect bash quoting

---

packages/utils/src/db/db.ts

Refs #3458 
Previously the count of neglected tickets wasn't incremented correctly by the number of deleted tickets.

[Hotifx Paleochora] Fix counter increment for ticket stats in db

---

CHANGELOG.md
packages/hoprd/src/index.ts
packages/utils/src/network/addrs.ts
packages/utils/src/network/constants.ts

Detect AVADO/Dappnode special private subnet

---

scripts/gcloud.sh

Fixes https://github.com/hoprnet/hoprnet/issues/3694

ci: prevent boot disk deletion in managed instance groups

---

packages/ethereum/deployments/master-goerli/goerli/HoprBoost.json
packages/ethereum/deployments/master-goerli/goerli/HoprNetworkRegistryProxy.json
packages/ethereum/deployments/master-goerli/goerli/HoprStake.json
packages/ethereum/deployments/master-goerli/goerli/xHoprToken.json

Adds blockNumber property to all `master-goerli` deployment files

add missing blockNumbers to deployment files

---

CHANGELOG.md
packages/connect/src/base/entry.ts
packages/connect/src/constants.ts
packages/connect/src/types.ts
packages/core/src/index.ts
packages/core/src/main.ts

Mirrors latest enhancements to #3990 to be get tested on `staging`

backport #3990 to master

---

packages/core-ethereum/src/index.ts
packages/core/src/index.ts
packages/hoprd/src/admin.ts
packages/hoprd/src/api/v2/paths/node/configuration.integration.spec.ts
packages/hoprd/src/api/v2/paths/node/configuration.ts
packages/hoprd/src/commands/commands.spec.ts
packages/hoprd/src/commands/index.ts
packages/hoprd/src/commands/info.ts
packages/hoprd/src/commands/settings.ts
packages/hoprd/src/commands/showConfiguration.ts
packages/hoprd/src/index.ts

Feat show node configuration

---

CHANGELOG.md
packages/core/src/index.ts
packages/hoprd/hopr-admin/src/commands/entryNodes.ts
packages/hoprd/hopr-admin/src/commands/help.ts
packages/hoprd/hopr-admin/src/commands/index.ts
packages/hoprd/hopr-admin/src/utils/api.ts
packages/hoprd/src/api/v2/paths/node/entryNodes.integration.spec.ts
packages/hoprd/src/api/v2/paths/node/entryNodes.ts
packages/hoprd/src/api/v2/paths/node/peers.integration.spec.ts
packages/hoprd/src/api/v2/paths/peerInfo/{peerid}.spec.ts

mirror: add entryNodes command (#4049)

---

packages/core-ethereum/src/ethereum.ts
packages/ethereum/deployments/master-goerli/goerli/HoprChannels.json
packages/ethereum/src/index.ts

mirrors #4051 for `release/paleochora`

Mirror #4051 for release branch

---

packages/connect/src/webrtc/connection.ts
packages/core/src/network/network-peers.ts

Remove some unnecessary logging entries that pollute the logs.

Silence some of the most talkative log writes

---

cloudbuild.yaml

Increase docker build timeout

---

packages/connect/src/webrtc/connection.ts

Silence some additional log write

---

packages/utils/src/types/publicKey.spec.ts
packages/utils/src/types/publicKey.ts

Allows serialization and deserialization of PublicKey arrays
- add static method `PublicKey.serializeArray` + `PublicKey.deserializeArray`

serialize and deserialize arrays of publicKey instances

---

packages/core/src/environment.spec.ts
packages/core/src/environment.ts
packages/cover-traffic-daemon/src/index.ts
packages/hoprd/src/index.ts
scripts/api.sh
scripts/fund-address.mts

Re #3803 
- use core's `FULL_VERSION` when checking environments
- fix send_message status code in E2E test

various hotfixes for Paleochora

---

scripts/verify-docker-image.sh

Fix version regex

---

.processes/release.md

Update release process to be more in line with new environments

update release process

---

packages/hoprd/hopr-admin/pages/index.tsx
packages/hoprd/hopr-admin/src/state/index.ts
packages/hoprd/hopr-admin/src/state/useAPI.ts
packages/hoprd/hopr-admin/src/state/useWS.ts
packages/hoprd/hopr-admin/src/utils/api.ts
packages/hoprd/hopr-admin/src/utils/command.ts
packages/hoprd/hopr-admin/src/utils/stream.ts
packages/hoprd/src/api/v2.ts
packages/hoprd/src/logs.ts

Re #4045
- `admin.ts` is already removing sockets, this PR restores the legacy behaviour
- improves `hopr-admin` message handling by listening to messages sooner

various hopr-admin message improvements

---

packages/core/protocol-config.json
packages/ethereum/deploy/16_HoprNetworkRegistryProxy.ts
packages/ethereum/deploy/17_HoprNetworkRegistry.ts

- Revert to the previous NR smart contracts
- Skip all NR deployments for now

freeze to old NR

---

scripts/setup-gcloud-cluster.sh

- add eligibility update
- do only staking special NFT for nodes in gcloud cluster

Fix for CI

---

packages/ethereum/package.hardhat.json

Fixes Hardhat Docker image build

Add missing chai dependency to hardhat docker image

---

Makefile
packages/ethereum/hardhat.config.ts
packages/ethereum/tasks/requestTestTokens.ts
packages/ethereum/tasks/stake.ts

- rename `nftRank` to `nftrank` in "stake" and "requestToken" task
- move check on "nftrank" in "register-node-when-dummy-proxy" to "register-node-with-nft" target

rename from nftRank to nftrank

---

packages/ethereum/tasks/requestTestTokens.ts
packages/ethereum/tasks/stake.ts
packages/ethereum/test/HoprToken.test.ts

- fix test case check on token symbol
- fix check on redeemed boost tokens
- let tx fail "loudly"

fix test case check on token symbol

---

scripts/gcloud.sh

Add explicit `--data` directory to the CI GCP deployment args

---

packages/avado/build/Dockerfile
packages/avado/dappnode_package.json
packages/avado/docker-compose.yml
scripts/build_avado.sh

This build simplifies and refactors the Avado build.
Also fixes the missing default token on the Onboarding link and makes the Onboarding wizard open in the same window.
Refs #3821

Various improvements to Avado build

---

packages/hoprd/hopr-admin/pages/index.tsx
packages/hoprd/hopr-admin/src/commands/addresses.spec.ts
packages/hoprd/hopr-admin/src/commands/addresses.ts
packages/hoprd/hopr-admin/src/commands/balances.spec.ts
packages/hoprd/hopr-admin/src/commands/balances.ts
packages/hoprd/hopr-admin/src/commands/channels.ts
packages/hoprd/hopr-admin/src/commands/tickets.ts
packages/hoprd/hopr-admin/src/state/index.ts
packages/hoprd/hopr-admin/src/utils/command.ts

small hopr-admin improvements

---

.processes/tokens.md

Add token info for mHOPR to docs

---

packages/core-ethereum/src/indexer/index.ts
packages/ethereum/hardhat.config.ts
packages/ethereum/tasks/faucet.ts

Close https://github.com/hoprnet/hoprnet/issues/4198
- Fixed HOPR token balance not updated when it's funded right after node launches
- Introduced `--token-type (native|hopr)` parameter for `faucet` task to separate funding native tokens and hopr tokens

Fix token balance not properly updated right after startup

---

CHANGELOG.md
packages/hoprd/hopr-admin/pages/index.tsx
packages/hoprd/hopr-admin/src/state/useWS.ts
packages/hoprd/package.json
packages/hoprd/src/api/utils.ts
packages/hoprd/src/api/v2.ts
packages/hoprd/src/index.ts
yarn.lock

- remove complexity validation on the API token
- properly encode API token passed from Admin UI
Closes #4181 
Closes #3480

Properly encode API token, remove password strength validation

---

Makefile

Remove redundant check

---

packages/connect/src/webrtc/connection.ts
packages/cover-traffic-daemon/src/index.ts
packages/cover-traffic-daemon/src/utils.ts

Minor bugfixes
- adds a missing try / catch block to WebRTCConnection + minor refactoring
- correct formatting of `ctd` debug log

minor overall fixes

---

packages/avado/docker-compose.yml
scripts/build_avado.sh

Fix Avado build

---

packages/core-ethereum/package.json
packages/core-ethereum/src/ethereum.ts
packages/core-ethereum/src/indexer/index.ts
packages/utils/src/async/abortableTimeout.ts
yarn.lock

Replaces some occurences of `setTimeout` by `retimer` to use smaller closures

replace occurences of `setTimeout` by `retimer`

---

packages/utils/src/libp2p/dialHelper.ts

Slight enhancement to debug logs to show less stack traces

enhance debug log

---

CHANGELOG.md
METRICS.md
packages/utils/src/process/promiseRejectionFilter.ts

- simple counter to count suppressed unhandled promise rejections
- add missing changelog entry for Metrics PR

Added UHP rejection metric,  add missing metrics changelog entry

---

packages/hoprd/releases.json

As part of the task 2 on https://github.com/hoprnet/hoprnet/blob/master/.processes/release.md#release-cycle, I modify the releases.json accordingly.

Preparing Bogota release

---

Makefile
NETWORK_REGISTRY.md
packages/ethereum/deploy/20_mintNetworkRegistryNfts.ts
packages/ethereum/tasks/selfRegister.ts
packages/ethereum/utils/constants.ts
scripts/setup-gcloud-cluster.sh

Port changes in https://github.com/hoprnet/hoprnet/pull/4336 to unblock `release/bogota`, see details in original PR

Fix CI staking network registry

---

.github/ISSUE_TEMPLATE/bug.md

Added consistent reproducibility question.

Improved bug GH template

---

scripts/setup-gcloud-cluster.sh

fiz gcloud script typo

---

Makefile

fix makefile typo

---

.github/workflows/deploy.yaml

Cherry-pick from #4320 
Prevents `deploy` workflow to rebuilt artifacts

Cache built artifacts in deploy workflow

---

.processes/release.md
.processes/testing.md

Documents Phase 1 testing in `.processes`
Closes #3499

Document Phase 1 testing in `.processes`

---

.gitignore
Makefile
packages/hoprd/hopr-admin/src/commands/ping.ts
packages/hoprd/hopr-admin/src/components/logs.tsx
packages/hoprd/hopr-admin/styles/log.module.css
packages/hoprd/src/admin.ts

Fixes #4368
Also provide better error message for failed ping commands.
Fixes #4160

hoprd-admin: Move warning log into header as static message

---

CHANGELOG.md
packages/avado/releases.json
packages/core/src/index.ts
packages/core/src/path/index.ts
packages/hoprd/hopr-admin/src/commands/closeChannel.ts
packages/utils/src/db/db.ts
packages/utils/src/libp2p/index.ts

Improves error handling and forwarding certain error messages passed to the User.
Closes #4132

Improve error messages passed to the user

---

docs/hopr-documentation/package.json
packages/core-ethereum/package.json
packages/core/package.json
packages/cover-traffic-daemon/package.json
packages/ethereum/package.json
packages/hoprd/package.json
packages/real/package.json
packages/utils/package.json
yarn.lock

bump docs packages

---

.github/workflows/deploy.yaml
.processes/release.md
packages/hoprd/releases.json
scripts/publish-version.sh

(cherry picked from commit a91bd52c3bd68149527929a759987469134cab54)

Introduce Staging releases (backport of #4301)

---

scripts/deploy.sh

Small fix in the naming of the Staging Cluster.

Fix cluster tag naming

---

packages/hoprd/hopr-admin/src/commands/ping.spec.ts
scripts/run-integration-tests-source.sh
test/integration-test.sh

This fixes the ping unit test for the API by adapting the expected return message. Moreover, the smoke tests are fixed so they actually fail when ticket redemption doesn't work.

hotfix-bogota: fix broken test execution

---

packages/hoprd/hopr-admin/pages/index.tsx

The message is improved to better legibility

Improve message on WebAdmin UI for Connected peers

---

.github/workflows/deploy.yaml
.processes/release.md
CHANGELOG.md
METRICS.md
packages/avado/releases.json
packages/connect/package.json
packages/connect/src/base/stun.ts
packages/core-ethereum/package.json
packages/core-ethereum/src/index.ts
packages/core/package.json
packages/core/src/index.ts
packages/core/src/path/index.ts
packages/cover-traffic-daemon/package.json
packages/ethereum/package.json
packages/hoprd/hopr-admin/src/commands/closeChannel.ts
packages/hoprd/hopr-admin/src/commands/ping.spec.ts
packages/hoprd/package.json
packages/hoprd/releases.json
packages/real/package.json
packages/utils/package.json
packages/utils/src/db/db.ts
packages/utils/src/libp2p/index.ts
scripts/build-docker.sh
scripts/build_avado.sh
scripts/deploy.sh
scripts/publish-version.sh
scripts/run-integration-tests-source.sh
test/integration-test.sh

Generate Bogota v1.91.19
This includes mostly usability improvements in HOPRd admin, a STUN fix and ticket redemption fix.
Refs #4275

Release update bogota/v1.91.19

---

.github/workflows/deploy.yaml
.github/workflows/e2e-gcloud.yaml
packages/avado/README.md
packages/avado/docker-compose.yml
scripts/build-avado.sh

Fixes https://github.com/hoprnet/hoprnet/actions/runs/3530152644/jobs/5922188448

avado: Fix identification of master builds

---

CHANGELOG.md
packages/connect/package.json
packages/connect/src/base/listener.ts
packages/connect/src/base/stun.spec.ts
packages/connect/src/base/stun.ts
packages/connect/src/base/utils.spec.ts
packages/connect/src/relay/handshake.spec.ts
yarn.lock

This reverts commit e38bcee014dd5e703d56ab124b8f9ce381fd3c4d.
Refs #4403

[hotfix/bogota] Revert "Restore STUN functionality (#4312)"

---

packages/avado/releases.json
packages/connect/package.json
packages/core-ethereum/package.json
packages/core/docs/classes/default.md
packages/core/docs/modules.md
packages/core/package.json
packages/cover-traffic-daemon/package.json
packages/ethereum/package.json
packages/hoprd/package.json
packages/real/package.json
packages/utils/docs/classes/HoprDB.md
packages/utils/package.json

Mergeback staging bogota/v1.91.20

---

.processes/wallets.md
scripts/testnet.sh

Backport of some changes from #4404 
This ensures the nodes in Bogota are funded when needed.

[hotfix/bogota] ci: Improve faucet min balance handling

---

.processes/wallets.md
CHANGELOG.md
packages/avado/releases.json
packages/core-ethereum/src/constants.ts
packages/core-ethereum/src/ethereum.ts
scripts/testnet.sh

Generate Bogota v1.91.22
Includes #4425

Release update bogota/v1.91.22

---

packages/avado/releases.json
packages/connect/package.json
packages/core-ethereum/package.json
packages/core/package.json
packages/cover-traffic-daemon/package.json
packages/ethereum/package.json
packages/hoprd/package.json
packages/real/package.json
packages/utils/package.json

Refs https://github.com/hoprnet/hoprnet/issues/4275

Mergeback staging bogota/v1.91.22

---

CHANGELOG.md
packages/core-ethereum/src/index.ts
packages/utils/src/db/db.ts

Cherry pick ticket redemption fixes for Valencia

---

CHANGELOG.md
packages/core-ethereum/src/index.ts
packages/utils/src/db/db.ts
scripts/setup-local-cluster.sh

+ Fixed use of pluto on playground.hoprnet.org
+ cherry-picks from Bogota release that fix Ticket Redemption

Release valencia hotfix/pluto init script

---

packages/avado/releases.json
packages/connect/package.json
packages/core-ethereum/package.json
packages/core/package.json
packages/cover-traffic-daemon/package.json
packages/ethereum/package.json
packages/hoprd/package.json
packages/real/package.json
packages/utils/package.json

Staging update after upgrading Bogota to 1.91.23

Staging upgrade bogota/v1.91.23

---

CHANGELOG.md
packages/avado/releases.json
packages/utils/src/db/db.ts
scripts/setup-local-cluster.sh

Some of the recent changes on Valencia cannot be applied to `master` anymore because those files don't exist anymore. Therefore, we will need to make sure that these fixes are done separately on `master` if needed.\
Refs #4037

Merge back #8 for release Valencia

---

packages/hoprd/Dockerfile
scripts/toolchain/install-toolchain.sh

Fixes build issue, see https://github.com/hoprnet/hoprnet/actions/runs/3704857880/jobs/6278499804

toolchain: Fix version output at the end

---

packages/core/src/index.ts

Fixes an incorrect if condition introduced by #4454

Fix typo in #4454

---

flake.lock
rust-toolchain.toml

This allows use of `rust-analyzer`.

toolchain: Add rust-src

---

packages/avado/releases.json
packages/connect/package.json
packages/core-ethereum/package.json
packages/core/docs/classes/default.md
packages/core/docs/enums/NetworkHealthIndicator.md
packages/core/docs/modules.md
packages/core/package.json
packages/cover-traffic-daemon/package.json
packages/ethereum/package.json
packages/hoprd/package.json
packages/real/package.json
packages/utils/docs/modules.md
packages/utils/package.json

Update staging after pushing 1.91.24 out.

Staging Upgrade for Release Bogota/v1.91.24

---

packages/hoprd/package.json
yarn.lock

removes now obsolete `yargs` dependency from `hoprd`

remove yargs

---

package.json

Cargo clean

---

.github/workflows/deploy.yaml
.github/workflows/docs.yaml
scripts/publish-version.sh

Fixes an issue during publishing the npm packages: https://github.com/hoprnet/hoprnet/actions/runs/3985798997/jobs/6833613929

ci: Don't wait for ethereum package

---

.dockerignore
.github/workflows/deploy.yaml
.github/workflows/docs.yaml
.github/workflows/e2e.yaml
.github/workflows/lint.yaml
.github/workflows/test.yaml
.gitignore
cloudbuild.yaml
packages/hoprd/Dockerfile
packages/hoprd/src/index.ts

Also include some other minor build fixes.

cli: use exit code 0 for version and help

---

RUST_WASM.md

More improvements, as the title says.

Added more examples and improved guidelines

---

test/security-test.sh

This PR fixes the security tests to expect correct HTTP status codes on errors.

Improvements in Capability based API

---

scripts/setup-gcloud-cluster.sh

Bugfix deployment riga

---

README.md
scripts/setup-gcloud-cluster.sh

Dummy PR with renaming a variable

Devops - create staging branch

---

Cargo.lock
packages/hoprd/crates/hoprd-misc/Cargo.toml
packages/hoprd/crates/hoprd-misc/src/cli.rs
packages/hoprd/src/identity.spec.ts
packages/hoprd/src/identity.ts

Fixes private key parsing from CLI argument string to Ethers.js Wallet instance

Fix incorrect private key parsing

---

packages/hoprd/src/api/v2/paths/fundmulti/index.ts

Correct outgoing amount and incoming amount order

Fix order of outgoing and incoming amount in fund command

---

packages/core/src/index.ts

Correct the merge error. 
Fixes https://github.com/hoprnet/hoprnet/issues/4606 and e2e test

Fix merge error in channel closure

---

scripts/run-local-anvil.sh
scripts/setup-local-cluster.sh

Starts Anvil listening on `0.0.0.0:8545`, instead `127.0.0.1:8454`
Refs https://github.com/Rpc-h/RPCh/issues/195

Make Anvil listen on all addresses

---

package.json
yarn.lock

fix CI pipeline, see https://github.com/hoprnet/hoprnet/actions/runs/4194945802

add missing ethersproject dependency

---

packages/connect/src/base/stun/tcp/constants.ts
packages/connect/src/base/stun/udp/constants.ts

Fix incorrect STUN URL

---

.gitattributes
vendor/cargo/adler-1.0.2/CHANGELOG.md

Update .gitattributes to ignore vendor directory changes

---

packages/hoprd/Dockerfile

Revert PR 4687 as it has been created a new docker image

---

packages/utils/crates/utils-metrics/src/metrics.rs

Fix metrics exports so that they are properly imported by different environments specifying WASM and non-WASM bindings.

Fix export for metrics objects

---

CHANGELOG.md
README.md
docs/hopr-documentation/docs/node/using-hopr-admin.md
docs/hopr-documentation/versioned_docs/version-v1.85/node/using-docker.md
docs/hopr-documentation/versioned_docs/version-v1.86/node/using-docker.md
docs/hopr-documentation/versioned_docs/version-v1.87/node/using-docker.md
docs/hopr-documentation/versioned_docs/version-v1.90/node/using-docker.md
docs/hopr-documentation/versioned_docs/version-v1.90/node/using-hopr-admin.md
docs/hopr-documentation/versioned_docs/version-v1.91/node/using-docker.md
docs/hopr-documentation/versioned_docs/version-v1.91/node/using-hopr-admin.md
packages/connect/package.json
packages/connect/src/base/listener.ts
packages/connect/src/base/stun/index.ts
packages/connect/src/base/stun/types.ts
packages/connect/src/base/stun/udp/client.ts
packages/connect/src/index.ts
packages/connect/src/utils/addressSorters.ts
packages/core-ethereum/package.json
packages/core/package.json
packages/core/src/index.ts
packages/core/src/main.ts
packages/cover-traffic-daemon/Dockerfile
packages/ethereum/contracts/contracts-addresses.json
packages/hoprd/Dockerfile
packages/hoprd/package.json
packages/real/package.json
packages/utils/package.json

Release update riga/v1.92.12

---

yarn.lock

Regenerates `yarn.lock` file such that Vercel can deploy assets

fix docs build

---

packages/core/crates/core-network/src/network.rs

Rust-based `Network` had minor inconsistencies and was not easily configurable using an external object.

Update network logic and fix inconsistencies

---

Makefile
docs/hopr-documentation/docs/node/grafana-dashboards.md
docs/hopr-documentation/versioned_docs/version-v1.92/node/grafana-dashboards.md
docs/hopr-documentation/versioned_docs/version-v1.92/node/using-docker.md
packages/core/src/index.ts
packages/core/src/interactions/packet/forward.ts
packages/hoprd/src/api/v2/paths/node/metrics.ts
packages/utils/crates/utils-metrics/README.md
packages/utils/src/index.ts

Fixes issues seen in https://github.com/hoprnet/hoprnet/actions/runs/4466427296/jobs/7844602597

ci: Fix PATH usage when it includes spaces

---

.github/workflows/deploy.yaml

Fixes issue seen in CI: https://github.com/hoprnet/hoprnet/actions/runs/4481064799/jobs/7877820050

ci: Add missing nix step

---

packages/cover-traffic-daemon/Dockerfile
packages/hoprd/Dockerfile

Fixes a Docker build issue introduced in #4750

docker: Remove deleted file from image

---

packages/hoprd/src/api/token.spec.ts
packages/hoprd/src/api/token.ts

Closes https://github.com/hoprnet/hoprnet/issues/4755
- Add LimitType for `calls` in `Limit`
- Keep other capabilities when updating token in storage.
- Add test for scenario reported in #4755

Update token for capabilities independently

---

.actrc
.github/workflows/deploy.yaml
.github/workflows/docs.yaml
.github/workflows/e2e.yaml
.github/workflows/lint.yaml
.github/workflows/test.yaml
Makefile

Fixes https://github.com/hoprnet/hoprnet/actions/runs/4547741851/jobs/8017997418?pr=3842

ci: Fix docs generation

---

.github/workflows/deploy.yaml
.github/workflows/e2e.yaml
.github/workflows/test.yaml
Makefile

Fixes CI issues:
https://github.com/hoprnet/hoprnet/actions/runs/4597636347/jobs/8120603806
https://github.com/hoprnet/hoprnet/actions/runs/4576997352/jobs/8082895375

ci: Fix invocation of test runs

---

.github/workflows/deploy.yaml
.github/workflows/e2e.yaml
.github/workflows/test.yaml
Makefile

Fix similar issues (https://github.com/hoprnet/hoprnet/actions/runs/4628689421) in runners that's been fixed in https://github.com/hoprnet/hoprnet/pull/4833

Port changes in PR#4833 to release Bratislava to unblock CICD

---

.github/workflows/deploy.yaml
.github/workflows/docs.yaml
.github/workflows/e2e.yaml
.github/workflows/lint.yaml
.github/workflows/test.yaml

Fix CI builds that use cachix by ignoring the errors.

Ignore errors if cachix fails

---

.github/workflows/deploy.yaml
.github/workflows/docs.yaml
.github/workflows/e2e.yaml
.github/workflows/lint.yaml
.github/workflows/test.yaml

Fix cachix to have working builds.

Fix cachix

---

packages/connect/package.json
packages/connect/src/webrtc/upgrader.ts
packages/core/src/channel-strategy.ts
yarn.lock

The WebRTC change did not appear to affect the daemon instability.

Revert webrtc change

---

rust-toolchain.toml
shell.nix

Update the base version of Rust

---

.github/workflows/deploy.yaml
.github/workflows/docs.yaml
.github/workflows/e2e.yaml
.github/workflows/lint.yaml
.github/workflows/test.yaml

Fix cachix nix install by updating the github action.

Fix cachix install

---

.github/workflows/deploy.yaml
.github/workflows/docs.yaml
.github/workflows/e2e.yaml
.github/workflows/lint.yaml
.github/workflows/test.yaml

Fix cachix install on the `master` branch.

Fix cachix install using nix

---

Makefile
pyproject.toml
tests/hoprd_api.py
tests/requirements.txt
tests/test_integration.py

`ruff` is extremely fast and can detect almost all python lint rules, therefore is a welcome addition to the stack.

Add ruff linter for python code

---

packages/hopli/src/environment_config.rs
packages/hopli/src/identity_input.rs
packages/hopli/src/initialize_node.rs
packages/hopli/src/password.rs
packages/hopli/src/process.rs

Some minor stuff spotted mostly by a linter.
Feel free to improve/change.

Small code-style improvements to `hopli`

---

packages/ethereum/README.md
packages/ethereum/contracts/src/stake/HoprStakeSeason7.sol
packages/ethereum/contracts/test/stake/HoprStakeSeason7.t.sol

Include staking season 7 contracts https://github.com/hoprnet/hopr-devrel/issues/326
This PR is save to merge. The update to `protocol-config` is in a separate PR https://github.com/hoprnet/hoprnet/pull/4907

Staking Season 7 contracts

---

scripts/toolchain/install-toolchain.sh

Remove additional -- in install-toolchain.sh

---

packages/avado/releases.json
packages/connect/package.json
packages/core-ethereum/package.json
packages/core/docs/classes/PeerStatus.md
packages/core/docs/classes/ResolvedEnvironment.md
packages/core/docs/classes/StrategyTickResult.md
packages/core/docs/classes/default.md
packages/core/docs/modules.md
packages/core/package.json
packages/hoprd/docs/modules.md
packages/hoprd/package.json
packages/real/package.json
packages/utils/docs/classes/MultiCounter.md
packages/utils/docs/classes/MultiGauge.md
packages/utils/docs/classes/MultiHistogram.md
packages/utils/docs/classes/SimpleCounter.md
packages/utils/docs/classes/SimpleGauge.md
packages/utils/docs/classes/SimpleHistogram.md
packages/utils/docs/classes/SimpleTimer.md
packages/utils/docs/enums/DialStatus.md
packages/utils/docs/modules.md
packages/utils/package.json
scripts/toolchain/install-toolchain.sh

Staging upgrade Release Bratislava

---

CHANGELOG.md
packages/connect/src/base/listener.ts
packages/connect/src/base/stun/index.ts
packages/connect/src/base/stun/types.ts
packages/connect/src/base/stun/udp/client.ts
packages/connect/src/index.ts
packages/connect/src/utils/addressSorters.ts
packages/core/src/index.ts
packages/core/src/main.ts
packages/hoprd/docs/modules.md
packages/utils/docs/modules.md

Ports missing changes from Riga (`1.92.10` to `1.92.12`) to `master`. See #4888 for reference

forward-port #4714

---

packages/ethereum/contracts/test/HoprNetworkRegistry.t.sol
packages/ethereum/contracts/test/proxy/HoprDummyProxyForNetworkRegistry.t.sol
packages/ethereum/contracts/test/stake/HoprStakeSeason7.t.sol

Similar fuzzy test may fail in master, as in `staging/bratislava`, see https://github.com/hoprnet/hoprnet/actions/runs/4819865662
Port fixes in https://github.com/hoprnet/hoprnet/pull/5006 to master
Fixes tests due to changes in foundry https://github.com/foundry-rs/foundry/pull/4827

hotfix fuzzy test

---

CHANGELOG.md
package.json
packages/core/crates/core-network/src/core.rs
packages/core/src/index.ts
packages/hoprd/package.json
packages/hoprd/src/api/v2.ts
packages/hoprd/src/api/v2/paths/messages/websocket.ts
scripts/fixture_local_test_setup.sh
scripts/utils.sh
tests/conftest.py
tests/pytest.ini
tests/requirements.txt
tests/test_integration.py
tests/test_websocket_api.py
yarn.lock

Fixes #4646
This PR fixes locations of some log files used in the smoke tests and adds an additional log file which can be tailed during a running smoke tests.
Test coverage of the send message functionality is added as a smoke test.

api: Add send message over web socket support

---

Cargo.lock
packages/core/crates/core-crypto/Cargo.toml
packages/core/crates/core-crypto/src/errors.rs
packages/core/crates/core-crypto/src/types.rs
packages/core/crates/core-types/Cargo.toml
packages/core/crates/core-types/src/account.rs
packages/core/crates/core-types/src/acknowledgement.rs
packages/core/crates/core-types/src/channels.rs
packages/utils/crates/utils-types/Cargo.toml
packages/utils/crates/utils-types/src/primitives.rs

This PR adds various improvements and fixes to `core-types` and `utils-types` crates.
Namely:
- added unit tests
- added TS bindings for type methods
- added missing functions needed in TS
This is cherry-pick (and prerequisite) for #5039

Cherry-pick Rust type improvements

---

CHANGELOG.md
packages/avado/build/supervisord.conf
packages/avado/docker-compose.yml

Increase the limit to make restarts less often.

Increase memory limit for Avado to 2GB

---

flake.lock
rust-toolchain.toml

Update the nix environment

---

packages/connect/package.json
packages/core-ethereum/package.json
packages/core/package.json
packages/hoprd/package.json
packages/real/package.json
packages/utils/package.json
rustfmt.toml
shell.nix

This will also fix issues seen on `master` in the deploy workflow: https://github.com/hoprnet/hoprnet/actions/runs/5022497419/jobs/9006023853

Bump to v2.0.0-next.0

---

packages/core/package.json
packages/core/src/index.ts
yarn.lock

The profiler on GCP is not used anymore.

core: Remove gcloud profiler

---

packages/ethereum/contracts/src/node-stake/NodeSafeRegistry.sol

eip712 signing structs

---

packages/ethereum/contracts/src/Announcements.sol

Rename import path to make `forge test` pass

rename oz 4.8.3 lib import

---

tests/requirements.txt

Fix Python test requirements conflict.

Fix test requirements dependency conflict

---

Makefile
shell.nix

Improvements to the failed nix setup.

Fix Darwin environment setup

---

.github/workflows/docs.yaml
.github/workflows/e2e.yaml
.github/workflows/test.yaml
Cargo.lock
Makefile
packages/core-ethereum/crates/core-ethereum-db/Cargo.toml
packages/core-ethereum/crates/core-ethereum-misc/Cargo.toml
packages/core/crates/core-crypto/Cargo.toml
packages/core/crates/core-packet/Cargo.toml
shell.nix

Improvements for migrate core ethereum db callbacks

---

.github/workflows/e2e.yaml
.github/workflows/lint.yaml

Introduce self-hosted runners for compute demanding activity

---

packages/ethereum/contracts/src/Channels.sol

some ABI changes + bugfix in Balance modifier

channels wip

---

packages/utils/src/db/db.ts

some refactoring + in-code documentation

some cleanup

---

scripts/compose/.env
scripts/compose/docker-compose.yml

compose: Fix env vars to work with bratislava

---

.github/workflows/draft.yaml

TESTING EVENT OF OPENING A PR

---

scripts/check-pr.sh

Fixes https://github.com/hoprnet/hoprnet/actions/runs/5487307228/jobs/9998588249

scripts: Fix typo

---

.vscode/settings.json
packages/core/crates/core-network/src/messaging.rs

Development environment fixes.

Remove obsolete configuration from the .vscode settings

---

packages/ethereum/contracts/test/node-stake/NodeSafeRegistry.t.sol
packages/ethereum/contracts/test/utils/Precompiles.sol

filter *all* known precompiles

filter precompile addresses

---

packages/ethereum/contracts/contracts-addresses.json
packages/ethereum/contracts/script/DeployAll.s.sol
packages/ethereum/contracts/script/utils/NetworkConfig.s.sol
packages/ethereum/contracts/src/TicketPriceOracle.sol
packages/ethereum/contracts/src/node-stake/NodeSafeRegistry.sol
packages/ethereum/contracts/src/node-stake/permissioned-module/CapabilityPermissions.sol
packages/ethereum/contracts/src/node-stake/permissioned-module/NodeManagementModule.sol
packages/ethereum/contracts/src/utils/TargetUtils.sol
packages/ethereum/contracts/test/TicketPriceOracle.t.sol
packages/ethereum/contracts/test/node-stake/NodeSafeRegistry.t.sol

Implements the smart contract for https://github.com/hoprnet/hoprnet/issues/5147
The oracle is simple, exposing a single setter/getter function pair and event upon update.
Also adds a helper getter function for https://github.com/hoprnet/hoprnet/issues/5249

sc: Add HoprTicketPriceOracle

---

docs/sc-audit-08-2023/docs/01-overview.md

adds documentation about of the protocol for the upcoming audit

audit documentation

---

packages/ethereum/contracts/src/Channels.sol
packages/ethereum/contracts/src/node-stake/NodeSafeRegistry.sol
packages/ethereum/contracts/src/proxy/SafeProxyForNetworkRegistry.sol
packages/ethereum/contracts/test/Channels.t.sol

changes:
- always bumps sigNonce, meaning any change breaks validity of a signature

minor SC fixes after audit fixes

---

scripts/compose/prometheus/prometheus.local-dev.yml
scripts/compose/prometheus/prometheus.yml
scripts/deploy-rotsee-nodes.sh
scripts/deploy.sh
scripts/get-hopr-address.sh
scripts/init-gitpod.sh
scripts/setup-local-cluster.sh
scripts/utils.sh

This is a temporary helper script to deploy Rotsee nodes on a set of pre-created VMs which are accessible via `ssh`.

ops: Add script to manually deploy rotsee nodes

---

.github/workflows/merge.yml
packages/hoprd/README.md

Makes the docker image tagging conditional work properly based on whether an image was actually built too.

gha: Fix docker image tagging

---

packages/core-ethereum/src/index.ts

Fix build by removing unused import

Remove unused import

---

packages/ethereum/contracts/Makefile

Makefile variable definition had wrong indentation.

Proper indentation in the Makefile

---

packages/core/src/main.ts
packages/hoprd/src/api/v3/paths/messages/index.integration.spec.ts
packages/hoprd/src/api/v3/paths/messages/index.ts
packages/hoprd/src/api/v3/paths/messages/pop-all.spec.ts
packages/hoprd/src/api/v3/paths/messages/pop-all.ts
packages/hoprd/src/api/v3/paths/messages/pop.spec.ts
packages/hoprd/src/api/v3/paths/messages/pop.ts
packages/hoprd/src/api/v3/paths/messages/size.spec.ts
packages/hoprd/src/api/v3/paths/messages/size.ts

Added full test coverage of those endpoints.
Also fixed an issue during startup where a non-existing safe or module address in the db would lead to a `undefined` crash.
Refs #5182

api: Fixed bugs in messages endpoints

---

packages/core-ethereum/crates/core-ethereum-indexer/src/handlers.rs
packages/core-ethereum/crates/core-ethereum-misc/src/chain.rs
packages/core-ethereum/src/index.ts

- Add missing linkage between packet key and chain key in the Annoucement event
- Fixes code style issues

Fix key linkage on announcement and other tweaks

---

Makefile
packages/ethereum/contracts/script/SingleAction.s.sol
packages/ethereum/contracts/src/node-stake/NodeSafeRegistry.sol
packages/ethereum/contracts/src/node-stake/NodeStakeFactory.sol
packages/ethereum/contracts/src/utils/TargetUtils.sol
packages/ethereum/contracts/test/Channels.t.sol
packages/ethereum/contracts/test/node-stake/NodeSafeRegistry.t.sol
packages/ethereum/contracts/test/proxy/SafeProxyForNetworkRegistry.t.sol
packages/utils/src/libp2p/index.ts
tests/test_integration.py

Trying to get CI to be green again.

fmt: Making linter happy

---

packages/hoprd/rest-api-v3-spec.yaml
packages/hoprd/src/api/token.spec.ts
packages/hoprd/src/api/token.ts
packages/hoprd/src/api/v3.ts
packages/hoprd/src/api/v3/paths/account/addresses.ts
packages/hoprd/src/api/v3/paths/account/withdraw.integration.spec.ts
packages/hoprd/src/api/v3/paths/account/withdraw.ts
packages/hoprd/src/api/v3/paths/aliases/index.integration.spec.ts
packages/hoprd/src/api/v3/paths/aliases/index.ts
packages/hoprd/src/api/v3/paths/messages/index.integration.spec.ts
packages/hoprd/src/api/v3/paths/messages/index.ts
packages/hoprd/src/api/v3/paths/messages/websocket.ts
packages/hoprd/src/api/v3/paths/node/info.integration.spec.ts
packages/hoprd/src/api/v3/paths/peers/{peerid}/index.spec.ts
packages/hoprd/src/api/v3/paths/token.integration.spec.ts
packages/hoprd/src/api/v3/paths/tokens/index.integration.spec.ts
packages/hoprd/src/api/v3/paths/tokens/{id}.integration.spec.ts

This PR completes the API v3 migration and all `hoprd` unit tests are green.
Refs #5182

api: Fix remaining endpoints

---

.github/workflows/lint-optional.yaml
.github/workflows/lint.yaml
packages/core-ethereum/src/ethereum.ts
packages/core-ethereum/src/index.ts
packages/core-ethereum/src/utils/utils.ts
packages/core/crates/core-network/src/network.rs
packages/core/crates/core-packet/src/validation.rs
packages/core/crates/core-types/src/acknowledgement.rs
packages/core/src/network.ts
packages/ethereum/contracts/test/Channels.t.sol
packages/hoprd/src/api/v3.ts
packages/hoprd/src/api/v3/paths/channels/{channelid}/index.ts
packages/hoprd/src/api/v3/paths/channels/{channelid}/tickets.ts
packages/hoprd/src/api/v3/paths/channels/{channelid}/tickets/redeem.ts
packages/utils/src/utils.spec.ts

This makes the full unit test setup pass and the linter should report green in the CI as well.

Fix all unit tests and linter errors

---

README.md
docs/sc-audit-08-2023/docs/02-response-to-preliminary-report.md
packages/core/src/main.ts

Add correct formatting to the Ed25519 private key when passed to libp2p

Format Ed25519 private key properly for libp2p

---

packages/hoprd/src/api/v3/paths/channels/index.ts

Fixed incorrect address usage

---

docs/sc-audit-08-2023/docs/03-response-to-second-preliminary-report.md
packages/ethereum/contracts/src/Channels.sol

Address audit report findings 5.1 and 5.2

sc: Fix ticket index check when redeeming tickets

---

packages/core-ethereum/crates/core-ethereum-indexer/src/handlers.rs
packages/core-ethereum/crates/core-ethereum-misc/src/chain.rs
packages/core-ethereum/src/ethereum.ts
packages/core-ethereum/src/indexer/index.ts

Built on top of https://github.com/hoprnet/hoprnet/pull/5362
- set `set_use_safe` after successful registration to NodeSafeRegistry
- Return payloads for module if safe/module is in usage

Create wrapped payload for transactions target to module

---

packages/core-ethereum/src/ethereum.ts
packages/core-ethereum/src/index.ts
packages/core-ethereum/src/indexer/index.ts

- adjust fund amount
- fix typo in callback

Bug fix on open channel

---

docs/sc-audit-08-2023/docs/03-response-to-second-preliminary-report.md
packages/ethereum/contracts/src/node-stake/permissioned-module/CapabilityPermissions.sol
packages/ethereum/contracts/src/node-stake/permissioned-module/NodeManagementModule.sol

- Change enforced order
- Add getters
Ref https://github.com/hoprnet/hoprnet/issues/5278

SC: address audit report and add getters

---

packages/core/crates/core-types/src/channels.rs
packages/hoprd/src/api/v3/paths/tickets/index.ts

update `formatTicket` for to use latest data

fix js ticket formating

---

packages/core/crates/core-types/src/channels.rs
packages/hoprd/rest-api-v3-spec.yaml
packages/hoprd/src/api/v3/fixtures.ts
packages/hoprd/src/api/v3/paths/channels/{channelid}/tickets.integration.spec.ts
packages/hoprd/src/api/v3/paths/tickets/index.ts

fix failing js unit test, resulting from legacy mocks

fix js fixture

---

packages/core-ethereum/crates/core-ethereum-indexer/Cargo.toml

Fix test build issue breaking the test build

---

packages/core/src/constants.ts
packages/core/src/index.ts
packages/hoprd/src/index.ts
scripts/fixture_local_test_setup.sh
tests/integration-test.sh

- Also let smoke tests run through multi-hop messages and close channels

hoprd: Move onboarding message

---

scripts/setup-local-cluster.sh

re https://github.com/hoprnet/hoprnet/pull/5424

fix script typo

---

packages/ethereum/contracts/script/SingleAction.s.sol

Make salt calculation more robust against collision

Avoid collision in nonce salt

---

packages/core/src/main.ts

Move DB into its own folder

---

docs/changelog/changelog-2.0.0-rc.3.md
packages/core-ethereum/crates/core-ethereum-indexer/src/handlers.rs
packages/core-ethereum/src/index.ts
packages/core/src/index.ts
packages/hoprd/src/api/v3/paths/account/balances.integration.spec.ts
packages/hoprd/src/api/v3/paths/account/balances.ts
packages/hoprd/src/api/v3/paths/channels/index.ts
pyproject.toml
scripts/api.sh
scripts/ldbdump.py
scripts/topologies/full_interconnected_cluster.sh
tests/integration-test.sh
tests/requirements.txt

- api: Make channels list endpoint more robust
- Add utility for inspecting LevelDB database
Fixes https://github.com/hoprnet/hoprnet/issues/5436
Fixes #5446

api: Expose safe allowance in balances endpoint

---

packages/core-ethereum/crates/core-ethereum-indexer/src/handlers.rs
packages/core/src/constants.ts
packages/hoprd/src/api/v3.ts

indexer: Reset channel balance on close

---

packages/core-ethereum/src/index.ts

core: Fix allowance check on open channel

---

.github/workflows/close-release.yaml
Makefile
scripts/generate-changelog.sh

Fixes build issue seen in https://github.com/hoprnet/hoprnet/actions/runs/6252299399/job/16975262161

gha: Unblock close release workflow by formatting only md

---

.github/workflows/merge.yaml

By adding Gcloud SDK in previous commit

Fixing merge pipeline

---

.github/workflows/load-tests.yaml
DAPPNODE_PUBLISH.md
scripts/pluto/Dockerfile

- Open the list host to the container
- Update DappNode publish procedure
- Fixing load testing pipeline

Open container ports for pluto image

---

tests/conftest.py

Fix missing format string in Python tests

---

packages/ethereum/contracts/src/static/stake/HoprStakeSeason8.sol
packages/ethereum/contracts/test/static/stake/HoprStakeSeason8.t.sol

Closes https://github.com/hoprnet/hopr-devrel/issues/333
Create contracts for staking season 8 and its tests

Add smart contract and tests for staking season 8

---

Cargo.lock
packages/core/crates/core-crypto/Cargo.toml
packages/core/crates/core-crypto/src/routing.rs
packages/core/crates/core-hopr/src/p2p.rs
packages/core/crates/core-packet/Cargo.toml
packages/core/crates/core-packet/src/packet.rs
packages/core/crates/core-protocol/Cargo.toml
packages/core/crates/core-protocol/src/msg/chain.rs
packages/core/crates/core-protocol/src/msg/mod.rs
packages/core/crates/core-protocol/src/msg/packet.rs
packages/core/crates/core-protocol/src/msg/processor.rs

Move operations to packet closer to chain processing to allow further optimizations.
Closes #5588

Simplify packet pipeline processing by adapting the Packet class

---

packages/core/crates/core-hopr/src/p2p.rs
packages/core/crates/core-protocol/src/msg/processor.rs

Not taken in the previous PR due to auto-merge.

Minor fmt fixes

---

.github/workflows/cleanup.yaml
packages/hoprd/src/index.ts
scripts/deploy.sh

- Modifies metric `hoprd_mgauge_version` to print the full semver.
- Improves deployment script to allow remove DB

Show full version on metrics

---

packages/core-ethereum/crates/core-ethereum-actions/src/channels.rs
packages/core-ethereum/crates/core-ethereum-actions/src/transaction_queue.rs
packages/core-ethereum/crates/core-ethereum-db/src/db.rs
packages/core-ethereum/src/ethereum.ts
packages/core/crates/core-hopr/src/lib.rs
packages/core/crates/core-strategy/src/promiscuous.rs
packages/core/crates/core-strategy/src/strategy.rs
packages/core/crates/core-types/src/channels.rs

- invalid deserialization of neglected ticket count caused premature failure of indexed TX handling
- reset ack ticket state on restart since we don't have tx persistence yet
- if redemption fails, make ticket Untouched again
- fix failure mode of sendTransaction function in TS
Fixes #5653

Fix TX processing bugs

---

.github/workflows/build-dappnode.yaml

Missing login to Artifact registry

Fix dappnode pipeline failing due to credentials missing

---

packages/core/crates/core-hopr/src/p2p.rs

Some of these logs were missing from the infrastructure to allow creating a better picture about what's going on.
Find out later why the debug logs are on in the libp2p package and how they propagate to WASM and stop them.

Add logs to p2p event mechanism

---

packages/core/src/constants.ts

Increases the DB version to start with a clean DB on the 2.0 release.

Bump the DB version

---

packages/core-ethereum/crates/core-ethereum-db/src/db.rs
packages/core/crates/core-hopr/src/lib.rs
packages/utils/crates/utils-db/src/db.rs
packages/utils/crates/utils-db/src/hashmap.rs
packages/utils/crates/utils-db/src/rusty.rs
packages/utils/crates/utils-db/src/traits.rs

This PR adds manual DB write (flush) after some operations where it was missing. It also adds periodic DB flushing each 90 seconds.
Refs #5673

Force flush on some DB operations

---

.github/workflows/build-dappnode.yaml
.github/workflows/merge.yaml
.github/workflows/promote-release.yaml
scripts/get-next-version.sh

- Fix bumping minor version
- Fix dappnode docker tag
- Fix promote workflow not finding branch

Fixing pipelines on bumping minor release

---

Cargo.lock
Cargo.toml
packages/core-ethereum/crates/Makefile
packages/core-ethereum/crates/core-ethereum-rpc/Cargo.toml
packages/core-ethereum/crates/core-ethereum-rpc/src/errors.rs
packages/core-ethereum/crates/core-ethereum-rpc/src/lib.rs

This is a ground work for RPC and Indexer migration work.

Add trait API for RPC operations

---

packages/core-ethereum/crates/core-ethereum-rpc/src/lib.rs

This PR updates the `HoprRpcOperations` methods

Update RPC trait

---

packages/hoprd/src/api/v3/paths/tickets/statistics.ts

Add back `pending` in ticket stats and set it to 0

---

packages/core-ethereum/crates/core-ethereum-rpc/src/lib.rs
packages/hoprd/crates/hopr-lib/data/protocol-config.json

Updates the API based on recent discussions and RPC provider capabilities.
Also update RPC provider URL for Gnosis.

Update RPC API

---

.github/workflows/build-anvil.yaml
.github/workflows/build-dappnode.yaml
.github/workflows/build-hopli.yaml
.github/workflows/build-hoprd.yaml
.github/workflows/build-pluto.yaml
.github/workflows/build-toolchain.yaml
.github/workflows/close-release.yaml
.github/workflows/k8s.yaml
.github/workflows/merge.yaml
.github/workflows/promote-release.yaml
scripts/bump-version.sh
scripts/get-current-version.sh
scripts/get-next-version.sh

This PR is a forward-port of the #5721 and #5727

Enable K8s deployment in providence versions

---

packages/core-ethereum/crates/core-ethereum-db/src/db.rs

More logging to identify where and if the cache sync breaks.

Extend db cache sync logs

---

.github/workflows/build-dappnode.yaml

Remove reviewers that are not collaborators on dappnode PR creation

---

packages/core-ethereum/crates/core-ethereum-actions/src/payload.rs

Explicitly set gas, so channel can be opened in local cluster

make max gas explicit for anvil

---

packages/core-ethereum/crates/core-ethereum-db/src/db.rs

Before the unrealized balance cache, which is used in ticket validation, would use both acked and unacked tickets. However, the aggregation strategy only considers acked tickets when calculating the unrealized balance thresholds. Thus, a channel could get into a state where new tickets are rejected and the aggregation won't start.
Refs #5737 
Refs #5767

core: Use only acknowledged tickets in unrealized balance calculation

---

packages/core/crates/core-p2p/src/lib.rs
packages/core/src/constants.ts

p2p: Increase concurrent connections to 1024

---

README.md
flake.nix

Nix environment setup instructions now in README.md

Update nix installation instructions

---

.dockerignore
packages/hoprd/.dockerignore
packages/hoprd/Dockerfile
scripts/toolchain/Dockerfile

- properly copies files required for Cargo vendoring into Docker image
- removes some legacy instructions

fix Docker build

---

packages/hoprd/.dockerignore
packages/hoprd/Dockerfile
scripts/toolchain/install-toolchain.sh

Ports #5852 from `master` to `release/providence` and such that Docker build works with latest `hopr-toolchain` Docker image

Fix Docker build with latest hopr-toolchain image

---

Cargo.lock
packages/core-ethereum/crates/core-ethereum-db/src/db.rs
packages/core-ethereum/crates/core-ethereum-indexer/src/handlers.rs
packages/core/crates/core-protocol/src/ticket_aggregation/processor.rs
packages/core/crates/core-strategy/src/promiscuous.rs
packages/hoprd/crates/hopr-lib/src/chain.rs
tests/test_integration.py

Merge-back of Providence Release 2.0.7+ to master

Merge back Providence to master

---

.github/workflows/build-docs.yaml

Enable workspace index generation, as described in https://github.com/rust-lang/cargo/issues/8229

Generate the workspace index.html

---

ethereum/README.md
ethereum/contracts/Makefile
ethereum/contracts/broadcast/DeployAll.s.sol/100/run-latest.json
ethereum/contracts/foundry.toml

Relates to https://github.com/hoprnet/hoprnet/issues/5876

Change the default RPC provider to https://gnosis-provider.rpch.tech/

---

hoprd/hoprd/src/cli.rs
hoprd/hoprd/src/config.rs
hoprd/hoprd/src/main.rs

Properly override boolean configuration files with CLI arguments

---

.github/workflows/lint.yaml
Makefile
flake.nix
hoprd/rest-api/src/lib.rs
tests/hopr.py
tests/requirements.txt

Closes https://github.com/hoprnet/hoprnet/issues/5943

Unify object naming in the hoprd rest api

---

ethereum/contracts/Makefile
ethereum/contracts/script/SingleAction.s.sol

Ensure `DEPLOYER_PRIVATE_KEY` is set
```
cd ethereum/contracts/
source .env
make manager-retry-register-nodes network=dufour environment-type=production node_addresses="[<paste_your_node_ethereum_address>]"
```

make: Add manager-retry-register-nodes

---

chain/actions/src/action_queue.rs
chain/actions/src/action_state.rs
chain/db/src/db.rs
chain/indexer/src/block.rs
chain/indexer/src/handlers.rs
chain/rpc/src/client.rs
chain/types/src/chain_events.rs
common/internal-types/src/channels.rs
common/primitive-types/src/traits.rs
hopr/hopr-lib/src/lib.rs
logic/path/src/channel_graph.rs
logic/strategy/src/aggregating.rs
logic/strategy/src/strategy.rs
misc/utils-db/src/sqlite.rs
transport/api/src/lib.rs
transport/api/src/timer.rs
transport/packet/src/validation.rs
transport/protocol/src/ack/processor.rs
transport/protocol/src/msg/processor.rs
transport/protocol/src/ticket_aggregation/processor.rs

This PR also adds and changes logging levels in various places

Fix parsing panic in `from_hex`

---

Cargo.lock
chain/indexer/Cargo.toml
chain/indexer/src/block.rs
hopr/hopr-lib/src/lib.rs
hopr/hopr-lib/tests/chain_integration_tests.rs
hoprd/hoprd/src/main.rs

Fixes to code exeuction and real-world run optimizations

---

METRICS.md
scripts/compose/grafana/provisioning/dashboards/hopr/hoprd-grafana-dashboard.json
scripts/compose/prometheus/prometheus.yml
transport/network/src/heartbeat.rs
transport/network/src/ping.rs

Fix the docker-compose setup to comply with 2.1

---

transport/protocol/src/msg/mixer.rs

fix randomly failing mixer test

---

Cargo.lock
flake.lock

Update the nix environment and the package lock

---

hoprd/hoprd/src/config.rs

Relax the limitation to strictly check existence of the hoprd identity from the configuration

---

hopr/hopr-lib/src/config.rs
hoprd/hoprd/src/config.rs
hoprd/inbox/src/config.rs
hoprd/rest-api/src/config.rs
logic/strategy/src/strategy.rs
tests/hopr-smoke-test-node_5.cfg.yaml
transport/api/src/config.rs
transport/network/src/heartbeat.rs
transport/network/src/network.rs
transport/protocol/src/config.rs

Fixes https://github.com/hoprnet/hoprnet/issues/5996

Enforce strict configuration file parsing to deny unknown keys

---

chain/rpc/src/indexer.rs

Panics when unrecoverable RPC error occurs during processing of block batch.
Fixes #6038

Terminate Indexer processing loop on hard failure

---

hopr/hopr-lib/src/lib.rs
hoprd/rest-api/src/lib.rs
logic/strategy/src/aggregating.rs
transport/api/src/lib.rs
transport/api/src/p2p.rs
transport/api/src/processes/indexer.rs

Decrease the scope of some RwLocks

---

METRICS.md
ethereum/contracts/foundry.toml
flake.nix
transport/api/src/p2p.rs
transport/p2p/src/api.rs
transport/p2p/src/constants.rs

Minor tweaks to improve the readability and parsability of the node.

Improve visbility into code hot paths using metrics and logs

---

Cargo.lock
transport/packet/Cargo.toml
transport/packet/src/validation.rs
transport/protocol/src/msg/processor.rs

Collection of fixes to scoping and locks for the DB

---

.github/workflows/build-dappnode.yaml
.github/workflows/build-docs.yaml
.github/workflows/build.yaml
.github/workflows/clean-pr.yaml
.github/workflows/cleanup.yaml
.github/workflows/close-release.yaml
.github/workflows/generate-sdk.yaml
.github/workflows/k8s.yaml
.github/workflows/latexcompile.yaml
.github/workflows/lint.yaml
.github/workflows/load-tests.yaml
.github/workflows/merge.yaml
.github/workflows/new-pr.yaml
.github/workflows/open-release.yaml
.github/workflows/promote-release.yaml
.github/workflows/publish-release.yaml
.github/workflows/renovate-cargo-update.yaml
.github/workflows/tests.yaml
.github/workflows/update-flake-lock.yaml
scripts/get-next-version.sh

Modify the github runners from hetzner to GCP

Change github runners from Hetzner to GCP

---

hoprd/rest-api/src/lib.rs

Fix return code for set alias API call

---

.github/labeler.yml
.github/workflows/label.yaml

Add automatic labeling mechanism for PRs.

Add support for PR labeling

---

hoprd/rest-api/src/lib.rs

Add more info to the payload of pop-all and peek-all in swagger of messages

Add more info to the payload of pop-all and peek-all in swagger of messages

---

tests/test_hopli.py
transport/api/src/lib.rs
transport/api/src/p2p.rs
transport/network/src/errors.rs
transport/network/src/heartbeat.rs
transport/network/src/ping.rs

Fix logging issues to make the log output more readable.

Fix minor logging issues to make the info output more readable

---

hoprd/rest-api/src/lib.rs

- adds `INVALID_ADDRESS` error code for open channel
- adds fund channel error when not enough balance/safe allowance
Closes #6163
Closes #6164

Fix error codes on certain API endpoints

---

chain/indexer/src/handlers.rs

Add log information when node gets registered

---

hopli/src/environment_config.rs
tests/test_hopli.py

Reduce execution time for integration test

Reduce hopli default provider tx poll interval from 7s to 10 ms

---

Cargo.lock
hopr/hopr-lib/Cargo.toml

Open Release 2.1.0-rc.4

---

db/api/src/info.rs
hopr/hopr-lib/src/lib.rs
logic/path/src/channel_graph.rs
logic/strategy/src/promiscuous.rs

`node_info` table didn't have proper upserts to populate the table for the first time.
Also when a node was pre-registered, the node safe info was not populated, since the code path did not execute
Refs https://github.com/hoprnet/hoprnet/issues/6187

Fix updating node info table

---

db/api/src/db.rs

This PR increases the size of all 3 connection pools to 30 connections each (previously was 10 each).
Closes #6212

Increase size of the DB connection pool

---

chain/rpc/src/client.rs
hopr/hopr-lib/tests/chain_integration_tests.rs

Adds logging of full RPC request/responses in the `TRACE` level

Log RPC request/response JSON

---

common/internal-types/src/account.rs
db/api/src/db.rs

Sets more parameters in the database connection pools.
Refs #6212

Add more connection pool parameters

---

Cargo.lock
README.md
docs/changelog/changelog-2.1.0.md
hopr/hopr-lib/src/lib.rs
hoprd/hoprd/src/config.rs
hoprd/rest-api/Cargo.toml

changelog: Add changelog for v2.1.0

---

Cargo.lock
hopr/hopr-lib/Cargo.toml

Prepare version 2.1.1

---

flake.nix

Update the merge script dependencies

---

.github/workflows/build-dappnode.yaml
.github/workflows/close-release.yaml
.github/workflows/load-tests.yaml
.github/workflows/merge.yaml

Execute several load tests to find the hardware requirements limits of nodes.

Find hardware requirement limits on node

---

common/network-types/src/frame.rs
common/network-types/src/lib.rs

The auto-merge on the #6295 PR was faster than my push.

Add missing docs to Frame reassembly

---

.github/workflows/merge.yaml
scripts/get-next-version.sh

This PR publishes the docker image into the docker hub registry

Publishing to docker hub

---

.github/workflows/build-dappnode.yaml

Creates the dappNode PR from the upstream project

Fix dAppNode packaging

---

hoprd/rest-api/src/lib.rs

Backwards compatible extension of the API to allow it to ingest byte sequence, as well as a string from the `send_message` request body.

Add the ability to process bytes from the api to send message

---

common/internal-types/src/tickets.rs

Correctly assigned self.vrf_params instead of the default parameters. Additionally, the ticket_entire_ticket_transfer_flow test has been implemented. This test ensures the transfer and redemption of tickets is working as intended by validating all stages including acknowledgment and conversion.
This problem didn't have any real consequence.

Update ticket handling and add tests

---

deploy/compose/.env-secrets.sample
deploy/compose/.env.example
deploy/compose/.gitignore
deploy/compose/README.md
deploy/compose/docker-compose.yml
deploy/compose/grafana/provisioning/dashboards/hopr/hoprd-grafana-dashboard.json
deploy/compose/grafana/provisioning/datasources/datasource.yml
deploy/compose/hoprd.cfg.yaml
deploy/compose/prometheus/metricspusher.sh
deploy/compose/prometheus/prometheus.yml
hopli/src/safe_module.rs

Fixes the deployment using docker compose by testing the monitoring and improving documentation
- The hoprd volume had incorrect path
- The prometheus push gateway was not working
- Added more detailed documentation on how to run
- The fixed hashed image tags were not suitable for other platforms
- Externalise the sensitive data (HOPRD_API_TOKEN) from the config file so it can be used as well from Prometheus gateway
- Updated the grafana dashboards so the user can see a working hoprd dashboard

Fixing the docker compose deployment setup

---

hoprd/hoprd/src/main.rs

Fix log output to be only a single line

---

.github/workflows/generate-dappnode-pr.yaml
.github/workflows/k8s.yaml
.github/workflows/merge.yaml

First approach for building dappnode on labeling PR

Add building dappnode

---

.github/scripts/immutable-files-check.sh
flake.nix

Add check for immutable file commit

---

.github/workflows/merge.yaml

Improves the merge workflow to add a notification to Ronny when the deploy folder has changed

Notify ronny when there are changes in deploy folder

---

.github/workflows/load-tests.yaml

Allows to run incremental load tests in K6

Allow incremental workload load testing

---

.github/workflows/README.md
.github/workflows/load-tests.yaml
.github/workflows/merge.yaml

Allow to execute a new scenario where to deliver all messages to a single relayer.

Allow relayer scenario for load testing

---

.github/workflows/README.md
.github/workflows/load-tests.yaml
.github/workflows/merge.yaml

Add sender sceanario and hysteresis workload on load testing

Add sender sceanario and hysteresis workload on load testing

---

Makefile
README.md
SETUP_LOCAL_CLUSTER.md
chain/indexer/src/block.rs
db/api/src/info.rs
db/api/src/peers.rs
db/migration/src/lib.rs
db/migration/src/m20240226_000005_index_create_chain_info.rs
db/migration/src/m20240810_000013_index_extend_chain_info_with_pre_checksum_block.rs
hopr/hopr-lib/src/lib.rs
hopr/hopr-lib/tests/chain_integration_tests.rs
hoprd/rest-api/src/lib.rs
scripts/api.sh
scripts/local-cluster-hoprd.cfg.yaml
scripts/run-local-anvil.sh
scripts/setup-local-cluster.sh
scripts/utils.sh

Add a new field in `get_last_indexed_block` and update the return structure of `info` endpoint
Closes https://github.com/hoprnet/hoprnet/issues/6440
Sample return:
```json
{
"announcedAddress": [
"/ip4/127.0.0.1/tcp/19091"
],
"chain": "anvil",
"channelClosurePeriod": 15,
"connectivityStatus": "Green",
"hoprChannels": "0x9a9f2ccfde556a7e9ff0848998aa4a0cfd8863ae",
"hoprManagementModule": "0xa51c1fc2f0d1a1b8494ed1fe312d7c3a78ed91c0",
"hoprNetworkRegistry": "0x3aa5ebb10dc797cac828524e59a333d0a371443c",
"hoprNodeSafe": "0x6a64fe01c3aba5bdcd04b81fef375369ca47326f",
"hoprNodeSafeRegistry": "0x0dcd1bf9a1b36ce34237eeafef220932846bcd82",
"hoprToken": "0x9a676e781a523b5d0c0e43731313a708cb607508",
"indexBlockPrevChecksum": 70,
"indexerBlock": 126,
"indexerChecksum": …
```

Modify info api endpoint to return last block before the update of checksum

---

scripts/setup-local-cluster.sh

Fix setup-local-cluster script execution

---

ethereum/contracts/src/Channels.sol
ethereum/contracts/src/Crypto.sol
ethereum/contracts/src/NetworkRegistry.sol
ethereum/contracts/src/node-stake/NodeSafeRegistry.sol
ethereum/contracts/src/node-stake/permissioned-module/CapabilityPermissions.sol
ethereum/contracts/src/node-stake/permissioned-module/NodeManagementModule.sol
ethereum/contracts/src/proxy/SafeProxyForNetworkRegistry.sol
ethereum/contracts/src/static/HoprToken.sol
ethereum/contracts/src/static/stake/HoprBoost.sol
ethereum/contracts/test/Crypto.t.sol
ethereum/contracts/test/node-stake/NodeSafeRegistry.t.sol
flake.lock
flake.nix

- Fix EC doubling calculation
- Remove deprecated library usage

Response to audit 20240826

---

tests/test_session.py

- Further improve the conditions under which the UDP packets are sorted in the test case - that is also for the situations in which they arrive completely unordered.
- Improve error handling in the `fetch_data` function

Improve Session UDP tests

---

chain/indexer/src/constants.rs
chain/indexer/src/handlers.rs
rustfmt.toml

Do not use the nightly features for rustfmt

---

chain/indexer/src/handlers.rs

As in title.
This fixes broken E2E tests not starting.

Fix failing sync due to missing winning probability SC address

---

logic/strategy/src/auto_redeeming.rs

Fix the default min_redeem_hopr value to 0.09 wxHOPR

---

transport/p2p/src/lib.rs

Increase the max number of streams for yamux

---

README.md

Close #6471
Redirect root README to the docker-compose deployment README

Update readme on docker compose

---

flake.lock
rust-toolchain.toml

More information on changes in: https://blog.rust-lang.org/2024/10/17/Rust-1.82.0.html

Bump the rust version to 1.82 and update library dependencies

---

.github/workflows/tests.yaml

Adds a new GHA workflow which runs the unit tests using Rust nightly.

gha: Add test run using Rust nightly

---

Cargo.lock
hoprd/rest-api/Cargo.toml
hoprd/rest-api/src/alias.rs
hoprd/rest-api/src/channels.rs
hoprd/rest-api/src/messages.rs
hoprd/rest-api/src/peers.rs
hoprd/rest-api/src/session.rs
hoprd/rest-api/src/types.rs

Fix backwards compatibility with the 2.1.x

---

hoprd/hoprd/example_cfg.yaml
logic/strategy/src/auto_redeeming.rs
logic/strategy/src/lib.rs

The following changes were missed in the merge-back PRs from saint-louis:
- #6338
- #6437

Add auto-redeem strategy changes missed in the merge-back

---

Cargo.lock
db/migration/Cargo.toml
db/migration/src/lib.rs
db/migration/src/m20241112_000018_logs_add_index.rs

db: Add index to improve log_status queries

---

hoprd/rest-api/src/session.rs

Add data counters to WS Session adapter and log them

---

chain/indexer/src/block.rs

The logging was confusing, redundant in `info` level and used dynamic data in log messages, not fields. Ths PR fixes that in order to improve the log output.

Update the logging in indexer block processing

---

chain/indexer/src/errors.rs
chain/indexer/src/handlers.rs
db/sql/src/logs.rs

- avoid race conditions when updating checksum
- simplify counting query
- add more logs for failures

Improve some Logs DB queries

---

deploy/compose/.env.sample
deploy/compose/README.md

Changelog:
- update .env.sample to reflect changes to METRICS_PUSH_URL better
- update README.md for docker compose with new docs url

Update .env.sample and README.md for the docker compose

---

.github/workflows/build-binaries.yaml
.github/workflows/build.yaml

Allow to generate the `hopli` and `hoprd` binaries from a manual workflow and select a branch.

Allow to launch binaries manually

---

.github/ISSUE_TEMPLATE/bug.md

Update bug template to current project context

Update bug template

---

Cargo.lock
hopli/Cargo.toml
hopli/src/environment_config.rs
hopli/src/win_prob.rs

Cleanup of the `hopli` crate and its dependencies.

hopli: Cleanup unnecessary dependencies

---

deploy/compose/prometheus/metricspusher.sh

Fixes the port as it is hardcoded internally

Fix metrics pusher on docker compose

---

hopr/hopr-lib/src/lib.rs

Do not swallow strategy errors on winning tickets

---

transport/session/src/types.rs

- decrease frame expiration age when not using retransmission

Session configuration tweaks

---

hopr/hopr-lib/src/lib.rs
hoprd/rest-api/src/node.rs
hoprd/rest-api/src/peers.rs
transport/session/src/types.rs

Minor fixes to hopr-lib and hoprd

---

hoprd/rest-api/src/account.rs

Merge back bug fixes from 2.1.5

---

hoprd/rest-api/src/messages.rs

Port message schema fixes.
Last of the missing merge back changes from 2.1.5

Porting schema fixes from 2.1.5

---

Cargo.lock
hoprd/rest-api/Cargo.toml
hoprd/rest-api/src/lib.rs

The recursion upon error handling would lead to a stack overflow.
Fixes #6684

rest-api: Fix recursion in error conversion

---

Cargo.lock
hoprd/hoprd/example_cfg.yaml
hoprd/rest-api/Cargo.toml
hoprd/rest-api/src/lib.rs
hoprd/rest-api/src/peers.rs
transport/api/Cargo.toml
transport/api/src/network_notifier.rs
transport/network/Cargo.toml
transport/network/src/config.rs
transport/network/src/constants.rs
transport/network/src/ping.rs
transport/protocol/src/heartbeat/config.rs
transport/protocol/src/lib.rs

Fix network issues

---

Cargo.lock
hoprd/hoprd/example_cfg.yaml
hoprd/rest-api/Cargo.toml
hoprd/rest-api/src/lib.rs
hoprd/rest-api/src/peers.rs
transport/api/Cargo.toml
transport/api/src/network_notifier.rs
transport/network/Cargo.toml
transport/network/src/config.rs
transport/network/src/constants.rs
transport/network/src/ping.rs
transport/protocol/src/heartbeat/config.rs
transport/protocol/src/lib.rs

(cherry picked from commit 81946c29ed50dcabf9ff9c92da601012398ff399)
Fix #6782

Fix network issues to accomodate the larger network size (#6791)

---

transport/p2p/src/constants.rs
transport/p2p/src/swarm.rs

(cherry picked from commit e0ce9475bb008b6d996c844740131c3c12321ac6)

Update libp2p config to account for dufour size and CT requirements (#6815)

---

.github/workflows/tests.yaml
sdk/barebone-lower-win-prob.cfg.yaml
sdk/barebone.cfg.yaml
sdk/default.cfg.yaml
sdk/python/localcluster/anvil.py
sdk/python/localcluster/cluster.py

*Cherry-pick from  #6820*
Restore snapshot functionality in the CI.

Fix CI workflow to be able to create/use snapshots

---

Cargo.lock
METRICS.md
transport/session/Cargo.toml
transport/session/src/manager.rs

The above metric has incorrectly accounted for closed sessions.
Closes #6840 6840

Fix hopr_session_num_active_sessions metric

---

transport/session/src/types.rs

Frame expiration age should be halved.

Lower the frame expiration age

---

.github/workflows/merge.yaml
Cargo.lock
METRICS.md
chain/indexer/src/block.rs
common/internal-types/src/tickets.rs
db/sql/Cargo.toml
db/sql/src/tickets.rs
deploy/compose/docker-compose.yml
deploy/compose/hoprd_data/hoprd.cfg.yaml
hoprd/hoprd/example_cfg.yaml
hoprd/hoprd/src/config.rs
hoprd/hoprd/src/exit.rs
hoprd/hoprd/src/main.rs
logic/strategy/src/channel_finalizer.rs
sdk/barebone-lower-win-prob.cfg.yaml
sdk/barebone.cfg.yaml
sdk/default.cfg.yaml
transport/network/Cargo.toml
transport/network/src/ping.rs
transport/p2p/src/swarm.rs
transport/protocol/src/ticket_aggregation/processor.rs
transport/session/Cargo.toml
transport/session/src/manager.rs
transport/session/src/types.rs

Changes:
- #6842 (will be done as a separate PR)

Forward ports of 2.2.2 changes to master

---

.github/workflows/build-binaries.yaml
.github/workflows/build-docker.yaml
.github/workflows/build-docs.yaml
.github/workflows/lint.yaml
.github/workflows/tests.yaml
Cargo.lock
chain/rpc/src/client.rs
ethereum/bindings/build.rs
flake.lock
flake.nix
hoprd/hoprd/Cargo.toml
nix/rust-builder.nix
nix/rust-package.nix
nix/shell.nix
scripts/bump-version.sh

Fix debug/prod docker build pipeline

---

db/sql/src/tickets.rs
hoprd/hoprd/example_cfg.yaml
logic/strategy/Cargo.toml
logic/strategy/src/aggregating.rs
transport/p2p/src/swarm.rs

strategy: Improve ticket aggregation defaults, config validation and logging

---

chain/rpc/src/rpc.rs
chain/types/src/lib.rs
chain/types/src/utils.rs
hoprd/rest-api/src/checks.rs
logic/strategy/src/channel_finalizer.rs

Porting changes from https://github.com/hoprnet/hoprnet/pull/6842
Fewer assumptions on the eligibility check.
Use multicall to query staking threshold and registered staking account.

Port fix check eligibility

---

db/migration/src/lib.rs
db/migration/src/m20250219_000020_logs_add_index.rs
db/migration/src/m20250219_000021_channels_add_index.rs
db/sql/src/logs.rs

Fix #6880
Refs https://github.com/hoprnet/hoprnet/issues/6296

db: Add more indices

---

Cargo.lock
chain/actions/src/channels.rs
db/sql/src/channels.rs
logic/strategy/Cargo.toml
logic/strategy/src/promiscuous.rs

- split quality threshold: for channel opening and for channel closing
- better treat automatic channel determination
- refactor code
Refs #6879

Updates to Promiscuous strategy

---

README.md
chain/indexer/src/block.rs
common/internal-types/src/protocol.rs
common/internal-types/src/tickets.rs
common/network-types/src/session/frame.rs
common/network-types/src/session/protocol.rs
common/network-types/src/session/state.rs
common/primitive-types/src/primitives.rs
db/sql/src/accounts.rs
db/sql/src/channels.rs
db/sql/src/db.rs
db/sql/src/logs.rs
db/sql/src/resolver.rs
db/sql/src/ticket_manager.rs
db/sql/src/tickets.rs
flake.lock
flake.nix
hopr/hopr-lib/src/lib.rs
hoprd/hoprd/src/cli.rs
hoprd/hoprd/src/lib.rs
rust-toolchain.toml

Update the toolchain and fix some misspellings:

Update the flake and rust

---

Cargo.lock
logic/strategy/Cargo.toml
logic/strategy/src/promiscuous.rs

Changes some default values of promiscuous strategy and log levels of some messages.

Update defaults of Promiscuous strategy

---

.github/renovate.json

ci: Fix renovate

---

.github/renovate.json

Bump crates in `Cargo.toml`: https://github.com/renovatebot/renovate/discussions/32890

Bump also Cargo.toml dependencies, not only the Cargo.lock

---

.github/workflows/build-binaries.yaml
.github/workflows/build-dappnode.yaml
.github/workflows/build-docker.yaml
.github/workflows/build-docs.yaml
.github/workflows/build.yaml
.github/workflows/clean-pr.yaml
.github/workflows/cleanup.yaml
.github/workflows/close-release.yaml
.github/workflows/deploy-nodes.yaml
.github/workflows/generate-dappnode-pr.yaml
.github/workflows/k8s.yaml
.github/workflows/latexcompile.yaml
.github/workflows/load-tests.yaml
.github/workflows/merge.yaml
.github/workflows/open-release.yaml
.github/workflows/promote-release.yaml
.github/workflows/publish-release.yaml
.github/workflows/tests.yaml
.github/workflows/update-flake-lock.yaml
.github/workflows/zizmor.yaml
nix/shell.nix

Port changes from #6934, #6943 and #6944 to `master`.

ci: Add harden-runner to all workflows

---

.github/workflows/update-flake-lock.yaml
flake.lock

ci: Fix flake update action

---

.github/workflows/build-docker.yaml

Fixes merge pipeline by specifying the branch as parameter

Fix merge pipeline

---

.github/workflows/cache-deps.yaml

The nix condition is not necessary.

ci: Fix cache dependency workflow

---

Cargo.lock
hoprd/rest-api/src/lib.rs

Fix the missing schemas for the utoipa generation.

Fix missing schema definition in the REST API

---

.github/workflows/merge.yaml

Change the destination of the Zulip channel

Change Zulip channel

---

.github/renovate.json

**Summary of Changes:**
This PR updates the Renovate configuration to align with recommended practices and improve dependency management.
1. **Configuration Update**:
- Switched to `config:recommended` for better defaults.
- Enabled `semanticCommits` and updated `rangeStrategy` to `bump`.
2. **Vulnerability Alerts**:
- Consolidated the configuration for vulnerability alerts.
3. **Package Rules**:
- Added rules for `rust` and `docker` categories:
- Rust: Enables updates for dependencies.
- Docker: Enables updates and pins digests.
4. **Removed Redundant Configurations**:
- Deprecated fields for `docker`, `rust`, and individual vulnerability alerts.
**Impact**:
- Ensures Renovate follows the latest best practices.
- Simplifies configuration management.
- Improves dependency updates for …

ci: Update renovate configuration

---

.github/renovate.json
Cargo.toml
uv.lock

Some dependencies must be kept back, this PR extends the renovate ignore list.

renovate: Update the ignore list

---

.cargo/audit.toml
Cargo.lock
Cargo.toml
chain/rpc/Cargo.toml
chain/rpc/src/client.rs
chain/rpc/src/errors.rs
chain/rpc/src/lib.rs

This pull request introduces several changes, primarily focused on replacing the `http-types` dependency with the `http` crate across multiple files, updating dependencies, and improving serialization handling. Below is a categorized summary of the most important changes:
* Updated `.cargo/audit.toml` to remove older advisories and add new ones, including `RUSTSEC-2024-0436` for the `paste` dependency and `RUSTSEC-2025-0009`/`RUSTSEC-2025-0010` for the `ring` dependency.
* Updated `Cargo.toml` to replace `http-types` with `http` and added `serde_with` for enhanced serialization support. Also added comments to clarify dependency audit status. [[1]](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L102-R103) …

audit: Fix deps

---

Cargo.lock
hoprd/hoprd/example_cfg.yaml
transport/api/Cargo.toml
transport/api/src/lib.rs
transport/p2p/Cargo.toml
transport/p2p/src/lib.rs
transport/p2p/src/swarm.rs
transport/protocol/src/config.rs

Introduce NAT server functionality, so that current local development can be tested against nodes that *can* be used as servers.

Introduce NAT server functionality

---

Cargo.lock
common/network-types/Cargo.toml
common/network-types/src/session/frame.rs
common/network-types/src/session/state.rs
transport/protocol/Cargo.toml
transport/protocol/src/lib.rs

session: Add more tracing logs

---

.github/renovate.json

Renovate will from now on group dependency updates into a single PR.

Update renovate.json to group updates

---

Cargo.lock
chain/actions/src/action_queue.rs
chain/api/Cargo.toml
chain/api/src/executors.rs
db/sql/src/logs.rs

Lowers the timeout for transmitting a transaction on-chain from 30s to 5s
Adds some more informative logs

Lower the TX transmission timeout

---

hoprd/rest-api/src/lib.rs

The order of router element construction is important, as described in: https://docs.rs/axum/latest/axum/struct.Router.html#method.layer

api: Fix CORS layer in checks

---

hopr/hopr-lib/src/lib.rs
scripts/protocol-config-anvil.json
sdk/python/localcluster/main_process.py
transport/api/src/lib.rs
transport/p2p/src/behavior/discovery.rs
transport/probe/src/probe.rs
transport/protocol/src/stream.rs

Cherry pick from https://github.com/hoprnet/hoprnet/pull/7255 so that peers in the localcluster can connect with each other.

fix(hopr-lib): Cherry pick fixes for localcluster connectivity

---

.github/workflows/build-binaries.yaml
.github/workflows/build-dappnode.yaml
.github/workflows/build-docker.yaml
.github/workflows/build-docs.yaml
.github/workflows/build.yaml
.github/workflows/cache-deps.yaml
.github/workflows/checks-audit.yaml
.github/workflows/checks-lint.yaml
.github/workflows/checks-zizmor.yaml
.github/workflows/checks.yaml
.github/workflows/merge.yaml
.github/workflows/open-pr.yaml
.github/workflows/tests.yaml

Fixes the checkout branch for cleanup and notify jobs

fix(ci): Fixing merge pipeline

---

.github/workflows/bencher-nightly.disabled
.github/workflows/close-release.yaml
.github/workflows/open-release.yaml
.github/workflows/publish-release.yaml
README.md
docs/changelog/changelog-3.0.0-rc.1.md
releases.json

This Pull requests contains all the required changes needed before releasing a new version.
- If the release will run in its own network ($RELEASENAME == $NETWORK) then a new entry in `hopr/hopr-lib/data/protocol-config.json` should be created for the network.
- If the release will run in a multinetwork network like `dufour` then update the file `hopr/hopr-lib/data/protocol-config.json` for the `dufour` entry to accept the new `version_range` of the new release.
```
"new_network": {
"boost_contract_address": "",
"channels_contract_address": "",
"environment_type": "production",
"indexer_start_block_number": 0,
"network_registry_contract_address": "",
"network_registry_proxy_contract_address": "",
"stake_contract_address": "",
"stake_season": 7,
"token_contract_address": "", …
```

Close release 3.0.0-rc.1

---

.github/workflows/build-docker.yaml

Add this flag to enable/disable and avoid merge pipeline unnecessary failures

ci: Add pluto build flag

---

.github/workflows/create-release.yaml
scripts/download-workflow-binaries.sh

- Using wrong branch when creating release
- Using wrong folder when downloading artifacts

fix: Using wrong branch when creating release 

---

docs/changelog/changelog-3.0.0-rc.1.md
scripts/download-workflow-binaries.sh

https://github.com/hoprnet/hoprnet/pull/7322#discussion_r2213284189

fix: Incorrect coderabbit suggestion on #7322

---

deploy/nfpm/README.md
deploy/nfpm/install-hoprd-package.sh

Fixes the testing process for ArchLinux package

fix: Fix testing process for archlinux package

---

common/network-types/src/types.rs
transport/protocol/hopr.lua
transport/protocol/src/capture.rs
transport/protocol/src/lib.rs

This PR adds number of SURBs into the outgoing packet and includes other improvements and tweaks to the dissector

feat: add number of surbs into the dissector

---

README.md
flake.nix

feat(nix): Add capture-enabled binaries

---

sdk/python/localcluster/__main__.py
sdk/python/localcluster/cluster.py
sdk/python/localcluster/main_process.py

Localcluster size can be set by providing `--size <INT>`.
The maximum cluster size is the number of nodes in `localcluster.params.yml`

feat: parametrable localcluster size

---

Cargo.lock
crypto/sphinx/Cargo.toml
crypto/sphinx/src/ec_groups.rs
crypto/sphinx/src/packet.rs
crypto/sphinx/src/shared_keys.rs
crypto/types/Cargo.toml
crypto/types/benches/lioness_bench.rs
crypto/types/src/lib.rs
crypto/types/src/lioness.rs

This PR adds missing re-implementation of the Lioness wide-block cipher, that fulfills the PRP requirements from the Sphinx paper.
Closes https://github.com/hoprnet/hoprnet/issues/7420

feat: updated Lioness wide-block cipher implementation

---

deploy/compose/hoprd/conf/hoprd.cfg.yaml

Update docker compose configuration file to remove aggregation strategy

fix: Remove aggregation strategy

---

.github/workflows/k8s.yaml
Cargo.lock
METRICS.md
common/network-types/Cargo.toml
common/network-types/src/udp.rs
db/node/src/protocol.rs
db/node/src/ticket_manager.rs
db/node/src/tickets.rs
deploy/compose/grafana/provisioning/dashboards/hopr/hoprd-grafana-dashboard.json
hopr/hopr-lib/Cargo.toml
hoprd/hoprd/Cargo.toml
hoprd/rest-api/Cargo.toml
hoprd/rest-api/src/middleware/prometheus.rs
logic/path/Cargo.toml
logic/path/src/channel_graph.rs
transport/protocol/Cargo.toml
transport/protocol/src/lib.rs

fix: verbose metrics (#7553)

---

ethereum/contracts/contracts-addresses.json

Port changes in https://github.com/hoprnet/hoprnet/pull/7562 to kaunas release

fix(hopr-lib): cherry-pick wrong rotsee winprob contract address
